### ISSUE TITLE
[gl3w] build failure on macos

### ISSUE THREAD

**Issue by Nelarius** [microsoft/vcpkg#11667]
**Host Environment**
- OS: MacOS 10.15
- Compiler: revision

**To Reproduce**
`./vcpkg install gl3w`

**Failure logs** 
```
$ ./vcpkg install gl3w
Computing installation plan...
The following packages will be built and installed:
    gl3w[core]:x64-osx
Starting package 1/1: gl3w:x64-osx
Building package gl3w[core]:x64-osx...
-- Using cached /Users/nelarius/vcpkg/downloads/skaslev-gl3w-99ed321100d37032cb6bfa7dd8dea85f10c86132.tar.gz
-- Using source at /Users/nelarius/vcpkg/buildtrees/gl3w/src/5f10c86132-7e24c6e824
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: /usr/local/bin/python3 /Users/nelarius/vcpkg/buildtrees/gl3w/src/5f10c86132-7e24c6e824/gl3w_gen.py
    Working Directory: /Users/nelarius/vcpkg/buildtrees/gl3w/src/5f10c86132-7e24c6e824
    Error code: 1
    See logs for more information:
      /Users/nelarius/vcpkg/buildtrees/gl3w/gl3w-gen-out.log
      /Users/nelarius/vcpkg/buildtrees/gl3w/gl3w-gen-err.log
```

gl3w-gen-err.log:
```
Traceback (most recent call last):
  File "/Users/nelarius/vcpkg/buildtrees/gl3w/src/5f10c86132-7e24c6e824/gl3w_gen.py", line 115, in <module>
    web = urllib2.urlopen('https://www.khronos.org/registry/EGL/api/KHR/khrplatform.h')
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 549, in _open
    'unknown_open', req)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1388, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>
```

**Comment by Nelarius** [comment]
**Additional context**

Running `gl3w_gen.py` manually actually works, and after that `./vcpkg install gl3w` succeeds.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. I install `gl3w:x64-osx` successfully on MACOSX 10.15.2. Could you clone new vcpkg and rebuild `gl3w:x64-osx` again? If installing successfully, this issue is not a bug.

**Comment by Nelarius** [comment]
Cloned a fresh copy of `vcpkg`, but still got the same error while installing `gl3w`. If everything worked on your end, then I suspect that the cause is my fiddly homebrew-python3 installation, which is causing me all sorts other problems as well 😄 If I can think of something, then I'll share it here!

**Comment by LilyWangL** [comment]
@Nelarius Does this issue still occur?

**Comment by Nelarius** [comment]
I haven't been able to figure out what to do about it 😞

**Comment by PhoebeHui** [comment]
@Nelarius, Could you try to remove the python localy, and use the one that vcpkg download instead? and see if the issue persist?

**Comment by Nelarius** [comment]
Hi @PhoebeHui, and thanks for the tip!I removed the homebrew python installation, and that solved the problem! 👍
