### ISSUE TITLE
libepoxy build failure 

### ISSUE THREAD

**Issue by Checkam** [microsoft/vcpkg#12225]
**Host Environment**
- OS: Windows

**To Reproduce**
`./vcpkg install gtk:x64-windows

**Failure logs** 
Console :
```
Computing installation plan...
The following packages will be built and installed:
    gtk[core]:x64-windows
  * harfbuzz[core,glib]:x64-windows
  * libepoxy[core]:x64-windows
  * pango[core]:x64-windows
  * ragel[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/5: libepoxy:x64-windows
Building package libepoxy[core]:x64-windows...

-- Using cached C:/Users/admin/Documents/Dev/vcpkg/downloads/anholt-libepoxy-1.5.4.tar.gz
-- Using source at C:/Users/admin/Documents/Dev/vcpkg/buildtrees/libepoxy/src/1.5.4-337c486045
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Configuring x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/Users/admin/Documents/Dev/vcpkg/downloads/tools/python/python-3.8.3-x64/python.exe C:/Users/admin/Documents/Dev/vcpkg/downloads/tools/meson/meson-0.54.2/meson.py -Denable-glx=no -Denable-egl=no -Dcmake_prefix_path=['C:/Users/admin/Documents/Dev/vcpkg/installed/x64-windows','C:/Users/admin/Documents/Dev/vcpkg/installed/x64-windows/share'] --buildtype plain --backend ninja --wrap-mode nodownload --default-library shared --libdir lib --prefix C:/Users/admin/Documents/Dev/vcpkg/packages/libepoxy_x64-windows/debug --includedir ../include C:/Users/admin/Documents/Dev/vcpkg/buildtrees/libepoxy/src/1.5.4-337c486045 -Dc_args=['/nologo','/DWIN32','/D_WINDOWS','/W3','/MP','/D_DEBUG','/MDd','/Z7','/Ob0','/Od','/RTC1'] -Dcpp_args=['/nologo','/DWIN32','/D_WINDOWS','/W3','/GR','/EHsc','/MP','/D_DEBUG','/MDd','/Z7','/Ob0','/Od','/RTC1'] -Dc_link_args=[] -Dcpp_link_args=[]
    Working Directory: C:/Users/admin/Documents/Dev/vcpkg/buildtrees/libepoxy/x64-windows-dbg
    Error code: 2
    See logs for more information:
      C:\Users\admin\Documents\Dev\vcpkg\buildtrees\libepoxy\config-x64-windows-dbg-out.log
      C:\Users\admin\Documents\Dev\vcpkg\buildtrees\libepoxy\config-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:161 (vcpkg_execute_required_process)
  ports/libepoxy/portfile.cmake:16 (vcpkg_configure_meson)
  scripts/ports.cmake:76 (include)

```
config-x64-windows-dbg-err : 
```
Traceback (most recent call last):
  File "C:\Users\admin\Documents\Dev\vcpkg\downloads\tools\meson\meson-0.54.2\mesonbuild\mesonmain.py", line 131, in run
    return options.run_func(options)
  File "C:\Users\admin\Documents\Dev\vcpkg\downloads\tools\meson\meson-0.54.2\mesonbuild\msetup.py", line 245, in run
    app.generate()
  File "C:\Users\admin\Documents\Dev\vcpkg\downloads\tools\meson\meson-0.54.2\mesonbuild\msetup.py", line 159, in generate
    self._generate(env)
  File "C:\Users\admin\Documents\Dev\vcpkg\downloads\tools\meson\meson-0.54.2\mesonbuild\msetup.py", line 192, in _generate
    intr.run()
  File "C:\Users\admin\Documents\Dev\vcpkg\downloads\tools\meson\meson-0.54.2\mesonbuild\interpreter.py", line 4359, in run
    super().run()
  File "C:\Users\admin\Documents\Dev\vcpkg\downloads\tools\meson\meson-0.54.2\mesonbuild\interpreterbase.py", line 465, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "C:\Users\admin\Documents\Dev\vcpkg\downloads\tools\meson\meson-0.54.2\mesonbuild\interpreterbase.py", line 490, in evaluate_codeblock
    raise e
  File "C:\Users\admin\Documents\Dev\vcpkg\downloads\tools\meson\meson-0.54.2\mesonbuild\interpreterbase.py", line 483, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:\Users\admin\Documents\Dev\vcpkg\downloads\tools\meson\meson-0.54.2\mesonbuild\interpreterbase.py", line 498, in evaluate_statement
    self.assignment(cur)
  File "C:\Users\admin\Documents\Dev\vcpkg\downloads\tools\meson\meson-0.54.2\mesonbuild\interpreterbase.py", line 1151, in assignment
    value = self.evaluate_statement(node.value)
  File "C:\Users\admin\Documents\Dev\vcpkg\downloads\tools\meson\meson-0.54.2\mesonbuild\interpreterbase.py", line 496, in evaluate_statement
    return self.function_call(cur)
  File "C:\Users\admin\Documents\Dev\vcpkg\downloads\tools\meson\meson-0.54.2\mesonbuild\interpreterbase.py", line 853, in function_call
    return func(node, func_args, self.kwargs_string_keys(kwargs))
  File "C:\Users\admin\Documents\Dev\vcpkg\downloads\tools\meson\meson-0.54.2\mesonbuild\interpreterbase.py", line 350, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\Users\admin\Documents\Dev\vcpkg\downloads\tools\meson\meson-0.54.2\mesonbuild\interpreterbase.py", line 350, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\Users\admin\Documents\Dev\vcpkg\downloads\tools\meson\meson-0.54.2\mesonbuild\interpreterbase.py", line 350, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  [Previous line repeated 3 more times]
  File "C:\Users\admin\Documents\Dev\vcpkg\downloads\tools\meson\meson-0.54.2\mesonbuild\interpreterbase.py", line 194, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
  File "C:\Users\admin\Documents\Dev\vcpkg\downloads\tools\meson\meson-0.54.2\mesonbuild\interpreterbase.py", line 213, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\Users\admin\Documents\Dev\vcpkg\downloads\tools\meson\meson-0.54.2\mesonbuild\interpreter.py", line 3411, in func_dependency
    d = self.dependency_impl(name, display_name, kwargs)
  File "C:\Users\admin\Documents\Dev\vcpkg\downloads\tools\meson\meson-0.54.2\mesonbuild\interpreter.py", line 3470, in dependency_impl
    dep = dependencies.find_external_dependency(name, self.environment, kwargs)
  File "C:\Users\admin\Documents\Dev\vcpkg\downloads\tools\meson\meson-0.54.2\mesonbuild\dependencies\base.py", line 2329, in find_external_dependency
    d = c()
  File "C:\Users\admin\Documents\Dev\vcpkg\downloads\tools\meson\meson-0.54.2\mesonbuild\dependencies\base.py", line 1090, in __init__
    CMakeDependency.class_cmakeinfo[self.for_machine] = self._get_cmake_info()
  File "C:\Users\admin\Documents\Dev\vcpkg\downloads\tools\meson\meson-0.54.2\mesonbuild\dependencies\base.py", line 1166, in _get_cmake_info
    temp_parser.parse(err1)
  File "C:\Users\admin\Documents\Dev\vcpkg\downloads\tools\meson\meson-0.54.2\mesonbuild\cmake\traceparser.py", line 141, in parse
    trace = self.trace_file_path.read_text()
  File "pathlib.py", line 1233, in read_text
  File "encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 388518: character maps to <undefined>
```

**Additional context**
i try this : 
- https://github.com/Microsoft/vcpkg/issues/1631

**Comment by Voskrese** [comment]
open `CMD.EXE`

`chcp`

?

**Comment by Checkam** [comment]
Yes i try !
So i just remove vcpkg and reinstall vcpkg and now it's ok.
Thanks i close issue.
