### ISSUE TITLE
[qt5-webengine] build failure on Windows

### ISSUE THREAD

**Issue by Berrysoft** [microsoft/vcpkg#13133]
**Host Environment**
- OS: Windows 10
- Compiler: MSVC 19.27

**To Reproduce**
`./vcpkg install qt5-webengine:x64-windows`

**Failure logs** 
```
[3389/28243] C:\Users\Berrysoft\Documents\GitHub\vcpkg\downloads\tools\python\python-2.7.16-x64\python.exe ../../../../src/5.15.0-358d713a2a.clean/src/3rdparty/chromium/third_party/blink/renderer/bindings/scripts/compute_interfaces_info_individual.py --cache-directory gen/third_party/blink/renderer/bindings/scripts --idl-files-list __third_party_blink_renderer_bindings_modules_interfaces_info_modules___build_toolchain_win_x64__rule.rsp --interfaces-info-file gen/third_party/blink/renderer/bindings/modules/interfaces_info_modules.pickle --component-info-file gen/third_party/blink/renderer/bindings/modules/component_info_modules.pickle --runtime-enabled-features-file gen/third_party/blink/renderer/build/scripts/runtime_enabled_features.pickle
FAILED: gen/third_party/blink/renderer/bindings/modules/interfaces_info_modules.pickle gen/third_party/blink/renderer/bindings/modules/component_info_modules.pickle 
C:\Users\Berrysoft\Documents\GitHub\vcpkg\downloads\tools\python\python-2.7.16-x64\python.exe ../../../../src/5.15.0-358d713a2a.clean/src/3rdparty/chromium/third_party/blink/renderer/bindings/scripts/compute_interfaces_info_individual.py --cache-directory gen/third_party/blink/renderer/bindings/scripts --idl-files-list __third_party_blink_renderer_bindings_modules_interfaces_info_modules___build_toolchain_win_x64__rule.rsp --interfaces-info-file gen/third_party/blink/renderer/bindings/modules/interfaces_info_modules.pickle --component-info-file gen/third_party/blink/renderer/bindings/modules/component_info_modules.pickle --runtime-enabled-features-file gen/third_party/blink/renderer/build/scripts/runtime_enabled_features.pickle
Traceback (most recent call last):
  File "../../../../src/5.15.0-358d713a2a.clean/src/3rdparty/chromium/third_party/blink/renderer/bindings/scripts/compute_interfaces_info_individual.py", line 376, in <module>
    sys.exit(main())
  File "../../../../src/5.15.0-358d713a2a.clean/src/3rdparty/chromium/third_party/blink/renderer/bindings/scripts/compute_interfaces_info_individual.py", line 367, in main
    info_collector.collect_info(idl_filename)
  File "../../../../src/5.15.0-358d713a2a.clean/src/3rdparty/chromium/third_party/blink/renderer/bindings/scripts/compute_interfaces_info_individual.py", line 288, in collect_info
    this_include_path = include_path(idl_filename, implemented_as)
  File "../../../../src/5.15.0-358d713a2a.clean/src/3rdparty/chromium/third_party/blink/renderer/bindings/scripts/compute_interfaces_info_individual.py", line 110, in include_path
    relative_dir = relative_dir_posix(idl_filename, source_path)
  File "../../../../src/5.15.0-358d713a2a.clean/src/3rdparty/chromium/third_party/blink/renderer/bindings/scripts/compute_interfaces_info_individual.py", line 96, in relative_dir_posix
    relative_path_local = os.path.relpath(idl_filename, base_path)
  File "C:\Users\Berrysoft\Documents\GitHub\vcpkg\downloads\tools\python\python-2.7.16-x64\lib\ntpath.py", line 529, in relpath
    % (path_prefix, start_prefix))
ValueError: path is on drive , start on drive C:
```

[package-build-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5123976/package-build-x64-windows-dbg-out.log)

**Additional context**
I also tracked other build failures when using MSVC 19.28, while ANGLE depends on a non-standard `pow` of STL, which is fixed and shipped with VS 19.8. Ironically, this non-standard one was fixed(actually, deleted) by me ;)

**Comment by Neumann-A** [comment]
`C:\Users\Berrysoft\Documents\GitHub\vcpkg` could be too long for qt5-webengine which uses deeply nested folders.

**Comment by JackBoosY** [comment]
`ValueError: path is on drive , start on drive C:` It must be the same as Neumann said.

**Comment by Berrysoft** [comment]
Thanks! I moved the `vcpkg` folder to just `C:`, and it is still building🤣 I'll report later whether it is success.

**Comment by Berrysoft** [comment]
It works! Thanks!
