### ISSUE TITLE
gRPC: vcpkg and NuGet packages

### ISSUE THREAD

**Issue by veronicagarciavazquez** [microsoft/vcpkg#13169]
If we create a project in Visual Studio 2019 with NuGet packages Google.Protobuf (version 3.13.0) and Grpc.Core (version 2.30.0), can we overwrite \bin\x64\Debug\netcoreapp3.1\runtimes\win\native\grpc_csharp_ext.x64.dll with grpc_csharp_ext.dll (renamed as \grpc_csharp_ext.x64.dll) generated with vcpkg (grpc 1.29.1 and protobuf 3.12.3) and the triplet x64-windows? Which versions of vcpkg (grpc and protobuf) and the NuGet packages Google.Protobuf and Grpc.Core are compatible regarding grpc_csharp_ext.dll?

I have done that and I have the following error in Visual Studio:
```
Unhandled exception. System.IO.IOException: Error loading native library "C:\example\example\bin\x64\Debug\netcoreapp3.1\runtimes/win/native\grpc_csharp_ext.x64.dll".
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.LoadUnmanagedLibrary()
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.Internal.NativeMethods.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Server..ctor(IEnumerable`1 options)
   at Grpc.Core.Server..ctor()
   at GRPC_CSharpCSharpServer.GRPC_Server.Main(String[] args) in C:\example\example\GRPC_Server.cs:line 44

C:\example\example\bin\x64\Debug\netcoreapp3.1\example.exe (process 12844) exited with code -532462766.
```

**Comment by JackBoosY** [comment]
@vicroms Can you please take a look?

Thanks.

**Comment by JackBoosY** [comment]
See https://stackoverflow.com/questions/14711633/my-c-sharp-application-is-returning-0xe0434352-to-windows-task-scheduler-but-it
