### ISSUE TITLE
[<brotli>] build failure

### ISSUE THREAD

**Issue by lgp8z** [microsoft/vcpkg#13177]
**Host Environment**
- OS: Win10
- Compiler: VS 2019

**To Reproduce**
Steps to reproduce the [behavior:](url
[copy-tool-dependencies-err.log](https://github.com/microsoft/vcpkg/files/5134689/copy-tool-dependencies-err.log)
)
`./vcpkg install brotli:x64-windows`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    brotli[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: brotli:x64-windows
Building package brotli[core]:x64-windows...
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg/archives\e9\e9252ebdeedb08dd3c7671ffb887649998d90290.zip
-- Using cached F:/vcpkg/downloads/google-brotli-v1.0.7.tar.gz
-- Cleaning sources at F:/vcpkg/buildtrees/brotli/src/v1.0.7-c2af986dcd.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/vcpkg/downloads/google-brotli-v1.0.7.tar.gz
-- Applying patch install.patch
-- Applying patch fix-arm-uwp.patch
-- Applying patch pkgconfig.patch
-- Using source at F:/vcpkg/buildtrees/brotli/src/v1.0.7-c2af986dcd.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: F:/vcpkg/downloads/tools/powershell-core-6.2.1-windows/powershell.exe -noprofile -executionpolicy Bypass -nologo -file F:/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary F:/vcpkg/packages/brotli_x64-windows/tools/brotli/brotli.exe -installedDir F:/vcpkg/packages/brotli_x64-windows/bin
    Working Directory: F:/vcpkg
    Error code: -2146232797
    See logs for more information:
      F:\vcpkg\buildtrees\brotli\copy-tool-dependencies-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:27 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:37 (search_for_dependencies)
  ports/brotli/portfile.cmake:23 (vcpkg_copy_tool_dependencies)
  scripts/ports.cmake:79 (include)

Error: Building package brotli:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: brotli:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by NancyLi1013** [comment]
Hi @lgp8z 
Thanks for posting this issue.
```

FailFast:
Infinite recursion during resource lookup within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: Arg_AccessViolationException

   at System.Environment.FailFast(System.String)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String, System.String)
   at System.AccessViolationException..ctor()
   at System.SpanHelpers.IndexOf(Char ByRef, Char, Int32)
   at System.Globalization.CultureData.InitCultureData()
   at System.Globalization.CultureData.CreateCultureData(System.String, Boolean)
   at System.Globalization.CultureData.GetCultureData(System.String, Boolean)
   at System.Globalization.CultureInfo.InitializeFromName(System.String, Boolean)
   at System.Globalization.CultureInfo..ctor(System.String, Boolean)
   at System.Globalization.CultureInfo.GetCultureInfoHelper(Int32, System.String, System.String)
   at System.Globalization.CultureInfo.GetCultureInfo(System.String)
   at System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage(System.Reflection.Assembly, System.Resources.UltimateResourceFallbackLocation ByRef)
   at System.Resources.ResourceManager.CommonAssemblyInit()
   at System.Resources.ResourceManager..ctor(System.Type)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String, System.String)
   at System.AccessViolationException..ctor()
   at System.SpanHelpers.SequenceEqual(Byte ByRef, Byte ByRef, UInt32)
   at System.String.Equals(System.String, System.String)
   at System.AppDomain.Setup(System.Object)
```

Duplicated to #12849. let's track this issue there.
