### ISSUE TITLE
How to build opencv_python when installing  opencv4 package by vcpkg ?

### ISSUE THREAD

**Issue by uiemUI** [microsoft/vcpkg#13210]
The content of  "config-x64-windows-out.log" is "
[1/2] cmd /c "cd .. && "C:/INclude/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe" "C:/INclude/vcpkg/buildtrees/opencv4/src/4.3.0-0c6047baf6.clean" "-DOPENCV_CUDA_FORCE_BUILTIN_CMAKE_MODULE=ON" "-DOpenCV_INSTALL_BINARIES_PREFIX=" "-DOPENCV_BIN_INSTALL_PATH=bin" "-DOPENCV_INCLUDE_INSTALL_PATH=include" "-DOPENCV_LIB_INSTALL_PATH=lib" "-DOPENCV_3P_LIB_INSTALL_PATH=lib" "-DOPENCV_CONFIG_INSTALL_PATH=share/opencv" "-DINSTALL_TO_MANGLED_PATHS=OFF" "-DOPENCV_FFMPEG_USE_FIND_PACKAGE=FFMPEG" "-DCMAKE_DEBUG_POSTFIX=d" "-DOPENCV_DLLVERSION=" "-DOPENCV_DEBUG_POSTFIX=d" "-DOPENCV_GENERATE_SETUPVARS=OFF" "-DBUILD_DOCS=OFF" "-DBUILD_EXAMPLES=OFF" "-Dade_DIR=C:/INclude/vcpkg/installed/x64-windows/share/ade" "-DBUILD_JASPER=OFF" "-DBUILD_JPEG=OFF" "-DBUILD_OPENEXR=OFF" "-DBUILD_PNG=OFF" "-DBUILD_TIFF=OFF" "-DBUILD_WEBP=OFF" "-DBUILD_ZLIB=OFF" "-DBUILD_TBB=OFF" "-DBUILD_IPP_IW=OFF" "-DBUILD_ITT=OFF" "-DBUILD_PROTOBUF=OFF" "-DBUILD_opencv_apps=OFF" "-DBUILD_opencv_java=OFF" "-DBUILD_opencv_js=OFF" "-DBUILD_ANDROID_PROJECT=OFF" "-DBUILD_ANDROID_EXAMPLES=OFF" "-DBUILD_PACKAGE=OFF" "-DBUILD_PERF_TESTS=OFF" "-DBUILD_TESTS=OFF" "-DBUILD_WITH_DEBUG_INFO=ON" "-DBUILD_WITH_STATIC_CRT=0" "-DBUILD_JAVA=OFF" "-DCURRENT_INSTALLED_DIR=C:/INclude/vcpkg/installed/x64-windows" "-DPROTOBUF_UPDATE_FILES=ON" "-DUPDATE_PROTO_FILES=ON" "-DENABLE_PYLINT=OFF" "-DENABLE_FLAKE8=OFF" "-DBUILD_opencv_python3=ON" "-DOPENCV_PYTHON3_VERSION=ON" "-DBUILD_NEW_PYTHON_SUPPORT=ON" "-DHAVE_opencv_python3=ON" "-DPYTHON_DEFAULT_EXECUTABLE=C:/Users/123/AppData/Local/Programs/Python/Python37/python.exe" "-DBUILD_opencv_python_bindings_generator=ON" "-DPYTHON3_INCLUDE_DIR=C:/Users/123/AppData/Local/Programs/Python/Python37/include" "-DPYTHON3_LIBRARY=C:/Users/123/AppData/Local/Programs/Python/Python37/libs/python37.lib" "-DPYTHON3_EXECUTABLE=C:/Users/123/AppData/Local/Programs/Python/Python37/python.exe" "-DPYTHON3_NUMPY_INCLUDE_DIRS=C:/Users/123/AppData/Local/Programs/Python/Python37/lib/site-packages/numpy/core/include" "-DPYTHON3_PACKAGES_PATH=C:/Users/123/AppData/Local/Programs/Python/Python37/Lib/site-packages" "-DOPENCV_PYTHON3_INSTALL_PATH=C:/Users/123/AppData/Local/Programs/Python/Python37/Lib/site-packages" "-DCMAKE_DISABLE_FIND_PACKAGE_Git=ON" "-DCMAKE_DISABLE_FIND_PACKAGE_JNI=ON" "-DENABLE_CXX11=ON" "-DOPENCV_DOWNLOAD_PATH=C:/INclude/vcpkg/downloads/opencv-cache" "-DOPENCV_EXTRA_MODULES_PATH=C:/INclude/vcpkg/buildtrees/opencv4/src/4.3.0-795a2a992f.clean/modules" "-DOPENCV_OTHER_INSTALL_PATH=share/opencv" "-DWITH_ADE=OFF" "-DWITH_CONTRIB=ON" "-DWITH_CUDA=ON" "-DWITH_CUBLAS=ON" "-DWITH_EIGEN=ON" "-DWITH_FFMPEG=OFF" "-DWITH_GDCM=OFF" "-DWITH_HALIDE=OFF" "-DWITH_JASPER=OFF" "-DWITH_JPEG=ON" "-DOPENCV_ENABLE_NONFREE=ON" "-DWITH_OPENEXR=OFF" "-DWITH_OPENGL=ON" "-DWITH_PNG=ON" "-DWITH_QT=ON" "-DBUILD_opencv_sfm=ON" "-DWITH_TIFF=ON" "-DWITH_WEBP=ON" "-DBUILD_opencv_world=OFF" "-DHALIDE_ROOT_DIR=C:/INclude/vcpkg/installed/x64-windows" "-DCMAKE_DISABLE_FIND_PACKAGE_Halide=ON" "-DWITH_GTK=OFF" "-DWITH_IPP=OFF" "-DWITH_MSMF=ON" "-DWITH_OPENMP=OFF" "-DWITH_PROTOBUF=ON" "-DWITH_TBB=OFF" "-DWITH_VTK=ON" "-DWITH_OPENJPEG=OFF" "-DWITH_LAPACK=OFF" "-DBUILD_opencv_ovis=OFF" "-DBUILD_opencv_dnn=ON" "-DBUILD_opencv_quality=CMAKE_DEPENDS_IN_PROJECT_ONLY" "-DBUILD_opencv_rgbd=OFF" "-DCMAKE_AUTOMOC=ON" "-DCMAKE_MAKE_PROGRAM=C:/INclude/vcpkg/downloads/tools/ninja/1.10.0-windows/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/INclude/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/INclude/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/INclude/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/INclude/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/INclude/vcpkg/packages/opencv4_x64-windows""
-- The CXX compiler identification is MSVC 19.26.28806.0
-- The C compiler identification is MSVC 19.26.28806.0
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Detected processor: AMD64
-- Performing Test HAVE_CXX_FP:PRECISE
-- Performing Test HAVE_CXX_FP:PRECISE - Success
-- Performing Test HAVE_C_FP:PRECISE
-- Performing Test HAVE_C_FP:PRECISE - Success
-- Performing Test HAVE_CPU_SSE3_SUPPORT (check file: cmake/checks/cpu_sse3.cpp)
-- Performing Test HAVE_CPU_SSE3_SUPPORT - Success
-- Performing Test HAVE_CPU_SSSE3_SUPPORT (check file: cmake/checks/cpu_ssse3.cpp)
-- Performing Test HAVE_CPU_SSSE3_SUPPORT - Success
-- Performing Test HAVE_CPU_SSE4_1_SUPPORT (check file: cmake/checks/cpu_sse41.cpp)
-- Performing Test HAVE_CPU_SSE4_1_SUPPORT - Success
-- Performing Test HAVE_CPU_POPCNT_SUPPORT (check file: cmake/checks/cpu_popcnt.cpp)
-- Performing Test HAVE_CPU_POPCNT_SUPPORT - Success
-- Performing Test HAVE_CPU_SSE4_2_SUPPORT (check file: cmake/checks/cpu_sse42.cpp)
-- Performing Test HAVE_CPU_SSE4_2_SUPPORT - Success
-- Performing Test HAVE_CXX_ARCH:AVX (check file: cmake/checks/cpu_fp16.cpp)
-- Performing Test HAVE_CXX_ARCH:AVX - Success
-- Performing Test HAVE_CXX_ARCH:AVX2 (check file: cmake/checks/cpu_avx2.cpp)
-- Performing Test HAVE_CXX_ARCH:AVX2 - Success
-- Performing Test HAVE_CXX_ARCH:AVX512 (check file: cmake/checks/cpu_avx512.cpp)
-- Performing Test HAVE_CXX_ARCH:AVX512 - Success
-- Performing Test HAVE_CPU_BASELINE_FLAGS
-- Performing Test HAVE_CPU_BASELINE_FLAGS - Success
-- Performing Test HAVE_CPU_DISPATCH_FLAGS_SSE4_1
-- Performing Test HAVE_CPU_DISPATCH_FLAGS_SSE4_1 - Success
-- Performing Test HAVE_CPU_DISPATCH_FLAGS_SSE4_2
-- Performing Test HAVE_CPU_DISPATCH_FLAGS_SSE4_2 - Success
-- Performing Test HAVE_CPU_DISPATCH_FLAGS_FP16
-- Performing Test HAVE_CPU_DISPATCH_FLAGS_FP16 - Success
-- Performing Test HAVE_CPU_DISPATCH_FLAGS_AVX
-- Performing Test HAVE_CPU_DISPATCH_FLAGS_AVX - Success
-- Performing Test HAVE_CPU_DISPATCH_FLAGS_AVX2
-- Performing Test HAVE_CPU_DISPATCH_FLAGS_AVX2 - Success
-- Performing Test HAVE_CPU_DISPATCH_FLAGS_AVX512_SKX
-- Performing Test HAVE_CPU_DISPATCH_FLAGS_AVX512_SKX - Success
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Searching 16 bit integer - Using unsigned short
-- Check if the system is big endian - little endian
-- Found ZLIB: optimized;C:/INclude/vcpkg/installed/x64-windows/lib/zlib.lib;debug;C:/INclude/vcpkg/installed/x64-windows/debug/lib/zlibd.lib (found suitable version "1.2.11", minimum required is "1.2.3") 
-- Found JPEG: optimized;C:/INclude/vcpkg/installed/x64-windows/lib/jpeg.lib;debug;C:/INclude/vcpkg/installed/x64-windows/debug/lib/jpegd.lib (found version "62") 
-- Found TIFF: optimized;C:/INclude/vcpkg/installed/x64-windows/lib/tiff.lib;debug;C:/INclude/vcpkg/installed/x64-windows/debug/lib/tiffd.lib (found version "4.0.10") 
-- Found ZLIB: optimized;C:/INclude/vcpkg/installed/x64-windows/lib/zlib.lib;debug;C:/INclude/vcpkg/installed/x64-windows/debug/lib/zlibd.lib (found version "1.2.11") 
-- Found PNG: optimized;C:/INclude/vcpkg/installed/x64-windows/lib/libpng16.lib;debug;C:/INclude/vcpkg/installed/x64-windows/debug/lib/libpng16d.lib (found version "1.6.37") 
-- Looking for C:/INclude/vcpkg/installed/x64-windows/include/libpng/png.h
-- Looking for C:/INclude/vcpkg/installed/x64-windows/include/libpng/png.h - found
-- Found CUDNN: C:/INclude/vcpkg/installed/x64-windows/include (found suitable version "7.6.0", minimum required is "7.5") 
-- CUDA detected: 10.2
-- CUDA NVCC target flags: -gencode;arch=compute_30,code=sm_30;-gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-D_FORCE_INLINES
-- Found VTK 8.2.0 (C:/INclude/vcpkg/installed/x64-windows/share/vtk/../../share/vtk/UseVTK.cmake)
-- OpenCV Python: during development append to PYTHONPATH: C:/INclude/vcpkg/buildtrees/opencv4/x64-windows-rel/python_loader
-- Looking for mfapi.h
-- Looking for mfapi.h - found
-- Looking for d3d11_4.h
-- Looking for d3d11_4.h - found
-- Caffe:   NO
-- Found Protobuf: optimized;C:/INclude/vcpkg/installed/x64-windows/lib/libprotobuf.lib;debug;C:/INclude/vcpkg/installed/x64-windows/debug/lib/libprotobufd.lib (found version "3.11.3") 
-- Protobuf:   YES
-- Glog:   YES
-- freetype2:   NO
-- harfbuzz:    NO
-- Module opencv_ovis disabled because OGRE3D was not found
-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
-- Found installed version of gflags: C:/INclude/vcpkg/installed/x64-windows/share/gflags
-- Detected gflags version: 2.2.2
-- Found installed version of Eigen: C:/INclude/vcpkg/installed/x64-windows/share/eigen3
-- Found required Ceres dependency: Eigen version 3.3.7 in C:/INclude/vcpkg/installed/x64-windows/include/eigen3
-- Ceres version 1.14.0 detected here: C:/INclude/vcpkg/installed/x64-windows was built with C++11. Ceres target will add C++11 flags to compile options for targets using it.
-- Found Ceres version: 1.14.0 installed in: C:/INclude/vcpkg/installed/x64-windows with components: [SchurSpecializations, C++11, OpenMP, Multithreading]
-- Checking SFM deps... TRUE
-- Found TIFF: optimized;C:/INclude/vcpkg/installed/x64-windows/lib/tiff.lib;debug;C:/INclude/vcpkg/installed/x64-windows/debug/lib/tiffd.lib;optimized;C:/INclude/vcpkg/installed/x64-windows/lib/lzma.lib;debug;C:/INclude/vcpkg/installed/x64-windows/debug/lib/lzmad.lib;optimized;C:/INclude/vcpkg/installed/x64-windows/lib/jpeg.lib;debug;C:/INclude/vcpkg/installed/x64-windows/debug/lib/jpegd.lib;optimized;C:/INclude/vcpkg/installed/x64-windows/lib/zlib.lib;debug;C:/INclude/vcpkg/installed/x64-windows/debug/lib/zlibd.lib (found version "4.0.10") 
-- Found GIF: C:/INclude/vcpkg/installed/x64-windows/lib/gif.lib (found version "5.1.4") 
-- Tesseract:   YES (ver 4.1.1)
-- Allocator metrics storage type: 'long long'
-- Registering hook 'INIT_MODULE_SOURCES_opencv_dnn': C:/INclude/vcpkg/buildtrees/opencv4/src/4.3.0-0c6047baf6.clean/modules/dnn/cmake/hooks/INIT_MODULE_SOURCES_opencv_dnn.cmake
-- xfeatures2d/boostdesc: Download: boostdesc_bgm.i
-- xfeatures2d/boostdesc: Download: boostdesc_bgm_bi.i
-- xfeatures2d/boostdesc: Download: boostdesc_bgm_hd.i
-- xfeatures2d/boostdesc: Download: boostdesc_binboost_064.i
-- xfeatures2d/boostdesc: Download: boostdesc_binboost_128.i
-- xfeatures2d/boostdesc: Download: boostdesc_binboost_256.i
-- xfeatures2d/boostdesc: Download: boostdesc_lbgm.i
-- xfeatures2d/vgg: Download: vgg_generated_48.i
-- xfeatures2d/vgg: Download: vgg_generated_64.i
-- xfeatures2d/vgg: Download: vgg_generated_80.i
-- xfeatures2d/vgg: Download: vgg_generated_120.i
-- data: Download: face_landmark_model.dat
-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
-- Found installed version of gflags: C:/INclude/vcpkg/installed/x64-windows/share/gflags
-- Detected gflags version: 2.2.2
-- Found installed version of Eigen: C:/INclude/vcpkg/installed/x64-windows/share/eigen3
-- Found required Ceres dependency: Eigen version 3.3.7 in C:/INclude/vcpkg/installed/x64-windows/include/eigen3
-- Ceres version 1.14.0 detected here: C:/INclude/vcpkg/installed/x64-windows was built with C++11. Ceres target will add C++11 flags to compile options for targets using it.
-- Found Ceres version: 1.14.0 installed in: C:/INclude/vcpkg/installed/x64-windows with components: [SchurSpecializations, C++11, OpenMP, Multithreading]
-- Checking SFM deps... TRUE
-- NVIDIA_OPTICAL_FLOW: Download: 79c6cee80a2df9a196f20afd6b598a9810964c32.zip
-- 
-- General configuration for OpenCV 4.3.0 =====================================
--   Version control:               unknown
-- 
--   Extra modules:
--     Location (extra):            C:/INclude/vcpkg/buildtrees/opencv4/src/4.3.0-795a2a992f.clean/modules
--     Version control (extra):     unknown
-- 
--   Platform:
--     Timestamp:                   2020-08-28T22:18:32Z
--     Host:                        Windows 10.0.19041 AMD64
--     CMake:                       3.17.2
--     CMake generator:             Ninja
--     CMake build tool:            C:/INclude/vcpkg/downloads/tools/ninja/1.10.0-windows/ninja.exe
--     MSVC:                        1926
--     Configuration:               Release
-- 
--   CPU/HW features:
--     Baseline:                    SSE SSE2 SSE3
--       requested:                 SSE3
--     Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2 AVX512_SKX
--       requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
--       SSE4_1 (13 files):         + SSSE3 SSE4_1
--       SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
--       FP16 (0 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
--       AVX (4 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
--       AVX2 (27 files):           + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
--       AVX512_SKX (3 files):      + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2 AVX_512F AVX512_COMMON AVX512_SKX
-- 
--   C/C++:
--     Built as dynamic libs?:      YES
--     C++ standard:                11
--     C++ Compiler:                C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe  (ver 19.26.28806.0)
--     C++ flags (Release):         /nologo /DWIN32 /D_WINDOWS /W4 /utf-8 /GR /MP   /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise /FS     /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589  /MD /O2 /Oi /Gy /DNDEBUG /Z7  
--     C++ flags (Debug):           /nologo /DWIN32 /D_WINDOWS /W4 /utf-8 /GR /MP   /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise /FS     /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  
--     C Compiler:                  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe
--     C flags (Release):           /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP   /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise /FS       /MD /O2 /Oi /Gy /DNDEBUG /Z7  
--     C flags (Debug):             /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP   /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise /FS     /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  
--     Linker flags (Release):      /machine:x64  /nologo /DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF   /debug
--     Linker flags (Debug):        /machine:x64  /nologo  /debug /INCREMENTAL 
--     ccache:                      NO
--     Precompiled headers:         NO
--     Extra dependencies:          opengl32 glu32 cudart_static.lib nppc.lib nppial.lib nppicc.lib nppicom.lib nppidei.lib nppif.lib nppig.lib nppim.lib nppist.lib nppisu.lib nppitc.lib npps.lib cublas.lib cudnn.lib cufft.lib -LIBPATH:"C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/lib/x64" -LIBPATH:"C:/INclude/vcpkg/installed/x64-windows/lib"
--     3rdparty dependencies:
-- 
--   OpenCV modules:
--     To be built:                 alphamat aruco bgsegm bioinspired calib3d ccalib core cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev cvv datasets dnn dnn_objdetect dnn_superres dpm face features2d flann fuzzy hdf hfs highgui img_hash imgcodecs imgproc intensity_transform line_descriptor ml objdetect optflow phase_unwrapping photo plot quality rapid reg saliency sfm shape stereo stitching structured_light superres surface_matching text tracking video videoio videostab viz xfeatures2d ximgproc xobjdetect xphoto
--     Disabled:                    rgbd world
--     Disabled by dependency:      -
--     Unavailable:                 cnn_3dobj freetype gapi java js matlab ovis python2 python3 ts
--     Applications:                -
--     Documentation:               NO
--     Non-free algorithms:         YES
-- 
--   Windows RT support:            NO
-- 
--   GUI: 
--     QT:                          YES (ver 5.13.1)
--       QT OpenGL support:         YES (Qt5::OpenGL 5.13.1)
--     Win32 UI:                    YES
--     OpenGL support:              YES (opengl32 glu32)
--     VTK support:                 YES (ver 8.2.0)
-- 
--   Media I/O: 
--     ZLib:                        optimized C:/INclude/vcpkg/installed/x64-windows/lib/zlib.lib debug C:/INclude/vcpkg/installed/x64-windows/debug/lib/zlibd.lib (ver 1.2.11)
--     JPEG:                        optimized C:/INclude/vcpkg/installed/x64-windows/lib/jpeg.lib debug C:/INclude/vcpkg/installed/x64-windows/debug/lib/jpegd.lib (ver 62)
--     WEBP:                        optimized C:/INclude/vcpkg/installed/x64-windows/lib/webp.lib debug C:/INclude/vcpkg/installed/x64-windows/debug/lib/webpd.lib (ver 1.1.0)
--     PNG:                         optimized C:/INclude/vcpkg/installed/x64-windows/lib/libpng16.lib debug C:/INclude/vcpkg/installed/x64-windows/debug/lib/libpng16d.lib (ver 1.6.37)
--     TIFF:                        optimized C:/INclude/vcpkg/installed/x64-windows/lib/tiff.lib debug C:/INclude/vcpkg/installed/x64-windows/debug/lib/tiffd.lib optimized C:/INclude/vcpkg/installed/x64-windows/lib/lzma.lib debug C:/INclude/vcpkg/installed/x64-windows/debug/lib/lzmad.lib optimized C:/INclude/vcpkg/installed/x64-windows/lib/jpeg.lib debug C:/INclude/vcpkg/installed/x64-windows/debug/lib/jpegd.lib optimized C:/INclude/vcpkg/installed/x64-windows/lib/zlib.lib debug C:/INclude/vcpkg/installed/x64-windows/debug/lib/zlibd.lib (ver 42 / 4.0.10)
--     HDR:                         YES
--     SUNRASTER:                   YES
--     PXM:                         YES
--     PFM:                         YES
-- 
--   Video I/O:
--     DC1394:                      NO
--     GStreamer:                   NO
--     DirectShow:                  YES
--     Media Foundation:            YES
--       DXVA:                      YES
-- 
--   Parallel framework:            Concurrency
-- 
--   Trace:                         YES (built-in)
-- 
--   Other third-party libraries:
--     Eigen:                       YES (ver 3.3.7)
--     Custom HAL:                  NO
--     Protobuf:                    optimized C:/INclude/vcpkg/installed/x64-windows/lib/libprotobuf.lib debug C:/INclude/vcpkg/installed/x64-windows/debug/lib/libprotobufd.lib (3.11.3)
-- 
--   NVIDIA CUDA:                   YES (ver 10.2, CUFFT CUBLAS)
--     NVIDIA GPU arch:             30 35 37 50 52 60 61 70 75
--     NVIDIA PTX archs:
-- 
--   cuDNN:                         YES (ver 7.6.0)
-- 
--   OpenCL:                        YES (NVD3D11)
--     Include path:                C:/INclude/vcpkg/buildtrees/opencv4/src/4.3.0-0c6047baf6.clean/3rdparty/include/opencl/1.2
--     Link libraries:              Dynamic load
-- 
--   Python 3:
--     Interpreter:                 NO
--     Libraries:                   
--     numpy:                       C:/Users/123/AppData/Local/Programs/Python/Python37/lib/site-packages/numpy/core/include (ver )
--     install path:                
-- 
--   Python (for build):            NO
-- 
--   Install to:                    C:/INclude/vcpkg/packages/opencv4_x64-windows
-- -----------------------------------------------------------------
-- 
-- Configuring done

I  have set the  "-DOPENCV_PYTHON3_VERSION=ON"， but It doesn't work。

**Comment by PhoebeHui** [comment]
@uiemUI, the python module doesn't support now, see https://github.com/microsoft/vcpkg/blob/master/ports/opencv4/CONTROL.

**Comment by dg0yt** [comment]
There is opencv4[python] today.

**Comment by i2w3** [comment]
> There is opencv4[python] today.

Can you tell me how to use it? My code not work:
```bash
mamba create -n cucv python=3.12
mamba activate cucv
cd {VCPKG_ROOT}/buildtrees/opencv4/x64-windows-rel/python_loader
pip install .
python
import cv2
```
```
Python 3.12.12 | packaged by conda-forge | (main, Oct 22 2025, 23:13:34) [MSC v.1944 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Softwares\miniforge3\envs\cucv\Lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Softwares\miniforge3\envs\cucv\Lib\site-packages\cv2\__init__.py", line 112, in bootstrap
    load_first_config([
  File "C:\Softwares\miniforge3\envs\cucv\Lib\site-packages\cv2\__init__.py", line 109, in load_first_config
    raise ImportError('OpenCV loader: missing configuration file: {}. Check OpenCV installation.'.format(fnames))
ImportError: OpenCV loader: missing configuration file: ['config-3.12.py', 'config-3.py']. Check OpenCV installation.
```

**Comment by dg0yt** [comment]
> ~~~
> cd {VCPKG_ROOT}/buildtrees/opencv4/x64-windows-rel/python_loader

"buildtrees". Nothing to see here. Look for the "installed". And it may not be built for your conda python.
