### ISSUE TITLE
vcpkg install protobuf failed at newsest version 

### ISSUE THREAD

**Issue by whidbey** [microsoft/vcpkg#13246]
**Describe the bug**
simple runnin vcpkg install protobuf ,failed at Resource name: Arg_AccessViolationException

**Environment**
- OS: windows 7; [windows 10 also ,but ok when I installed vs2017 english pack ,and vs2019 english pack]
- Compiler: revision

**To Reproduce**
1. git pull
2. bootstrap-vcpkg.bat
3. clean c:/vcpkg/downloads/
4. ./vcpkg install protobuf
5. See error
c:\vcpkg>vcpkg install protobuf
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete o
ur survey by running: vcpkg contact --survey
Computing installation plan...
A suitable version of cmake was not found (required v3.17.2). Downloading portab
le cmake v3.17.2...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.17.2/cmake-3.17.2-win32-
x86.zip -> C:\vcpkg\downloads\cmake-3.17.2-win32-x86.zip
Extracting cmake...
A suitable version of 7zip was not found (required v18.1.0). Downloading portabl
e 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> C:\vcpkg\down
loads\7-zip.commandline.18.1.0.nupkg
Extracting 7zip...
A suitable version of nuget was not found (required v5.5.1). Downloading portabl
e nuget v5.5.1...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v5.5.1/nuget.exe -> C:\vcpkg\downlo
ads\22ea847d-nuget.exe
The following packages will be built and installed:
    protobuf[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
A suitable version of git was not found (required v2.26.2). Downloading portable
 git v2.26.2...
Downloading git...
  https://github.com/git-for-windows/git/releases/download/v2.26.2.windows.1/Por
tableGit-2.26.2-32-bit.7z.exe -> C:\vcpkg\downloads\PortableGit-2.26.2-32-bit.7z
.exe
Extracting git...
A suitable version of powershell-core was not found (required v6.2.1). Downloadi
ng portable powershell-core v6.2.1...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v6.2.1/PowerShell-6
.2.1-win-x86.zip -> C:\vcpkg\downloads\PowerShell-6.2.1-win-x86.zip
Extracting powershell-core...
Starting package 1/1: protobuf:x86-windows
Building package protobuf[core]:x86-windows...
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg/arch
ives\cb\cb2a2d450275b6d47c5f6b01e245b8ccb209438a.zip
-- Using cached C:/vcpkg/downloads/protocolbuffers-protobuf-fde7cf7358ec7cd69e8d
b9be4f1fa6a5c431386a.tar.gz
-- Cleaning sources at C:/vcpkg/buildtrees/protobuf/src/a5c431386a-c9deea9e31.cl
ean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/protocolbuffers-protobuf-fde7cf7358ec7cd
69e8db9be4f1fa6a5c431386a.tar.gz
-- Applying patch fix-uwp.patch
-- Applying patch fix-android-log.patch
-- Applying patch fix-static-build.patch
-- Using source at C:/vcpkg/buildtrees/protobuf/src/a5c431386a-c9deea9e31.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:83 (message):
    Command failed: C:/vcpkg/downloads/tools/powershell-core-6.2.1-windows/power
shell.exe -noprofile -executionpolicy Bypass -nologo -file C:/vcpkg/scripts/buil
dsystems/msbuild/applocal.ps1 -targetBinary C:/vcpkg/packages/protobuf_x86-windo
ws/tools/protobuf/protoc.exe -installedDir C:/vcpkg/packages/protobuf_x86-window
s/bin
    Working Directory: C:/vcpkg
    Error code: -2146232797
    See logs for more information:
      C:\vcpkg\buildtrees\protobuf\copy-tool-dependencies-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:27 (vcpkg_execute_required_pr
ocess)
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:37 (search_for_dependencies)
  scripts/cmake/vcpkg_copy_tools.cmake:55 (vcpkg_copy_tool_dependencies)
  ports/protobuf/portfile.cmake:93 (vcpkg_copy_tools)
  scripts/ports.cmake:79 (include)

Error: Building package protobuf:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: protobuf:x86-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

c:\vcpkg>
c:\vcpkg>
c:\vcpkg>
c:\vcpkg>
c:\vcpkg>
c:\vcpkg>
 
**Expected behavior**

**Failure logs** 

FailFast:
Infinite recursion during resource lookup within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: Arg_AccessViolationException

   at System.Environment.FailFast(System.String)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String, System.String)
   at System.AccessViolationException..ctor()
   at System.SpanHelpers.IndexOf(Char ByRef, Char, Int32)
   at System.Globalization.CultureData.InitCultureData()
   at System.Globalization.CultureData.CreateCultureData(System.String, Boolean)
   at System.Globalization.CultureData.GetCultureData(System.String, Boolean)
   at System.Globalization.CultureInfo.InitializeFromName(System.String, Boolean)
   at System.Globalization.CultureInfo..ctor(System.String, Boolean)
   at System.Globalization.CultureInfo.GetCultureInfoHelper(Int32, System.String, System.String)
   at System.Globalization.CultureInfo.GetCultureInfo(System.String)
   at System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage(System.Reflection.Assembly, System.Resources.UltimateResourceFallbackLocation ByRef)
   at System.Resources.ResourceManager.CommonAssemblyInit()
   at System.Resources.ResourceManager..ctor(System.Type)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String, System.String)
   at System.AccessViolationException..ctor()
   at System.SpanHelpers.SequenceEqual(Byte ByRef, Byte ByRef, UInt32)
   at System.String.Equals(System.String, System.String)
   at System.AppDomain.Setup(System.Object)

**Comment by whidbey** [comment]
I used 2020.06 version Of vcpkg.
warning with ccessViolationException but can continue succeed.
here is my log


c:\vcpkg-2020.06>.\vcpkg install protobuf
Computing installation plan...
The following packages will be built and installed:
    protobuf[core]:x86-windows
Starting package 1/1: protobuf:x86-windows
Building package protobuf[core]:x86-windows...
A suitable version of git was not found (required v2.26.2). Downloading portable
 git v2.26.2...
Extracting git...
-- Downloading https://github.com/protocolbuffers/protobuf/archive/v3.12.0.tar.g
z...
-- Extracting source C:/vcpkg-2020.06/downloads/protocolbuffers-protobuf-v3.12.0
.tar.gz
-- Applying patch fix-uwp.patch
-- Applying patch fix-android-log.patch
-- Applying patch fix-static-build.patch
-- Using source at C:/vcpkg-2020.06/buildtrees/protobuf/src/v3.12.0-3a905889d1
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: C:/vcpkg-2020.06/packages/protobuf_x86-windows/tools/protobuf/pro
toc.exe
FailFast:
Infinite recursion during resource lookup within System.Private.CoreLib.  This m
ay be a bug in System.Private.CoreLib, or potentially in certain extensibility p
oints such as assembly resolve events or CultureInfo names.  Resource name: Arg_
AccessViolationException

   at System.Environment.FailFast(System.String)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String, System.String)
   at System.AccessViolationException..ctor()
   at System.SpanHelpers.IndexOf(Char ByRef, Char, Int32)
   at System.Globalization.CultureData.InitCultureData()
   at System.Globalization.CultureData.CreateCultureData(System.String, Boolean)

   at System.Globalization.CultureData.GetCultureData(System.String, Boolean)
   at System.Globalization.CultureInfo.InitializeFromName(System.String, Boolean
)
   at System.Globalization.CultureInfo..ctor(System.String, Boolean)
   at System.Globalization.CultureInfo.GetCultureInfoHelper(Int32, System.String
, System.String)
   at System.Globalization.CultureInfo.GetCultureInfo(System.String)
   at System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage
(System.Reflection.Assembly, System.Resources.UltimateResourceFallbackLocation B
yRef)
   at System.Resources.ResourceManager.CommonAssemblyInit()
   at System.Resources.ResourceManager..ctor(System.Type)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String, System.String)
   at System.AccessViolationException..ctor()
   at System.SpanHelpers.SequenceEqual(Byte ByRef, Byte ByRef, UInt32)
   at System.String.Equals(System.String, System.String)
   at System.AppDomain.Setup(System.Object)
FailFast:
Infinite recursion during resource lookup within System.Private.CoreLib.  This m
ay be a bug in System.Private.CoreLib, or potentially in certain extensibility p
oints such as assembly resolve events or CultureInfo names.  Resource name: Arg_
AccessViolationException

   at System.Environment.FailFast(System.String)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String, System.String)
   at System.AccessViolationException..ctor()
   at System.SpanHelpers.IndexOf(Char ByRef, Char, Int32)
   at System.Globalization.CultureData.InitCultureData()
   at System.Globalization.CultureData.CreateCultureData(System.String, Boolean)

   at System.Globalization.CultureData.GetCultureData(System.String, Boolean)
   at System.Globalization.CultureInfo.InitializeFromName(System.String, Boolean
)
   at System.Globalization.CultureInfo..ctor(System.String, Boolean)
   at System.Globalization.CultureInfo.GetCultureInfoHelper(Int32, System.String
, System.String)
   at System.Globalization.CultureInfo.GetCultureInfo(System.String)
   at System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage
(System.Reflection.Assembly, System.Resources.UltimateResourceFallbackLocation B
yRef)
   at System.Resources.ResourceManager.CommonAssemblyInit()
   at System.Resources.ResourceManager..ctor(System.Type)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String, System.String)
   at System.AccessViolationException..ctor()
   at System.SpanHelpers.SequenceEqual(Byte ByRef, Byte ByRef, UInt32)
   at System.String.Equals(System.String, System.String)
   at System.AppDomain.Setup(System.Object)
-- Installing: C:/vcpkg-2020.06/packages/protobuf_x86-windows/share/protobuf/cop
yright
-- Performing post-build validation
-- Performing post-build validation done
Building package protobuf[core]:x86-windows... done
Installing package protobuf[core]:x86-windows...
Installing package protobuf[core]:x86-windows... done
Elapsed time for package protobuf:x86-windows: 10.88 min

Total elapsed time: 10.88 min

The package protobuf:x86-windows provides CMake targets:

    find_package(protobuf CONFIG REQUIRED)
    target_link_libraries(main PRIVATE protobuf::libprotoc protobuf::libprotobuf
 protobuf::libprotobuf-lite)

**Comment by JackBoosY** [comment]
Duplicate with issue #12849.
