### ISSUE TITLE
[openssl] build failure

### ISSUE THREAD

**Issue by blackknifes** [microsoft/vcpkg#13276]
**Host Environment**
- OS: [Windows 10]
- Compiler: vs 2019 msvc compiler

**To Reproduce**
`./vcpkg install openssl:x86-windows`

**Failure logs** 
Console:
```
Computing installation plan...
The following packages will be built and installed:
    openssl[core]:x86-windows
  * openssl-windows[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Starting package 1/2: openssl-windows:x86-windows
Building package openssl-windows[core]:x86-windows...
Could not locate cached archive: C:\Users\lkq\AppData\Local\vcpkg/archives\a6\a6feffcab2228d43bdca4e6536988b553874876b.zip
-- Using cached D:/lkq/repo/vcpkg/downloads/openssl-1.1.1g.tar.gz
-- Cleaning sources at D:/lkq/repo/vcpkg/buildtrees/openssl-windows/src/openssl-1-bb2a9a5801.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/lkq/repo/vcpkg/downloads/openssl-1.1.1g.tar.gz
-- Using source at D:/lkq/repo/vcpkg/buildtrees/openssl-windows/src/openssl-1-bb2a9a5801.clean
-- Copying openssl release source files...
-- Copying openssl release source files... done
-- Configure x86-windows-rel
-- Configure x86-windows-rel done
-- Build x86-windows-rel
-- Build x86-windows-rel done
-- Copying openssl debug source files...
-- Copying openssl debug source files... done
-- Configure x86-windows-dbg
-- Configure x86-windows-dbg done
-- Build x86-windows-dbg
-- Build x86-windows-dbg done
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:83 (message):
    Command failed: D:/lkq/repo/vcpkg/downloads/tools/powershell-core-6.2.1-windows/powershell.exe -noprofile -executionpolicy Bypass -nologo -file D:/lkq/repo/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary D:/lkq/repo/vcpkg/packages/openssl-windows_x86-windows/tools/openssl/openssl.exe -installedDir D:/lkq/repo/vcpkg/packages/openssl-windows_x86-windows/bin
    Working Directory: D:/lkq/repo/vcpkg
    Error code: -2146232797
    See logs for more information:
      D:\lkq\repo\vcpkg\buildtrees\openssl-windows\copy-tool-dependencies-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:27 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:37 (search_for_dependencies)
  ports/openssl-windows/portfile.cmake:169 (vcpkg_copy_tool_dependencies)
  scripts/ports.cmake:79 (include)


Error: Building package openssl-windows:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-windows:x86-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.
```

copy-tool-dependencies-err.log:
```
FailFast:
Infinite recursion during resource lookup within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: Arg_AccessViolationException

   at System.Environment.FailFast(System.String)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String, System.String)
   at System.AccessViolationException..ctor()
   at System.SpanHelpers.IndexOf(Char ByRef, Char, Int32)
   at System.Globalization.CultureData.InitCultureData()
   at System.Globalization.CultureData.CreateCultureData(System.String, Boolean)
   at System.Globalization.CultureData.GetCultureData(System.String, Boolean)
   at System.Globalization.CultureInfo.InitializeFromName(System.String, Boolean)
   at System.Globalization.CultureInfo..ctor(System.String, Boolean)
   at System.Globalization.CultureInfo.GetCultureInfoHelper(Int32, System.String, System.String)
   at System.Globalization.CultureInfo.GetCultureInfo(System.String)
   at System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage(System.Reflection.Assembly, System.Resources.UltimateResourceFallbackLocation ByRef)
   at System.Resources.ResourceManager.CommonAssemblyInit()
   at System.Resources.ResourceManager..ctor(System.Type)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String, System.String)
   at System.AccessViolationException..ctor()
   at System.SpanHelpers.SequenceEqual(Byte ByRef, Byte ByRef, UInt32)
   at System.String.Equals(System.String, System.String)
   at System.AppDomain.Setup(System.Object)
```

**Comment by NancyLi1013** [comment]
Hi @blackknifes 
Thanks for posting this issue.

Please provide `D:\lkq\repo\vcpkg\buildtrees\openssl-windows\copy-tool-dependencies-err.log`.

**Comment by blackknifes** [comment]
> Hi @blackknifes
> Thanks for posting this issue.
> 
> Please provide `D:\lkq\repo\vcpkg\buildtrees\openssl-windows\copy-tool-dependencies-err.log`.

copy-tool-dependencies-err.log is following Console log;

**Comment by NancyLi1013** [comment]
I see the error info now.

It's duplicated to #12849. Please try to update Visual Studio 2019 to the latest version and rebuild this.

**Comment by blackknifes** [comment]
> I see the error info now.
> 
> It's duplicated to #12849. Please try to update Visual Studio 2019 to the latest version and rebuild this.
VS Version:  16.7.2
I has been updated, but it still show this error.

**Comment by blackknifes** [comment]
![image](https://user-images.githubusercontent.com/9638801/91923386-d0fa3f00-ed02-11ea-8a82-52d8762bdeef.png)
When I run powershell, it show the error log.

**Comment by NancyLi1013** [comment]
Hi @blackknifes 
We need to do further investigation about this issue. Since the root cause is the same as that in #12849. 
Let's track this issue there.
