### ISSUE TITLE
[openssl-windows] build failure

### ISSUE THREAD

**Issue by 12GardenSeed** [microsoft/vcpkg#14042]
**Host Environment**
- OS: Windows
- Compiler: MVSC

**To Reproduce**
 run command`vcpkg install openssl-windows`

**Failure logs** 
```

Computing installation plan...
The following packages will be built and installed:
    openssl-windows[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: openssl-windows:x86-windows
Building package openssl-windows[core]:x86-windows...
Could not locate cached archive: C:\Users\EDZ\AppData\Local\vcpkg\archives\6c\6c87c5491e08469272204b76c02dbdd45a3e60d1.zip
-- Using cached D:/projects/vcpkg/downloads/openssl-1.1.1h.tar.gz
-- Cleaning sources at D:/projects/vcpkg/buildtrees/openssl-windows/src/openssl-1-09fb822c56.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/projects/vcpkg/downloads/openssl-1.1.1h.tar.gz
-- Using source at D:/projects/vcpkg/buildtrees/openssl-windows/src/openssl-1-09fb822c56.clean
-- Copying openssl release source files...
-- Copying openssl release source files... done
-- Configure x86-windows-rel
-- Configure x86-windows-rel done
-- Build x86-windows-rel
-- Build x86-windows-rel done
-- Copying openssl debug source files...
-- Configure x86-windows-dbg
-- Configure x86-windows-dbg done
-- Build x86-windows-dbg
-- Build x86-windows-dbg done
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:85 (message):
    Command failed: D:/projects/vcpkg/downloads/tools/powershell-core-7.0.3-windows/powershell.exe -noprofile -executionpolicy Bypass -nologo -file D:/projects/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary D:/projects/vcpkg/packages/openssl-windows_x86-windows/tools/openssl/openssl.exe -installedDir D:/projects/vcpkg/packages/openssl-windows_x86-windows/bin
    Working Directory: D:/projects/vcpkg
    Error code: -2146232797
    See logs for more information:
      D:\projects\vcpkg\buildtrees\openssl-windows\copy-tool-dependencies-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:27 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:37 (search_for_dependencies)
  ports/openssl-windows/portfile.cmake:169 (vcpkg_copy_tool_dependencies)
  scripts/ports.cmake:79 (include)


Error: Building package openssl-windows:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-windows:x86-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

```
**copy-tool-dependencies-err.log**
```
Process terminated. Infinite recursion during resource lookup within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: Arg_AccessViolationException
   at System.Environment.FailFast(System.String)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String, System.String)
   at System.AccessViolationException..ctor()
   at System.SpanHelpers.IndexOf(Char ByRef, Char, Int32)
   at System.Globalization.CultureData.InitCultureData()
   at System.Globalization.CultureData.CreateCultureData(System.String, Boolean)
   at System.Globalization.CultureData.GetCultureData(System.String, Boolean)
   at System.Globalization.CultureInfo..ctor(System.String, Boolean)
   at System.Globalization.CultureInfo.GetCultureByName(System.String)
   at System.Globalization.CultureInfo.GetUserDefaultUICulture()
   at System.Globalization.CultureInfo.InitializeUserDefaultUICulture()
   at System.Globalization.CultureInfo.get_UserDefaultUICulture()
   at System.Globalization.CultureInfo.get_CurrentUICulture()
   at System.Resources.ResourceManager.GetString(System.String, System.Globalization.CultureInfo)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String, System.String)
   at System.AccessViolationException..ctor()
   at System.SpanHelpers.IndexOf(Char ByRef, Char, Int32)
   at System.String.Ctor(Char*)
   at System.AppContext.Setup(Char**, Char**, Int32)
```

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/12849.
