### ISSUE TITLE
[libpq:x64-windows] build failure

### ISSUE THREAD

**Issue by WKleinschmit** [microsoft/vcpkg#15791]
**Host Environment**
- OS: Windows 10
- Compiler: 19.22.27906

**To Reproduce**
`./vcpkg install libpq:x64-windows`

**Failure logs** 
```
Building package libpq[core,openssl,zlib]:x64-windows...
-- Using cached D:/Depot/OpenCppCoverage/Build/ThirdParty/vcpkg/downloads/postgresql-12.0.tar.bz2
-- Using source at D:/Depot/OpenCppCoverage/Build/ThirdParty/vcpkg/buildtrees/libpq/src/tgresql-12-e44317bad5
-- Copying libpq source files to D:/Depot/OpenCppCoverage/Build/ThirdParty/vcpkg/buildtrees/libpq/x64-windows-rel...
-- Copying libpq source files... done
-- Applying patch patches/windows/Solution_RELEASE.patch
-- Patches applied!
-- Building libpq x64-windows-RELEASE...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: D:/Depot/OpenCppCoverage/Build/ThirdParty/vcpkg/downloads/tools/perl/perl/bin/perl.exe build.pl RELEASE libpq
    Working Directory: D:/Depot/OpenCppCoverage/Build/ThirdParty/vcpkg/buildtrees/libpq/x64-windows-rel/src/tools/msvc
    Error code: 255
    See logs for more information:
      D:\Depot\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\libpq\build-libpq-x64-windows-RELEASE-out.log
      D:\Depot\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\libpq\build-libpq-x64-windows-RELEASE-err.log

Call Stack (most recent call first):
  ports/libpq/portfile.cmake:194 (vcpkg_execute_required_process)
  scripts/ports.cmake:94 (include)


Error: Building package libpq:x64-windows failed with: BUILD_FAILED
```
---8<-------Content of build-libpq-x64-windows-RELEASE-err.log:
```
Unhandled Exception: System.Runtime.InteropServices.COMException: Invalid value for registry (Exception from HRESULT: 0x80040153 (REGDB_E_INVALIDVALUE))
   at System.Runtime.InteropServices.RuntimeEnvironment.GetDeveloperPath()
   at System.AppDomain.SetupFusionStore(AppDomainSetup info, AppDomainSetup oldInfo)
   at System.AppDomain.SetupDomain(Boolean allowRedirects, String path, String configFile, String[] propertyNames, String[] propertyValues)
```

**Comment by JackBoosY** [comment]
Hi @WKleinschmit, thanks for reporting this issue!
Can you provide full log _D:\Depot\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\libpq\build-libpq-x64-windows-RELEASE-out.log_ and provide your system-inside `powershell` version?

Thanks.

**Comment by WKleinschmit** [comment]
PowerShell version is  5.1.19041.610

[build-libpq-x64-windows-RELEASE-out.log](https://github.com/microsoft/vcpkg/files/5854706/build-libpq-x64-windows-RELEASE-out.log)

**Comment by PhoebeHui** [comment]
@WKleinschmit, could you check if it's same issue with https://stackoverflow.com/questions/11026168/vshost-crash-regdb-e-invalidvalue-loading-specific-project, if so, could you try the solution and see if it works for you?

**Comment by PhoebeHui** [comment]
Please reopne this issue if it still be a problem for you.
