### ISSUE TITLE
[harfbuzz] build failure

### ISSUE THREAD

**Issue by Krzmbrzl** [microsoft/vcpkg#16262]
**Host Environment**
- OS: Windows10
- Compiler:. MSVC (VS2019)

**To Reproduce**
`./vcpkg install harfbuzz:x64-windows-static-md`

**Failure logs** 
```
.\vcpkg install harfbuzz:x64-windows-static-md
Computing installation plan...
The following packages will be built and installed:
    harfbuzz[core]:x64-windows-static-md -> 2.7.4
Detecting compiler hash for triplet x64-windows-static-md...
Could not locate cached archive: C:\Users\dev-user\AppData\Local\vcpkg\archives\1f\1f35d44d702c88f19d8772179a3342b127d4f716.zip
Starting package 1/1: harfbuzz:x64-windows-static-md
Building package harfbuzz[core]:x64-windows-static-md...
-- Using community triplet x64-windows-static-md. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: \\VBoxSvr\Shared\vcpkg\triplets\community\x64-windows-static-md.cmake
-- Using cached S:/vcpkg/downloads/harfbuzz-harfbuzz-7236c7e29cef1c2d76c7a284c5081ff4d3aa1127.tar.gz
-- Extracting source S:/vcpkg/downloads/harfbuzz-harfbuzz-7236c7e29cef1c2d76c7a284c5081ff4d3aa1127.tar.gz
-- Applying patch 0002-fix-uwp-build.patch
-- Using source at S:/vcpkg/buildtrees/harfbuzz/src/f4d3aa1127-a820a32874.clean
-- Configuring x64-windows-static-md
-- Using msys root at S:/vcpkg/downloads/tools/msys2/50864d9fae363d6e
-- Configuring x64-windows-static-md-dbg
CMake Error at //VBoxSvr/Shared/vcpkg/scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: S:/vcpkg/downloads/tools/python/python-3.9.0-x64/python.exe S:/vcpkg/downloads/tools/meson/meson-f5871f434a5b768ad9fcafa797a6db0286421842/meson.py -Dicu=disabled -Dgraphite=disabled -Dglib=disabled -Dfreetype=enabled -Dgobject=disabled -Dcairo=disabled -Dfontconfig=disabled -Dintrospection=disabled -Ddocs=disabled -Dtests=disabled -Dbenchmark=disabled --buildtype plain --backend ninja --wrap-mode nodownload --native S:/vcpkg/buildtrees/harfbuzz/meson-nativ-x64-windows-static-md.log --default-library static --libdir lib --native S:/vcpkg/buildtrees/harfbuzz/meson-nativ-x64-windows-static-md-debug.log -Ddebug=true --prefix S:/vcpkg/packages/harfbuzz_x64-windows-static-md/debug --includedir ../include -Dcmake_prefix_path=['S:/vcpkg/installed/x64-windows-static-md/debug','S:/vcpkg/installed/x64-windows-static-md','S:/vcpkg/installed/x64-windows-static-md/share'] S:/vcpkg/buildtrees/harfbuzz/src/f4d3aa1127-a820a32874.clean
    Working Directory: S:/vcpkg/buildtrees/harfbuzz/x64-windows-static-md-dbg
    Error code: 1
    See logs for more information:
      S:\vcpkg\buildtrees\harfbuzz\config-x64-windows-static-md-dbg-out.log

Call Stack (most recent call first):
  //VBoxSvr/Shared/vcpkg/scripts/cmake/vcpkg_configure_meson.cmake:482 (vcpkg_execute_required_process)
  ports/harfbuzz/portfile.cmake:20 (vcpkg_configure_meson)
  //VBoxSvr/Shared/vcpkg/scripts/ports.cmake:131 (include)


Error: Building package harfbuzz:x64-windows-static-md failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: harfbuzz:x64-windows-static-md
  Vcpkg version: 2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35

Additionally, attach any relevant sections from the log files above.
```
The mentioned log file:
```
DEPRECATION: c_args in the [properties] section of the machine file is deprecated, use the [built-in options] section.
DEPRECATION: cpp_args in the [properties] section of the machine file is deprecated, use the [built-in options] section.
DEPRECATION: c_link_args in the [properties] section of the machine file is deprecated, use the [built-in options] section.
DEPRECATION: cpp_link_args in the [properties] section of the machine file is deprecated, use the [built-in options] section.
WARNING: Recommend using either -Dbuildtype or -Doptimization + -Ddebug. Using both is redundant since they override each other. See: https://mesonbuild.com/Builtin-options.html#build-type-options
The Meson build system
Version: 0.56.99
Source dir: \\VBoxSvr\Shared\vcpkg\buildtrees\harfbuzz\src\f4d3aa1127-a820a32874.clean
Build dir: \\VBoxSvr\Shared\vcpkg\buildtrees\harfbuzz\x64-windows-static-md-dbg
Build type: native build
Project name: harfbuzz
Project version: 2.7.4
C compiler for the host machine: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe (msvc 19.28.29334 "Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29334 for x64")
C linker for the host machine: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/link.exe link 14.28.29334.0
C++ compiler for the host machine: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe (msvc 19.28.29334 "Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29334 for x64")
C++ linker for the host machine: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/link.exe link 14.28.29334.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C++ supports arguments /utf-8: YES 
Compiler for C++ supports link arguments -Bsymbolic-functions: NO 
Compiler for C++ supports arguments -fno-exceptions: NO 
Compiler for C++ supports arguments -fno-rtti: NO 
Compiler for C++ supports arguments -fno-threadsafe-statics: NO 
Compiler for C++ supports arguments -fvisibility-inlines-hidden: NO 
Library m found: NO
Found pkg-config: S:/vcpkg/downloads/tools/msys2/50864d9fae363d6e/mingw32/bin/pkg-config.exe (0.29.2)
Run-time dependency freetype2 found: YES 23.4.17
Dependency glib-2.0 skipped: feature glib disabled
Dependency gobject-2.0 skipped: feature gobject disabled
Dependency fontconfig skipped: feature fontconfig disabled
Dependency graphite2 skipped: feature graphite disabled
Compiler for C++ supports arguments -Wno-non-virtual-dtor: NO 
WARNING: msvc does not support C++11; attempting best effort; setting the standard to C++14
Has header "unistd.h" : NO 
Has header "sys/mman.h" : NO 
Has header "stdbool.h" : YES 
Checking for function "atexit" : NO 
Checking for function "mprotect" : NO 
Checking for function "sysconf" : NO 
Checking for function "getpagesize" : NO 
Checking for function "mmap" : NO 
Checking for function "isatty" : YES 
Checking for function "FT_Get_Var_Blend_Coordinates" with dependency freetype2: YES 
Checking for function "FT_Set_Var_Blend_Coordinates" with dependency freetype2: YES 
Checking for function "FT_Done_MM_Var" with dependency freetype2: YES 
Checking if "Intel atomics" links: NO 
Checking if "Solaris atomic ops" links: NO 
Program gen-hb-version.py found: YES (S:\vcpkg\downloads\tools\python\python-3.9.0-x64\python.exe \\VBoxSvr\Shared\vcpkg\buildtrees\harfbuzz\src\f4d3aa1127-a820a32874.clean\src\gen-hb-version.py)
WARNING: Project targeting '>= 0.47.0' but tried to use feature introduced in '0.50.0': install arg in configure_file.
Configuring hb-version.h with command

\\VBoxSvr\Shared\vcpkg\buildtrees\harfbuzz\src\f4d3aa1127-a820a32874.clean\src\meson.build:1:0: ERROR: Running configure command failed.

Traceback (most recent call last):
  File "\\VBoxSvr\Shared\vcpkg\buildtrees\harfbuzz\src\f4d3aa1127-a820a32874.clean\src\gen-hb-version.py", line 36, in <module>
    shutil.copyfile (OUTPUT, os.path.join (CURRENT_SOURCE_DIR, os.path.basename (OUTPUT)))
  File "shutil.py", line 241, in copyfile
shutil.SameFileError: '\\\\VBoxSvr\\Shared\\vcpkg\\buildtrees\\harfbuzz\\x64-windows-static-md-dbg\\src\\hb-version.h' and '\\\\VBoxSvr\\Shared\\vcpkg\\buildtrees\\harfbuzz\\src\\f4d3aa1127-a820a32874.clean\\src\\hb-version.h' are the same file
```

I assme the error is either
```
WARNING: Project targeting '>= 0.47.0' but tried to use feature introduced in '0.50.0': install arg in configure_file.
```
or the last lines about these files being the same. Idk what files these are, so I don't just want to blindly start deleting either of them to see if that resolves the issue :thinking: 

**Additional context**

I am using the latest vcpkg version available as of now: e2ecca095c77180ab0114600f78b557ab6c99fc2

**Comment by Neumann-A** [comment]
The warning can be ignored. 
The question is why does:
`\\\\VBoxSvr\\Shared\\vcpkg\\buildtrees\\harfbuzz\\x64-windows-static-md-dbg\\src\\hb-version.h`
exist already? 
It simply shouldn't unless the buildtrees/triplet-config folder has not been successfully deleted in vcpkg_configure_meson

**Comment by Krzmbrzl** [comment]
So I previously had vcpkg installed and used (including this package). I now did an update by 
1. `git pull`
2. `vcpkg upgrade --no-dry-run`

I did that from my Linux machine. This caused vcpkg to remove all of the outdated ports, but it then ended up with an error stating it couldn't build a windows triplet on Linux (I am using the same vcpkg directory for windows and Linux).
I re-installed the necessary packages manually on Linux, where it worked fine and now I wanted to do the same on Windows.

So I guess the cleaning could have been interrupted by the mentioned error.

Now that I know that this file should not exist, I'll delete it manually and see if it works now. Thanks for the hint :+1:

**Comment by Neumann-A** [comment]
theoretically you can remove `\\\\VBoxSvr\\Shared\\vcpkg\\buildtrees\\harfbuzz\\` completely but `\\\\VBoxSvr\\Shared\\vcpkg\\buildtrees\\harfbuzz\\x64-windows-static-md-dbg\\` should be removed/cleaned by `vcpkg_configure_meson` before configure is called.

**Comment by Krzmbrzl** [comment]
Okay so deleting `\\\\VBoxSvr\\Shared\\vcpkg\\buildtrees\\harfbuzz\\x64-windows-static-md-dbg\\src\\hb-version.h` did not resolve the issue.

> \\\\VBoxSvr\\Shared\\vcpkg\\buildtrees\\harfbuzz\\x64-windows-static-md-dbg\\ should be removed/cleaned by vcpkg_configure_meson before configure is called.

I can confirm that it is cleaned before configuring.

I will now try to delete the entire `harfbuzz` directory to see if that helps

**Comment by Krzmbrzl** [comment]
Nope that did not help either. The error is still the same.

**Comment by Neumann-A** [comment]
I think there are two upstream bugs here:
a) meson running the `configure_file` command twice for some reason (probably has to do with your network share setup)
b) harfbuzz (`gen-hb-version.py`) erroring on the same file errors.

**Comment by Krzmbrzl** [comment]
> probably has to do with your network share setup

Dunno if that's relevant, but this is not a network drive. I am running Windows 10 in a VM (via VirtualBox) and I mounted the vcpkg directory from my local hard drive to the VM.

**Comment by Neumann-A** [comment]
> Dunno if that's relevant, but this is not a network drive. I am running Windows 10 in a VM (via VirtualBox) and I mounted the vcpkg directory from my local hard drive to the VM.

Doesn't matter the path is still an UNC network path ;)

**Comment by Krzmbrzl** [comment]
I just checked the python script and then the [documentation](https://docs.python.org/3/library/shutil.html) of `shutil.copyfile` and there it says:
 >  If src and dst specify the same file, SameFileError is raised.

This suggests that the script is somehow trying to copy the file to the location it already is in and that this is causing the error :eyes:
