### ISSUE TITLE
Error: Building package wxpython:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by cwangbh** [microsoft/vcpkg#17115]
**Host Environment**
- OS:  Windows
- Compiler: visual studio 2017 

**To Reproduce**
`./vcpkg install wxpython`

**Failure logs** 

![image](https://user-images.githubusercontent.com/21260868/113711674-d21ba080-9717-11eb-948f-882fcf4a781b.png)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JonLiu1993** [comment]
@cwangbh ,Is this port in the vcpkg library? I cannot install it locally

**Comment by cwangbh** [comment]
> @cwangbh ,Is this port in the vcpkg library? I cannot install it locally
Hi, i think i have raised the issue in the wrong place. The vcpkg is included maintained by another software called KICAD.

**Comment by l8513454** [comment]
Traceback (most recent call last):
  File "F:\VS2022-Project\KICAD\vcpkg\buildtrees\wxpython\src\8854625dd8-861bd167bd.clean\public\get-pip.py", line 33324, in <module>
    main()
  File "F:\VS2022-Project\KICAD\vcpkg\buildtrees\wxpython\src\8854625dd8-861bd167bd.clean\public\get-pip.py", line 135, in main
    bootstrap(tmpdir=tmpdir)
  File "F:\VS2022-Project\KICAD\vcpkg\buildtrees\wxpython\src\8854625dd8-861bd167bd.clean\public\get-pip.py", line 111, in bootstrap
    monkeypatch_for_cert(tmpdir)
  File "F:\VS2022-Project\KICAD\vcpkg\buildtrees\wxpython\src\8854625dd8-861bd167bd.clean\public\get-pip.py", line 92, in monkeypatch_for_cert
    from pip._internal.commands.install import InstallCommand
  File "C:\Users\Administrator\AppData\Local\Temp\tmp1gm4sd6c\pip.zip\pip\_internal\commands\__init__.py", line 9, in <module>
  File "C:\Users\Administrator\AppData\Local\Temp\tmp1gm4sd6c\pip.zip\pip\_internal\cli\base_command.py", line 15, in <module>
  File "C:\Users\Administrator\AppData\Local\Temp\tmp1gm4sd6c\pip.zip\pip\_internal\cli\cmdoptions.py", line 23, in <module>
  File "C:\Users\Administrator\AppData\Local\Temp\tmp1gm4sd6c\pip.zip\pip\_internal\cli\parser.py", line 12, in <module>
  File "C:\Users\Administrator\AppData\Local\Temp\tmp1gm4sd6c\pip.zip\pip\_internal\configuration.py", line 26, in <module>
  File "C:\Users\Administrator\AppData\Local\Temp\tmp1gm4sd6c\pip.zip\pip\_internal\utils\logging.py", line 27, in <module>
  File "C:\Users\Administrator\AppData\Local\Temp\tmp1gm4sd6c\pip.zip\pip\_internal\utils\misc.py", line 39, in <module>
  File "C:\Users\Administrator\AppData\Local\Temp\tmp1gm4sd6c\pip.zip\pip\_internal\locations\__init__.py", line 14, in <module>
  File "C:\Users\Administrator\AppData\Local\Temp\tmp1gm4sd6c\pip.zip\pip\_internal\locations\_distutils.py", line 9, in <module>
ModuleNotFoundError: No module named 'distutils'

**Comment by JonLiu1993** [comment]
@l8513454, If you have a new problem, please open a new issue.
