### ISSUE TITLE
wxpython:x64-windows build failure

### ISSUE THREAD

**Issue by hiber-wang** [microsoft/vcpkg#17591]
**Host Environment**
- OS: windows
- Compiler: revision

**To Reproduce**
```
./vcpkg install wxpython:x64-windows

Computing installation plan...
The following packages will be built and installed:
    wxpython[core]:x64-windows -> 3.x.x
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\user2\AppData\Local\vcpkg\archives\91\917e4befc6b973061a86deecf9bd9a83580b9237.zip
Starting package 1/1: wxpython:x64-windows
Building package wxpython[core]:x64-windows...
-- Using cached D:/app/vcpkg/vcpkg/downloads/wxWidgets-phoenix-bfb335672e3fe0c75de645b7d859e558babfaca2.tar.gz
-- Cleaning sources at D:/app/vcpkg/vcpkg/buildtrees/wxpython/src/58babfaca2-59a726416f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/app/vcpkg/vcpkg/downloads/wxWidgets-phoenix-bfb335672e3fe0c75de645b7d859e558babfaca2.tar.gz
-- Using source at D:/app/vcpkg/vcpkg/buildtrees/wxpython/src/58babfaca2-59a726416f.clean
-- Using cached D:/app/vcpkg/vcpkg/downloads/wxWidgets-wxWidgets-v3.1.4.tar.gz
-- Cleaning sources at D:/app/vcpkg/vcpkg/buildtrees/wxpython/src/v3.1.4-d3b845b5d1.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/app/vcpkg/vcpkg/downloads/wxWidgets-wxWidgets-v3.1.4.tar.gz
-- Using source at D:/app/vcpkg/vcpkg/buildtrees/wxpython/src/v3.1.4-d3b845b5d1.clean
-- Using msys root at D:/app/vcpkg/vcpkg/downloads/tools/msys2/969c0913b9df89e1
-- Found external ninja('1.10.2').
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:144 (message):
    Command failed: D:/app/CMAKE/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: D:/app/vcpkg/vcpkg/buildtrees/wxpython/x64-windows-dbg
    See logs for more information:
      D:\app\vcpkg\vcpkg\buildtrees\wxpython\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:27 (vcpkg_build_cmake)
  ports/wxpython/portfile.cmake:44 (vcpkg_install_cmake)
  scripts/ports.cmake:131 (include)


Error: Building package wxpython:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: wxpython:x64-windows
  Vcpkg version: 2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35
Additionally, attach any relevant sections from the log files above.
```

**Comment by autoantwort** [comment]
> Additionally, attach any relevant sections from the log files above.
> D:\app\vcpkg\vcpkg\buildtrees\wxpython\install-x64-windows-dbg-out.log

**Comment by hiber-wang** [comment]
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/6405448/install-x64-windows-dbg-out.log)

**Comment by JackBoosY** [comment]
```
[3/65] cmd.exe /C "cd /D D:\app\vcpkg\vcpkg\buildtrees\wxpython\src\58babfaca2-59a726416f.clean && D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe ./build.py etg --nodoc sip"
FAILED: CMakeFiles/sipgen 
cmd.exe /C "cd /D D:\app\vcpkg\vcpkg\buildtrees\wxpython\src\58babfaca2-59a726416f.clean && D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe ./build.py etg --nodoc sip"
Will build using: "D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe"
3.9.0 (default, Apr 30 2021, 15:41:51) [MSC v.1928 64 bit (AMD64)]
Python's architecture is 64bit
cfg.VERSION: 4.1.1a1

Running command: etg
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg\_core.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg\_adv.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg\_aui.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg\_dataview.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg\_glcanvas.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg\_grid.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg\_html.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg\_html2.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg\_media.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg\_msw.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg\_propgrid.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg\_ribbon.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg\_richtext.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg\_stc.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg\_webkit.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg\_xml.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg\_xrc.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg/defs.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg/debug.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg/object.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg/clntdatactnr.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg/wxdatetime.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg/stopwatch.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg/windowid.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg/platinfo.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg/vidmode.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg/display.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg/intl.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg/translation.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg/cmndata.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg/gdicmn.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg/geometry.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg/affinematrix2d.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg/position.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg/colour.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg/stream.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg/filesys.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg/image.py --sip --nodoc
"D:\app\vcpkg\vcpkg\installed\x64-windows\tools\python3\python.exe" etg/gdiobj.py --sip --nodoc
Traceback (most recent call last):
  File "D:\app\vcpkg\vcpkg\buildtrees\wxpython\src\58babfaca2-59a726416f.clean\build.py", line 2235, in <module>
    main(sys.argv[1:])
  File "D:\app\vcpkg\vcpkg\buildtrees\wxpython\src\58babfaca2-59a726416f.clean\build.py", line 204, in main
    function(options, args)
  File "D:\app\vcpkg\vcpkg\buildtrees\wxpython\src\58babfaca2-59a726416f.clean\build.py", line 1083, in cmd_etg
    ns = loadETG(script)
  File "D:\app\vcpkg\vcpkg\buildtrees\wxpython\src\58babfaca2-59a726416f.clean\buildtools\config.py", line 662, in loadETG
    myExecfile(name, ns.nsdict())
  File "D:\app\vcpkg\vcpkg\buildtrees\wxpython\src\58babfaca2-59a726416f.clean\buildtools\config.py", line 888, in myExecfile
    exec(f.read(), ns)
UnicodeDecodeError: 'gbk' codec can't decode byte 0x97 in position 7881: illegal multibyte sequence
```

**Comment by JackBoosY** [comment]
We don't have a port named `wxpython`, can you please provide the port folder?

**Comment by JackBoosY** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!

**Comment by Mxd353** [comment]
ttps://github.com/wxWidgets/Phoenix.git
