### ISSUE TITLE
[tensorflow:x64-windows] build failure 

### ISSUE THREAD

**Issue by traumedy** [microsoft/vcpkg#18500]
**Host Environment**
- OS: Windows Version 10.0.19043.1055
- Compiler: Visual Studio 2019 Community

**To Reproduce**
```
>vcpkg install tensorflow:x64-windows
```

**Failure logs** 
```
Starting package 1/1: tensorflow:x64-windows
Building package tensorflow[core]:x64-windows...
[DEBUG] CreateProcessW("C:\vcpkg\downloads\tools\cmake-3.20.2-windows\cmake-3.20.2-windows-i386\bin\cmake.exe" -DALL_FEATURES= -DCURRENT_PORT_DIR=C:/vcpkg/ports/tensorflow -D_HOST_TRIPLET=x64-windows -DFEATURES=core -DPORT=tensorflow -DVCPKG_USE_HEAD_VERSION=0 -D_VCPKG_DOWNLOAD_TOOL=BUILT_IN -D_VCPKG_EDITABLE=0 -D_VCPKG_NO_DOWNLOADS=0 -DCMD=BUILD -DDOWNLOADS=C:/vcpkg/downloads -DTARGET_TRIPLET=x64-windows "-DTARGET_TRIPLET_FILE=C:\vcpkg\triplets\x64-windows.cmake" -DVCPKG_BASE_VERSION=2021-05-05 -DVCPKG_CONCURRENCY=13 -DVCPKG_PLATFORM_TOOLSET=v142 -DGIT=c:/code/depot_tools/git.bat -DVCPKG_ROOT_DIR=C:/vcpkg -DPACKAGES_DIR=C:/vcpkg/packages -DBUILDTREES_DIR=C:/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=C:/vcpkg/installed -DDOWNLOADS=C:/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "C:\vcpkg\scripts\ports.cmake")
-- Using msys root at C:/vcpkg/downloads/tools/msys2/b3b3d399e80e310e
-- Using C:/vcpkg/downloads/tensorflow-tensorflow-v2.4.1.tar.gz
-- Extracting source C:/vcpkg/downloads/tensorflow-tensorflow-v2.4.1.tar.gz
-- Applying patch C:/vcpkg/installed/x64-windows/share/tensorflow-common/fix-build-error.patch
-- Applying patch C:/vcpkg/installed/x64-windows/share/tensorflow-common/fix-windows-build.patch
-- Using source at C:/vcpkg/buildtrees/tensorflow/src/v2.4.1-81b5bb6ede.clean
-- Configuring TensorFlow (dbg)
-- Warning: Building TensorFlow can take an hour or more.
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: C:/vcpkg/downloads/tools/msys2/b3b3d399e80e310e/usr/bin/bash.exe --noprofile --norc -c "'C:/vcpkg/downloads/tools/bazel/3.7.0-windows/bazel.exe' --output_user_root='C:/vcpkg/buildtrees/tensorflow/.bzl' build --verbose_failures --compilation_mode=dbg --features=fastbuild    --python_path='C:/vcpkg/downloads/tools/msys2/b3b3d399e80e310e/mingw64/bin/python3.exe' --define=no_tensorflow_py_deps=true ///tensorflow:tensorflow.dll ///tensorflow:install_headers"
    Working Directory: C:/vcpkg/buildtrees/tensorflow/x64-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\tensorflow\build-x64-windows-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/tensorflow-common/tensorflow-common.cmake:230 (vcpkg_execute_build_process)
  ports/tensorflow/portfile.cmake:7 (include)
  scripts/ports.cmake:139 (include)


[DEBUG] cmd_execute_and_stream_data() returned 1 after 27515884 us
Error: Building package tensorflow:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: tensorflow:x64-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

Additionally, attach any relevant sections from the log files above.
[DEBUG] C:\A\1\121\s\src\vcpkg\install.cpp(511)
[DEBUG] Exiting after 31109065 us (31108257 us)

----------------
[\vcpkg\buildtrees\tensorflow\build-x64-windows-dbg-err.log]
...
ERROR: no such package '@io_bazel_rules_go//go': error running 'git init C:/vcpkg/buildtrees/tensorflow/.bzl/yvfmeljr/external/io_bazel_rules_go' while working with @io_bazel_rules_go:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("git" init C:/vcpkg/buildtrees/tensorflow/.bzl/yvfmeljr/external/io_bazel_rules_go): The system cannot find the file specified.
 (error: 2)
...
```
[build-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/6669513/build-x64-windows-dbg-err.log)

**Comment by JackBoosY** [comment]
```
ERROR: An error occurred during the fetch of repository 'io_bazel_rules_go':
   Traceback (most recent call last):
	File "C:/vcpkg/buildtrees/tensorflow/.bzl/yvfmeljr/external/bazel_tools/tools/build_defs/repo/git.bzl", line 181, column 30, in _git_repository_implementation
		update = _clone_or_update(ctx)
	File "C:/vcpkg/buildtrees/tensorflow/.bzl/yvfmeljr/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update
		git_ = git_repo(ctx, directory)
	File "C:/vcpkg/buildtrees/tensorflow/.bzl/yvfmeljr/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
		_update(ctx, git_repo)
	File "C:/vcpkg/buildtrees/tensorflow/.bzl/yvfmeljr/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, column 9, in _update
		init(ctx, git_repo)
	File "C:/vcpkg/buildtrees/tensorflow/.bzl/yvfmeljr/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 118, column 15, in init
		_error(ctx.name, cl, st.stderr)
	File "C:/vcpkg/buildtrees/tensorflow/.bzl/yvfmeljr/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 190, column 9, in _error
		fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git init C:/vcpkg/buildtrees/tensorflow/.bzl/yvfmeljr/external/io_bazel_rules_go' while working with @io_bazel_rules_go:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("git" init C:/vcpkg/buildtrees/tensorflow/.bzl/yvfmeljr/external/io_bazel_rules_go): The system cannot find the file specified.
 (error: 2)
```

**Comment by traumedy** [comment]
Same results when cloned to D:
```
D:\>"C:\Program Files\Git\cmd\git.exe" clone https://github.com/microsoft/vcpkg.git
Cloning into 'vcpkg'...
...
D:\>cd vcpkg

D:\vcpkg>bootstrap-vcpkg.bat
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/vcpkg.exe -> D:\vcpkg\vcpkg.exe
Done.

D:\vcpkg>vcpkg install tensorflow
...
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: D:/vcpkg/downloads/tools/msys2/b3b3d399e80e310e/usr/bin/bash.exe --noprofile --norc -c "'D:/vcpkg/downloads/tools/bazel/3.7.0-windows/bazel.exe' --output_user_root='D:/vcpkg/buildtrees/tensorflow/.bzl' build --verbose_failures --compilation_mode=dbg --features=fastbuild    --python_path='D:/vcpkg/downloads/tools/msys2/b3b3d399e80e310e/mingw64/bin/python3.exe' --define=no_tensorflow_py_deps=true ///tensorflow:tensorflow.dll ///tensorflow:install_headers"
    Working Directory: D:/vcpkg/buildtrees/tensorflow/x64-windows-dbg
    See logs for more information:
      D:\vcpkg\buildtrees\tensorflow\build-x64-windows-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/tensorflow-common/tensorflow-common.cmake:230 (vcpkg_execute_build_process)
  ports/tensorflow/portfile.cmake:7 (include)
  scripts/ports.cmake:139 (include)
```

[build-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/6674923/build-x64-windows-dbg-err.log)


Possibly of note:  Immediately after build failure, if I try to remove the `buildtrees` directory I get in use/permission errors:
```
D:\vcpkg>rd /s buildtrees
buildtrees, Are you sure (Y/N)? y
buildtrees\tensorflow\.bzl\57u5iwxm\java.log.monster.Josh.log.java.20210617-225547.3524 - The process cannot access the file because it is being used by another process.
buildtrees\tensorflow\.bzl\57u5iwxm\server\jvm.out - The process cannot access the file because it is being used by another process.
buildtrees\tensorflow\.bzl\install\3d1356cc22901f271d47ddd780d95b50\A-server.jar - The process cannot access the file because it is being used by another process.
buildtrees\tensorflow\.bzl\install\3d1356cc22901f271d47ddd780d95b50\cpu_profiler.dll - Access is denied.
buildtrees\tensorflow\.bzl\install\3d1356cc22901f271d47ddd780d95b50\embedded_tools\jdk\bin\java.dll - Access is denied.
buildtrees\tensorflow\.bzl\install\3d1356cc22901f271d47ddd780d95b50\embedded_tools\jdk\bin\java.exe - Access is denied.
buildtrees\tensorflow\.bzl\install\3d1356cc22901f271d47ddd780d95b50\embedded_tools\jdk\bin\jimage.dll - Access is denied.
buildtrees\tensorflow\.bzl\install\3d1356cc22901f271d47ddd780d95b50\embedded_tools\jdk\bin\jli.dll - Access is denied.
buildtrees\tensorflow\.bzl\install\3d1356cc22901f271d47ddd780d95b50\embedded_tools\jdk\bin\management.dll - Access is denied.
buildtrees\tensorflow\.bzl\install\3d1356cc22901f271d47ddd780d95b50\embedded_tools\jdk\bin\management_ext.dll - Access is denied.
buildtrees\tensorflow\.bzl\install\3d1356cc22901f271d47ddd780d95b50\embedded_tools\jdk\bin\msvcp140.dll - Access is denied.
buildtrees\tensorflow\.bzl\install\3d1356cc22901f271d47ddd780d95b50\embedded_tools\jdk\bin\net.dll - Access is denied.
buildtrees\tensorflow\.bzl\install\3d1356cc22901f271d47ddd780d95b50\embedded_tools\jdk\bin\nio.dll - Access is denied.
buildtrees\tensorflow\.bzl\install\3d1356cc22901f271d47ddd780d95b50\embedded_tools\jdk\bin\server\jvm.dll - Access is denied.
buildtrees\tensorflow\.bzl\install\3d1356cc22901f271d47ddd780d95b50\embedded_tools\jdk\bin\sunec.dll - Access is denied.
buildtrees\tensorflow\.bzl\install\3d1356cc22901f271d47ddd780d95b50\embedded_tools\jdk\bin\vcruntime140.dll - Access is denied.
buildtrees\tensorflow\.bzl\install\3d1356cc22901f271d47ddd780d95b50\embedded_tools\jdk\bin\verify.dll - Access is denied.
buildtrees\tensorflow\.bzl\install\3d1356cc22901f271d47ddd780d95b50\embedded_tools\jdk\bin\zip.dll - Access is denied.
buildtrees\tensorflow\.bzl\install\3d1356cc22901f271d47ddd780d95b50\embedded_tools\jdk\lib\modules - The process cannot access the file because it is being used by another process.
buildtrees\tensorflow\.bzl\install\3d1356cc22901f271d47ddd780d95b50\windows_jni.dll - Access is denied.
```

**Comment by JackBoosY** [comment]
```
buildtrees\tensorflow\.bzl\57u5iwxm\server\jvm.out - The process cannot access the file because it is being used by another process.
```

Parallel build needs to be turned off.
cc @jgehw

**Comment by jgehw** [comment]
> Parallel build needs to be turned off.

I wouldn't say so: this error arose from parallel *manual* cleanup while no all build processes had been killed before.

The build error was caused by:
`CreateProcessW("git" init C:/vcpkg/buildtrees/tensorflow/.bzl/yvfmeljr/external/io_bazel_rules_go): The system cannot find the file specified.`

Seems that `git` is not in the `PATH` environment variable.

**Comment by JackBoosY** [comment]
@traumedy Can you please remove folder _C:/vcpkg/buildtrees/tensorflow_ and try again?

**Comment by JackBoosY** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
