### ISSUE TITLE
[wxpython:x64-windows] build failure

### ISSUE THREAD

**Issue by WANFULEI** [microsoft/vcpkg#18620]
Error: Building package wxpython:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: wxpython:x64-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

Traceback (most recent call last):
  File "F:\study\wxpython\src\730562224b-85d8de3c3e.clean\build.py", line 2293, in <module>
    main(sys.argv[1:])
  File "F:\study\buildtrees\wxpython\src\730562224b-85d8de3c3e.clean\build.py", line 201, in main
    function(options, args)
  File "F:\study\wxpython\src\730562224b-85d8de3c3e.clean\build.py", line 1101, in cmd_etg
    ns = loadETG(script)
  File "F:\study\wxpython\src\730562224b-85d8de3c3e.clean\buildtools\config.py", line 694, in loadETG
    myExecfile(name, ns.nsdict())
  File "F:\study\wxpython\src\730562224b-85d8de3c3e.clean\buildtools\config.py", line 920, in myExecfile
    exec(f.read(), ns)
UnicodeDecodeError: 'gbk' codec can't decode byte 0x97 in position 7881: illegal multibyte sequence

**Comment by JonLiu1993** [comment]
@WANFULEI ,Thanks for posting this issue.
We don't have a port named wxpython, can you please provide the port folder?

**Comment by PhoebeHui** [comment]
@WANFULEI, please submit a PR for the new port firstly, and reopen this issue if it still be a problem for you.
