### ISSUE TITLE
[tensorflow] Build failure on x64-osx

### ISSUE THREAD

**Issue by JackBoosY** [microsoft/vcpkg#18809]
When building tensorflow on x64-osx:
```
Starting package 2/2: tensorflow:x64-osx
Building package tensorflow[core]:x64-osx...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: /usr/bin/python3 -c "import numpy"
    Working Directory: /Users/vagrant/Data/buildtrees/tensorflow
    Error code: 1
    See logs for more information:
      /Users/vagrant/Data/buildtrees/tensorflow/prerequesits-numpy-x64-osx-err.log

Call Stack (most recent call first):
  /Users/vagrant/Data/installed/x64-osx/share/tensorflow-common/tensorflow-common.cmake:55 (vcpkg_execute_required_process)
  ports/tensorflow/portfile.cmake:7 (include)
  scripts/ports.cmake:139 (include)


Error: Building package tensorflow:x64-osx failed with: BUILD_FAILED
Elapsed time for package tensorflow:x64-osx: 1.311 s
```

`/Users/vagrant/Data/buildtrees/tensorflow/prerequesits-numpy-x64-osx-err.log` shows:
```
init_dgelsd failed init
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/vagrant/Library/Python/3.8/lib/python/site-packages/numpy/__init__.py", line 391, in <module>
    raise RuntimeError(msg)
RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, more information is available at https://numpy.org/doc/stable/user/building.html#accelerated-blas-lapack-libraries Otherwise report this to the vendor that provided NumPy.
RankWarning: Polyfit may be poorly conditioned
```

**Comment by JackBoosY** [comment]
cc @jgehw

**Comment by JackBoosY** [comment]
Same reason with https://github.com/microsoft/vcpkg/issues/18597.
