### ISSUE TITLE
[wxwidgets] build failure

### ISSUE THREAD

**Issue by ericfont** [microsoft/vcpkg#20471]
**Host Environment**
- OS: github ubuntu-latest
- Compiler: revision

**To Reproduce**
Push this branch and check giyhub action report:

https://github.com/ericfont/Examples_wxWidgets/tree/hosted-basic

**Failure logs** 
https://github.com/ericfont/Examples_wxWidgets/runs/3772013060?check_suite_focus=true
```
Error: Last command execution failed with error code '1'.
    at BaseUtilLib.throwIfErrorCode (/home/runner/work/_actions/lukka/run-vcpkg/main/dist/index.js:4920:19)
    at VcpkgRunner.<anonymous> (/home/runner/work/_actions/lukka/run-vcpkg/main/dist/index.js:5702:28)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/lukka/run-vcpkg/main/dist/index.js:5511:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: run-vcpkg action execution failed: Error: Last command execution failed with error code '1'.
```

**Comment by ericfont** [comment]
I am attaching the log archive of a separate attempt (https://github.com/ericfont/Examples_wxWidgets/actions/runs/1297769945 https://github.com/ericfont/Examples_wxWidgets/tree/hosted-basic-submod-vcpkg): following the lukka hosted-basic-cache-submod_vcpkg.yml example (https://github.com/lukka/CppBuildTasks-Validation/blob/master/.github/workflows/hosted-basic-cache-submod_vcpkg.yml):

[logs_9.zip](https://github.com/microsoft/vcpkg/files/7272281/logs_9.zip)

I will try later to replicate on my personal development machine and maybe with a simpler example to hopefully get a smaller and more useful log output.

**Comment by ericfont** [comment]
I noticed someone else had an issue (https://github.com/microsoft/vcpkg/issues/19649) and [someone said](https://github.com/microsoft/vcpkg/issues/19649#issuecomment-901674127):

> IIRC wxwidget needs gtk3 for Linux, but this is not available in vcpkg (was replaced by gtk4). You may need to install gtk3 dev system packages. wxwidets for Linux is skipped in vcpkg CI.
> But please check the port build logs first.

Don't know if that is relevant to my issue.

**Comment by ericfont** [comment]
and noticing on https://vcpkg.io/en/packages.html that wxwidgets is marked "Not compatible with x64 linux":

![Screenshot_20211004_234215](https://user-images.githubusercontent.com/6502474/135956641-a7d05d75-075e-41dd-84fb-a0e0db02700d.png)

So sounds like the vcpkg people already know about this issue...but doesn't anyone know the specific compatibility failure and is there anything being done about it?

**Comment by dg0yt** [comment]
> doesn't anyone know the specific compatibility failure

As you already noticed: "wxwidget needs gtk3 for Linux, but this is not available in vcpkg (was replaced by gtk4)."

> is there anything being done about it?

Perhaps slowly on the wxwidgets side (towards gtk-4).
Not on the vcpkg side AFAIK. It probably needs a volunteer to re-integrate gtk3.

**Comment by ericfont** [comment]
ok, thanks for clarifying.

**Comment by ericfont** [comment]
> wxwidget needs gtk3 for Linux, but this is not available in vcpkg (was replaced by gtk4)

I guess gtk3 is still buildable prior to this update to gtk4: https://github.com/microsoft/vcpkg/commit/546813ae7b9e2873dd3d38e78b27ac5582feae10#diff-9cecb059859a598a24533a45530e13a69ce765ddf9e53109d232d23eaac795b2

Looking more it seems the best route it is https://github.com/microsoft/vcpkg/issues/1681 to be implemented, and it seems that [simple package versioning support has been announced](https://devblogs.microsoft.com/cppblog/take-control-of-your-vcpkg-dependencies-with-versioning-support/).  So would it just be a matter of using this new versioning feature to specify that wxwidgets on x64-linux must use gtk3?

**Comment by dg0yt** [comment]
You can use versioning in manifest mode, or you can checkout the old version (3.x) of port gtk to a separate directory, to be used as a overlay port. However, this version hasn't been tested in CI for months, so your mileage may vary.

**Comment by ericfont** [comment]
I somehow was able to install `wxwidgets 3.1.5#3` via `vcpkg` on my local arch linux x86-64 machine using the [aur/vcpkg-git 2021.05.12.r575.g6b24f0fa76-1](https://aur.archlinux.org/packages/vcpkg-git/)...I forgot to save the installation log but runnign `vcpkg install wxwidgets` now shows:
```
Computing installation plan...
The following packages are already installed:
    wxwidgets[core]:x64-linux -> 3.1.5#3
Package wxwidgets:x64-linux is already installed
```

and I can see the library files via `ls -lh /usr/share/vcpkg/installed/x64-linux/lib/libwx*`...and since they're named "libwx_gtk3u_" it seems that they were clearly build with gtk3:
```
-rw-r--r-- 1 root root 7.8M Oct  5 00:07 /usr/share/vcpkg/installed/x64-linux/lib/libwx_baseu-3.1.a
-rw-r--r-- 1 root root 1.2M Oct  5 00:07 /usr/share/vcpkg/installed/x64-linux/lib/libwx_baseu_net-3.1.a
-rw-r--r-- 1 root root 143K Oct  5 00:07 /usr/share/vcpkg/installed/x64-linux/lib/libwx_baseu_xml-3.1.a
-rw-r--r-- 1 root root  12K Oct  5 00:07 /usr/share/vcpkg/installed/x64-linux/lib/libwx_gtk3u_adv-3.1.a
-rw-r--r-- 1 root root 2.0M Oct  5 00:07 /usr/share/vcpkg/installed/x64-linux/lib/libwx_gtk3u_aui-3.1.a
-rw-r--r-- 1 root root  32M Oct  5 00:07 /usr/share/vcpkg/installed/x64-linux/lib/libwx_gtk3u_core-3.1.a
-rw-r--r-- 1 root root 276K Oct  5 00:07 /usr/share/vcpkg/installed/x64-linux/lib/libwx_gtk3u_gl-3.1.a
-rw-r--r-- 1 root root 2.7M Oct  5 00:07 /usr/share/vcpkg/installed/x64-linux/lib/libwx_gtk3u_html-3.1.a
-rw-r--r-- 1 root root 200K Oct  5 00:07 /usr/share/vcpkg/installed/x64-linux/lib/libwx_gtk3u_media-3.1.a
-rw-r--r-- 1 root root 2.6M Oct  5 00:07 /usr/share/vcpkg/installed/x64-linux/lib/libwx_gtk3u_propgrid-3.1.a
-rw-r--r-- 1 root root 411K Oct  5 00:07 /usr/share/vcpkg/installed/x64-linux/lib/libwx_gtk3u_qa-3.1.a
-rw-r--r-- 1 root root 1.7M Oct  5 00:07 /usr/share/vcpkg/installed/x64-linux/lib/libwx_gtk3u_ribbon-3.1.a
-rw-r--r-- 1 root root 4.6M Oct  5 00:07 /usr/share/vcpkg/installed/x64-linux/lib/libwx_gtk3u_richtext-3.1.a
-rw-r--r-- 1 root root 1.1M Oct  5 00:07 /usr/share/vcpkg/installed/x64-linux/lib/libwx_gtk3u_stc-3.1.a
-rw-r--r-- 1 root root 446K Oct  5 00:07 /usr/share/vcpkg/installed/x64-linux/lib/libwx_gtk3u_webview-3.1.a
-rw-r--r-- 1 root root 5.4M Oct  5 00:07 /usr/share/vcpkg/installed/x64-linux/lib/libwx_gtk3u_xrc-3.1.a
-rw-r--r-- 1 root root 163K Oct  5 00:07 /usr/share/vcpkg/installed/x64-linux/lib/libwxregexu-3.1.a
-rw-r--r-- 1 root root 5.3M Oct  5 00:07 /usr/share/vcpkg/installed/x64-linux/lib/libwxscintilla-3.1.a
```

and looking at the dependencies via `vcpkg depend-info wxwidgets` I don't see any "gtk3" mentioned:
```
vcpkg-cmake: 
vcpkg-cmake-config: 
libjpeg-turbo: 
liblzma: vcpkg-cmake, vcpkg-cmake-config
zlib: 
expat: 
libpng: vcpkg-cmake, vcpkg-cmake-config, zlib
tiff[zip, lzma, jpeg]: libjpeg-turbo, liblzma, vcpkg-cmake, zlib
wxwidgets: expat, libpng, tiff, zlib
```

so it sounds like the gtk3 stuff is all incorporated inside those "libwx_gtk3u_" library files rather than being a separate package.

So now I'm going to try to build a simple cmake project with this vcpkg installed version of wxwidgets and see if it works.  And I guess I should try to figure out how to run the automated CI testing to see what errors are reported (if any) which are preventing x64-linux wxwidgets from being built on github-ci.

**Comment by ericfont** [comment]
looking more closely at [my failed build of wxwidgets via github-ci on ubuntu-latest](https://github.com/ericfont/Examples_wxWidgets/runs/3775207527?check_suite_focus=true), I [noticed the line error: missing GTK3_INCLUDE_DIRS GTK3_LIBRARIES](https://github.com/microsoft/vcpkg/files/7290542/wxwidgets-github-build-error_missing-GTK3_INCLUDE_DIRS-GTK3_LIBRARIES.txt).

So (and I'm still understanding how vcpkg works) it sounds like when vcpkg builds something, if cmake can't find the package via vcpkg libraries (which it seems is where cmake will look first) then the fall back is to look in the non-vcpkg installed libraries in the filesystem.  And since ubuntu-latest on github-ci didn't have gtk3 libraries, that is why the github-ci failed...  but since my local arch machine has gtk installed, then I guess cmake was able to find my system's gtk3 library and so incorporated that into the vcpkg build on wxwidgets.

**Comment by timmeh87** [comment]
Hello I would like to add something to this issue, I figured I could put this here instead of making a new issue because I believe it is basically the same problem. 

### on x64-linx, wxwidgets directly conflicts with opencv over GTK version 

This is perhaps related to #21039 and a direct result of #12621, and it specifically relates to using wxwidgets and opencv **together**

I need to use opencv4 and wxwidgets in a project. 
I have built it on x64-linux from vcpkg around august 2021, and it worked fine and I was happy.

I am already using a manifest and pinning down versions, and recently I decided to push everything including my baseline forwards. 
Suspiciously, the wxwidgets build would always fail when built with the whole manifest, but when isolated in the manifest for debugging it would build fine, add to the binary cache, then the manifest could build with the cache, since it would not rebuild. I ignored this.
I am overriding the triplet and forcing wxwidgets to be dynamic. _This is not a problem as it worked fine before_
Now the application builds and links, it fails at runtime with this error:

(process:44630): Gtk-ERROR **: 09:00:59.932: GTK 2/3 symbols detected. Using GTK 2/3 and GTK 4 in the same process is not supported

I have identified the libraries that use the conflicting versions. you guessed it, opencv=gtk4, wxwidgets=gtk3

As we already know, there are reasons for this, and the fix it so use manifests and version pinning to go back to a time before #12621. Or you could use a port overlay i guess.

I think we can agree the easiest option with the highest conformity is to have wxwidgets update to gtk4. [this blog posts basically says they wont do that soon](https://www.wxwidgets.org/blog/2021/01/wxwidgets-in-2020-and-beyond/)

Right now this seems okay but in the future to keep up to date with the latest opencv versions a custom port to force [gtk] off might be necessary. It seems that currently in the opencv port, the [gtk] feature is "perma-on" , I cant disable it with default-features:false.

**Comment by dg0yt** [comment]
> I have built it on x64-linux from vcpkg around august 2021, and it worked fine and I was happy.

Oh, probably not the most recent versions at that time? IIRC port gtk was update from 3 to 4 earlier in 2021 but wxwidget's hard dependency on gtk3 wasn't noticed. Now we struggle for some time to get wxwidgets working again on linux (with system GTK3). 

Anyways, looking at port opencv4, I think that you can opt-out from the gtk dependency: You must opt-out from the default features, and list the desired features explicitly. In manifest mode, you there is a property for opt-out, and in classic mode, you would neet to include `core` in the list of features.

**Comment by timmeh87** [comment]
From my reading of #12621, I interpret it to say that prior to that issue getting fixed and merged, the opencv port actually had GTK _disabled_ rather than depending on the vcpkg "3" version, which was unsuitable for reasons I do not understand.

I rolled back to opencv port 4.5.3#3 which I believe is the one before GTK was turned on, according to the git logs (still awaiting the results of that build, will take a day)

I thought I could disable opencv[gtk]  with my manifest, but It didnt seem to work. Perhaps we could look at that here so that it might help others. My manifest had this as a dependency:

```
       {"name": "opencv4",
	"default-features": false,
	"features": [ "cuda", "dnn", "png", "jpeg", "tiff", "ffmpeg", "vtk", "world"]
	},
```
However [gtk] was still built, I checked the opencv port's `vcpkg.json` file because I thought maybe some other feature depending on [gtk] but there were only two places I could find it:

1) listed as its own feature with is very misleadingly labelled as support for some specific medical images
```
    "gtk": {
      "description": "GDCM support for opencv",
      "dependencies": [
        "gtk"
      ]
    },	
```	

2) listed as some aspect of "default-features" which I don't fully understand but I suspect overrides [gtk] to always be enabled on linux
```
    "default-features": {
      "description": "Platform-dependent default features",
      "dependencies": [
        {
          "name": "opencv4",
          "default-features": false,
          "features": [
            "dnn",
            "jpeg",
            "png",
            "quirc",
            "tiff",
            "webp"
          ]
        },
        {
          "name": "opencv4",
          "default-features": false,
          "features": [
            "gtk"
          ],
          "platform": "linux"
        }
      ]
    },
```

Am I just missing something? What could the manifest say to turn off [gtk]?

**Comment by JackBoosY** [comment]
That's hard to fix since the upstream still uses gtk3 now.

**Comment by dg0yt** [comment]
Maybe would have been better started as a discussion...

> 1. listed as its own feature with is very misleadingly labelled as support for some specific medical images

This is an is a common issue: port "features" are named after single dependencies, not after the feature.

> 2. listed as some aspect of "default-features" which I don't fully understand but I suspect overrides [gtk] to always be enabled on linux

"default-features" is a little bit misleading, too: It is an explicit *feature* which can be turned off. It only depends on features from the opencv port itself. But unlike the ports global "default-features" property, it can use "supports" expression, to have different defaults for different platforms.

> I thought I could disable opencv[gtk] with my manifest, but It didnt seem to work. Perhaps we could look at that here so that it might help others. My manifest had this as a dependency:
> 
> ```
>        {"name": "opencv4",
> 	"default-features": false,
> 	"features": [ "cuda", "dnn", "png", "jpeg", "tiff", "ffmpeg", "vtk", "world"]
> 	},
> ```

It turns out that feature "vtk" lacks the the `"default-features": false` property for its opencv4 dependency. This is where it pulls in the default features again. I don't know if this is intentional, but it looks like a mistake. Can you test it, and make a PR if it is a bug?

**Comment by timmeh87** [comment]
Im not sure if I understand what I recently did this friday during my work day, but it seemed like a build of only wxwidgets + opencv (rolled back) works okay, but when the **darknet** port is added (it has always been there in my manifest) I get an error along the lines of "`error, opencv is missing required feature [gtk]`". I had to figure that out by trial and error (its not mentioned which port actually requested [gtk]) but its definitely darknet that causes the error message. It sort of confuses me how darket can require the [gtk] feature implicitly when it does not exist at my requested version of opencv. Nowhere in darknet's files does it mention [gtk] by name, and with my opencv version being rolled back, [gtk] does not exist, as the error message seems to notice. Maybe something to do with how versioning resolves these things. Not sure if it is a bug or an edge-case or by-design or what.

Anyways this suggests to me that darknet was actually the thing that was forcing [gtk]. I was able to remove darknet, then do a build with rolled-back opencv, and my application works. Ill have to do more testing later to really figure out what the heck I have done but does that seem to make sense to you? Like, what I want to know now is what happens when I build opencv+wxwidgets without rolling back and without darknet. I dont have time right now to do experiments, for me right now I can just get darknet from a second manifest If i really need it.

**Comment by dg0yt** [comment]
I can't  say much about `darknet` but this: It requires `opencv` ports with certain features, but it lacks the `"default-features": false` property for these dependencies. I don't know if this is intentional or simply unnoticed - I guess the latter.

**Comment by cenit** [comment]
a viz frontend is required by darknet functions that output video on screen, so it is not unnoticed the requirement of all base opencv functionalities for darknet.
OpenCV otoh is not fully necessary for darknet to work, but when enabled there is no distinction inside the code from the input (where gtk is not necessary) to the output (where gtk might be necessary if output is on screen - imshow is used inside the codebase)

**Comment by sfhacker** [comment]
This OPEN issue from .... 2021!
