### ISSUE TITLE
[protobuf] build failure

### ISSUE THREAD

**Issue by tpdussla93** [microsoft/vcpkg#21619]
**Host Environment**
- OS: Windows 10(Version 1909)
- Compiler: Visual Studio 2022 Professional

**To Reproduce**
`./vcpkg install protobuf[core]:x64-windows`

**Failure logs** 
- **Build messages and console output**
```
PS C:\vcpkg> .\vcpkg.exe install protobuf[core]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    protobuf[core]:x64-windows -> 3.18.0
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\user\AppData\Local\vcpkg\archives in 132 us. Use --debug to see more details.
Starting package 1/1: protobuf:x64-windows
Building package protobuf[core]:x64-windows...
-- Downloading https://github.com/protocolbuffers/protobuf/archive/v3.18.0.tar.gz -> protocolbuffers-protobuf-v3.18.0.tar.gz...
-- Extracting source C:/vcpkg/downloads/protocolbuffers-protobuf-v3.18.0.tar.gz
-- Applying patch fix-static-build.patch
-- Applying patch fix-default-proto-file-path.patch
-- Applying patch fix-uwp-build.patch
-- Using source at C:/vcpkg/buildtrees/protobuf/src/v3.18.0-44e21376af.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: C:/Users/user/.dotnet/tools/pwsh.exe -noprofile -executionpolicy Bypass -nologo -file C:/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/vcpkg/packages/protobuf_x64-windows/tools/protobuf/protoc.exe -installedDir C:/vcpkg/packages/protobuf_x64-windows/bin -verbose
    Working Directory: C:/vcpkg
    Error code: -532462766
    See logs for more information:
      C:\vcpkg\buildtrees\protobuf\copy-tool-dependencies-0-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:30 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:62 (z_vcpkg_copy_tool_dependencies_search)
  scripts/cmake/vcpkg_copy_tools.cmake:82 (vcpkg_copy_tool_dependencies)
  ports/protobuf/portfile.cmake:80 (vcpkg_copy_tools)
  scripts/ports.cmake:142 (include)


Error: Building package protobuf:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: protobuf[core]:x64-windows -> 3.18.0
  vcpkg version: 30465138e 2021-11-22 (3 hours ago)
  vcpkg-tool version: 2021-11-15-ec76affcc987efbf172b7da0b05df711b48fa535

Additionally, attach any relevant sections from the log files above.
```
- **C:\vcpkg\buildtrees\protobuf\copy-tool-dependencies-0-err.log**
```
Unhandled exception. System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'dotnet' with working directory 'C:\vcpkg'. 지정된 파일을 찾을 수 없습니다.(which means "Can't find specified file")
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName, String arguments)
   at Microsoft.PowerShell.GlobalTool.Shim.EntryPoint.Main(String[] args)
```

**Additional context**
Actually I had exact same error from installing opencv4 with vcpkg.
So, I reproduced the error by installing protobuf cloning vcpkg again.

This is the result of running `protoc.exe` in the above error message.
```
PS C:\vcpkg\packages\protobuf_x64-windows\bin> ..\tools\protobuf\protoc.exe
Usage: C:\vcpkg\packages\protobuf_x64-windows\tools\protobuf\protoc.exe [OPTION] PROTO_FILES
Parse PROTO_FILES and generate output based on the options given:
  -IPATH, --proto_path=PATH   Specify the directory in which to search for
                              imports.  May be specified multiple times;
                              directories will be searched in order.  If not
                              given, the current working directory is used.
                              If not found in any of the these directories,
                              the --descriptor_set_in descriptors will be
                              checked for required proto file.
  --version                   Show version info and exit.
  -h, --help                  Show this text and exit.
  --encode=MESSAGE_TYPE       Read a text-format message of the given type
                              from standard input and write it in binary
                              to standard output.  The message type must
                              be defined in PROTO_FILES or their imports.
  --deterministic_output      When using --encode, ensure map fields are
                              deterministically ordered. Note that this order
                              is not canonical, and changes across builds or
                              releases of protoc.
  --decode=MESSAGE_TYPE       Read a binary message of the given type from
                              standard input and write it in text format
                              to standard output.  The message type must
                              be defined in PROTO_FILES or their imports.
  --decode_raw                Read an arbitrary protocol message from
                              standard input and write the raw tag/value
                              pairs in text format to standard output.  No
                              PROTO_FILES should be given when using this
                              flag.
  --descriptor_set_in=FILES   Specifies a delimited list of FILES
                              each containing a FileDescriptorSet (a
                              protocol buffer defined in descriptor.proto).
                              The FileDescriptor for each of the PROTO_FILES
                              provided will be loaded from these
                              FileDescriptorSets. If a FileDescriptor
                              appears multiple times, the first occurrence
                              will be used.
  -oFILE,                     Writes a FileDescriptorSet (a protocol buffer,
    --descriptor_set_out=FILE defined in descriptor.proto) containing all of
                              the input files to FILE.
  --include_imports           When using --descriptor_set_out, also include
                              all dependencies of the input files in the
                              set, so that the set is self-contained.
  --include_source_info       When using --descriptor_set_out, do not strip
                              SourceCodeInfo from the FileDescriptorProto.
                              This results in vastly larger descriptors that
                              include information about the original
                              location of each decl in the source file as
                              well as surrounding comments.
  --dependency_out=FILE       Write a dependency output file in the format
                              expected by make. This writes the transitive
                              set of input file paths to FILE
  --error_format=FORMAT       Set the format in which to print errors.
                              FORMAT may be 'gcc' (the default) or 'msvs'
                              (Microsoft Visual Studio format).
  --fatal_warnings            Make warnings be fatal (similar to -Werr in
                              gcc). This flag will make protoc return
                              with a non-zero exit code if any warnings
                              are generated.
  --print_free_field_numbers  Print the free field numbers of the messages
                              defined in the given proto files. Groups share
                              the same field number space with the parent
                              message. Extension ranges are counted as
                              occupied fields numbers.
  --plugin=EXECUTABLE         Specifies a plugin executable to use.
                              Normally, protoc searches the PATH for
                              plugins, but you may specify additional
                              executables not in the path using this flag.
                              Additionally, EXECUTABLE may be of the form
                              NAME=PATH, in which case the given plugin name
                              is mapped to the given executable even if
                              the executable's own name differs.
  --cpp_out=OUT_DIR           Generate C++ header and source.
  --csharp_out=OUT_DIR        Generate C# source file.
  --java_out=OUT_DIR          Generate Java source file.
  --js_out=OUT_DIR            Generate JavaScript source.
  --kotlin_out=OUT_DIR        Generate Kotlin file.
  --objc_out=OUT_DIR          Generate Objective-C header and source.
  --php_out=OUT_DIR           Generate PHP source file.
  --python_out=OUT_DIR        Generate Python source file.
  --ruby_out=OUT_DIR          Generate Ruby source file.
  @<filename>                 Read options and filenames from file. If a
                              relative file path is specified, the file
                              will be searched in the working directory.
                              The --proto_path option will not affect how
                              this argument file is searched. Content of
                              the file will be expanded in the position of
                              @<filename> as in the argument list. Note
                              that shell expansion is not applied to the
                              content of the file (i.e., you cannot use
                              quotes, wildcards, escapes, commands, etc.).
                              Each line corresponds to a single argument,
                              even if it contains spaces.
PS C:\vcpkg\packages\protobuf_x64-windows\bin> ..\tools\protobuf\protoc.exe --version
libprotoc 3.18.0
```

I used powershell. Here's the result of `Get-Host`.
```
PS C:\vcpkg> get-host

Name             : ConsoleHost
Version          : 7.2.0
InstanceId       : 7c7cf866-e396-4624-a04b-16987b0ebb4a
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : ko-KR
CurrentUICulture : ko-KR
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

Thank you

**Comment by JackBoosY** [comment]
```
 C:/Users/user/.dotnet/tools/pwsh.exe -noprofile -executionpolicy Bypass -nologo -file C:/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/vcpkg/packages/protobuf_x64-windows/tools/protobuf/protoc.exe -installedDir C:/vcpkg/packages/protobuf_x64-windows/bin -verbose
```
vcpkg found the mismatched powershell version.

Please track issue https://github.com/microsoft/vcpkg/issues/16721

**Comment by tpdussla93** [comment]
Seeing the issue #16721, it seems that vcpkg using unexpected powershell that I'm using(v7.2).
So, I was able to install the package without error after uninstalling already installed powershell v7.2, anyway.

Thank you
