### ISSUE TITLE
[tensorflow] Build error

### ISSUE THREAD

**Issue by rsantanaf** [microsoft/vcpkg#21950]
I need help here, I am trying to use vcpkg to install tensorflow and use it with visual studio 2022, this is the error I got

**Host Environment**
- OS:Windows
- Compiler: 19041.1348

**To Reproduce**
`./vcpkg install tensorflow

**Failure logs** 
-Starting local Bazel server and connecting to it...
```
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'build' from e:\users\rsantana\vcpkg\buildtrees\tensorflow\x64-windows-static-crtdll-dbg\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=U:/vcpkg/downloads/tools/msys2/5ac3933426d8437e/mingw64/bin/python.exe
INFO: Reading rc options for 'build' from e:\users\rsantana\vcpkg\buildtrees\tensorflow\x64-windows-static-crtdll-dbg\.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true
INFO: Reading rc options for 'build' from e:\users\rsantana\vcpkg\buildtrees\tensorflow\x64-windows-static-crtdll-dbg\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=U:/vcpkg/downloads/tools/msys2/5ac3933426d8437e/mingw64/bin/python3.exe --action_env PYTHON_LIB_PATH=U:/vcpkg/downloads/tools/msys2/5ac3933426d8437e/mingw64/lib/python3.8/site-packages --python_path=U:/vcpkg/downloads/tools/msys2/5ac3933426d8437e/mingw64/bin/python3.exe --define=with_xla_support=false --copt=/d2ReducedOptimizeHugeFunctions --host_copt=/d2ReducedOptimizeHugeFunctions --define=override_eigen_strong_inline=true
INFO: Found applicable config definition build:short_logs in file e:\users\rsantana\vcpkg\buildtrees\tensorflow\x64-windows-static-crtdll-dbg\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file e:\users\rsantana\vcpkg\buildtrees\tensorflow\x64-windows-static-crtdll-dbg\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:windows in file e:\users\rsantana\vcpkg\buildtrees\tensorflow\x64-windows-static-crtdll-dbg\.bazelrc: --copt=/W0 --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/experimental:preprocessor --host_copt=/experimental:preprocessor --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file e:\users\rsantana\vcpkg\buildtrees\tensorflow\x64-windows-static-crtdll-dbg\.bazelrc: --define framework_shared_object=false
Loading: 
Loading: 0 packages loaded
DEBUG: E:/users/rsantana/vcpkg/buildtrees/tensorflow/.bzl/zcnszkij/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
Loading: 0 packages loaded
Loading: 0 packages loaded
    currently loading: tensorflow
Analyzing: 2 targets (1 packages loaded, 0 targets configured)
Analyzing: 2 targets (19 packages loaded, 11 targets configured)
Analyzing: 2 targets (21 packages loaded, 30 targets configured)
Analyzing: 2 targets (24 packages loaded, 32 targets configured)
Analyzing: 2 targets (63 packages loaded, 198 targets configured)
INFO: Repository local_config_def_file_filter instantiated at:
  E:/users/rsantana/vcpkg/buildtrees/tensorflow/x64-windows-static-crtdll-dbg/WORKSPACE:15:14: in <toplevel>
  E:/users/rsantana/vcpkg/buildtrees/tensorflow/x64-windows-static-crtdll-dbg/tensorflow/workspace2.bzl:1088:19: in workspace
  E:/users/rsantana/vcpkg/buildtrees/tensorflow/x64-windows-static-crtdll-dbg/tensorflow/workspace2.bzl:101:30: in _tf_toolchains
Repository rule def_file_filter_configure defined at:
  E:/users/rsantana/vcpkg/buildtrees/tensorflow/x64-windows-static-crtdll-dbg/tensorflow/tools/def_file_filter/def_file_filter_configure.bzl:55:44: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_def_file_filter':
   Traceback (most recent call last):
	File "E:/users/rsantana/vcpkg/buildtrees/tensorflow/x64-windows-static-crtdll-dbg/tensorflow/tools/def_file_filter/def_file_filter_configure.bzl", line 37, column 28, in _def_file_filter_configure_impl
		auto_configure_fail("Couldn't find undname.exe under %s, please check your VC installation and set BAZEL_VC environment variable correctly." % vc_path)
	File "E:/users/rsantana/vcpkg/buildtrees/tensorflow/.bzl/zcnszkij/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 112, column 9, in auto_configure_fail
		fail("\n%sAuto-Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail: 
Auto-Configuration Error: Couldn't find undname.exe under C:\Program Files\Microsoft Visual Studio\2022\Community\VC, please check your VC installation and set BAZEL_VC environment variable correctly.
ERROR: Error fetching repository: Traceback (most recent call last):
	File "E:/users/rsantana/vcpkg/buildtrees/tensorflow/x64-windows-static-crtdll-dbg/tensorflow/tools/def_file_filter/def_file_filter_configure.bzl", line 37, column 28, in _def_file_filter_configure_impl
		auto_configure_fail("Couldn't find undname.exe under %s, please check your VC installation and set BAZEL_VC environment variable correctly." % vc_path)
	File "E:/users/rsantana/vcpkg/buildtrees/tensorflow/.bzl/zcnszkij/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 112, column 9, in auto_configure_fail
		fail("\n%sAuto-Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail: 
Auto-Configuration Error: Couldn't find undname.exe under C:\Program Files\Microsoft Visual Studio\2022\Community\VC, please check your VC installation and set BAZEL_VC environment variable correctly.
ERROR: E:/users/rsantana/vcpkg/buildtrees/tensorflow/x64-windows-static-crtdll-dbg/tensorflow/BUILD:1091:8: //tensorflow:tensorflow_filtered_def_file depends on @local_config_def_file_filter//:def_file_filter in repository @local_config_def_file_filter which failed to fetch. no such package '@local_config_def_file_filter//': 
Auto-Configuration Error: Couldn't find undname.exe under C:\Program Files\Microsoft Visual Studio\2022\Community\VC, please check your VC installation and set BAZEL_VC environment variable correctly.
ERROR: Analysis of target '//tensorflow:tensorflow.dll' failed; build aborted: Analysis failed
INFO: Elapsed time: 16.186s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (76 packages loaded, 1680 targets configured)
FAILED: Build did NOT complete successfully (76 packages loaded, 1680 targets configured)
```

**Comment by LilyWangLL** [comment]
This issue is due todownload repository failed, duplicate to #21758, it will be fix in PR #21912.
