### ISSUE TITLE
V8 Build Fail

### ISSUE THREAD

**Issue by chriscp-cat** [microsoft/vcpkg#22001]
**Host Environment**
- OS: Windows

**To Reproduce**
`./vcpkg install V8`

**Failure logs** 
```
Traceback (most recent call last):
  File "D:/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean/build/vs_toolchain.py", line 573, in <module>
    sys.exit(main())
  File "D:/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean/build/vs_toolchain.py", line 569, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "D:/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean/build/vs_toolchain.py", line 546, in GetToolchainDir
    runtime_dll_dirs = SetEnvironmentAndGetRuntimeDllDirs()
  File "D:/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean/build/vs_toolchain.py", line 106, in SetEnvironmentAndGetRuntimeDllDirs
    os.environ['GYP_MSVS_OVERRIDE_PATH'] = DetectVisualStudioPath()
  File "D:/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean/build/vs_toolchain.py", line 197, in DetectVisualStudioPath
    version_as_year = GetVisualStudioVersion()
  File "D:/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean/build/vs_toolchain.py", line 187, in GetVisualStudioVersion
    ' Supported versions are: %s.' % supported_versions_str)
Exception: No supported Visual Studio can be found. Supported versions are: 16.0 (2019), 15.0 (2017).

```

**Additional context**
not support VS2022

**Comment by JackBoosY** [comment]
According to your log, I think v8 doesn't support VS2022 officially, please report this to the upstream.

Thanks.

**Comment by JackBoosY** [comment]
Close this PR until upstream fixes this.
