### ISSUE TITLE
[v8] build failure

### ISSUE THREAD

**Issue by TwoPizza9621536** [microsoft/vcpkg#22282]
**Host Environment**
- OS: Windows 11 Insider Build 22523
- Compiler: VS2019 v16.11.8

**To Reproduce**
`./vcpkg install v8`

**Failure logs** 
```
Computing installation plan...
The following packages will be built and installed:
    v8[core]:x86-windows -> 9.1.269.39#2
Detecting compiler hash for triplet x86-windows...
Restored 0 packages from C:\Users\Samgo\AppData\Local\vcpkg\archives in 140.3 us. Use --debug to see more details.
Starting package 1/1: v8:x86-windows
Building package v8[core]:x86-windows...
-- Found external ninja('1.10.2').
-- Using cached msys-gzip-1.10-1-x86_64.pkg.tar.xz.
-- Using cached msys-bash-4.4.023-2-x86_64.pkg.tar.xz.
-- Using cached msys-diffutils-3.7-1-x86_64.pkg.tar.xz.
-- Using cached msys-coreutils-8.32-1-x86_64.pkg.tar.xz.
-- Using cached msys-grep-3.0-2-x86_64.pkg.tar.xz.
-- Using cached msys-sed-4.8-1-x86_64.pkg.tar.xz.
-- Using cached msys-libpcre-8.44-1-x86_64.pkg.tar.xz.
-- Using cached msys-gawk-5.1.0-1-x86_64.pkg.tar.xz.
-- Using cached msys-mpfr-4.1.0-1-x86_64.pkg.tar.zst.
-- Using cached msys-gmp-6.2.0-1-x86_64.pkg.tar.xz.
-- Using cached msys-libreadline-8.0.004-1-x86_64.pkg.tar.xz.
-- Using cached msys-ncurses-6.2-1-x86_64.pkg.tar.xz.
-- Using cached msys-pkg-config-0.29.2-4-x86_64.pkg.tar.zst.
-- Using cached msys-make-4.3-1-x86_64.pkg.tar.xz.
-- Using cached msys-libintl-0.19.8.1-1-x86_64.pkg.tar.xz.
-- Using cached msys-libiconv-1.16-2-x86_64.pkg.tar.zst.
-- Using cached msys-gcc-libs-9.3.0-1-x86_64.pkg.tar.xz.
-- Using cached msys-msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst.
-- Using msys root at C:/dev/vcpkg/downloads/tools/msys2/1dd5855cc99d59fc
-- Using cached C:/dev/vcpkg/downloads/v8-7d3d62c91f69a702e5aa54c6b4dbbaa883683717.tar.gz
-- Cleaning sources at C:/dev/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/v8-7d3d62c91f69a702e5aa54c6b4dbbaa883683717.tar.gz
-- Applying patch C:/dev/vcpkg/ports/v8/v8.patch
-- Using source at C:/dev/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean
-- Fetching submodules
-- Generating v8 build files. Please wait...
-- Generating build (x86-windows-dbg)...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: C:/dev/vcpkg/downloads/tools/gn/qUkAhy9J0P7c5racy-9wB6AHNK_btS18im8S06_ehhwC/gn.exe gen C:/dev/vcpkg/buildtrees/v8/x86-windows-dbg "--args=is_component_build=true target_cpu=\"x86\" v8_monolithic=false v8_use_external_startup_data=true use_sysroot=false is_clang=false use_custom_libcxx=false v8_enable_verify_heap=false icu_use_data_file=false is_debug=true enable_iterator_debugging=true pkg_config_libdir=\"/c/dev/vcpkg/installed/x86-windows/debug/lib/pkgconfig\""
    Working Directory: C:/dev/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean
    Error code: 1
    See logs for more information:
      C:\dev\vcpkg\buildtrees\v8\generate-x86-windows-dbg-out.log
      C:\dev\vcpkg\buildtrees\v8\generate-x86-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_gn.cmake:39 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_configure_gn.cmake:66 (z_vcpkg_configure_gn_generate)
  ports/v8/portfile.cmake:150 (vcpkg_configure_gn)
  scripts/ports.cmake:142 (include)


Error: Building package v8:x86-windows failed with: BUILD_FAILED
```

C:\dev\vcpkg\buildtrees\v8\generate-x86-windows-dbg-out.log
```
ERROR at //build/toolchain/win/BUILD.gn:423:24: Script returned non-zero exit code.
  win_toolchain_data = exec_script("setup_toolchain.py",
                       ^----------
Current dir: C:/dev/vcpkg/buildtrees/v8/x86-windows-dbg/
Command: C:/dev/vcpkg/downloads/tools/python/python-2.7.18-x86/python.exe C:/dev/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean/build/toolchain/win/setup_toolchain.py "C:\Program Files (x86)/Microsoft Visual Studio/2019/Community" "C:\Program Files (x86)\Windows Kits\10" "C:\WINDOWS\Sysnative;C:\WINDOWS\SysWOW64;Arm64Unused" win x86 environment.x86
Returned 1.
See //build/toolchain/win/BUILD.gn:485:3: whence it was called.
  win_toolchains("x86") {
  ^-----------------------
See //BUILD.gn:1195:1: which caused the file to be included.
action("postmortem-metadata") {
^------------------------------
```

C:\dev\vcpkg\buildtrees\v8\generate-x86-windows-dbg-err.log
```
Traceback (most recent call last):
  File "C:/dev/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean/build/toolchain/win/setup_toolchain.py", line 311, in <module>
    main()
  File "C:/dev/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean/build/toolchain/win/setup_toolchain.py", line 268, in main
    vc_lib_path = FindFileInEnvList(env, 'LIB', ';', 'msvcrt.lib')
  File "C:/dev/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean/build/toolchain/win/setup_toolchain.py", line 210, in FindFileInEnvList
    file_name, env_name, '\n'.join(parts))
AssertionError: msvcrt.lib is not found in LIB:
C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x86
C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x86
C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x86
Check if it is installed.
Traceback (most recent call last):
  File "C:/dev/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean/build/toolchain/win/setup_toolchain.py", line 311, in <module>
    main()
  File "C:/dev/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean/build/toolchain/win/setup_toolchain.py", line 268, in main
    vc_lib_path = FindFileInEnvList(env, 'LIB', ';', 'msvcrt.lib')
  File "C:/dev/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean/build/toolchain/win/setup_toolchain.py", line 210, in FindFileInEnvList
    file_name, env_name, '\n'.join(parts))
AssertionError: msvcrt.lib is not found in LIB:
C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x86
C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x86
C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x86
Check if it is installed.
```

**Additional context**
Similar to #15939 and #15351 but vcpkg and VS 2019 are in the same directory. Applied the fixes in the issues but nothing works. Also, these issues have been stalled for almost a year. Tried copying msvcrt.lib but it also did not work.

**Comment by JackBoosY** [comment]
```
AssertionError: msvcrt.lib is not found in LIB:
C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x86
C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x86
C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x86
Check if it is installed.
```
Please install the latest Windows 10 SDK first.

**Comment by TwoPizza9621536** [comment]
Installed the latest Windows 10 sdk still the same error.
[generate-x86-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/7799742/generate-x86-windows-dbg-err.log)
[generate-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/7799743/generate-x86-windows-dbg-out.log)
stalled the latest Windows 10 SDK
![image](https://user-images.githubusercontent.com/47703212/147888533-cc8ca6c1-5491-47ee-97af-bb5bf6841586.png)

**Comment by JackBoosY** [comment]
```
AssertionError: msvcrt.lib is not found in LIB:
C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x86
C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x86
C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x86
```

`msvcrt.lib` should in Visual Studio path.

**Comment by TwoPizza9621536** [comment]
It does not look in the Visual Studio path, even if I add it to the path.

**Comment by Cheney-W** [comment]
Could you please open the `x86 Native Tools Command Prompt for VS 2019` and run `set lib`, then send the output to us?

**Comment by TwoPizza9621536** [comment]
Set lib env
```
LIB=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\lib\x86;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\lib\x86;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x86;C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\ucrt\x86;C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\um\x86
LIBPATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\lib\x86;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\lib\x86;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\lib\x86\store\references;C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.22000.0;C:\Program Files (x86)\Windows Kits\10\References\10.0.22000.0;C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319
```

**Comment by Cheney-W** [comment]
Thanks for your reply! 
Could you please check if the msvcrt.lib file saved in the `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\lib\x86` folder. 
If not, I think you should repair or re-install your VS first; If yes, please run `./vcpkg install v8 --debug` and send the stdout.*.log and the failure log to me. Thank you!

**Comment by TwoPizza9621536** [comment]
I can confirm that msvcrt.lib is in the `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\lib\x86` folder
[stdout-x86-windows.log](https://github.com/microsoft/vcpkg/files/7846972/stdout-x86-windows.log)
[error.log](https://github.com/microsoft/vcpkg/files/7846973/error.log)
.

**Comment by Cheney-W** [comment]
According to the error.log line 40, you are actually using VS2022 instead of VS2019.

Since the upstream (google/v8) doesn't support Visual Studio 2022 yet, you should use Visual Studio 2019 instead of Visual Studio 2022 to fix this issue, you could uninstall the VS2022 or add set(VCPKG_PLATFORM_TOOLSET v142) into the triplet file, for example: .\triplets\x86-windows.cmake
```
set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_PLATFORM_TOOLSET v142)
```

**Comment by TwoPizza9621536** [comment]
It compiled, but do I have to keep patching the cmake file when a package does not support a tool chain?

**Comment by JackBoosY** [comment]
Since v8 uses gn files, you also have to modify the search Visual Studio part.

**Comment by TwoPizza9621536** [comment]
Thanks
