### ISSUE TITLE
[tensorflow-cc] Build error with vcpkg

### ISSUE THREAD

**Issue by jayantySrikrishna** [microsoft/vcpkg#22373]
**Host Environment**
- OS: Windows 10 - 64 bit
- Compiler: vs2022

`./vcpkg install tensorflow-cc:x64-windows`

**Failure logs** 
Repository rule def_file_filter_configure defined at:
```
  C:/dev/vcpkg/buildtrees/tensorflow-cc/x64-windows-dbg/tensorflow/tools/def_file_filter/def_file_filter_configure.bzl:55:44: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_def_file_filter':
   Traceback (most recent call last):
	File "C:/dev/vcpkg/buildtrees/tensorflow-cc/x64-windows-dbg/tensorflow/tools/def_file_filter/def_file_filter_configure.bzl", line 37, column 28, in _def_file_filter_configure_impl
		auto_configure_fail("Couldn't find undname.exe under %s, please check your VC installation and set BAZEL_VC environment variable correctly." % vc_path)
	File "C:/dev/vcpkg/buildtrees/tensorflow-cc/.bzl/p6awiclp/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 112, column 9, in auto_configure_fail
		fail("\n%sAuto-Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail: 
Auto-Configuration Error: Couldn't find undname.exe under C:\Program Files\Microsoft Visual Studio\2022\Community\VC, please check your VC installation and set BAZEL_VC environment variable correctly.
ERROR: Error fetching repository: Traceback (most recent call last):
	File "C:/dev/vcpkg/buildtrees/tensorflow-cc/x64-windows-dbg/tensorflow/tools/def_file_filter/def_file_filter_configure.bzl", line 37, column 28, in _def_file_filter_configure_impl
		auto_configure_fail("Couldn't find undname.exe under %s, please check your VC installation and set BAZEL_VC environment variable correctly." % vc_path)
	File "C:/dev/vcpkg/buildtrees/tensorflow-cc/.bzl/p6awiclp/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 112, column 9, in auto_configure_fail
		fail("\n%sAuto-Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail: 
Auto-Configuration Error: Couldn't find undname.exe under C:\Program Files\Microsoft Visual Studio\2022\Community\VC, please check your VC installation and set BAZEL_VC environment variable correctly.
ERROR: C:/dev/vcpkg/buildtrees/tensorflow-cc/x64-windows-dbg/tensorflow/BUILD:1102:8: //tensorflow:tensorflow_filtered_def_file depends on @local_config_def_file_filter//:def_file_filter in repository @local_config_def_file_filter which failed to fetch. no such package '@local_config_def_file_filter//': 
Auto-Configuration Error: Couldn't find undname.exe under C:\Program Files\Microsoft Visual Studio\2022\Community\VC, please check your VC installation and set BAZEL_VC environment variable correctly.
ERROR: Analysis of target '//tensorflow:tensorflow_cc.dll' failed; build aborted: Analysis failed
```
More Info:
    package: tensorflow-cc[core]:x64-windows -> 2.7.0#1
    vcpkg-tool version: 2021-11-24-48b94a6946b8a70abd21529218927fd478d02b6c
    vcpkg-scripts version: b934807c7

Any tips on fixing the issue would be appreciated.

**Comment by JackBoosY** [comment]
```
Auto-Configuration Error: Couldn't find undname.exe under C:\Program Files\Microsoft Visual Studio\2022\Community\VC, please check your VC installation and set BAZEL_VC environment variable correctly.
```
I think that's caused by the upstream bazel doesn't support Visual Studio 2022 now.

**Comment by JackBoosY** [comment]
Please track #21246 instead.
