### ISSUE TITLE
[V8] build failure

### ISSUE THREAD

**Issue by sornian** [microsoft/vcpkg#22422]
**Host Environment**
- OS: Windows 10     Build 19043
- Compiler: Visual studio 2022 17.04

**To Reproduce**
`./vcpkg install v8`

**Failure logs** 
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.
```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: E:/vcpkg/downloads/tools/gn/qUkAhy9J0P7c5racy-9wB6AHNK_btS18im8S06_ehhwC/gn.exe gen E:/vcpkg/buildtrees/v8/x86-windows-dbg "--args=is_component_build=true target_cpu=\"x86\" v8_monolithic=false v8_use_external_startup_data=true use_sysroot=false is_clang=false use_custom_libcxx=false v8_enable_verify_heap=false icu_use_data_file=false is_debug=true enable_iterator_debugging=true pkg_config_libdir=\"/e/vcpkg/installed/x86-windows/debug/lib/pkgconfig\""
    Working Directory: E:/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean
    Error code: 1
    See logs for more information:
      E:\vcpkg\buildtrees\v8\generate-x86-windows-dbg-out.log
      E:\vcpkg\buildtrees\v8\generate-x86-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_gn.cmake:39 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_configure_gn.cmake:66 (z_vcpkg_configure_gn_generate)
  ports/v8/portfile.cmake:150 (vcpkg_configure_gn)
  scripts/ports.cmake:142 (include)
```

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

dbg-err.log
```
Traceback (most recent call last):
  File "E:/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean/build/vs_toolchain.py", line 573, in <module>
    sys.exit(main())
  File "E:/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean/build/vs_toolchain.py", line 569, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "E:/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean/build/vs_toolchain.py", line 546, in GetToolchainDir
    runtime_dll_dirs = SetEnvironmentAndGetRuntimeDllDirs()
  File "E:/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean/build/vs_toolchain.py", line 106, in SetEnvironmentAndGetRuntimeDllDirs
    os.environ['GYP_MSVS_OVERRIDE_PATH'] = DetectVisualStudioPath()
  File "E:/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean/build/vs_toolchain.py", line 197, in DetectVisualStudioPath
    version_as_year = GetVisualStudioVersion()
  File "E:/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean/build/vs_toolchain.py", line 187, in GetVisualStudioVersion
    ' Supported versions are: %s.' % supported_versions_str)
Exception: No supported Visual Studio can be found. Supported versions are: 16.0 (2019), 15.0 (2017).
```
dbg-out.log
```
ERROR at //build/config/win/visual_studio_version.gni:27:7: Script returned non-zero exit code.
      exec_script("../../vs_toolchain.py", [ "get_toolchain_dir" ], "scope")
      ^----------
Current dir: E:/vcpkg/buildtrees/v8/x86-windows-dbg/
Command: E:/vcpkg/downloads/tools/python/python-2.7.18-x86/python.exe E:/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean/build/vs_toolchain.py get_toolchain_dir
Returned 1.
See //build/toolchain/win/BUILD.gn:8:1: whence it was imported.
import("//build/config/win/visual_studio_version.gni")
^----------------------------------------------------
See //BUILD.gn:1195:1: which caused the file to be included.
action("postmortem-metadata") {
^------------------------------
```

**Comment by JackBoosY** [comment]
I've looked at the build scripts for v8, where the path to Visual Studio is fixed.
We can't do anything unless Visual Studio 2022 is supported upstream.

**Comment by JackBoosY** [comment]
Close this issue/PR until upstream fixes this.
