### ISSUE TITLE
Post PR suggestions are broken

### ISSUE THREAD

**Issue by dg0yt** [microsoft/vcpkg#23584]
**Describe the bug**
For each PR CI run, I'm notified that "Post PR suggestions" failed.

**Environment**
https://github.com/microsoft/vcpkg/actions/workflows/trustedPR.yml

**Failure logs** 
~~~
TypeError: Cannot read properties of undefined (reading 'listWorkflowRunArtifacts')
    at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:4797:16), <anonymous>:3:38)
    at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:4798:12)
    at main (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:4852:26)
    at Module.272 (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:4836:1)
    at __webpack_require__ (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:24:31)
    at startup (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:43:19)
    at /home/runner/work/_actions/actions/github-script/v6/dist/index.js:49:18
    at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:52:10)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
Error: Unhandled error: TypeError: Cannot read properties of undefined (reading 'listWorkflowRunArtifacts')
~~~

**Comment by autoantwort** [comment]
Maybe also because of https://github.com/microsoft/vcpkg/pull/23520

**Comment by JackBoosY** [comment]
cc @BillyONeal
