### ISSUE TITLE
[openvdb] build failure on win (The process cannot access the file because it is being used by another process)

### ISSUE THREAD

**Issue by archibate** [microsoft/vcpkg#24352]
**Host Environment**
- OS: Windows Server 2022
- Compiler: MSVC 2019

**To Reproduce**
`./vcpkg install openvdb`

**Failure logs**
```  Stored binary cache: D:\a\zeno\b\vcpkg_cache\dc\dcc6795b0fdc493208648a329921729dfa310bf68394f3680c6dd0b39ea77a67.zip
  Installing package lz4[core]:x64-windows...
  Elapsed time for package lz4:x64-windows: 8.855 s
  Starting package 116/117: blosc:x64-windows
  Building package blosc[core]:x64-windows...
  -- Downloading https://github.com/Blosc/c-blosc/archive/9fae1c9acb659159321aca69aefcdbce663e2374.tar.gz -> Blosc-c-blosc-9fae1c9acb659159321aca69aefcdbce663e2374.tar.gz...
  -- Extracting source D:/a/zeno/zeno/vcpkg/downloads/Blosc-c-blosc-9fae1c9acb659159321aca69aefcdbce663e2374.tar.gz
  -- Applying patch 0001-find-deps.patch
  -- Applying patch 0002-export-blosc-config.patch
  -- Using source at D:/a/zeno/zeno/vcpkg/buildtrees/blosc/src/ce663e2374-6c8531829e.clean
  -- Found external ninja('1.10.2').
  -- Configuring x64-windows
  -- Building x64-windows-dbg
  -- Building x64-windows-rel
  -- Installing: D:/a/zeno/zeno/vcpkg/packages/blosc_x64-windows/share/blosc/copyright
  -- Fixing pkgconfig file: D:/a/zeno/zeno/vcpkg/packages/blosc_x64-windows/lib/pkgconfig/blosc.pc
  -- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst -> msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst...
  -- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst -> msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst...
  -- Using msys root at D:/a/zeno/zeno/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
  -- Fixing pkgconfig file: D:/a/zeno/zeno/vcpkg/packages/blosc_x64-windows/debug/lib/pkgconfig/blosc.pc
  -- Performing post-build validation
  -- Performing post-build validation done
  Stored binary cache: D:\a\zeno\b\vcpkg_cache\3e\3ebd209fd0cce93e6e7c7bb8bd85c7e94447b77538a869d0e422e11174cf2e8a.zip
  Installing package blosc[core]:x64-windows...
  Elapsed time for package blosc:x64-windows: 7.683 s
  Starting package 117/117: openvdb:x64-windows
  Building package openvdb[core]:x64-windows...
  -- Downloading https://github.com/AcademySoftwareFoundation/openvdb/archive/0ed0f19ea4fbb0d8bf64d3dca07abab3c7429803.tar.gz -> AcademySoftwareFoundation-openvdb-0ed0f19ea4fbb0d8bf64d3dca07abab3c7429803.tar.gz...
  -- Extracting source D:/a/zeno/zeno/vcpkg/downloads/AcademySoftwareFoundation-openvdb-0ed0f19ea4fbb0d8bf64d3dca07abab3c7429803.tar.gz
  -- Applying patch 0003-fix-cmake.patch
  -- Applying patch fix-Target-notfound.patch
  -- Using source at D:/a/zeno/zeno/vcpkg/buildtrees/openvdb/src/b3c7429803-66ab1161d7.clean
  -- Found external ninja('1.10.2').
  -- Configuring x64-windows
  CMake Warning at D:/a/zeno/b/vcpkg_installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:418 (message):
  Warning:   The following variables are not used in CMakeLists.txt:
  
        OPENVDB_ENABLE_3_ABI_COMPATIBLE
        USE_GLFW3
  
    Please recheck them and remove the unnecessary options from the
    `vcpkg_cmake_configure` call.
  
    If these options should still be passed for whatever reason, please use the
    `MAYBE_UNUSED_VARIABLES` argument.
  Call Stack (most recent call first):
    ports/openvdb/portfile.cmake:36 (vcpkg_cmake_configure)
    scripts/ports.cmake:145 (include)
  
  
  -- Building x64-windows-dbg
  -- Building x64-windows-rel
  -- Installing: D:/a/zeno/zeno/vcpkg/packages/openvdb_x64-windows/share/openvdb/usage
  -- Installing: D:/a/zeno/zeno/vcpkg/packages/openvdb_x64-windows/share/openvdb/copyright
  -- Performing post-build validation
  -- Performing post-build validation done
  Stored binary cache: D:\a\zeno\b\vcpkg_cache\70\7070c13cb75ac6410dee6da28f6ea751ce9118e03890bf784e0cf9920b78211b.zip
  Installing package openvdb[core]:x64-windows...
  Failure to remove_all("D:\a\zeno\zeno\vcpkg\packages\openvdb_x64-windows") due to file "\\?\D:\a\zeno\zeno\vcpkg\packages\openvdb_x64-windows": The process cannot access the file because it is being used by another process.
  Error: Last command execution failed with error code '1'.
⏱ elapsed: 5520.726 seconds
Error: Last command execution failed with error code '1'.
    at BaseUtilLib.throwIfErrorCode (D:\a\_actions\lukka\run-vcpkg\v10\dist\index.js:6537:19)
    at VcpkgRunner.<anonymous> (D:\a\_actions\lukka\run-vcpkg\v10\dist\index.js:7124:28)
    at Generator.next (<anonymous>)
    at fulfilled (D:\a\_actions\lukka\run-vcpkg\v10\dist\index.js:6982:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: run-vcpkg action execution failed: Last command execution failed with error code '1'.
```

The full build log can be seen here: https://github.com/zenustech/zeno/runs/6136895750?check_suite_focus=true

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
Can we have a CI to test all package are working well? We are constantly getting random vcpkg build failures these days.

**Comment by archibate** [comment]
The Ubuntu 18.04 build worked BTW. Maybe because win cannot modify the file on-the-fly when it's being opened.

**Comment by JackBoosY** [comment]
cc @BillyONeal

**Comment by BillyONeal** [comment]
Looks like antivirus interference.

**Comment by archibate** [comment]
GitHub actions has antivirus software?

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
