### ISSUE TITLE
libepoxy fails to configure

### ISSUE THREAD

**Issue by mohitisgreat** [Microsoft/vcpkg#2660]
Package: libepoxy:x86-windows
  Vcpkg version: 0.0.103-unknownhash

ON vcpkg install libepoxy
===================================
The following packages will be built and installed:
    libepoxy[core]:x86-windows
Starting package 1/1: libepoxy:x86-windows
Building package libepoxy[core]:x86-windows...
-- CURRENT_INSTALLED_DIR=E:/IDM_Downloads/vcpkg-master/installed/x86-windows
-- DOWNLOADS=E:/IDM_Downloads/vcpkg-master/downloads
-- CURRENT_PACKAGES_DIR=E:/IDM_Downloads/vcpkg-master/packages/libepoxy_x86-windows
-- CURRENT_BUILDTREES_DIR=E:/IDM_Downloads/vcpkg-master/buildtrees/libepoxy
-- CURRENT_PORT_DIR=E:/IDM_Downloads/vcpkg-master/ports/libepoxy/.
-- Using cached E:/IDM_Downloads/vcpkg-master/downloads/anholt-libepoxy-1.4.3.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Configuring x86-windows-rel
CMake Error at E:/IDM_Downloads/vcpkg-master/scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: E:/IDM_Downloads/vcpkg-master/downloads/tools/python/python3/python.exe;E:/IDM_Downloads/vcpkg-master/downloads/tools/meson/meson-0.43.0/meson.py;-Denable-glx=no;-Denable-e
gl=no;--buildtype;plain;--backend;ninja;--default-library;shared;--prefix;E:/IDM_Downloads/vcpkg-master/packages/libepoxy_x86-windows;E:/IDM_Downloads/vcpkg-master/buildtrees/libepoxy/src/libe
poxy-1.4.3
    Working Directory: E:/IDM_Downloads/vcpkg-master/buildtrees/libepoxy/x86-windows-rel
    See logs for more information:
      E:\IDM_Downloads\vcpkg-master\buildtrees\libepoxy\config-x86-windows-rel-out.log
      E:\IDM_Downloads\vcpkg-master\buildtrees\libepoxy\config-x86-windows-rel-err.log

Call Stack (most recent call first):
  E:/IDM_Downloads/vcpkg-master/scripts/cmake/vcpkg_configure_meson.cmake:52 (vcpkg_execute_required_process)
  E:/IDM_Downloads/vcpkg-master/ports/libepoxy/portfile.cmake:14 (vcpkg_configure_meson)
  E:/IDM_Downloads/vcpkg-master/scripts/ports.cmake:72 (include)

Error: Building package libepoxy:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libepoxy:x86-windows
  Vcpkg version: 0.0.103-unknownhash

Additionally, attach any relevant sections from the log files above.

config-x86-windows-rel-out.log:
==========================
The Meson build system
Version: 0.43.0
Source dir: E:\IDM_Downloads\vcpkg-master\buildtrees\libepoxy\src\libepoxy-1.4.3
Build dir: E:\IDM_Downloads\vcpkg-master\buildtrees\libepoxy\x86-windows-rel
Build type: native build
Project name: libepoxy
Native C compiler: cl (msvc 19.12.25835)
Appending CFLAGS from environment: ' /DWIN32 /D_WINDOWS /W3 /utf-8  /MD /O2 /Oi /Gy /DNDEBUG /Z7'
Appending LDFLAGS from environment: ' /DEBUG  /INCREMENTAL:NO /OPT:REF /OPT:ICF'
Appending CPPFLAGS from environment: ' '
Build machine cpu family: x86
Build machine cpu: x86
Has header "KHR/khrplatform.h": NO
Compiler for C supports argument -we4002: YES
Compiler for C supports argument -we4003: YES
Compiler for C supports argument -w14010: YES
Compiler for C supports argument -we4013: YES
Compiler for C supports argument -w14016: YES
Compiler for C supports argument -we4020: YES
Compiler for C supports argument -we4021: YES
Compiler for C supports argument -we4027: YES
Compiler for C supports argument -we4029: YES
Compiler for C supports argument -we4033: YES
Compiler for C supports argument -we4035: YES
Compiler for C supports argument -we4045: YES
Compiler for C supports argument -we4047: YES
Compiler for C supports argument -we4049: YES
Compiler for C supports argument -we4053: YES
Compiler for C supports argument -we4071: YES
Compiler for C supports argument -we4819: YES
Library dl found: NO
Found Pkg-config: NO
Dependency egl found: NO
Dependency x11 found: NO
Dependency glesv2 found: NO
Library libGLESv2 found: NO
Dependency glesv1_cm found: NO
Library libGLESv1_CM found: NO
Library opengl32 found: YES
Library gdi32 found: YES
Configuring epoxy.pc using configuration
WARNING: The variable(s) 'DLOPEN_LIBS' in the input file epoxy.pc.in are not present in the given configuration data
Configuring config.h using configuration
Build targets in project: 13

config-x86-windows-rel-err.log:
==========================
Traceback (most recent call last):
  File "E:\IDM_Downloads\vcpkg-master\downloads\tools\meson\meson-0.43.0\mesonbuild\mesonmain.py", line 352, in run
    app.generate()
  File "E:\IDM_Downloads\vcpkg-master\downloads\tools\meson\meson-0.43.0\mesonbuild\mesonmain.py", line 147, in generate
    self._generate(env)
  File "E:\IDM_Downloads\vcpkg-master\downloads\tools\meson\meson-0.43.0\mesonbuild\mesonmain.py", line 197, in _generate
    g.generate(intr)
  File "E:\IDM_Downloads\vcpkg-master\downloads\tools\meson\meson-0.43.0\mesonbuild\backend\ninjabackend.py", line 194, in generate
    self.ninja_command = environment.detect_ninja(log=True)
  File "E:\IDM_Downloads\vcpkg-master\downloads\tools\meson\meson-0.43.0\mesonbuild\environment.py", line 96, in detect_ninja
    p, found = Popen_safe([n, '--version'])[0:2]
  File "E:\IDM_Downloads\vcpkg-master\downloads\tools\meson\meson-0.43.0\mesonbuild\mesonlib.py", line 544, in Popen_safe
    return Popen_safe_legacy(args, write=write, stderr=stderr, **kwargs)
  File "E:\IDM_Downloads\vcpkg-master\downloads\tools\meson\meson-0.43.0\mesonbuild\mesonlib.py", line 555, in Popen_safe_legacy
    stderr=stderr, **kwargs)
  File "subprocess.py", line 676, in __init__
  File "subprocess.py", line 957, in _execute_child
OSError: [WinError 216] This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher

**Comment by mohitisgreat** [comment]
I was using x86-based windows but the ninja was x64 which caused this issue after compiling the ninja from source(as it doesn't have x86 pre-built binaries, at least I can't find one) and moving to the tools directory fixed my issue.
