### ISSUE TITLE
When I execute the command python3 setup.py build, the following problem occurs

### ISSUE THREAD

**Issue by fossettekkss** [microsoft/vcpkg#27248]
Please create a discussion in https://github.com/microsoft/vcpkg/discussions/new instead.
~~~When I execute the command python3 setup.py build, the following problem occurs~~~

CMake Warning at D:/My document/My code/code/myproject/github-opensfm/OpenSfM/vcpkg/scripts/buildsystems/vcpkg.cmake:834 (_find_package):
  Could not find a configuration file for package "Ceres" that is compatible
  with requested version "".

  The following configuration files were considered but not accepted:

    D:/My document/My code/code/myproject/github-opensfm/OpenSfM/vcpkg/installed/x64-windows/share/ceres/CeresConfig.cmake, version: 2.1.0 (64bit)

Call Stack (most recent call first):
  CMakeLists.txt:58 (find_package)


-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
-- Found installed version of gflags: D:/My document/My code/code/myproject/github-opensfm/OpenSfM/vcpkg/installed/x64-windows/share/gflags
-- Detected gflags version: 2.2.2
-- Found OpenCV: D:/My document/My code/code/myproject/github-opensfm/OpenSfM/vcpkg/installed/x64-windows (found version "4.6.0")
-- Found OpenCV: D:/My document/My code/code/myproject/github-opensfm/OpenSfM/vcpkg/installed/x64-windows (found version "4.6.0") found components: core imgproc calib3d imgcodecs
CMake Error at third_party/pybind11/tools/FindPythonLibsNew.cmake:122 (message):
  Python config failure: Python is 64-bit, chosen compiler is 32-bit
Call Stack (most recent call first):
  D:/My document/My code/code/myproject/github-opensfm/OpenSfM/vcpkg/scripts/buildsystems/vcpkg.cmake:834 (_find_package)
  third_party/pybind11/tools/pybind11Tools.cmake:16 (find_package)
  third_party/pybind11/CMakeLists.txt:33 (include)


-- Configuring incomplete, errors occurred!
See also "D:/My document/My code/code/myproject/github-opensfm/OpenSfM/cmake_build/CMakeFiles/CMakeOutput.log".
See also "D:/My document/My code/code/myproject/github-opensfm/OpenSfM/cmake_build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 59, in <module>
    configure_c_extension()
  File "setup.py", line 43, in configure_c_extension
    subprocess.check_call(cmake_command, cwd="cmake_build")
  File "d:\Users\fossettekk\Anaconda3\envs\opensfm1\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '../opensfm/src', '-DPYTHON_EXECUTABLE=d:\\Users\\fossettekk\\Anaconda3\\envs\\opensfm1\\python.exe', '-DVCPKG_TARGET_TRIPLET=x64-windows', '-DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake']' returned non-zero exit status 1.


So I was unable to use opensfm when I executed the next command

**Comment by Adela0814** [comment]
@fossettekkss please provide the reproduce steps and full failure logs. Thanks.

**Comment by Adela0814** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
