### ISSUE TITLE
[glib:x64-windows] build failure

### ISSUE THREAD

**Issue by ajtribick** [microsoft/vcpkg#27405]
Package: glib[core]:x64-windows -> 2.74.0

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.33.31630.0
-    vcpkg-tool version: 2022-10-17-3247920fbdd47d08f36cbd480addd9890d3c2435
    vcpkg-scripts version: 934a99dc1 2022-10-21 (23 hours ago)

**To Reproduce**

`vcpkg install glib`

**Failure logs**

```
-- Downloading https://download.gnome.org/sources/glib/2.74/glib-2.74.0.tar.xz -> glib-2.74.0.tar.xz...
-- Extracting source C:/vcpkg/downloads/glib-2.74.0.tar.xz
-- Applying patch use-libiconv-on-windows.patch
-- Applying patch libintl.patch
-- Using source at C:/vcpkg/buildtrees/glib/src/glib-2-22354247da.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-windows
-- Configuring x64-windows-dbg
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at C:/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Configuring x64-windows-dbg done
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Package x64-windows-dbg
-- Package x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" install -v
    Working Directory: C:/vcpkg/buildtrees/glib/x64-windows-rel
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\glib\package-x64-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_meson.cmake:33 (vcpkg_execute_required_process)
  ports/glib/portfile.cmake:47 (vcpkg_install_meson)
  scripts/ports.cmake:147 (include)



```
<details><summary>C:\vcpkg\buildtrees\glib\package-x64-windows-rel-out.log</summary>

```
[1/566] "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe" "-Iglib\gnulib\libgnulib.a.p" "-Iglib\gnulib" "-I..\src\glib-2-22354247da.clean\glib\gnulib" "-I." "-I..\src\glib-2-22354247da.clean" "-Iglib" "-I..\src\glib-2-22354247da.clean\glib" "-IC:/vcpkg/installed/x64-windows/include" "/MD" "/nologo" "/showIncludes" "/utf-8" "/W4" "/Od" "/FImsvc_recommended_pragmas.h" "/utf-8" "-D_GNU_SOURCE" "/wo4057" "/wd4068" "/wo4090" "/wd4100" "/wd4116" "/wo4125" "/wd4127" "/wd4146" "/wd4152" "/wd4201" "/wd4232" "/wo4245" "/wo4267" "/wd4334" "/wo4389" "/wo4702" "/wd4706" "-nologo" "-DWIN32" "-D_WINDOWS" "-W3" "-utf-8" "-MP" "-MD" "-O2" "-Oi" "-Gy" "-DNDEBUG" "-Z7" "-DGCC_LINT=1" "-DLIBDIR=\"C:/vcpkg/packages/glib_x64-windows/lib\"" "-DGLIB_COMPILATION" "-DG_LOG_DOMAIN=\"GLib\"" "-DHAVE_ISNAN_IN_LIBC" "-DHAVE_ISNAND_IN_LIBC" "-DHAVE_ISNANF_IN_LIBC" "-DHAVE_ISNANL_IN_LIBC" "/Fdglib\gnulib\libgnulib.a.p\printf-frexpl.c.pdb" /Foglib/gnulib/libgnulib.a.p/printf-frexpl.c.obj "/c" ../src/glib-2-22354247da.clean/glib/gnulib/printf-frexpl.c
cl : Command line warning D9025 : overriding '/W4' with '/W3'
cl : Command line warning D9025 : overriding '/Od' with '/O2'
[2/566] "C:/Program Files (x86)/Windows Kits/10/bin/10.0.19041.0/x64/rc.exe" "/nologo" "/foglib/glib_glib.rc_glib.res" "glib/glib.rc"
[3/566] "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe" "-Iglib\gnulib\libgnulib.a.p" "-Iglib\gnulib" "-I..\src\glib-2-22354247da.clean\glib\gnulib" "-I." "-I..\src\glib-2-22354247da.clean" "-Iglib" "-I..\src\glib-2-22354247da.clean\glib" "-IC:/vcpkg/installed/x64-windows/include" "/MD" "/nologo" "/showIncludes" "/utf-8" "/W4" "/Od" "/FImsvc_recommended_pragmas.h" "/utf-8" "-D_GNU_SOURCE" "/wo4057" "/wd4068" "/wo4090" "/wd4100" "/wd4116" "/wo4125" "/wd4127" "/wd4146" "/wd4152" "/wd4201" "/wd4232" "/wo4245" "/wo4267" "/wd4334" "/wo4389" "/wo4702" "/wd4706" "-nologo" "-DWIN32" "-D_WINDOWS" "-W3" "-utf-8" "-MP" "-MD" "-O2" "-Oi" "-Gy" "-DNDEBUG" "-Z7" "-DGCC_LINT=1" "-DLIBDIR=\"C:/vcpkg/packages/glib_x64-windows/lib\"" "-DGLIB_COMPILATION" "-DG_LOG_DOMAIN=\"GLib\"" "-DHAVE_ISNAN_IN_LIBC" "-DHAVE_ISNAND_IN_LIBC" "-DHAVE_ISNANF_IN_LIBC" "-DHAVE_ISNANL_IN_LIBC" "/Fdglib\gnulib\libgnulib.a.p\printf-frexp.c.pdb" /Foglib/gnulib/libgnulib.a.p/printf-frexp.c.obj "/c" ../src/glib-2-22354247da.clean/glib/gnulib/printf-frexp.c
cl : Command line warning D9025 : overriding '/W4' with '/W3'
cl : Command line warning D9025 : overriding '/Od' with '/O2'
[4/566] "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe" "-Iglib\glib-2.0-0.dll.p" "-Iglib" "-I..\src\glib-2-22354247da.clean\glib" "-I." "-I..\src\glib-2-22354247da.clean" "-IC:/vcpkg/installed/x64-windows/include" "/MD" "/nologo" "/showIncludes" "/utf-8" "/W4" "/Od" "/FImsvc_recommended_pragmas.h" "/utf-8" "-D_GNU_SOURCE" "/wo4057" "/wd4068" "/wo4090" "/wd4100" "/wd4116" "/wo4125" "/wd4127" "/wd4146" "/wd4152" "/wd4201" "/wd4232" "/wo4245" "/wo4267" "/wd4334" "/wo4389" "/wo4702" "/wd4706" "-nologo" "-DWIN32" "-D_WINDOWS" "-W3" "-utf-8" "-MP" "-MD" "-O2" "-Oi" "-Gy" "-DNDEBUG" "-Z7" "-DG_LOG_DOMAIN=\"GLib\"" "-DGLIB_COMPILATION" "-DPCRE2_STATIC" "/Fdglib\glib-2.0-0.dll.p\deprecated_gallocator.c.pdb" /Foglib/glib-2.0-0.dll.p/deprecated_gallocator.c.obj "/c" ../src/glib-2-22354247da.clean/glib/deprecated/gallocator.c
...
Skipped 757 lines
...

[297/566] "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe" "-Igio\gio-2.0-0.dll.p" "-Igio" "-I..\src\glib-2-22354247da.clean\gio" "-I." "-I..\src\glib-2-22354247da.clean" "-Iglib" "-I..\src\glib-2-22354247da.clean\glib" "-Igobject" "-I..\src\glib-2-22354247da.clean\gobject" "-Igmodule" "-I..\src\glib-2-22354247da.clean\gmodule" "-Isubprojects\gvdb" "-I..\src\glib-2-22354247da.clean\subprojects\gvdb" "-IC:/vcpkg/installed/x64-windows/include" "/MD" "/nologo" "/showIncludes" "/utf-8" "/W4" "/Od" "/FImsvc_recommended_pragmas.h" "/utf-8" "-D_GNU_SOURCE" "/wo4057" "/wd4068" "/wo4090" "/wd4100" "/wd4116" "/wo4125" "/wd4127" "/wd4146" "/wd4152" "/wd4201" "/wd4232" "/wo4245" "/wo4267" "/wd4334" "/wo4389" "/wo4702" "/wd4706" "-nologo" "-DWIN32" "-D_WINDOWS" "-W3" "-utf-8" "-MP" "-MD" "-O2" "-Oi" "-Gy" "-DNDEBUG" "-Z7" "-DG_LOG_DOMAIN=\"GLib-GIO\"" "-DGIO_COMPILATION" "-DGIO_LAUNCH_DESKTOP=\"C:/vcpkg/packages/glib_x64-windows/libexec/gio-launch-desktop\"" "-DGIO_MODULE_DIR=\"C:/vcpkg/packages/glib_x64-windows/lib/gio/modules\"" "-DLOCALSTATEDIR=\"C:/vcpkg/packages/glib_x64-windows/var\"" "/Fdgio\gio-2.0-0.dll.p\gdebugcontrollerdbus.c.pdb" /Fogio/gio-2.0-0.dll.p/gdebugcontrollerdbus.c.obj "/c" ../src/glib-2-22354247da.clean/gio/gdebugcontrollerdbus.c
cl : Command line warning D9025 : overriding '/W4' with '/W3'
cl : Command line warning D9025 : overriding '/Od' with '/O2'
C:\vcpkg\buildtrees\glib\x64-windows-rel\gio/gioenumtypes.h(1): warning C4828: The file contains a character starting at offset 0xe8 that is illegal in the current source character set (codepage 65001).
[298/566] "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe" "-Igio\gio-2.0-0.dll.p" "-Igio" "-I..\src\glib-2-22354247da.clean\gio" "-I." "-I..\src\glib-2-22354247da.clean" "-Iglib" "-I..\src\glib-2-22354247da.clean\glib" "-Igobject" "-I..\src\glib-2-22354247da.clean\gobject" "-Igmodule" "-I..\src\glib-2-22354247da.clean\gmodule" "-Isubprojects\gvdb" "-I..\src\glib-2-22354247da.clean\subprojects\gvdb" "-IC:/vcpkg/installed/x64-windows/include" "/MD" "/nologo" "/showIncludes" "/utf-8" "/W4" "/Od" "/FImsvc_recommended_pragmas.h" "/utf-8" "-D_GNU_SOURCE" "/wo4057" "/wd4068" "/wo4090" "/wd4100" "/wd4116" "/wo4125" "/wd4127" "/wd4146" "/wd4152" "/wd4201" "/wd4232" "/wo4245" "/wo4267" "/wd4334" "/wo4389" "/wo4702" "/wd4706" "-nologo" "-DWIN32" "-D_WINDOWS" "-W3" "-utf-8" "-MP" "-MD" "-O2" "-Oi" "-Gy" "-DNDEBUG" "-Z7" "-DG_LOG_DOMAIN=\"GLib-GIO\"" "-DGIO_COMPILATION" "-DGIO_LAUNCH_DESKTOP=\"C:/vcpkg/packages/glib_x64-windows/libexec/gio-launch-desktop\"" "-DGIO_MODULE_DIR=\"C:/vcpkg/packages/glib_x64-windows/lib/gio/modules\"" "-DLOCALSTATEDIR=\"C:/vcpkg/packages/glib_x64-windows/var\"" "/Fdgio\gio-2.0-0.dll.p\gdatainputstream.c.pdb" /Fogio/gio-2.0-0.dll.p/gdatainputstream.c.obj "/c" ../src/glib-2-22354247da.clean/gio/gdatainputstream.c
cl : Command line warning D9025 : overriding '/W4' with '/W3'
cl : Command line warning D9025 : overriding '/Od' with '/O2'
C:\vcpkg\buildtrees\glib\x64-windows-rel\gio\gioenumtypes.h(1): warning C4828: The file contains a character starting at offset 0xe8 that is illegal in the current source character set (codepage 65001).
[299/566] "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe" "-Igio\gio-2.0-0.dll.p" "-Igio" "-I..\src\glib-2-22354247da.clean\gio" "-I." "-I..\src\glib-2-22354247da.clean" "-Iglib" "-I..\src\glib-2-22354247da.clean\glib" "-Igobject" "-I..\src\glib-2-22354247da.clean\gobject" "-Igmodule" "-I..\src\glib-2-22354247da.clean\gmodule" "-Isubprojects\gvdb" "-I..\src\glib-2-22354247da.clean\subprojects\gvdb" "-IC:/vcpkg/installed/x64-windows/include" "/MD" "/nologo" "/showIncludes" "/utf-8" "/W4" "/Od" "/FImsvc_recommended_pragmas.h" "/utf-8" "-D_GNU_SOURCE" "/wo4057" "/wd4068" "/wo4090" "/wd4100" "/wd4116" "/wo4125" "/wd4127" "/wd4146" "/wd4152" "/wd4201" "/wd4232" "/wo4245" "/wo4267" "/wd4334" "/wo4389" "/wo4702" "/wd4706" "-nologo" "-DWIN32" "-D_WINDOWS" "-W3" "-utf-8" "-MP" "-MD" "-O2" "-Oi" "-Gy" "-DNDEBUG" "-Z7" "-DG_LOG_DOMAIN=\"GLib-GIO\"" "-DGIO_COMPILATION" "-DGIO_LAUNCH_DESKTOP=\"C:/vcpkg/packages/glib_x64-windows/libexec/gio-launch-desktop\"" "-DGIO_MODULE_DIR=\"C:/vcpkg/packages/glib_x64-windows/lib/gio/modules\"" "-DLOCALSTATEDIR=\"C:/vcpkg/packages/glib_x64-windows/var\"" "/Fdgio\gio-2.0-0.dll.p\gdatagrambased.c.pdb" /Fogio/gio-2.0-0.dll.p/gdatagrambased.c.obj "/c" ../src/glib-2-22354247da.clean/gio/gdatagrambased.c
cl : Command line warning D9025 : overriding '/W4' with '/W3'
cl : Command line warning D9025 : overriding '/Od' with '/O2'
C:\vcpkg\buildtrees\glib\x64-windows-rel\gio\gioenumtypes.h(1): warning C4828: The file contains a character starting at offset 0xe8 that is illegal in the current source character set (codepage 65001).
[300/566] "C:\vcpkg\downloads\tools\python\python-3.10.5-x64\python.exe" "C:\vcpkg\installed\x64-windows\tools\meson\meson.py" "--internal" "symbolextractor" "C:\vcpkg\buildtrees\glib\x64-windows-rel" gobject/gobject-2.0-0.dll "gobject\gobject-2.0.lib" gobject/gobject-2.0-0.dll.p/gobject-2.0-0.dll.symbols 
[301/566] "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe" "-Igio\gio-2.0-0.dll.p" "-Igio" "-I..\src\glib-2-22354247da.clean\gio" "-I." "-I..\src\glib-2-22354247da.clean" "-Iglib" "-I..\src\glib-2-22354247da.clean\glib" "-Igobject" "-I..\src\glib-2-22354247da.clean\gobject" "-Igmodule" "-I..\src\glib-2-22354247da.clean\gmodule" "-Isubprojects\gvdb" "-I..\src\glib-2-22354247da.clean\subprojects\gvdb" "-IC:/vcpkg/installed/x64-windows/include" "/MD" "/nologo" "/showIncludes" "/utf-8" "/W4" "/Od" "/FImsvc_recommended_pragmas.h" "/utf-8" "-D_GNU_SOURCE" "/wo4057" "/wd4068" "/wo4090" "/wd4100" "/wd4116" "/wo4125" "/wd4127" "/wd4146" "/wd4152" "/wd4201" "/wd4232" "/wo4245" "/wo4267" "/wd4334" "/wo4389" "/wo4702" "/wd4706" "-nologo" "-DWIN32" "-D_WINDOWS" "-W3" "-utf-8" "-MP" "-MD" "-O2" "-Oi" "-Gy" "-DNDEBUG" "-Z7" "-DG_LOG_DOMAIN=\"GLib-GIO\"" "-DGIO_COMPILATION" "-DGIO_LAUNCH_DESKTOP=\"C:/vcpkg/packages/glib_x64-windows/libexec/gio-launch-desktop\"" "-DGIO_MODULE_DIR=\"C:/vcpkg/packages/glib_x64-windows/lib/gio/modules\"" "-DLOCALSTATEDIR=\"C:/vcpkg/packages/glib_x64-windows/var\"" "/Fdgio\gio-2.0-0.dll.p\giomodule.c.pdb" /Fogio/gio-2.0-0.dll.p/giomodule.c.obj "/c" ../src/glib-2-22354247da.clean/gio/giomodule.c
cl : Command line warning D9025 : overriding '/W4' with '/W3'
cl : Command line warning D9025 : overriding '/Od' with '/O2'
C:\vcpkg\buildtrees\glib\x64-windows-rel\gio/gioenumtypes.h(1): warning C4828: The file contains a character starting at offset 0xe8 that is illegal in the current source character set (codepage 65001).
[302/566] "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe" "-Igio\gio-2.0-0.dll.p" "-Igio" "-I..\src\glib-2-22354247da.clean\gio" "-I." "-I..\src\glib-2-22354247da.clean" "-Iglib" "-I..\src\glib-2-22354247da.clean\glib" "-Igobject" "-I..\src\glib-2-22354247da.clean\gobject" "-Igmodule" "-I..\src\glib-2-22354247da.clean\gmodule" "-Isubprojects\gvdb" "-I..\src\glib-2-22354247da.clean\subprojects\gvdb" "-IC:/vcpkg/installed/x64-windows/include" "/MD" "/nologo" "/showIncludes" "/utf-8" "/W4" "/Od" "/FImsvc_recommended_pragmas.h" "/utf-8" "-D_GNU_SOURCE" "/wo4057" "/wd4068" "/wo4090" "/wd4100" "/wd4116" "/wo4125" "/wd4127" "/wd4146" "/wd4152" "/wd4201" "/wd4232" "/wo4245" "/wo4267" "/wd4334" "/wo4389" "/wo4702" "/wd4706" "-nologo" "-DWIN32" "-D_WINDOWS" "-W3" "-utf-8" "-MP" "-MD" "-O2" "-Oi" "-Gy" "-DNDEBUG" "-Z7" "-DG_LOG_DOMAIN=\"GLib-GIO\"" "-DGIO_COMPILATION" "-DGIO_LAUNCH_DESKTOP=\"C:/vcpkg/packages/glib_x64-windows/libexec/gio-launch-desktop\"" "-DGIO_MODULE_DIR=\"C:/vcpkg/packages/glib_x64-windows/lib/gio/modules\"" "-DLOCALSTATEDIR=\"C:/vcpkg/packages/glib_x64-windows/var\"" "/Fdgio\gio-2.0-0.dll.p\gdummyfile.c.pdb" /Fogio/gio-2.0-0.dll.p/gdummyfile.c.obj "/c" ../src/glib-2-22354247da.clean/gio/gdummyfile.c
cl : Command line warning D9025 : overriding '/W4' with '/W3'
cl : Command line warning D9025 : overriding '/Od' with '/O2'
C:\vcpkg\buildtrees\glib\x64-windows-rel\gio/gioenumtypes.h(1): warning C4828: The file contains a character starting at offset 0xe8 that is illegal in the current source character set (codepage 65001).
../src/glib-2-22354247da.clean/gio/gdummyfile.c(244): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
[303/566] "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe" "-Igio\gio-2.0-0.dll.p" "-Igio" "-I..\src\glib-2-22354247da.clean\gio" "-I." "-I..\src\glib-2-22354247da.clean" "-Iglib" "-I..\src\glib-2-22354247da.clean\glib" "-Igobject" "-I..\src\glib-2-22354247da.clean\gobject" "-Igmodule" "-I..\src\glib-2-22354247da.clean\gmodule" "-Isubprojects\gvdb" "-I..\src\glib-2-22354247da.clean\subprojects\gvdb" "-IC:/vcpkg/installed/x64-windows/include" "/MD" "/nologo" "/showIncludes" "/utf-8" "/W4" "/Od" "/FImsvc_recommended_pragmas.h" "/utf-8" "-D_GNU_SOURCE" "/wo4057" "/wd4068" "/wo4090" "/wd4100" "/wd4116" "/wo4125" "/wd4127" "/wd4146" "/wd4152" "/wd4201" "/wd4232" "/wo4245" "/wo4267" "/wd4334" "/wo4389" "/wo4702" "/wd4706" "-nologo" "-DWIN32" "-D_WINDOWS" "-W3" "-utf-8" "-MP" "-MD" "-O2" "-Oi" "-Gy" "-DNDEBUG" "-Z7" "-DG_LOG_DOMAIN=\"GLib-GIO\"" "-DGIO_COMPILATION" "-DGIO_LAUNCH_DESKTOP=\"C:/vcpkg/packages/glib_x64-windows/libexec/gio-launch-desktop\"" "-DGIO_MODULE_DIR=\"C:/vcpkg/packages/glib_x64-windows/lib/gio/modules\"" "-DLOCALSTATEDIR=\"C:/vcpkg/packages/glib_x64-windows/var\"" "/Fdgio\gio-2.0-0.dll.p\gcredentials.c.pdb" /Fogio/gio-2.0-0.dll.p/gcredentials.c.obj "/c" ../src/glib-2-22354247da.clean/gio/gcredentials.c
cl : Command line warning D9025 : overriding '/W4' with '/W3'
cl : Command line warning D9025 : overriding '/Od' with '/O2'
C:\vcpkg\buildtrees\glib\x64-windows-rel\gio\gioenumtypes.h(1): warning C4828: The file contains a character starting at offset 0xe8 that is illegal in the current source character set (codepage 65001).
[304/566] "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe" "-Igio\gio-2.0-0.dll.p" "-Igio" "-I..\src\glib-2-22354247da.clean\gio" "-I." "-I..\src\glib-2-22354247da.clean" "-Iglib" "-I..\src\glib-2-22354247da.clean\glib" "-Igobject" "-I..\src\glib-2-22354247da.clean\gobject" "-Igmodule" "-I..\src\glib-2-22354247da.clean\gmodule" "-Isubprojects\gvdb" "-I..\src\glib-2-22354247da.clean\subprojects\gvdb" "-IC:/vcpkg/installed/x64-windows/include" "/MD" "/nologo" "/showIncludes" "/utf-8" "/W4" "/Od" "/FImsvc_recommended_pragmas.h" "/utf-8" "-D_GNU_SOURCE" "/wo4057" "/wd4068" "/wo4090" "/wd4100" "/wd4116" "/wo4125" "/wd4127" "/wd4146" "/wd4152" "/wd4201" "/wd4232" "/wo4245" "/wo4267" "/wd4334" "/wo4389" "/wo4702" "/wd4706" "-nologo" "-DWIN32" "-D_WINDOWS" "-W3" "-utf-8" "-MP" "-MD" "-O2" "-Oi" "-Gy" "-DNDEBUG" "-Z7" "-DG_LOG_DOMAIN=\"GLib-GIO\"" "-DGIO_COMPILATION" "-DGIO_LAUNCH_DESKTOP=\"C:/vcpkg/packages/glib_x64-windows/libexec/gio-launch-desktop\"" "-DGIO_MODULE_DIR=\"C:/vcpkg/packages/glib_x64-windows/lib/gio/modules\"" "-DLOCALSTATEDIR=\"C:/vcpkg/packages/glib_x64-windows/var\"" "/Fdgio\gio-2.0-0.dll.p\gfile.c.pdb" /Fogio/gio-2.0-0.dll.p/gfile.c.obj "/c" ../src/glib-2-22354247da.clean/gio/gfile.c
cl : Command line warning D9025 : overriding '/W4' with '/W3'
cl : Command line warning D9025 : overriding '/Od' with '/O2'
C:\vcpkg\buildtrees\glib\x64-windows-rel\gio/gioenumtypes.h(1): warning C4828: The file contains a character starting at offset 0xe8 that is illegal in the current source character set (codepage 65001).
[305/566] "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe" "-Igio\gio-2.0-0.dll.p" "-Igio" "-I..\src\glib-2-22354247da.clean\gio" "-I." "-I..\src\glib-2-22354247da.clean" "-Iglib" "-I..\src\glib-2-22354247da.clean\glib" "-Igobject" "-I..\src\glib-2-22354247da.clean\gobject" "-Igmodule" "-I..\src\glib-2-22354247da.clean\gmodule" "-Isubprojects\gvdb" "-I..\src\glib-2-22354247da.clean\subprojects\gvdb" "-IC:/vcpkg/installed/x64-windows/include" "/MD" "/nologo" "/showIncludes" "/utf-8" "/W4" "/Od" "/FImsvc_recommended_pragmas.h" "/utf-8" "-D_GNU_SOURCE" "/wo4057" "/wd4068" "/wo4090" "/wd4100" "/wd4116" "/wo4125" "/wd4127" "/wd4146" "/wd4152" "/wd4201" "/wd4232" "/wo4245" "/wo4267" "/wd4334" "/wo4389" "/wo4702" "/wd4706" "-nologo" "-DWIN32" "-D_WINDOWS" "-W3" "-utf-8" "-MP" "-MD" "-O2" "-Oi" "-Gy" "-DNDEBUG" "-Z7" "-DG_LOG_DOMAIN=\"GLib-GIO\"" "-DGIO_COMPILATION" "-DGIO_LAUNCH_DESKTOP=\"C:/vcpkg/packages/glib_x64-windows/libexec/gio-launch-desktop\"" "-DGIO_MODULE_DIR=\"C:/vcpkg/packages/glib_x64-windows/lib/gio/modules\"" "-DLOCALSTATEDIR=\"C:/vcpkg/packages/glib_x64-windows/var\"" "/Fdgio\gio-2.0-0.dll.p\gfileenumerator.c.pdb" /Fogio/gio-2.0-0.dll.p/gfileenumerator.c.obj "/c" ../src/glib-2-22354247da.clean/gio/gfileenumerator.c
cl : Command line warning D9025 : overriding '/W4' with '/W3'
cl : Command line warning D9025 : overriding '/Od' with '/O2'
C:\vcpkg\buildtrees\glib\x64-windows-rel\gio/gioenumtypes.h(1): warning C4828: The file contains a character starting at offset 0xe8 that is illegal in the current source character set (codepage 65001).
ninja: build stopped: subcommand failed.
```
</details>

**Additional context**

Actual failure seems to be here:

```
[288/566] "C:\vcpkg\downloads\tools\python\python-3.10.5-x64\python.exe" "C:\vcpkg\installed\x64-windows\tools\meson\meson.py" "--internal" "symbolextractor" "C:\vcpkg\buildtrees\glib\x64-windows-rel" gmodule/gmodule-2.0-0.dll "gmodule\gmodule-2.0.lib" gmodule/gmodule-2.0-0.dll.p/gmodule-2.0-0.dll.symbols 
FAILED: gmodule/gmodule-2.0-0.dll.p/gmodule-2.0-0.dll.symbols 
"C:\vcpkg\downloads\tools\python\python-3.10.5-x64\python.exe" "C:\vcpkg\installed\x64-windows\tools\meson\meson.py" "--internal" "symbolextractor" "C:\vcpkg\buildtrees\glib\x64-windows-rel" gmodule/gmodule-2.0-0.dll "gmodule\gmodule-2.0.lib" gmodule/gmodule-2.0-0.dll.p/gmodule-2.0-0.dll.symbols 
Traceback (most recent call last):
  File "C:\vcpkg\installed\x64-windows\tools\meson\meson.py", line 29, in <module>
    sys.exit(mesonmain.main())
  File "C:\vcpkg\installed\x64-windows\tools\meson\mesonbuild\mesonmain.py", line 271, in main
    return run(sys.argv[1:], launcher)
  File "C:\vcpkg\installed\x64-windows\tools\meson\mesonbuild\mesonmain.py", line 260, in run
    return run_script_command(args[1], args[2:])
  File "C:\vcpkg\installed\x64-windows\tools\meson\mesonbuild\mesonmain.py", line 203, in run_script_command
    return module.run(script_args)
  File "C:\vcpkg\installed\x64-windows\tools\meson\mesonbuild\scripts\symbolextractor.py", line 329, in run
    gen_symbols(libfile, impfile, outfile, options.cross_host)
  File "C:\vcpkg\installed\x64-windows\tools\meson\mesonbuild\scripts\symbolextractor.py", line 295, in gen_symbols
    windows_syms(impfilename, outfilename)
  File "C:\vcpkg\installed\x64-windows\tools\meson\mesonbuild\scripts\symbolextractor.py", line 269, in windows_syms
    symbols, e = _get_implib_exports(impfilename)
  File "C:\vcpkg\installed\x64-windows\tools\meson\mesonbuild\scripts\symbolextractor.py", line 243, in _get_implib_exports
    start = lines.index('File Type: LIBRARY')
ValueError: 'File Type: LIBRARY' is not in list
```

**Comment by Cheney-W** [comment]
This issue is not reproducible on the glib 2.76.
```
Installing 3/3 glib:x64-windows...
Building glib:x64-windows...
-- Downloading https://download.gnome.org/sources/glib/2.76/glib-2.76.3.tar.xz -> glib-2.76.3.tar.xz...
-- Extracting source F:/vcpkg/downloads/glib-2.76.3.tar.xz
-- Applying patch use-libiconv-on-windows.patch
-- Applying patch libintl.patch
-- Using source at F:/vcpkg/buildtrees/glib/src/glib-2-fa63404107
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Downloading https://www.python.org/ftp/python/3.10.7/python-3.10.7-embed-amd64.zip -> python-3.10.7-embed-amd64.zip...
-- Configuring x64-windows-dbg
-- Using cached mingw-w64-i686-pkgconf-1~1.8.0-2-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using msys root at F:/vcpkg/downloads/tools/msys2/6f3fa1a12ef85a6f
-- Configuring x64-windows-dbg done
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Package x64-windows-dbg
-- Package x64-windows-rel
-- Fixing pkgconfig file: F:/vcpkg/packages/glib_x64-windows/lib/pkgconfig/gio-2.0.pc
-- Fixing pkgconfig file: F:/vcpkg/packages/glib_x64-windows/lib/pkgconfig/gio-windows-2.0.pc
-- Fixing pkgconfig file: F:/vcpkg/packages/glib_x64-windows/lib/pkgconfig/glib-2.0.pc
-- Fixing pkgconfig file: F:/vcpkg/packages/glib_x64-windows/lib/pkgconfig/gmodule-2.0.pc
-- Fixing pkgconfig file: F:/vcpkg/packages/glib_x64-windows/lib/pkgconfig/gmodule-export-2.0.pc
-- Fixing pkgconfig file: F:/vcpkg/packages/glib_x64-windows/lib/pkgconfig/gmodule-no-export-2.0.pc
-- Fixing pkgconfig file: F:/vcpkg/packages/glib_x64-windows/lib/pkgconfig/gobject-2.0.pc
-- Fixing pkgconfig file: F:/vcpkg/packages/glib_x64-windows/lib/pkgconfig/gthread-2.0.pc
-- Fixing pkgconfig file: F:/vcpkg/packages/glib_x64-windows/debug/lib/pkgconfig/gio-2.0.pc
-- Fixing pkgconfig file: F:/vcpkg/packages/glib_x64-windows/debug/lib/pkgconfig/gio-windows-2.0.pc
-- Fixing pkgconfig file: F:/vcpkg/packages/glib_x64-windows/debug/lib/pkgconfig/glib-2.0.pc
-- Fixing pkgconfig file: F:/vcpkg/packages/glib_x64-windows/debug/lib/pkgconfig/gmodule-2.0.pc
-- Fixing pkgconfig file: F:/vcpkg/packages/glib_x64-windows/debug/lib/pkgconfig/gmodule-export-2.0.pc
-- Fixing pkgconfig file: F:/vcpkg/packages/glib_x64-windows/debug/lib/pkgconfig/gmodule-no-export-2.0.pc
-- Fixing pkgconfig file: F:/vcpkg/packages/glib_x64-windows/debug/lib/pkgconfig/gobject-2.0.pc
-- Fixing pkgconfig file: F:/vcpkg/packages/glib_x64-windows/debug/lib/pkgconfig/gthread-2.0.pc
-- Installing: F:/vcpkg/packages/glib_x64-windows/share/glib/copyright
-- Performing post-build validation
Elapsed time to handle glib:x64-windows: 7.2 min
```
