### ISSUE TITLE
[glib] Build error

### ISSUE THREAD

**Issue by Zhou-Tx** [microsoft/vcpkg#27429]
Package: glib[core]:x64-windows -> 2.74.0

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.33.31630.0
-    vcpkg-tool version: 2022-10-17-3247920fbdd47d08f36cbd480addd9890d3c2435
    vcpkg-scripts version: 934a99dc1 2022-10-21 (2 days ago)

**To Reproduce**

`vcpkg install gtk`

**Failure logs**

```
-- Using cached glib-2.74.0.tar.xz.
-- Cleaning sources at C:/mnt/lib/vcpkg/buildtrees/glib/src/glib-2-22354247da.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/mnt/lib/vcpkg/downloads/glib-2.74.0.tar.xz
-- Applying patch use-libiconv-on-windows.patch
-- Applying patch libintl.patch
-- Using source at C:/mnt/lib/vcpkg/buildtrees/glib/src/glib-2-22354247da.clean
-- Getting CMake variables for x64-windows
-- Configuring x64-windows-dbg
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at C:/mnt/lib/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Configuring x64-windows-dbg done
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Package x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: C:/mnt/lib/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe install -v
    Working Directory: C:/mnt/lib/vcpkg/buildtrees/glib/x64-windows-dbg
    Error code: 1
    See logs for more information:
      C:\mnt\lib\vcpkg\buildtrees\glib\package-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_meson.cmake:33 (vcpkg_execute_required_process)
  ports/glib/portfile.cmake:47 (vcpkg_install_meson)
  scripts/ports.cmake:147 (include)



```
<details><summary>C:\mnt\lib\vcpkg\buildtrees\glib\package-x64-windows-dbg-out.log</summary>

```
[1/566] "C:/mnt/lib/vcpkg/downloads/tools/python/python-3.10.5-x64/python.exe" "../src/glib-2-22354247da.clean/gio/data-to-c.py" "../src/glib-2-22354247da.clean/gio/../glib/gconstructor.h" "gconstructor_code" "gio/gconstructor_as_data.h"
[2/566] "C:/mnt/lib/vcpkg/installed/x64-windows/tools/gettext/bin\msgfmt.EXE" "../src/glib-2-22354247da.clean/po/kn.po" "-o" "po/kn/LC_MESSAGES/glib20.mo"
[3/566] "C:/mnt/lib/vcpkg/installed/x64-windows/tools/gettext/bin\msgfmt.EXE" "../src/glib-2-22354247da.clean/po/ja.po" "-o" "po/ja/LC_MESSAGES/glib20.mo"
[4/566] "C:/mnt/lib/vcpkg/installed/x64-windows/tools/gettext/bin\msgfmt.EXE" "../src/glib-2-22354247da.clean/po/hu.po" "-o" "po/hu/LC_MESSAGES/glib20.mo"
[5/566] "C:/mnt/lib/vcpkg/installed/x64-windows/tools/gettext/bin\msgfmt.EXE" "../src/glib-2-22354247da.clean/po/hi.po" "-o" "po/hi/LC_MESSAGES/glib20.mo"
[6/566] "C:/mnt/lib/vcpkg/installed/x64-windows/tools/gettext/bin\msgfmt.EXE" "../src/glib-2-22354247da.clean/po/id.po" "-o" "po/id/LC_MESSAGES/glib20.mo"
[7/566] "C:/mnt/lib/vcpkg/installed/x64-windows/tools/gettext/bin\msgfmt.EXE" "../src/glib-2-22354247da.clean/po/ka.po" "-o" "po/ka/LC_MESSAGES/glib20.mo"
[8/566] "C:/mnt/lib/vcpkg/installed/x64-windows/tools/gettext/bin\msgfmt.EXE" "../src/glib-2-22354247da.clean/po/kk.po" "-o" "po/kk/LC_MESSAGES/glib20.mo"
[9/566] "C:/mnt/lib/vcpkg/installed/x64-windows/tools/gettext/bin\msgfmt.EXE" "../src/glib-2-22354247da.clean/po/is.po" "-o" "po/is/LC_MESSAGES/glib20.mo"
[10/566] "C:/mnt/lib/vcpkg/installed/x64-windows/tools/gettext/bin\msgfmt.EXE" "../src/glib-2-22354247da.clean/po/he.po" "-o" "po/he/LC_MESSAGES/glib20.mo"
[11/566] "C:/mnt/lib/vcpkg/installed/x64-windows/tools/gettext/bin\msgfmt.EXE" "../src/glib-2-22354247da.clean/po/hy.po" "-o" "po/hy/LC_MESSAGES/glib20.mo"
[12/566] "C:/mnt/lib/vcpkg/installed/x64-windows/tools/gettext/bin\msgfmt.EXE" "../src/glib-2-22354247da.clean/po/it.po" "-o" "po/it/LC_MESSAGES/glib20.mo"
[13/566] "C:/mnt/lib/vcpkg/installed/x64-windows/tools/gettext/bin\msgfmt.EXE" "../src/glib-2-22354247da.clean/po/hr.po" "-o" "po/hr/LC_MESSAGES/glib20.mo"
[14/566] "C:/mnt/lib/vcpkg/installed/x64-windows/tools/gettext/bin\msgfmt.EXE" "../src/glib-2-22354247da.clean/po/af.po" "-o" "po/af/LC_MESSAGES/glib20.mo"
[15/566] "C:/mnt/lib/vcpkg/installed/x64-windows/tools/gettext/bin\msgfmt.EXE" "../src/glib-2-22354247da.clean/po/am.po" "-o" "po/am/LC_MESSAGES/glib20.mo"
[16/566] "C:/mnt/lib/vcpkg/installed/x64-windows/tools/gettext/bin\msgfmt.EXE" "../src/glib-2-22354247da.clean/po/an.po" "-o" "po/an/LC_MESSAGES/glib20.mo"
[17/566] "C:/mnt/lib/vcpkg/installed/x64-windows/tools/gettext/bin\msgfmt.EXE" "../src/glib-2-22354247da.clean/po/ab.po" "-o" "po/ab/LC_MESSAGES/glib20.mo"
[18/566] "C:/mnt/lib/vcpkg/installed/x64-windows/tools/gettext/bin\msgfmt.EXE" "../src/glib-2-22354247da.clean/po/ar.po" "-o" "po/ar/LC_MESSAGES/glib20.mo"
[19/566] "C:/mnt/lib/vcpkg/installed/x64-windows/tools/gettext/bin\msgfmt.EXE" "../src/glib-2-22354247da.clean/po/az.po" "-o" "po/az/LC_MESSAGES/glib20.mo"
...
Skipped 409 lines
...
2-22354247da.clean/gio/gtlsbackend.h" "../src/glib-2-22354247da.clean/gio/gtlscertificate.h" "../src/glib-2-22354247da.clean/gio/gtlsclientconnection.h" "../src/glib-2-22354247da.clean/gio/gtlsconnection.h" "../src/glib-2-22354247da.clean/gio/gtlsdatabase.h" "../src/glib-2-22354247da.clean/gio/gtlsfiledatabase.h" "../src/glib-2-22354247da.clean/gio/gtlsinteraction.h" "../src/glib-2-22354247da.clean/gio/gtlspassword.h" "../src/glib-2-22354247da.clean/gio/gtlsserverconnection.h" "../src/glib-2-22354247da.clean/gio/gdtlsconnection.h" "../src/glib-2-22354247da.clean/gio/gdtlsclientconnection.h" "../src/glib-2-22354247da.clean/gio/gdtlsserverconnection.h" "../src/glib-2-22354247da.clean/gio/gunixconnection.h" "../src/glib-2-22354247da.clean/gio/gunixcredentialsmessage.h" "../src/glib-2-22354247da.clean/gio/gunixfdlist.h" "../src/glib-2-22354247da.clean/gio/gunixsocketaddress.h" "../src/glib-2-22354247da.clean/gio/gvfs.h" "../src/glib-2-22354247da.clean/gio/gvolume.h" "../src/glib-2-22354247da.clean/gio/gvolumemonitor.h" "../src/glib-2-22354247da.clean/gio/gzlibcompressor.h" "../src/glib-2-22354247da.clean/gio/gzlibdecompressor.h" "../src/glib-2-22354247da.clean/gio/glistmodel.h" "../src/glib-2-22354247da.clean/gio/gliststore.h" "../src/glib-2-22354247da.clean/gio/gapplication.h" "../src/glib-2-22354247da.clean/gio/gapplicationcommandline.h" "../src/glib-2-22354247da.clean/gio/gactiongroup.h" "../src/glib-2-22354247da.clean/gio/gactionmap.h" "../src/glib-2-22354247da.clean/gio/gsimpleactiongroup.h" "../src/glib-2-22354247da.clean/gio/gremoteactiongroup.h" "../src/glib-2-22354247da.clean/gio/gactiongroupexporter.h" "../src/glib-2-22354247da.clean/gio/gdbusactiongroup.h" "../src/glib-2-22354247da.clean/gio/gaction.h" "../src/glib-2-22354247da.clean/gio/gpropertyaction.h" "../src/glib-2-22354247da.clean/gio/gsimpleaction.h" "../src/glib-2-22354247da.clean/gio/gmenumodel.h" "../src/glib-2-22354247da.clean/gio/gmenu.h" "../src/glib-2-22354247da.clean/gio/gmenuexporter.h" "../src/glib-2-22354247da.clean/gio/gdbusmenumodel.h" "../src/glib-2-22354247da.clean/gio/gnotification.h" "../src/glib-2-22354247da.clean/gio/gsettingsbackend.h" "../src/glib-2-22354247da.clean/gio/gsettingsschema.h" "../src/glib-2-22354247da.clean/gio/gsettings.h" "../src/glib-2-22354247da.clean/gio/gdbusauthobserver.h" "../src/glib-2-22354247da.clean/gio/gcredentials.h" "../src/glib-2-22354247da.clean/gio/gdbusutils.h" "../src/glib-2-22354247da.clean/gio/gdbuserror.h" "../src/glib-2-22354247da.clean/gio/gdbusaddress.h" "../src/glib-2-22354247da.clean/gio/gdbusconnection.h" "../src/glib-2-22354247da.clean/gio/gdbusmessage.h" "../src/glib-2-22354247da.clean/gio/gdbusnameowning.h" "../src/glib-2-22354247da.clean/gio/gdbusnamewatching.h" "../src/glib-2-22354247da.clean/gio/gdbusproxy.h" "../src/glib-2-22354247da.clean/gio/gdbusintrospection.h" "../src/glib-2-22354247da.clean/gio/gdbusmethodinvocation.h" "../src/glib-2-22354247da.clean/gio/gdbusserver.h" "../src/glib-2-22354247da.clean/gio/gdbusinterface.h" "../src/glib-2-22354247da.clean/gio/gdbusinterfaceskeleton.h" "../src/glib-2-22354247da.clean/gio/gdbusobject.h" "../src/glib-2-22354247da.clean/gio/gdbusobjectskeleton.h" "../src/glib-2-22354247da.clean/gio/gdbusobjectproxy.h" "../src/glib-2-22354247da.clean/gio/gdbusobjectmanager.h" "../src/glib-2-22354247da.clean/gio/gdbusobjectmanagerclient.h" "../src/glib-2-22354247da.clean/gio/gdbusobjectmanagerserver.h" "../src/glib-2-22354247da.clean/gio/gtestdbus.h" "gio/gnetworking.h"
--- stderr ---
Traceback (most recent call last):

  File "C:\mnt\lib\vcpkg\buildtrees\glib\x64-windows-dbg\gobject\glib-mkenums", line 486, in <module>

    write_output(prod)

  File "C:\mnt\lib\vcpkg\buildtrees\glib\x64-windows-dbg\gobject\glib-mkenums", line 97, in write_output

    print(output, file=output_stream)

UnicodeEncodeError: 'gbk' codec can't encode character '\xa9' in position 17: illegal multibyte sequence


[185/566] "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe" "-Igmodule\gmodule-2.0-0.dll.p" "-Igmodule" "-I..\src\glib-2-22354247da.clean\gmodule" "-I." "-I..\src\glib-2-22354247da.clean" "-Iglib" "-I..\src\glib-2-22354247da.clean\glib" "-IC:/mnt/lib/vcpkg/installed/x64-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W4" "/Od" "/Zi" "/FImsvc_recommended_pragmas.h" "/utf-8" "-D_GNU_SOURCE" "-DG_ENABLE_DEBUG" "/wo4057" "/wd4068" "/wo4090" "/wd4100" "/wd4116" "/wo4125" "/wd4127" "/wd4146" "/wd4152" "/wd4201" "/wd4232" "/wo4245" "/wo4267" "/wd4334" "/wo4389" "/wo4702" "/wd4706" "-nologo" "-DWIN32" "-D_WINDOWS" "-W3" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DG_LOG_DOMAIN=\"GModule\"" "/Fdgmodule\gmodule-2.0-0.dll.p\gmodule.c.pdb" /Fogmodule/gmodule-2.0-0.dll.p/gmodule.c.obj "/c" ../src/glib-2-22354247da.clean/gmodule/gmodule.c
cl: 命令行 warning D9025 :正在重写“/W4”(用“/W3”)
cl: 命令行 warning D9025 :正在重写“/Zi”(用“/Z7”)
C:\mnt\lib\vcpkg\buildtrees\glib\src\glib-2-22354247da.clean\gmodule\gmodule-win32.c(210): warning C4267: “=”: 从“size_t”转换到“gint”，可能丢失数据
[186/566] "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe" "-Igobject\gobject-2.0-0.dll.p" "-Igobject" "-I..\src\glib-2-22354247da.clean\gobject" "-I." "-I..\src\glib-2-22354247da.clean" "-Iglib" "-I..\src\glib-2-22354247da.clean\glib" "-IC:/mnt/lib/vcpkg/installed/x64-windows/debug/../include" "-IC:/mnt/lib/vcpkg/installed/x64-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W4" "/Od" "/Zi" "/FImsvc_recommended_pragmas.h" "/utf-8" "-D_GNU_SOURCE" "-DG_ENABLE_DEBUG" "/wo4057" "/wd4068" "/wo4090" "/wd4100" "/wd4116" "/wo4125" "/wd4127" "/wd4146" "/wd4152" "/wd4201" "/wd4232" "/wo4245" "/wo4267" "/wd4334" "/wo4389" "/wo4702" "/wd4706" "-nologo" "-DWIN32" "-D_WINDOWS" "-W3" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DG_LOG_DOMAIN=\"GLib-GObject\"" "-DGOBJECT_COMPILATION" "/Fdgobject\gobject-2.0-0.dll.p\gatomicarray.c.pdb" /Fogobject/gobject-2.0-0.dll.p/gatomicarray.c.obj "/c" ../src/glib-2-22354247da.clean/gobject/gatomicarray.c
cl: 命令行 warning D9025 :正在重写“/W4”(用“/W3”)
cl: 命令行 warning D9025 :正在重写“/Zi”(用“/Z7”)
[187/566] "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe" "-Igobject\gobject-2.0-0.dll.p" "-Igobject" "-I..\src\glib-2-22354247da.clean\gobject" "-I." "-I..\src\glib-2-22354247da.clean" "-Iglib" "-I..\src\glib-2-22354247da.clean\glib" "-IC:/mnt/lib/vcpkg/installed/x64-windows/debug/../include" "-IC:/mnt/lib/vcpkg/installed/x64-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W4" "/Od" "/Zi" "/FImsvc_recommended_pragmas.h" "/utf-8" "-D_GNU_SOURCE" "-DG_ENABLE_DEBUG" "/wo4057" "/wd4068" "/wo4090" "/wd4100" "/wd4116" "/wo4125" "/wd4127" "/wd4146" "/wd4152" "/wd4201" "/wd4232" "/wo4245" "/wo4267" "/wd4334" "/wo4389" "/wo4702" "/wd4706" "-nologo" "-DWIN32" "-D_WINDOWS" "-W3" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DG_LOG_DOMAIN=\"GLib-GObject\"" "-DGOBJECT_COMPILATION" "/Fdgobject\gobject-2.0-0.dll.p\gclosure.c.pdb" /Fogobject/gobject-2.0-0.dll.p/gclosure.c.obj "/c" ../src/glib-2-22354247da.clean/gobject/gclosure.c
cl: 命令行 warning D9025 :正在重写“/W4”(用“/W3”)
cl: 命令行 warning D9025 :正在重写“/Zi”(用“/Z7”)
[188/566] "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe" "-Igobject\gobject-2.0-0.dll.p" "-Igobject" "-I..\src\glib-2-22354247da.clean\gobject" "-I." "-I..\src\glib-2-22354247da.clean" "-Iglib" "-I..\src\glib-2-22354247da.clean\glib" "-IC:/mnt/lib/vcpkg/installed/x64-windows/debug/../include" "-IC:/mnt/lib/vcpkg/installed/x64-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W4" "/Od" "/Zi" "/FImsvc_recommended_pragmas.h" "/utf-8" "-D_GNU_SOURCE" "-DG_ENABLE_DEBUG" "/wo4057" "/wd4068" "/wo4090" "/wd4100" "/wd4116" "/wo4125" "/wd4127" "/wd4146" "/wd4152" "/wd4201" "/wd4232" "/wo4245" "/wo4267" "/wd4334" "/wo4389" "/wo4702" "/wd4706" "-nologo" "-DWIN32" "-D_WINDOWS" "-W3" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DG_LOG_DOMAIN=\"GLib-GObject\"" "-DGOBJECT_COMPILATION" "/Fdgobject\gobject-2.0-0.dll.p\gmarshal.c.pdb" /Fogobject/gobject-2.0-0.dll.p/gmarshal.c.obj "/c" ../src/glib-2-22354247da.clean/gobject/gmarshal.c
cl: 命令行 warning D9025 :正在重写“/W4”(用“/W3”)
cl: 命令行 warning D9025 :正在重写“/Zi”(用“/Z7”)
[189/566] "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe" "-Igobject\gobject-2.0-0.dll.p" "-Igobject" "-I..\src\glib-2-22354247da.clean\gobject" "-I." "-I..\src\glib-2-22354247da.clean" "-Iglib" "-I..\src\glib-2-22354247da.clean\glib" "-IC:/mnt/lib/vcpkg/installed/x64-windows/debug/../include" "-IC:/mnt/lib/vcpkg/installed/x64-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W4" "/Od" "/Zi" "/FImsvc_recommended_pragmas.h" "/utf-8" "-D_GNU_SOURCE" "-DG_ENABLE_DEBUG" "/wo4057" "/wd4068" "/wo4090" "/wd4100" "/wd4116" "/wo4125" "/wd4127" "/wd4146" "/wd4152" "/wd4201" "/wd4232" "/wo4245" "/wo4267" "/wd4334" "/wo4389" "/wo4702" "/wd4706" "-nologo" "-DWIN32" "-D_WINDOWS" "-W3" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DG_LOG_DOMAIN=\"GLib-GObject\"" "-DGOBJECT_COMPILATION" "/Fdgobject\gobject-2.0-0.dll.p\genums.c.pdb" /Fogobject/gobject-2.0-0.dll.p/genums.c.obj "/c" ../src/glib-2-22354247da.clean/gobject/genums.c
cl: 命令行 warning D9025 :正在重写“/W4”(用“/W3”)
cl: 命令行 warning D9025 :正在重写“/Zi”(用“/Z7”)
[190/566] "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe" "-Igobject\gobject-2.0-0.dll.p" "-Igobject" "-I..\src\glib-2-22354247da.clean\gobject" "-I." "-I..\src\glib-2-22354247da.clean" "-Iglib" "-I..\src\glib-2-22354247da.clean\glib" "-IC:/mnt/lib/vcpkg/installed/x64-windows/debug/../include" "-IC:/mnt/lib/vcpkg/installed/x64-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W4" "/Od" "/Zi" "/FImsvc_recommended_pragmas.h" "/utf-8" "-D_GNU_SOURCE" "-DG_ENABLE_DEBUG" "/wo4057" "/wd4068" "/wo4090" "/wd4100" "/wd4116" "/wo4125" "/wd4127" "/wd4146" "/wd4152" "/wd4201" "/wd4232" "/wo4245" "/wo4267" "/wd4334" "/wo4389" "/wo4702" "/wd4706" "-nologo" "-DWIN32" "-D_WINDOWS" "-W3" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DG_LOG_DOMAIN=\"GLib-GObject\"" "-DGOBJECT_COMPILATION" "/Fdgobject\gobject-2.0-0.dll.p\gbinding.c.pdb" /Fogobject/gobject-2.0-0.dll.p/gbinding.c.obj "/c" ../src/glib-2-22354247da.clean/gobject/gbinding.c
cl: 命令行 warning D9025 :正在重写“/W4”(用“/W3”)
cl: 命令行 warning D9025 :正在重写“/Zi”(用“/Z7”)
[191/566] "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe" "-Igobject\gobject-2.0-0.dll.p" "-Igobject" "-I..\src\glib-2-22354247da.clean\gobject" "-I." "-I..\src\glib-2-22354247da.clean" "-Iglib" "-I..\src\glib-2-22354247da.clean\glib" "-IC:/mnt/lib/vcpkg/installed/x64-windows/debug/../include" "-IC:/mnt/lib/vcpkg/installed/x64-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W4" "/Od" "/Zi" "/FImsvc_recommended_pragmas.h" "/utf-8" "-D_GNU_SOURCE" "-DG_ENABLE_DEBUG" "/wo4057" "/wd4068" "/wo4090" "/wd4100" "/wd4116" "/wo4125" "/wd4127" "/wd4146" "/wd4152" "/wd4201" "/wd4232" "/wo4245" "/wo4267" "/wd4334" "/wo4389" "/wo4702" "/wd4706" "-nologo" "-DWIN32" "-D_WINDOWS" "-W3" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DG_LOG_DOMAIN=\"GLib-GObject\"" "-DGOBJECT_COMPILATION" "/Fdgobject\gobject-2.0-0.dll.p\gobject.c.pdb" /Fogobject/gobject-2.0-0.dll.p/gobject.c.obj "/c" ../src/glib-2-22354247da.clean/gobject/gobject.c
cl: 命令行 warning D9025 :正在重写“/W4”(用“/W3”)
cl: 命令行 warning D9025 :正在重写“/Zi”(用“/Z7”)
../src/glib-2-22354247da.clean/gobject/gobject.c(4935): warning C4312: “类型强制转换”: 从“unsigned int”转换到更大的“void *”
[192/566] "C:\mnt\lib\vcpkg\downloads\tools\python\python-3.10.5-x64\python.exe" "C:\mnt\lib\vcpkg\installed\x64-windows\tools\meson\meson.py" "--internal" "exe" "--capture" "gobject\glib-enumtypes.c" "--" "C:/mnt/lib/vcpkg/downloads/tools/python/python-3.10.5-x64/python.exe" "gobject/glib-mkenums" "--template" "../src/glib-2-22354247da.clean/gobject/glib-enumtypes.c.template" "../src/glib-2-22354247da.clean/gobject/../glib/gunicode.h"
[193/566] "C:\mnt\lib\vcpkg\downloads\tools\python\python-3.10.5-x64\python.exe" "C:\mnt\lib\vcpkg\installed\x64-windows\tools\meson\meson.py" "--internal" "symbolextractor" "C:\mnt\lib\vcpkg\buildtrees\glib\x64-windows-dbg" glib/glib-2.0-0.dll "glib\glib-2.0.lib" glib/glib-2.0-0.dll.p/glib-2.0-0.dll.symbols 
ninja: build stopped: subcommand failed.
```
</details>

**Additional context**
vcpkg-tool version: 2022-10-17-3247920fbdd47d08f36cbd480addd9890d3c2435
vcpkg-scripts version: 934a99dc1 2022-10-21

**Comment by Zhou-Tx** [comment]
我已收到你发的邮件，谢谢
