### ISSUE TITLE
[crashpad] Build error

### ISSUE THREAD

**Issue by bleriaf** [microsoft/vcpkg#28341]
Package: crashpad[core]:x86-windows -> 2022-09-05#1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.35.32019.0
-    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: e82778a71 2022-12-13 (8 hours ago)

**To Reproduce**

`vcpkg install crashpad`

**Failure logs**

```
-- Note: crashpad only supports static library linkage. Building static library.
-- Using cached D:/vcpkg/downloads/crashpad-261679b3d2f3336d8531ed38e110254c3e2d1c10.tar.gz
-- Cleaning sources at D:/vcpkg/buildtrees/crashpad/src/4c3e2d1c10-076c03c4e9.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/crashpad-261679b3d2f3336d8531ed38e110254c3e2d1c10.tar.gz
-- Using source at D:/vcpkg/buildtrees/crashpad/src/4c3e2d1c10-076c03c4e9.clean
-- Downloading https://www.python.org/ftp/python/3.10.7/python-3.10.7-embed-win32.zip -> python-3.10.7-embed-win32.zip...
-- Using cached D:/vcpkg/downloads/crashpad-5654edb4225bcad13901155c819febb5748e502b.tar.gz
-- Extracting source D:/vcpkg/downloads/crashpad-5654edb4225bcad13901155c819febb5748e502b.tar.gz
-- Using source at D:/vcpkg/buildtrees/crashpad/src/b5748e502b-300fec4c6b.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x86-windows
-- Generating build (x86-windows-dbg)...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: D:/vcpkg/installed/x64-windows/tools/gn/gn.exe gen D:/vcpkg/buildtrees/crashpad/x86-windows-dbg "--args= is_debug=true         extra_cflags_c=\"  -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -MP  -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1  \"         extra_cflags_cc=\"  -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -GR -EHsc -MP  -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1  \"         extra_ldflags=\" -machine:X86 -nologo    -debug -INCREMENTAL \"         extra_arflags=\"-machine:X86 -nologo\"         extra_cflags=\"/GL-\"         extra_ldflags=\"/LTCG:OFF\"         extra_arflags=\"/LTCG:OFF\""
    Working Directory: D:/vcpkg/buildtrees/crashpad/src/4c3e2d1c10-076c03c4e9.clean
    Error code: 1
    See logs for more information:
      D:\vcpkg\buildtrees\crashpad\generate-x86-windows-dbg-out.log
      D:\vcpkg\buildtrees\crashpad\generate-x86-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_gn.cmake:9 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_configure_gn.cmake:36 (z_vcpkg_configure_gn_generate)
  ports/crashpad/portfile.cmake:93 (vcpkg_configure_gn)
  scripts/ports.cmake:147 (include)



```
<details><summary>D:\vcpkg\buildtrees\crashpad\generate-x86-windows-dbg-out.log</summary>

```
ERROR at //third_party/mini_chromium/mini_chromium/build/config/BUILD.gn:611:20: Script returned non-zero exit code.
  toolchain_data = exec_script(helper_path,
                   ^----------
Current dir: D:/vcpkg/buildtrees/crashpad/x86-windows-dbg/
Command: D:/vcpkg/downloads/tools/python/python-3.10.7-x86/python.exe D:/vcpkg/buildtrees/crashpad/src/4c3e2d1c10-076c03c4e9.clean/third_party/mini_chromium/mini_chromium/build/win_helper.py get-visual-studio-data D:/vcpkg/buildtrees/crashpad/x86-windows-dbg D:/vcpkg/buildtrees/crashpad/src/4c3e2d1c10-076c03c4e9.clean/third_party/mini_chromium/mini_chromium/build/config/<autodetect>
Returned 1.
See //build/BUILDCONFIG.gn:65:3: which caused the file to be included.
  "$_mini_chromium_dir/build/config:Wimplicit_fallthrough",
  ^-------------------------------------------------------
```
</details>
<details><summary>D:\vcpkg\buildtrees\crashpad\generate-x86-windows-dbg-err.log</summary>

```
Traceback (most recent call last):
  File "D:\vcpkg\buildtrees\crashpad\src\4c3e2d1c10-076c03c4e9.clean\third_party\mini_chromium\mini_chromium\build\win_helper.py", line 230, in <module>
    sys.exit(WinTool().Dispatch(sys.argv[1:]))
  File "D:\vcpkg\buildtrees\crashpad\src\4c3e2d1c10-076c03c4e9.clean\third_party\mini_chromium\mini_chromium\build\win_helper.py", line 124, in Dispatch
    return getattr(self, method)(*args[1:])
  File "D:\vcpkg\buildtrees\crashpad\src\4c3e2d1c10-076c03c4e9.clean\third_party\mini_chromium\mini_chromium\build\win_helper.py", line 210, in ExecGetVisualStudioData
    install_dir, script_path = (explicit() or env() or autodetect() or fail())
  File "D:\vcpkg\buildtrees\crashpad\src\4c3e2d1c10-076c03c4e9.clean\third_party\mini_chromium\mini_chromium\build\win_helper.py", line 205, in fail
    def fail(): raise Exception('Visual Studio installation dir not found')
Exception: Visual Studio installation dir not found
```
</details>

**Additional context**

**Comment by MonicaLiu0311** [comment]
Please try the installation after running the following command:
`D:\vcpkg> ./vcpkg integrate install`

If it still fails, please attach a complete log file.

**Comment by bleriaf** [comment]
which log file? ill send the output from console if that helps

```D:\vcpkg>vcpkg integrate install
Applied user-wide integration for this vcpkg root.
CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=D:/vcpkg/scripts/buildsystems/vcpkg.cmake"

All MSBuild C++ projects can now #include any installed libraries. Linking will be handled automatically. Installing new libraries will make them instantly available.

D:\vcpkg>vcpkg install crashpad:x64-windows
Computing installation plan...
The following packages will be built and installed:
    crashpad[core]:x64-windows -> 2022-09-05#1
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\User\AppData\Local\vcpkg\archives in 128 us. Use --debug to see more details.
Installing 1/1 crashpad:x64-windows...
Building crashpad[core]:x64-windows...
-- Note: crashpad only supports static library linkage. Building static library.
-- Using cached D:/vcpkg/downloads/crashpad-261679b3d2f3336d8531ed38e110254c3e2d1c10.tar.gz
-- Cleaning sources at D:/vcpkg/buildtrees/crashpad/src/4c3e2d1c10-076c03c4e9.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/crashpad-261679b3d2f3336d8531ed38e110254c3e2d1c10.tar.gz
-- Using source at D:/vcpkg/buildtrees/crashpad/src/4c3e2d1c10-076c03c4e9.clean
-- Using cached D:/vcpkg/downloads/crashpad-5654edb4225bcad13901155c819febb5748e502b.tar.gz
-- Extracting source D:/vcpkg/downloads/crashpad-5654edb4225bcad13901155c819febb5748e502b.tar.gz
-- Using source at D:/vcpkg/buildtrees/crashpad/src/b5748e502b-300fec4c6b.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Generating build (x64-windows-dbg)...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: D:/vcpkg/installed/x64-windows/tools/gn/gn.exe gen D:/vcpkg/buildtrees/crashpad/x64-windows-dbg "--args= is_debug=true         extra_cflags_c=\"  -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -MP  -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1  \"         extra_cflags_cc=\"  -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -GR -EHsc -MP  -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1  \"         extra_ldflags=\" -machine:x64 -nologo    -debug -INCREMENTAL \"         extra_arflags=\"-machine:x64 -nologo\"         extra_cflags=\"/GL-\"         extra_ldflags=\"/LTCG:OFF\"         extra_arflags=\"/LTCG:OFF\""
    Working Directory: D:/vcpkg/buildtrees/crashpad/src/4c3e2d1c10-076c03c4e9.clean
    Error code: 1
    See logs for more information:
      D:\vcpkg\buildtrees\crashpad\generate-x64-windows-dbg-out.log
      D:\vcpkg\buildtrees\crashpad\generate-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_gn.cmake:9 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_configure_gn.cmake:36 (z_vcpkg_configure_gn_generate)
  ports/crashpad/portfile.cmake:93 (vcpkg_configure_gn)
  scripts/ports.cmake:147 (include)


error: building crashpad:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+crashpad
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[crashpad]+Build+error
Include '[crashpad] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: 9074f8334 2022-12-14 (12 hours ago)


Please use the prefilled template from D:\vcpkg\installed\vcpkg\issue_body.md when reporting your issue.```

**Comment by bleriaf** [comment]
says something about visual studio not found however i have been using vcpkg for a while and have never had issues installing any libraries. and my visual studio is definitely installed on the english language (2022 community)

generate-x64-windows-dbg-err.log:
```Traceback (most recent call last):
  File "D:\vcpkg\buildtrees\crashpad\src\4c3e2d1c10-076c03c4e9.clean\third_party\mini_chromium\mini_chromium\build\win_helper.py", line 230, in <module>
    sys.exit(WinTool().Dispatch(sys.argv[1:]))
  File "D:\vcpkg\buildtrees\crashpad\src\4c3e2d1c10-076c03c4e9.clean\third_party\mini_chromium\mini_chromium\build\win_helper.py", line 124, in Dispatch
    return getattr(self, method)(*args[1:])
  File "D:\vcpkg\buildtrees\crashpad\src\4c3e2d1c10-076c03c4e9.clean\third_party\mini_chromium\mini_chromium\build\win_helper.py", line 210, in ExecGetVisualStudioData
    install_dir, script_path = (explicit() or env() or autodetect() or fail())
  File "D:\vcpkg\buildtrees\crashpad\src\4c3e2d1c10-076c03c4e9.clean\third_party\mini_chromium\mini_chromium\build\win_helper.py", line 205, in fail
    def fail(): raise Exception('Visual Studio installation dir not found')
Exception: Visual Studio installation dir not found
```

**Comment by MonicaLiu0311** [comment]
Win 10
VS 2022
```
PS E:\vcpkg02> ./vcpkg version
vcpkg package management program version 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9

See LICENSE.txt for license information.
```
```
PS E:\vcpkg02> ./vcpkg install crashpad:x64-windows
Computing installation plan...
The following packages are already installed:
    crashpad[core]:x64-windows -> 2022-09-05#2
crashpad:x64-windows is already installed
Restored 0 package(s) from C:\Users\v-liumonica\AppData\Local\vcpkg\archives in 124.1 us. Use --debug to see more details.
Total install time: 903.8 us
crashpad provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(crashpad CONFIG REQUIRED)
    target_link_libraries(main PRIVATE crashpad crashpad::crashpad)
```

I really can't reproduce your problem, but https://github.com/microsoft/vcpkg/issues/29057 and https://github.com/microsoft/vcpkg/pull/29058 made some fixes to vcpkg_configure_gn, would you like to try again?

**Comment by MonicaLiu0311** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
