### ISSUE TITLE
Powershell 7.3.1 fails to run.

### ISSUE THREAD

**Issue by sigmareaver** [microsoft/vcpkg#28660]
**Describe the bug**
```
A suitable version of powershell-core was not found (required v7.3.1) Downloading portable powershell-core 7.3.1...
Extracting powershell-core...
error: Failed to run "D:\vcpkg\downloads\tools\powershell-core-7.3.1-windows\pwsh.exe" to determine the powershell-core
version.
error: D:\vcpkg\downloads\tools\powershell-core-7.3.1-windows\pwsh.exe failed with exit code: (-2146232797).
Process terminated. An attempt was made to load a program with an incorrect format. (0x8007000B)
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)
   at Microsoft.PowerShell.ConsoleControl.NativeMethods.GetConsoleScreenBufferInfo(IntPtr consoleHandle, CONSOLE_SCREEN_
BUFFER_INFO& consoleScreenBufferInfo)
   at Microsoft.PowerShell.ConsoleControl.GetConsoleScreenBufferInfo(SafeFileHandle consoleHandle)
   at Microsoft.PowerShell.ConsoleHostRawUserInterface..ctor(ConsoleHostUserInterface mshConsole)
   at Microsoft.PowerShell.ConsoleHostUserInterface..ctor(ConsoleHost parent)
   at Microsoft.PowerShell.ConsoleHost..ctor()
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText, Boolean issProvidedExternally)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc)
```

**Environment**
- OS: Windows 7 Pro SP1
- Compiler: Visual Studio 2019 v142

**To Reproduce**
1. ./vcpkg install xxxx
2. See error
Repro code when

**Expected behavior**
The readme still lists Windows 7 as the minimum spec required to use vcpkg. However, I don't believe Powershell 7.3 is compiled for Windows 7 compatibility.

Can anyone tell me what is the last version of vcpkg to use an older version of Powershell, or if there's a way I can tell vcpkg to use an older version, e.g. Powershell 7.2?

**Comment by sigmareaver** [comment]
I believe I've found the commit that made the change: 9bf374fb6d99f8973ec8781d3b41ffac2defee63
I will see if I can revert this change on my end.

I will leave this issue open as a reminder to the devs to update the minimum specs required to use vcpkg, since Windows 7 will no longer run the latest version of vcpkg.

**Comment by Brainy0207** [comment]
This change just crippled one of our build systems (that is still running Windows 7). Will (locally) downgrading the pwsh requirement to 7.2.8 fix this, or does something actually depend on 7.3.1?

**Comment by sigmareaver** [comment]
> This change just crippled one of our build systems (that is still running Windows 7). Will (locally) downgrading the pwsh requirement to 7.2.8 fix this, or does something actually depend on 7.3.1?

Yes, downgrading pwsh works. At least, for me it did. All I did was change all mentions of `7.3.1` to `7.2.8` in the file `scripts/vcpkgTools.xml`. Refer to the aforementioned commit for exact line numbers.

**Comment by Cheney-W** [comment]
Fixed by https://github.com/microsoft/vcpkg/pull/29054.
