### ISSUE TITLE
[tomlplusplus] Build error

### ISSUE THREAD

**Issue by wu1274704958** [microsoft/vcpkg#29056]
**Host Environment**

- OS: Windows
- Compiler: ndk-21.4.7075529

**To Reproduce**

$env:VCPKG_ROOT="D:\xxx\vcpkg"
$env:ANDROID_NDK_HOME="D:\xxx\AndroidSdk\ndk\25.1.8937393"
vcpkg install tomlplusplus:arm-android

**Failure logs**

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: D:/code/vcpkg/downloads/tools/python/python-3.10.7-x64/python.exe D:/code/vcpkg/installed/x64-windows/tools/meson/meson.py -Dgenerate_cmake_config=true -Dbuild_tests=false -Dbuild_examples=false --buildtype plain --backend ninja --wrap-mode nodownload --native D:/code/vcpkg/scripts/buildsystems/meson/none.txt --libdir lib --cross D:/code/vcpkg/buildtrees/tomlplusplus/meson-arm-android-dbg.log -Ddebug=true --prefix D:/code/vcpkg/packages/tomlplusplus_arm-android/debug --includedir ../include -Dcmake_prefix_path=['D:/code/vcpkg/installed/arm-android/debug','D:/code/vcpkg/installed/arm-android'] D:/code/vcpkg/buildtrees/tomlplusplus/src/v3.1.0-faec73997b.clean
    Working Directory: D:/code/vcpkg/buildtrees/tomlplusplus/arm-android-dbg
    Error code: 2
    See logs for more information:
      D:\code\vcpkg\buildtrees\tomlplusplus\config-arm-android-dbg-meson-log.txt.log
      D:\code\vcpkg\buildtrees\tomlplusplus\config-arm-android-dbg-out.log
      D:\code\vcpkg\buildtrees\tomlplusplus\config-arm-android-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:432 (vcpkg_execute_required_process)
  ports/tomlplusplus/portfile.cmake:9 (vcpkg_configure_meson)
  scripts/ports.cmake:147 (include)

**Additional context**

Under is content of ‘ D:\code\vcpkg\buildtrees\tomlplusplus\config-arm-android-dbg-err.log’
Traceback (most recent call last):
  File "D:\code\vcpkg\installed\x64-windows\tools\meson\mesonbuild\mesonmain.py", line 153, in run
    return options.run_func(options)
  File "D:\code\vcpkg\installed\x64-windows\tools\meson\mesonbuild\msetup.py", line 301, in run
    app.generate()
  File "D:\code\vcpkg\installed\x64-windows\tools\meson\mesonbuild\msetup.py", line 185, in generate
    self._generate(env)
  File "D:\code\vcpkg\installed\x64-windows\tools\meson\mesonbuild\msetup.py", line 207, in _generate
    intr = interpreter.Interpreter(b, user_defined_options=user_defined_options)
  File "D:\code\vcpkg\installed\x64-windows\tools\meson\mesonbuild\interpreter\interpreter.py", line 317, in __init__
    self.parse_project()
  File "D:\code\vcpkg\installed\x64-windows\tools\meson\mesonbuild\interpreterbase\interpreterbase.py", line 119, in parse_project
    self.evaluate_codeblock(self.ast, end=1)
  File "D:\code\vcpkg\installed\x64-windows\tools\meson\mesonbuild\interpreterbase\interpreterbase.py", line 174, in evaluate_codeblock
    raise e
  File "D:\code\vcpkg\installed\x64-windows\tools\meson\mesonbuild\interpreterbase\interpreterbase.py", line 167, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "D:\code\vcpkg\installed\x64-windows\tools\meson\mesonbuild\interpreterbase\interpreterbase.py", line 180, in evaluate_statement
    return self.function_call(cur)
  File "D:\code\vcpkg\installed\x64-windows\tools\meson\mesonbuild\interpreterbase\interpreterbase.py", line 455, in function_call
    res = func(node, func_args, kwargs)
  File "D:\code\vcpkg\installed\x64-windows\tools\meson\mesonbuild\interpreterbase\decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "D:\code\vcpkg\installed\x64-windows\tools\meson\mesonbuild\interpreterbase\decorators.py", line 574, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "D:\code\vcpkg\installed\x64-windows\tools\meson\mesonbuild\interpreter\interpreter.py", line 1198, in func_project
    if mesonlib.setup_vsenv(force_vsenv):
  File "D:\code\vcpkg\installed\x64-windows\tools\meson\mesonbuild\mesonlib\vsenv.py", line 105, in setup_vsenv
    return _setup_vsenv(force)
  File "D:\code\vcpkg\installed\x64-windows\tools\meson\mesonbuild\mesonlib\vsenv.py", line 99, in _setup_vsenv
    k, v = bat_line.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)

-------------------------------------------------------------------------
Under is content of ‘D:\code\vcpkg\buildtrees\tomlplusplus\config-arm-android-dbg-meson-log.txt.log‘
Build started at 2023-01-19T10:19:59.217954
Main binary: D:\code\vcpkg\downloads\tools\python\python-3.10.7-x64\python.exe
Build Options: -Dgenerate_cmake_config=true -Dbuild_tests=false -Dbuild_examples=false -Ddebug=true '-Dcmake_prefix_path=['"'"'D:/code/vcpkg/installed/arm-android/debug'"'"','"'"'D:/code/vcpkg/installed/arm-android'"'"']' -Dprefix=D:/code/vcpkg/packages/tomlplusplus_arm-android/debug -Dincludedir=../include -Dlibdir=lib -Dbackend=ninja -Dbuildtype=plain -Dwrap_mode=nodownload '--cross-file D:/code/vcpkg/buildtrees/tomlplusplus/meson-arm-android-dbg.log' '--native-file D:/code/vcpkg/scripts/buildsystems/meson/none.txt'
Python system: Windows
The Meson build system
Version: 0.62.1
Source dir: D:\code\vcpkg\buildtrees\tomlplusplus\src\v3.1.0-faec73997b.clean
Build dir: D:\code\vcpkg\buildtrees\tomlplusplus\arm-android-dbg
Build type: cross build
Project name: tomlplusplus
Project version: 3.1.0
Activating VS 16.11.23

..\src\v3.1.0-faec73997b.clean\meson.build:1:0: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
--------------------------------------------------------------------------------
Under is content of ’D:\code\vcpkg\buildtrees\tomlplusplus\config-arm-android-dbg-out.log‘
WARNING: Recommend using either -Dbuildtype or -Doptimization + -Ddebug. Using both is redundant since they override each other. See: https://mesonbuild.com/Builtin-options.html#build-type-options
The Meson build system
Version: 0.62.1
Source dir: D:\code\vcpkg\buildtrees\tomlplusplus\src\v3.1.0-faec73997b.clean
Build dir: D:\code\vcpkg\buildtrees\tomlplusplus\arm-android-dbg
Build type: cross build
Project name: tomlplusplus
Project version: 3.1.0
Activating VS 16.11.23

..\src\v3.1.0-faec73997b.clean\meson.build:1:0: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!

**Comment by eli-schwartz** [comment]
```
 File "D:\code\vcpkg\installed\x64-windows\tools\meson\mesonbuild\mesonlib\vsenv.py", line 99, in _setup_vsenv
k, v = bat_line.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

```
..\src\v3.1.0-faec73997b.clean\meson.build:1:0: ERROR: Unhandled python exception

This is a Meson bug and should be reported!
```

Interesting! This is Meson bug https://github.com/mesonbuild/meson/pull/10635 and it is fixed in 0.63.1, but you are using 0.62.1

Currently, vcpkg provides Meson 0.63.0 which is not good enough, but is also newer than what you're running right now...

**Comment by Neumann-A** [comment]
@eli-schwartz update to 1.0 in #28084

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
