### ISSUE TITLE
[pkgconf] build failure

### ISSUE THREAD

**Issue by soroshsabz** [microsoft/vcpkg#29835]
**Host Environment**

- OS: Linux (Ubuntu 18.04.6)
- Compiler: g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**To Reproduce**

`./vcpkg install pkgconf`

**Failure logs**

```
ssoroosh@bionic:~/vcpkg$ ./vcpkg install pkgconf
Computing installation plan...
The following packages will be built and installed:
    pkgconf[core]:x64-linux -> 1.8.0#5
Detecting compiler hash for triplet x64-linux...
Restored 0 package(s) from /home/ssoroosh/.cache/vcpkg/archives in 3.7 us. Use --debug to see more details.
Installing 1/1 pkgconf:x64-linux...
Building pkgconf[core]:x64-linux...
-- Using cached pkgconf-pkgconf-cef30268e1a3f79efd607c26abcf556aa314c9c4.tar.gz.
-- Cleaning sources at /home/ssoroosh/vcpkg/buildtrees/pkgconf/src/6aa314c9c4-8bd74a463d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/ssoroosh/vcpkg/downloads/pkgconf-pkgconf-cef30268e1a3f79efd607c26abcf556aa314c9c4.tar.gz
-- Using source at /home/ssoroosh/vcpkg/buildtrees/pkgconf/src/6aa314c9c4-8bd74a463d.clean
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/python3 /home/ssoroosh/vcpkg/installed/x64-linux/tools/meson/meson.py -Dtests=false --buildtype plain --backend ninja --wrap-mode nodownload --libdir lib --native /home/ssoroosh/vcpkg/buildtrees/pkgconf/meson-x64-linux-dbg.log -Ddebug=true --prefix /home/ssoroosh/vcpkg/packages/pkgconf_x64-linux/debug --includedir ../include -Dcmake_prefix_path=['/home/ssoroosh/vcpkg/installed/x64-linux/debug','/home/ssoroosh/vcpkg/installed/x64-linux'] /home/ssoroosh/vcpkg/buildtrees/pkgconf/src/6aa314c9c4-8bd74a463d.clean
    Working Directory: /home/ssoroosh/vcpkg/buildtrees/pkgconf/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /home/ssoroosh/vcpkg/buildtrees/pkgconf/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:433 (vcpkg_execute_required_process)
  ports/pkgconf/portfile.cmake:9 (vcpkg_configure_meson)
  scripts/ports.cmake:147 (include)


error: building pkgconf:x64-linux failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+pkgconf
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[pkgconf]+Build+error
Include '[pkgconf] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 54cc53c43 2023-02-23 (8 hours ago)
```

 /home/ssoroosh/vcpkg/buildtrees/pkgconf/config-x64-linux-dbg-err.log
```
Traceback (most recent call last):
  File "/home/ssoroosh/vcpkg/installed/x64-linux/tools/meson/meson.py", line 26, in <module>
    from mesonbuild import mesonmain
  File "/home/ssoroosh/vcpkg/installed/x64-linux/tools/meson/mesonbuild/mesonmain.py", line 28, in <module>
    from . import mesonlib
  File "/home/ssoroosh/vcpkg/installed/x64-linux/tools/meson/mesonbuild/mesonlib/__init__.py", line 21, in <module>
    from .universal import *
  File "/home/ssoroosh/vcpkg/installed/x64-linux/tools/meson/mesonbuild/mesonlib/universal.py", line 17
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by soroshsabz** [comment]
related to https://github.com/tmakkonen/sipcmd/issues/83

**Comment by dg0yt** [comment]
You need a more recent python3 for any port which builds with meson.
The python3 from port python is good enough.

**Comment by dg0yt** [comment]
> You need a more recent python3 for any port which builds with meson.

This should really be checked as part of the meson build scripts in vcpkg.

**Comment by soroshsabz** [comment]
I have default bionic python, and I think vcpkg must be work with official live ubuntu LTS

```
ssoroosh@bionic:~/vcpkg$ python3 --version
Python 3.6.9
```

**Comment by dg0yt** [comment]
Ubuntu 18.04 is five years old, so there were at least two more recent LTS release.... (Written on an 18.04 installation.)

**Comment by soroshsabz** [comment]
@dg0yt But it is still live and official supported.

https://endoflife.software/operating-systems/linux/ubuntu
https://ubuntu.com/about/release-cycle

**Comment by dg0yt** [comment]
i.e. Ubuntu gives certain promises. Obviously, these don't include offering new versions of python. Ubuntu 18.04 also lacks modern compilers.

**Comment by soroshsabz** [comment]
@dg0yt Ok, I say vcpkg must use python version that support on bionic. (or download itself like cmake)

**Comment by soroshsabz** [comment]
@Cheney-W Why add `question` tag? I think it is bug
