### ISSUE TITLE
[v8] Build error

### ISSUE THREAD

**Issue by RayIon** [microsoft/vcpkg#30240]
Package: v8[core]:x64-windows-static -> 9.1.269.39#5

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.35.32215.0
-    vcpkg-tool version: 2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454
    vcpkg-scripts version: 07da05c20 2023-03-15 (21 hours ago)

**To Reproduce**

`vcpkg install v8:x64-windows-static`

**Failure logs**

```
-- Found external ninja('1.11.0').
-- Using cached msys-gzip-1.11-1-x86_64.pkg.tar.zst.
-- Using cached msys-bash-5.1.008-1-x86_64.pkg.tar.zst.
-- Using cached msys-diffutils-3.8-2-x86_64.pkg.tar.zst.
-- Using cached msys-coreutils-8.32-2-x86_64.pkg.tar.zst.
-- Using cached msys-grep-3.0-2-x86_64.pkg.tar.xz.
-- Using cached msys-sed-4.8-2-x86_64.pkg.tar.zst.
-- Using cached msys-libpcre-8.45-1-x86_64.pkg.tar.zst.
-- Using cached msys-gawk-5.1.0-2-x86_64.pkg.tar.zst.
-- Using cached msys-mpfr-4.1.0-1-x86_64.pkg.tar.zst.
-- Using cached msys-gmp-6.2.1-1-x86_64.pkg.tar.zst.
-- Using cached msys-libreadline-8.1.001-1-x86_64.pkg.tar.zst.
-- Using cached msys-ncurses-6.2-2-x86_64.pkg.tar.zst.
-- Using cached msys-pkg-config-0.29.2-4-x86_64.pkg.tar.zst.
-- Using cached msys-make-4.3-3-x86_64.pkg.tar.zst.
-- Using cached msys-libintl-0.21-1-x86_64.pkg.tar.zst.
-- Using cached msys-libiconv-1.16-2-x86_64.pkg.tar.zst.
-- Using cached msys-gcc-libs-11.2.0-3-x86_64.pkg.tar.zst.
-- Using cached msys-msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst.
-- Using msys root at D:/Projects/Git/vcpkg/downloads/tools/msys2/79d5b6b790550399
-- Using cached D:/Projects/Git/vcpkg/downloads/v8-7d3d62c91f69a702e5aa54c6b4dbbaa883683717.tar.gz
-- Cleaning sources at D:/Projects/Git/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Projects/Git/vcpkg/downloads/v8-7d3d62c91f69a702e5aa54c6b4dbbaa883683717.tar.gz
-- Applying patch D:/Projects/Git/vcpkg/ports/v8/v8.patch
-- Using source at D:/Projects/Git/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean
-- Fetching submodules
-- Generating v8 build files. Please wait...
-- Generating build (x64-windows-static-dbg)...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: D:/Projects/Git/vcpkg/installed/x64-windows/tools/gn/gn.exe gen D:/Projects/Git/vcpkg/buildtrees/v8/x64-windows-static-dbg "--args=is_component_build=false target_cpu=\"x64\" v8_monolithic=true v8_use_external_startup_data=false use_sysroot=false is_clang=false use_custom_libcxx=false v8_enable_verify_heap=false icu_use_data_file=false is_debug=true enable_iterator_debugging=true pkg_config_libdir=\"/d/Projects/Git/vcpkg/installed/x64-windows-static/debug/lib/pkgconfig\""
    Working Directory: D:/Projects/Git/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean
    Error code: 1
    See logs for more information:
      D:\Projects\Git\vcpkg\buildtrees\v8\generate-x64-windows-static-dbg-out.log
      D:\Projects\Git\vcpkg\buildtrees\v8\generate-x64-windows-static-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-gn/vcpkg_gn_configure.cmake:11 (vcpkg_execute_required_process)
  installed/x64-windows/share/vcpkg-gn/vcpkg_gn_configure.cmake:35 (z_vcpkg_gn_configure_generate)
  ports/v8/portfile.cmake:150 (vcpkg_gn_configure)
  scripts/ports.cmake:147 (include)



```
<details><summary>D:\Projects\Git\vcpkg\buildtrees\v8\generate-x64-windows-static-dbg-out.log</summary>

```
ERROR at //build/config/win/BUILD.gn:299:27: Script returned non-zero exit code.
  vcvars_toolchain_data = exec_script("../../toolchain/win/setup_toolchain.py",
                          ^----------
Current dir: D:/Projects/Git/vcpkg/buildtrees/v8/x64-windows-static-dbg/
Command: D:/Projects/Git/vcpkg/downloads/tools/python/python-3.10.7-x64/python.exe D:/Projects/Git/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean/build/toolchain/win/setup_toolchain.py "C:\Program Files (x86)/Microsoft Visual Studio/2019/Community" "C:\Program Files (x86)\Windows Kits\10" "C:\Windows\System32;C:\Windows\SysWOW64;Arm64Unused" win x64 none
Returned 1.
See //build/config/BUILDCONFIG.gn:344:5: which caused the file to be included.
    "//build/config/win:default_cfg_compiler",
    ^----------------------------------------
```
</details>
<details><summary>D:\Projects\Git\vcpkg\buildtrees\v8\generate-x64-windows-static-dbg-err.log</summary>

```
Traceback (most recent call last):
  File "D:\Projects\Git\vcpkg\buildtrees\v8\src\a883683717-e774d37ef1.clean\build\toolchain\win\setup_toolchain.py", line 311, in <module>
    main()
  File "D:\Projects\Git\vcpkg\buildtrees\v8\src\a883683717-e774d37ef1.clean\build\toolchain\win\setup_toolchain.py", line 268, in main
    vc_lib_path = FindFileInEnvList(env, 'LIB', ';', 'msvcrt.lib')
  File "D:\Projects\Git\vcpkg\buildtrees\v8\src\a883683717-e774d37ef1.clean\build\toolchain\win\setup_toolchain.py", line 209, in FindFileInEnvList
    assert optional, "%s is not found in %s:\n%s\nCheck if it is installed." % (
AssertionError: msvcrt.lib is not found in LIB:
C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64
C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64
C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64
Check if it is installed.
Traceback (most recent call last):
  File "D:\Projects\Git\vcpkg\buildtrees\v8\src\a883683717-e774d37ef1.clean\build\toolchain\win\setup_toolchain.py", line 311, in <module>
    main()
  File "D:\Projects\Git\vcpkg\buildtrees\v8\src\a883683717-e774d37ef1.clean\build\toolchain\win\setup_toolchain.py", line 268, in main
    vc_lib_path = FindFileInEnvList(env, 'LIB', ';', 'msvcrt.lib')
  File "D:\Projects\Git\vcpkg\buildtrees\v8\src\a883683717-e774d37ef1.clean\build\toolchain\win\setup_toolchain.py", line 209, in FindFileInEnvList
    assert optional, "%s is not found in %s:\n%s\nCheck if it is installed." % (
AssertionError: msvcrt.lib is not found in LIB:
C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x86
C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x86
C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x86
Check if it is installed.
```
</details>

**Additional context**

I've previously installed and built v8 multiple times before, so not sure what's changed here. VCPKG installation and directories haven't changed.

**Comment by RayIon** [comment]
Oh, I did also update VCPKG beforehand.

**Comment by FrankXie05** [comment]
Do you independently install Windows SDK for x64？
 `C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0`
 
And check if `msvcrt.lib` is included?

v8: https://github.com/microsoft/vcpkg/blob/b51f391cd8f1f5a406b3baf9b014acff61702dc3/ports/v8/portfile.cmake#LL121-L124C8

**Comment by FrankXie05** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
