### ISSUE TITLE
[gmp-6.2.1] build fails without automake on macOS

### ISSUE THREAD

**Issue by abhinavnatarajan** [microsoft/vcpkg#31362]
### Operating system

macOS 13

### Compiler

Clang/LLVM 14.0.0

### Steps to reproduce the behavior

```Shell
./vcpkg install gmp:x64-osx
```

### Failure logs

```
Installing 5/106 gmp:x64-osx...
  Building gmp[core]:x64-osx...
  -- Downloading https://gmplib.org/download/gmp/gmp-6.2.1.tar.xz -> gmp-6.2.1.tar.xz...
  -- Downloading https://gmplib.org/repo/gmp/raw-rev/5f32dbc41afc -> gmp-arm64-asm-fix-5f32dbc41afc.patch...
  -- Extracting source /Users/runner/work/Chalc/Chalc/vcpkg/downloads/gmp-6.2.1.tar.xz
  -- Applying patch asmflags.patch
  -- Applying patch cross-tools.patch
  -- Applying patch subdirs.patch
  -- Applying patch msvc_symbol.patch
  -- Applying patch arm64-coff.patch
  -- Applying patch /Users/runner/work/Chalc/Chalc/vcpkg/downloads/gmp-arm64-asm-fix-5f32dbc41afc.patch
  -- Using source at /Users/runner/work/Chalc/Chalc/vcpkg/buildtrees/gmp/src/v6.2.1-0c723d4b6f.clean
  -- Found external ninja('1.11.1.git.kitware.jobserver-1').
  -- Getting CMake variables for x64-osx
  -- Getting CMake variables for x64-osx-dbg
  -- Getting CMake variables for x64-osx-rel
  -- Generating configure for x64-osx
  [LogCollection][Start]File:'/Users/runner/work/Chalc/Chalc/vcpkg/buildtrees/gmp/autoconf-x64-osx-err.log':
  autoreconf: export WARNINGS=
  autoreconf: Entering directory '.'
  autoreconf: configure.ac: not using Gettext
  autoreconf: running: aclocal --force 
  Can't exec "aclocal": No such file or directory at /usr/local/Cellar/autoconf/2.71/share/autoconf/Autom4te/FileUtils.pm line 274.
  autoreconf: error: aclocal failed with exit status: 2
  
  [LogCollection][End]File:'/Users/runner/work/Chalc/Chalc/vcpkg/buildtrees/gmp/autoconf-x64-osx-err.log'.
  [LogCollection][Start]File:'/Users/runner/work/Chalc/Chalc/vcpkg/buildtrees/gmp/autoconf-x64-osx-err.log':
  autoreconf: export WARNINGS=
  autoreconf: Entering directory '.'
  autoreconf: configure.ac: not using Gettext
  autoreconf: running: aclocal --force 
  Can't exec "aclocal": No such file or directory at /usr/local/Cellar/autoconf/2.71/share/autoconf/Autom4te/FileUtils.pm line 274.
  autoreconf: error: aclocal failed with exit status: 2
  
  [LogCollection][End]File:'/Users/runner/work/Chalc/Chalc/vcpkg/buildtrees/gmp/autoconf-x64-osx-err.log'.
  CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
  Error:     Command failed: /usr/local/bin/autoreconf -vfi
      Working Directory: /Users/runner/work/Chalc/Chalc/vcpkg/buildtrees/gmp/src/v6.2.1-0c723d4b6f.clean/
      Error code: 2
      See logs for more information:
        /Users/runner/work/Chalc/Chalc/vcpkg/buildtrees/gmp/autoconf-x64-osx-err.log
  
  Call Stack (most recent call first):
    scripts/cmake/vcpkg_configure_make.cmake:630 (vcpkg_execute_required_process)
    ports/gmp/portfile.cmake:85 (vcpkg_configure_make)
    scripts/ports.cmake:147 (include)
  
  
  error: building gmp:x64-osx failed with: BUILD_FAILED
  Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
  Then check for known issues at:
      https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+gmp
  You can submit a new issue at:
      https://github.com/microsoft/vcpkg/issues/new?title=[gmp]+Build+error&body=Copy+issue+body+from+%2FUsers%2Frunner%2Fwork%2FChalc%2Fb%2Fvcpkg_installed%2Fvcpkg%2Fissue_body.md
  You can also sumbit an issue by running (GitHub cli must be installed):
      gh issue create -R microsoft/vcpkg --title "[gmp] Build failure" --body-file /Users/runner/work/Chalc/b/vcpkg_installed/vcpkg/issue_body.md
  Error: Last command execution failed with error code '1'.
⏱ elapsed: 78.775 seconds
Error: Last command execution failed with error code '1'.
    at BaseUtilLib.throwIfErrorCode (/Users/runner/work/_actions/lukka/run-vcpkg/v11/dist/index.js:42413:19)
    at VcpkgRunner.<anonymous> (/Users/runner/work/_actions/lukka/run-vcpkg/v11/dist/index.js:44[228](https://github.com/abhinavnatarajan/Chalc/actions/runs/4921382431/jobs/8791167188#step:4:237):28)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/runner/work/_actions/lukka/run-vcpkg/v11/dist/index.js:44072:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: run-vcpkg action execution failed: Last command execution failed with error code '1'.
```

### Additional context

I'm running a CI build of a package that requires GMP, and the build of GMP fails with the message `Can't exec "aclocal: No such file or directory`. Running `brew install automake` before `./vcpkg install ...` fixes the problem.

**Comment by MonicaLiu0311** [comment]
Related: #17657, #24870
