### ISSUE TITLE
[glib] build failure

### ISSUE THREAD

**Issue by WangHHY19931001** [microsoft/vcpkg#31515]
### Operating system

windows

### Compiler

clang

### Steps to reproduce the behavior

```Shell
vcpkg install glib:arm-android
```

### Failure logs

Package: glib[core]:arm-android -> 2.76.2

**Host Environment**

- Host: x64-windows
- Compiler: Clang 12.0.9
-    vcpkg-tool version: 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895
    vcpkg-scripts version: 40619a55c 2023-05-18 (11 hours ago)

**To Reproduce**

`vcpkg install glib:arm-android`

**Failure logs**

```
-- Using cached glib-2.76.2.tar.xz.
-- Cleaning sources at C:/vcpkg/buildtrees/glib/src/glib-2-2f2db3ea41.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/glib-2.76.2.tar.xz
-- Applying patch use-libiconv-on-windows.patch
-- Applying patch libintl.patch
-- Using source at C:/vcpkg/buildtrees/glib/src/glib-2-2f2db3ea41.clean
-- Getting CMake variables for arm-android
-- Configuring arm-android-dbg
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at C:/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/vcpkg/downloads/tools/python/python-3.10.7-x64/python.exe C:/vcpkg/installed/x64-windows/tools/meson/meson.py -Dselinux=disabled -Dlibmount=disabled -Dgtk_doc=false -Dinstalled_tests=false -Dlibelf=disabled -Dman=false -Dtests=false -Dxattr=false --buildtype plain --backend ninja --wrap-mode nodownload --native C:/vcpkg/scripts/buildsystems/meson/none.txt --libdir lib --cross C:/vcpkg/buildtrees/glib/meson-arm-android-dbg.log -Ddebug=true --prefix C:/vcpkg/packages/glib_arm-android/debug --includedir ../include -Dcmake_prefix_path=['C:/vcpkg/installed/arm-android/debug','C:/vcpkg/installed/arm-android'] C:/vcpkg/buildtrees/glib/src/glib-2-2f2db3ea41.clean
    Working Directory: C:/vcpkg/buildtrees/glib/arm-android-dbg
    Error code: 2
    See logs for more information:
      C:\vcpkg\buildtrees\glib\config-arm-android-dbg-meson-log.txt.log
      C:\vcpkg\buildtrees\glib\config-arm-android-dbg-out.log
      C:\vcpkg\buildtrees\glib\config-arm-android-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:431 (vcpkg_execute_required_process)
  ports/glib/portfile.cmake:38 (vcpkg_configure_meson)
  scripts/ports.cmake:147 (include)



```
<details><summary>C:\vcpkg\buildtrees\glib\config-arm-android-dbg-meson-log.txt.log</summary>

```
Build started at 2023-05-19T13:58:53.628751
Main binary: C:\vcpkg\downloads\tools\python\python-3.10.7-x64\python.exe
Build Options: -Dselinux=disabled -Dlibmount=disabled -Dgtk_doc=false -Dinstalled_tests=false -Dlibelf=disabled -Dman=false -Dtests=false -Dxattr=false -Ddebug=true '-Dcmake_prefix_path=['"'"'C:/vcpkg/installed/arm-android/debug'"'"','"'"'C:/vcpkg/installed/arm-android'"'"']' -Dprefix=C:/vcpkg/packages/glib_arm-android/debug -Dincludedir=../include -Dlibdir=lib -Dbackend=ninja -Dbuildtype=plain -Dwrap_mode=nodownload '--cross-file C:/vcpkg/buildtrees/glib/meson-arm-android-dbg.log' '--native-file C:/vcpkg/scripts/buildsystems/meson/none.txt'
Python system: Windows
The Meson build system
Version: 0.62.1
Source dir: C:\vcpkg\buildtrees\glib\src\glib-2-2f2db3ea41.clean
Build dir: C:\vcpkg\buildtrees\glib\arm-android-dbg
Build type: cross build
Project name: glib
Project version: 2.76.2
Activating VS 17.5.5

..\src\glib-2-2f2db3ea41.clean\meson.build:1:0: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```
</details>
<details><summary>C:\vcpkg\buildtrees\glib\config-arm-android-dbg-out.log</summary>

```
WARNING: Recommend using either -Dbuildtype or -Doptimization + -Ddebug. Using both is redundant since they override each other. See: https://mesonbuild.com/Builtin-options.html#build-type-options
The Meson build system
Version: 0.62.1
Source dir: C:\vcpkg\buildtrees\glib\src\glib-2-2f2db3ea41.clean
Build dir: C:\vcpkg\buildtrees\glib\arm-android-dbg
Build type: cross build
Project name: glib
Project version: 2.76.2
Activating VS 17.5.5

..\src\glib-2-2f2db3ea41.clean\meson.build:1:0: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```
</details>
<details><summary>C:\vcpkg\buildtrees\glib\config-arm-android-dbg-err.log</summary>

```
Traceback (most recent call last):
  File "C:\vcpkg\installed\x64-windows\tools\meson\mesonbuild\mesonmain.py", line 153, in run
    return options.run_func(options)
  File "C:\vcpkg\installed\x64-windows\tools\meson\mesonbuild\msetup.py", line 301, in run
    app.generate()
  File "C:\vcpkg\installed\x64-windows\tools\meson\mesonbuild\msetup.py", line 185, in generate
    self._generate(env)
  File "C:\vcpkg\installed\x64-windows\tools\meson\mesonbuild\msetup.py", line 207, in _generate
    intr = interpreter.Interpreter(b, user_defined_options=user_defined_options)
  File "C:\vcpkg\installed\x64-windows\tools\meson\mesonbuild\interpreter\interpreter.py", line 317, in __init__
    self.parse_project()
  File "C:\vcpkg\installed\x64-windows\tools\meson\mesonbuild\interpreterbase\interpreterbase.py", line 119, in parse_project
    self.evaluate_codeblock(self.ast, end=1)
  File "C:\vcpkg\installed\x64-windows\tools\meson\mesonbuild\interpreterbase\interpreterbase.py", line 174, in evaluate_codeblock
    raise e
  File "C:\vcpkg\installed\x64-windows\tools\meson\mesonbuild\interpreterbase\interpreterbase.py", line 167, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:\vcpkg\installed\x64-windows\tools\meson\mesonbuild\interpreterbase\interpreterbase.py", line 180, in evaluate_statement
    return self.function_call(cur)
  File "C:\vcpkg\installed\x64-windows\tools\meson\mesonbuild\interpreterbase\interpreterbase.py", line 455, in function_call
    res = func(node, func_args, kwargs)
  File "C:\vcpkg\installed\x64-windows\tools\meson\mesonbuild\interpreterbase\decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "C:\vcpkg\installed\x64-windows\tools\meson\mesonbuild\interpreterbase\decorators.py", line 574, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\vcpkg\installed\x64-windows\tools\meson\mesonbuild\interpreter\interpreter.py", line 1198, in func_project
    if mesonlib.setup_vsenv(force_vsenv):
  File "C:\vcpkg\installed\x64-windows\tools\meson\mesonbuild\mesonlib\vsenv.py", line 105, in setup_vsenv
    return _setup_vsenv(force)
  File "C:\vcpkg\installed\x64-windows\tools\meson\mesonbuild\mesonlib\vsenv.py", line 99, in _setup_vsenv
    k, v = bat_line.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```
</details>

**Additional context**

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
