### ISSUE TITLE
[crashpad] Build error

### ISSUE THREAD

**Issue by BA7LYA** [microsoft/vcpkg#32933]
Package: crashpad:x64-windows -> 2022-09-05#4

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.36.32537.0
-    vcpkg-tool version: 2023-06-22-f19f3d9939100085fe2f7e41502d60b08e2083b6
    vcpkg-scripts version: 980ec0f49 2023-08-02 (21 hours ago)

**To Reproduce**

`vcpkg install crashpad`

**Failure logs**

```
-- Note: crashpad only supports static library linkage. Building static library.
-- Fetching https://chromium.googlesource.com/crashpad/crashpad 261679b3d2f3336d8531ed38e110254c3e2d1c10...
-- Extracting source C:/ToolChain/vcpkg/downloads/crashpad-261679b3d2f3336d8531ed38e110254c3e2d1c10.tar.gz
-- Using source at C:/ToolChain/vcpkg/buildtrees/crashpad/src/4c3e2d1c10-1c4f0a1e28.clean
-- Fetching https://chromium.googlesource.com/chromium/mini_chromium 5654edb4225bcad13901155c819febb5748e502b...
-- Extracting source C:/ToolChain/vcpkg/downloads/crashpad-5654edb4225bcad13901155c819febb5748e502b.tar.gz
-- Using source at C:/ToolChain/vcpkg/buildtrees/crashpad/src/b5748e502b-44507d16bb.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Generating build (x64-windows-dbg)...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/ToolChain/vcpkg/installed/x64-windows/tools/gn/gn.exe gen C:/ToolChain/vcpkg/buildtrees/crashpad/x64-windows-dbg "--args= target_cpu=\"x64\"  is_debug=true         extra_cflags_c=\"  -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -MP  -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1  \"         extra_cflags_cc=\"  -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -GR -EHsc -MP  -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1  \"         extra_ldflags=\" -machine:x64 -nologo    -debug -INCREMENTAL \"         extra_arflags=\"-machine:x64 -nologo\"         extra_cflags=\"/GL-\"         extra_ldflags=\"/LTCG:OFF\"         extra_arflags=\"/LTCG:OFF\""
    Working Directory: C:/ToolChain/vcpkg/buildtrees/crashpad/src/4c3e2d1c10-1c4f0a1e28.clean
    Error code: 1
    See logs for more information:
      C:\ToolChain\vcpkg\buildtrees\crashpad\generate-x64-windows-dbg-out.log
      C:\ToolChain\vcpkg\buildtrees\crashpad\generate-x64-windows-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-gn/vcpkg_gn_configure.cmake:11 (vcpkg_execute_required_process)
  installed/x64-windows/share/vcpkg-gn/vcpkg_gn_configure.cmake:35 (z_vcpkg_gn_configure_generate)
  ports/crashpad/portfile.cmake:102 (vcpkg_gn_configure)
  scripts/ports.cmake:147 (include)
```
<details><summary>C:\ToolChain\vcpkg\buildtrees\crashpad\generate-x64-windows-dbg-out.log</summary>

```
ERROR at //third_party/mini_chromium/mini_chromium/build/config/BUILD.gn:611:20: Script returned non-zero exit code.
  toolchain_data = exec_script(helper_path,
                   ^----------
Current dir: C:/ToolChain/vcpkg/buildtrees/crashpad/x64-windows-dbg/
Command: C:/ToolChain/vcpkg/downloads/tools/python/python-3.10.7-x64/python.exe C:/ToolChain/vcpkg/buildtrees/crashpad/src/4c3e2d1c10-1c4f0a1e28.clean/third_party/mini_chromium/mini_chromium/build/win_helper.py get-visual-studio-data C:/ToolChain/vcpkg/buildtrees/crashpad/x64-windows-dbg C:/ToolChain/vcpkg/buildtrees/crashpad/src/4c3e2d1c10-1c4f0a1e28.clean/third_party/mini_chromium/mini_chromium/build/config/<autodetect>
Returned 1.
See //build/BUILDCONFIG.gn:63:3: which caused the file to be included.
  "$_mini_chromium_dir/build/config:default",
  ^-----------------------------------------
```
</details>

<details><summary>C:\ToolChain\vcpkg\buildtrees\crashpad\generate-x64-windows-dbg-err.log</summary>

```
Traceback (most recent call last):
  File "C:\ToolChain\vcpkg\buildtrees\crashpad\src\4c3e2d1c10-1c4f0a1e28.clean\third_party\mini_chromium\mini_chromium\build\win_helper.py", line 230, in <module>
    sys.exit(WinTool().Dispatch(sys.argv[1:]))
  File "C:\ToolChain\vcpkg\buildtrees\crashpad\src\4c3e2d1c10-1c4f0a1e28.clean\third_party\mini_chromium\mini_chromium\build\win_helper.py", line 124, in Dispatch
    return getattr(self, method)(*args[1:])
  File "C:\ToolChain\vcpkg\buildtrees\crashpad\src\4c3e2d1c10-1c4f0a1e28.clean\third_party\mini_chromium\mini_chromium\build\win_helper.py", line 210, in ExecGetVisualStudioData
    install_dir, script_path = (explicit() or env() or autodetect() or fail())
  File "C:\ToolChain\vcpkg\buildtrees\crashpad\src\4c3e2d1c10-1c4f0a1e28.clean\third_party\mini_chromium\mini_chromium\build\win_helper.py", line 205, in fail
    def fail(): raise Exception('Visual Studio installation dir not found')
Exception: Visual Studio installation dir not found
```
</details>

**Comment by Adela0814** [comment]
@BA7LYA  Please try to install the required Visual Studio components in https://github.com/microsoft/vcpkg-tool/pull/314.

**Comment by BA7LYA** [comment]
> @BA7LYA Please try to install the required Visual Studio components in [microsoft/vcpkg-tool#314](https://github.com/microsoft/vcpkg-tool/pull/314).

@Adela0814  Thanks for the tip.

**Comment by BA7LYA** [comment]
The install of crashpad failed on my machine because the build chain failed to find visual studio. but i have installed vs build tool, which i think it should work. The `ExecGetVisualStudioData` method failed on all three branch on find vs build tool.

```python

# in mini_cromium/build/win_helper.py, line 163 ~ 205:

def ExecGetVisualStudioData(self, outdir, toolchain_path):
    setenv_paths = [
        # cipd packaged SDKs from 10.0.19041.0 onwards.
        os.path.join("Windows Kits", "10", "bin", "SetEnv.cmd"),
        # cipd packaged SDKs prior to 10.0.19041.0.
        os.path.join("win_sdk", "bin", "SetEnv.cmd"),
    ]

    # **FAILED**, cause i got no `SetEnv.cmd` on my machine under path "C:/Program Files (x86)/Windows Kits/10/bin"
    def explicit():
        for setenv_path in setenv_paths:
            if os.path.exists(os.path.join(toolchain_path, setenv_path)):
                return toolchain_path, setenv_path

    # **FAILED**, cause the env-var on my machine is `VS2022INSTALLDIR` and `VS2019INSTALLDIR`, not `VSINSTALLDIR`
    def env():
        from_env = os.environ.get("VSINSTALLDIR")
        for setenv_path in setenv_paths:
            if from_env and os.path.exists(os.path.join(from_env, setenv_path)):
                return from_env, setenv_path

    # **FAILED**, cause i got no visual studio on my machine but just vs build tool, so i got no `vswhere` on my machine
    def autodetect():
        # Try vswhere, which will find VS2017.2+. Note that earlier VS2017s will
        # not be found.
        vswhere_path = os.path.join(
            os.environ.get("ProgramFiles(x86)"),
            "Microsoft Visual Studio",
            "Installer",
            "vswhere.exe",
        )
        if os.path.exists(vswhere_path):
            installation_path = subprocess.check_output(
                [vswhere_path, "-latest", "-property", "installationPath"]
            ).strip()
            if installation_path:
                return (
                    installation_path.decode("utf-8"),
                    os.path.join("VC", "Auxiliary", "Build", "vcvarsall.bat"),
                )

        # Otherwise, try VS2015.
        version = "14.0"
        keys = [
            r"HKLM\Software\Microsoft\VisualStudio\%s" % version,
            r"HKLM\Software\Wow6432Node\Microsoft\VisualStudio\%s" % version,
        ]
        for key in keys:
            path = _RegistryGetValue(key, "InstallDir")
            if not path:
                continue
            return (
                os.path.normpath(os.path.join(path, os.pardir, os.pardir)),
                os.path.join("VC", "vcvarsall.bat"),
            )

    def fail():
        raise Exception("Visual Studio installation dir not found")

```
