### ISSUE TITLE
[v8] Build error

### ISSUE THREAD

**Issue by bacoln** [microsoft/vcpkg#33447]
Copy issue body from 

```
E:\Program\vcpkg\buildtrees\v8\src\a883683717-e774d37ef1.clean\build\vs_toolchain.py:12: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
  import pipes
Traceback (most recent call last):
  File "E:\Program\vcpkg\buildtrees\v8\src\a883683717-e774d37ef1.clean\build\vs_toolchain.py", line 573, in <module>
    sys.exit(main())
             ^^^^^^
  File "E:\Program\vcpkg\buildtrees\v8\src\a883683717-e774d37ef1.clean\build\vs_toolchain.py", line 569, in main
    return commands[sys.argv[1]](*sys.argv[2:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program\vcpkg\buildtrees\v8\src\a883683717-e774d37ef1.clean\build\vs_toolchain.py", line 546, in GetToolchainDir
    runtime_dll_dirs = SetEnvironmentAndGetRuntimeDllDirs()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program\vcpkg\buildtrees\v8\src\a883683717-e774d37ef1.clean\build\vs_toolchain.py", line 106, in SetEnvironmentAndGetRuntimeDllDirs
    os.environ['GYP_MSVS_OVERRIDE_PATH'] = DetectVisualStudioPath()

**Comment by StarGate-One** [comment]
See [How to report a package build failure [explanation video]](https://github.com/microsoft/vcpkg/issues/30604) #30604

**Comment by bacoln** [comment]
DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13

**Comment by Adela0814** [comment]
Please provide your repro steps and failure logs. see https://github.com/microsoft/vcpkg/issues/30604.

**Comment by bacoln** [comment]
Package: v8:x64-windows -> 9.1.269.39#6

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.37.32822.0
-    vcpkg-tool version: 2023-08-09-9990a4c9026811a312cb2af78bf77f3d9d288416
    vcpkg-scripts version: unknown

**To Reproduce**

`vcpkg install `
**Failure logs**

```
-- Using cached msys2-pkgconf-1.9.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-bash-5.2.015-1-x86_64.pkg.tar.zst.
-- Using cached msys2-coreutils-8.32-5-x86_64.pkg.tar.zst.
-- Using cached msys2-file-5.44-5-x86_64.pkg.tar.zst.
-- Using cached msys2-gawk-5.2.1-2-x86_64.pkg.tar.zst.
-- Using cached msys2-grep-1~3.0-6-x86_64.pkg.tar.zst.
-- Using cached msys2-gzip-1.12-2-x86_64.pkg.tar.zst.
-- Using cached msys2-diffutils-3.9-1-x86_64.pkg.tar.zst.
-- Using cached msys2-make-4.4.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-pkgconf-1.9.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-sed-4.9-1-x86_64.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libiconv-1.17-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libintl-0.21-2-x86_64.pkg.tar.zst.
-- Using cached msys2-gmp-6.2.1-2-x86_64.pkg.tar.zst.
-- Using cached msys2-gcc-libs-11.3.0-3-x86_64.pkg.tar.zst.
-- Using cached msys2-libbz2-1.0.8-4-x86_64.pkg.tar.zst.
-- Using cached msys2-liblzma-5.4.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libzstd-1.5.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-zlib-1.2.13-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libreadline-8.2.001-3-x86_64.pkg.tar.zst.
-- Using cached msys2-mpfr-4.2.0-2-x86_64.pkg.tar.zst.
-- Using cached msys2-libpcre-8.45-3-x86_64.pkg.tar.zst.
-- Using cached msys2-ncurses-6.4-1-x86_64.pkg.tar.zst.
-- Using msys root at E:/Program/vcpkg/downloads/tools/msys2/fe2fc2a8e5496621
-- Using cached E:/Program/vcpkg/downloads/v8-7d3d62c91f69a702e5aa54c6b4dbbaa883683717.tar.gz
-- Cleaning sources at E:/Program/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/Program/vcpkg/downloads/v8-7d3d62c91f69a702e5aa54c6b4dbbaa883683717.tar.gz
-- Applying patch E:/Program/vcpkg/ports/v8/v8.patch
-- Using source at E:/Program/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean
-- Fetching submodules
-- Generating v8 build files. Please wait...
-- Generating build (x64-windows-dbg)...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: E:/C++/ZYQQNT/vcpkg_installed/x64-windows/tools/gn/gn.exe gen E:/Program/vcpkg/buildtrees/v8/x64-windows-dbg "--args=is_component_build=true target_cpu=\"x64\" v8_monolithic=false v8_use_external_startup_data=true use_sysroot=false is_clang=false use_custom_libcxx=false v8_enable_verify_heap=false icu_use_data_file=false is_debug=true enable_iterator_debugging=true pkg_config_libdir=\"/e/C++/ZYQQNT/vcpkg_installed/x64-windows/debug/lib/pkgconfig\""
    Working Directory: E:/Program/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean
    Error code: 1
    See logs for more information:
      E:\Program\vcpkg\buildtrees\v8\generate-x64-windows-dbg-out.log
      E:\Program\vcpkg\buildtrees\v8\generate-x64-windows-dbg-err.log

Call Stack (most recent call first):
  E:/C++/ZYQQNT/vcpkg_installed/x64-windows/share/vcpkg-gn/vcpkg_gn_configure.cmake:11 (vcpkg_execute_required_process)
  E:/C++/ZYQQNT/vcpkg_installed/x64-windows/share/vcpkg-gn/vcpkg_gn_configure.cmake:35 (z_vcpkg_gn_configure_generate)
  ports/v8/portfile.cmake:150 (vcpkg_gn_configure)
  scripts/ports.cmake:147 (include)



```
<details><summary>E:\Program\vcpkg\buildtrees\v8\generate-x64-windows-dbg-out.log</summary>

```
ERROR at //build/config/win/visual_studio_version.gni:27:7: Script returned non-zero exit code.
      exec_script("../../vs_toolchain.py", [ "get_toolchain_dir" ], "scope")
      ^----------
Current dir: E:/Program/vcpkg/buildtrees/v8/x64-windows-dbg/
Command: E:/Program/vcpkg/downloads/tools/python/python-3.11.4-x64/python.exe E:/Program/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean/build/vs_toolchain.py get_toolchain_dir
Returned 1.
See //build/toolchain/win/BUILD.gn:8:1: whence it was imported.
import("//build/config/win/visual_studio_version.gni")
^----------------------------------------------------
See //BUILD.gn:1195:1: which caused the file to be included.
action("postmortem-metadata") {
^------------------------------
```
</details>
<details><summary>E:\Program\vcpkg\buildtrees\v8\generate-x64-windows-dbg-err.log</summary>

```
E:\Program\vcpkg\buildtrees\v8\src\a883683717-e774d37ef1.clean\build\vs_toolchain.py:12: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
  import pipes
Traceback (most recent call last):
  File "E:\Program\vcpkg\buildtrees\v8\src\a883683717-e774d37ef1.clean\build\vs_toolchain.py", line 573, in <module>
    sys.exit(main())
             ^^^^^^
  File "E:\Program\vcpkg\buildtrees\v8\src\a883683717-e774d37ef1.clean\build\vs_toolchain.py", line 569, in main
    return commands[sys.argv[1]](*sys.argv[2:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program\vcpkg\buildtrees\v8\src\a883683717-e774d37ef1.clean\build\vs_toolchain.py", line 546, in GetToolchainDir
    runtime_dll_dirs = SetEnvironmentAndGetRuntimeDllDirs()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program\vcpkg\buildtrees\v8\src\a883683717-e774d37ef1.clean\build\vs_toolchain.py", line 106, in SetEnvironmentAndGetRuntimeDllDirs
    os.environ['GYP_MSVS_OVERRIDE_PATH'] = DetectVisualStudioPath()
                                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program\vcpkg\buildtrees\v8\src\a883683717-e774d37ef1.clean\build\vs_toolchain.py", line 197, in DetectVisualStudioPath
    version_as_year = GetVisualStudioVersion()
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program\vcpkg\buildtrees\v8\src\a883683717-e774d37ef1.clean\build\vs_toolchain.py", line 186, in GetVisualStudioVersion
    raise Exception('No supported Visual Studio can be found.'
Exception: No supported Visual Studio can be found. Supported versions are: 16.0 (2019), 15.0 (2017).
```
</details>**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "name": "zhyee",
  "description": "中异软件",
  "homepage": "http://zhongyee.cn",
  "license": "GPL-3.0-or-later",
  "version-string": "latest",
  "dependencies": [
    "v8"
  ],
  "maintainers": [
    "zhyee"
  ],
  "supports": "windows"
}

```
</details>

**Comment by StarGate-One** [comment]
>Call Stack (most recent call first):
  E:/C++/ZYQQNT/vcpkg_installed/x64-windows/share/vcpkg-gn/vcpkg_gn_configure.cmake:11 (vcpkg_execute_required_process)
  E:/C++/ZYQQNT/vcpkg_installed/x64-windows/share/vcpkg-gn/vcpkg_gn_configure.cmake:35 (z_vcpkg_gn_configure_generate)

I might suggest changing the path of vcpkg from `E:\C++` to something like `E:\CPP` as many of the tools used by vcpkg have been around for a long time and do not like spaces and/or special characters in the path name.

**Comment by Adela0814** [comment]
@bacoln Have you tried changing the vcpkg root directory to solve your problem?

**Comment by raphtalia** [comment]
Package: v8:x64-windows -> 9.1.269.39#4

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.36.32537.0
-    vcpkg-tool version: 2023-08-09-9990a4c9026811a312cb2af78bf77f3d9d288416
    vcpkg-scripts version: da21e45c9 2023-09-12 (24 hours ago)

**To Reproduce**

`vcpkg install `
**Failure logs**

```
Consider adding vcpkg-tool-gn as a host dependency of this port or create an issue at https://github.com/microsoft/vcpkg/issues
-- Found external ninja('1.11.0').
-- Using cached msys2-pkgconf-1.9.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-bash-5.2.015-1-x86_64.pkg.tar.zst.
-- Using cached msys2-coreutils-8.32-5-x86_64.pkg.tar.zst.
-- Using cached msys2-file-5.44-5-x86_64.pkg.tar.zst.
-- Using cached msys2-gawk-5.2.1-2-x86_64.pkg.tar.zst.
-- Using cached msys2-grep-1~3.0-6-x86_64.pkg.tar.zst.
-- Using cached msys2-gzip-1.12-2-x86_64.pkg.tar.zst.
-- Using cached msys2-diffutils-3.9-1-x86_64.pkg.tar.zst.
-- Using cached msys2-make-4.4.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-pkgconf-1.9.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-sed-4.9-1-x86_64.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libiconv-1.17-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libintl-0.21-2-x86_64.pkg.tar.zst.
-- Using cached msys2-gmp-6.2.1-2-x86_64.pkg.tar.zst.
-- Using cached msys2-gcc-libs-11.3.0-3-x86_64.pkg.tar.zst.
-- Using cached msys2-libbz2-1.0.8-4-x86_64.pkg.tar.zst.
-- Using cached msys2-liblzma-5.4.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libzstd-1.5.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-zlib-1.2.13-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libreadline-8.2.001-3-x86_64.pkg.tar.zst.
-- Using cached msys2-mpfr-4.2.0-2-x86_64.pkg.tar.zst.
-- Using cached msys2-libpcre-8.45-3-x86_64.pkg.tar.zst.
-- Using cached msys2-ncurses-6.4-1-x86_64.pkg.tar.zst.
-- Using msys root at C:/Users/kriss/Documents/GitHub/vcpkg/downloads/tools/msys2/fe2fc2a8e5496621
-- Using cached C:/Users/kriss/Documents/GitHub/vcpkg/downloads/v8-7d3d62c91f69a702e5aa54c6b4dbbaa883683717.tar.gz
-- Cleaning sources at C:/Users/kriss/Documents/GitHub/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/kriss/Documents/GitHub/vcpkg/downloads/v8-7d3d62c91f69a702e5aa54c6b4dbbaa883683717.tar.gz
-- Applying patch C:/Users/kriss/AppData/Local/vcpkg/registries/git-trees/f57ec75cb9169900555359752c65e8e4c79c34ec/v8.patch
-- Using source at C:/Users/kriss/Documents/GitHub/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean
-- Fetching submodules
-- Generating v8 build files. Please wait...
CMake Warning at scripts/cmake/vcpkg_configure_gn.cmake:20 (message):
  This function 'vcpkg_configure_gn' is obsolete.  Use 'vcpkg_gn_configure'
  in port 'vcpkg-gn'.
Call Stack (most recent call first):
  C:/Users/kriss/AppData/Local/vcpkg/registries/git-trees/f57ec75cb9169900555359752c65e8e4c79c34ec/portfile.cmake:150 (vcpkg_configure_gn)
  scripts/ports.cmake:147 (include)


-- Generating build (x64-windows-dbg)...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/Users/kriss/Documents/GitHub/vcpkg/downloads/tools/gn/q5ExVHmXyD34Q_Tzb-aRxsPipO-e37-csVRhVM7IJh0C/gn.exe gen C:/Users/kriss/Documents/GitHub/vcpkg/buildtrees/v8/x64-windows-dbg "--args=is_component_build=true target_cpu=\"x64\" v8_monolithic=false v8_use_external_startup_data=true use_sysroot=false is_clang=false use_custom_libcxx=false v8_enable_verify_heap=false icu_use_data_file=false is_debug=true enable_iterator_debugging=true pkg_config_libdir=\"/c/Users/kriss/Documents/GitHub/ckts/ckts/vcpkg_installed/x64-windows/debug/lib/pkgconfig\""
    Working Directory: C:/Users/kriss/Documents/GitHub/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean
    Error code: 1
    See logs for more information:
      C:\Users\kriss\Documents\GitHub\vcpkg\buildtrees\v8\generate-x64-windows-dbg-out.log
      C:\Users\kriss\Documents\GitHub\vcpkg\buildtrees\v8\generate-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_gn.cmake:9 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_configure_gn.cmake:38 (z_vcpkg_configure_gn_generate)
  C:/Users/kriss/AppData/Local/vcpkg/registries/git-trees/f57ec75cb9169900555359752c65e8e4c79c34ec/portfile.cmake:150 (vcpkg_configure_gn)
  scripts/ports.cmake:147 (include)



```
<details><summary>C:\Users\kriss\Documents\GitHub\vcpkg\buildtrees\v8\generate-x64-windows-dbg-out.log</summary>

```
ERROR at //build/config/win/visual_studio_version.gni:27:7: Script returned non-zero exit code.
      exec_script("../../vs_toolchain.py", [ "get_toolchain_dir" ], "scope")
      ^----------
Current dir: C:/Users/kriss/Documents/GitHub/vcpkg/buildtrees/v8/x64-windows-dbg/
Command: C:/Users/kriss/Documents/GitHub/vcpkg/downloads/tools/python/python-3.11.5-x64/python.exe C:/Users/kriss/Documents/GitHub/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean/build/vs_toolchain.py get_toolchain_dir
Returned 1.
See //build/config/win/BUILD.gn:11:1: whence it was imported.
import("//build/config/win/visual_studio_version.gni")
^----------------------------------------------------
See //build/config/BUILDCONFIG.gn:346:5: which caused the file to be included.
    "//build/config/win:lean_and_mean",
    ^---------------------------------
```
</details>
<details><summary>C:\Users\kriss\Documents\GitHub\vcpkg\buildtrees\v8\generate-x64-windows-dbg-err.log</summary>

```
C:\Users\kriss\Documents\GitHub\vcpkg\buildtrees\v8\src\a883683717-e774d37ef1.clean\build\vs_toolchain.py:12: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
  import pipes
Traceback (most recent call last):
  File "C:\Users\kriss\Documents\GitHub\vcpkg\buildtrees\v8\src\a883683717-e774d37ef1.clean\build\vs_toolchain.py", line 573, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\kriss\Documents\GitHub\vcpkg\buildtrees\v8\src\a883683717-e774d37ef1.clean\build\vs_toolchain.py", line 569, in main
    return commands[sys.argv[1]](*sys.argv[2:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kriss\Documents\GitHub\vcpkg\buildtrees\v8\src\a883683717-e774d37ef1.clean\build\vs_toolchain.py", line 546, in GetToolchainDir
    runtime_dll_dirs = SetEnvironmentAndGetRuntimeDllDirs()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kriss\Documents\GitHub\vcpkg\buildtrees\v8\src\a883683717-e774d37ef1.clean\build\vs_toolchain.py", line 106, in SetEnvironmentAndGetRuntimeDllDirs
    os.environ['GYP_MSVS_OVERRIDE_PATH'] = DetectVisualStudioPath()
                                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kriss\Documents\GitHub\vcpkg\buildtrees\v8\src\a883683717-e774d37ef1.clean\build\vs_toolchain.py", line 197, in DetectVisualStudioPath
    version_as_year = GetVisualStudioVersion()
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kriss\Documents\GitHub\vcpkg\buildtrees\v8\src\a883683717-e774d37ef1.clean\build\vs_toolchain.py", line 186, in GetVisualStudioVersion
    raise Exception('No supported Visual Studio can be found.'
Exception: No supported Visual Studio can be found. Supported versions are: 16.0 (2019), 15.0 (2017).
```
</details>**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg-tool/main/docs/vcpkg.schema.json",
  "name": "ckts",
  "version-string": "0.0.1",
  "dependencies": [
    "commonlibsse-ng",
    "v8"
  ]
}

```
</details>

**Comment by MonicaLiu0311** [comment]
```
PS E:\vcpkg> ./vcpkg  version
vcpkg package management program version 2024-11-12-eb492805e92a2c14a230f5c3deb3e89f6771c321

See LICENSE.txt for license information.
```
Repro locally.
```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: E:/vcpkg/installed/x64-windows/tools/gn/gn.exe gen E:/vcpkg/buildtrees/v8/x64-windows-static-dbg "--args=is_component_build=false target_cpu=\"x64\" v8_monolithic=true v8_use_external_startup_data=false use_sysroot=false is_clang=false use_custom_libcxx=false v8_enable_verify_heap=false icu_use_data_file=false is_debug=true enable_iterator_debugging=true pkg_config_libdir=\"/e/vcpkg/installed/x64-windows-static/debug/lib/pkgconfig\""
    Working Directory: E:/vcpkg/buildtrees/v8/src/a883683717-d6c82ef7bb.clean
    Error code: 1
    See logs for more information:
      E:\vcpkg\buildtrees\v8\generate-x64-windows-static-dbg-out.log
      E:\vcpkg\buildtrees\v8\generate-x64-windows-static-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-gn/vcpkg_gn_configure.cmake:10 (vcpkg_execute_required_process)
  installed/x64-windows/share/vcpkg-gn/vcpkg_gn_configure.cmake:34 (z_vcpkg_gn_configure_generate)
  ports/v8/portfile.cmake:161 (vcpkg_gn_configure)
  scripts/ports.cmake:196 (include)
```
**E:\vcpkg\buildtrees\v8\generate-x64-windows-static-dbg-out.log:**
```
ERROR at //build/config/win/visual_studio_version.gni:27:7: Script returned non-zero exit code.
      exec_script("../../vs_toolchain.py", [ "get_toolchain_dir" ], "scope")
      ^----------
Current dir: E:/vcpkg/buildtrees/v8/x64-windows-static-dbg/
Command: E:/vcpkg/downloads/tools/python/python-3.12.7-x64/python.exe E:/vcpkg/buildtrees/v8/src/a883683717-d6c82ef7bb.clean/build/vs_toolchain.py get_toolchain_dir
Returned 1.
See //build/toolchain/win/BUILD.gn:8:1: whence it was imported.
import("//build/config/win/visual_studio_version.gni")
^----------------------------------------------------
See //BUILD.gn:1195:1: which caused the file to be included.
action("postmortem-metadata") {
^------------------------------
```
