### ISSUE TITLE
protobuf 3.21.12 build failure

### ISSUE THREAD

**Issue by mikara89** [microsoft/vcpkg#33956]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
.\vcpkg.exe install protobuf
```

### Failure logs

PS C:\vcpkg-clion\vcpkg> .\vcpkg.exe install protobuf
warning: In the September 2023 release, the default triplet for vcpkg libraries changed from x86-windows to the detected host triplet (x64-windows). For the old behavior, add --triplet x86-windows . To suppress this message, add --triplet x64-windows .
Computing installation plan...
The following packages will be built and installed:
    protobuf:x64-windows -> 3.21.12
  * vcpkg-cmake:x64-windows -> 2023-05-04
  * vcpkg-cmake-config:x64-windows -> 2022-02-06#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 2 package(s) from C:\Users\slobo\AppData\Local\vcpkg\archives in 103 ms. Use --debug to see more details.
Installing 1/3 vcpkg-cmake:x64-windows...
Elapsed time to handle vcpkg-cmake:x64-windows: 4.8 ms
Installing 2/3 vcpkg-cmake-config:x64-windows...
Elapsed time to handle vcpkg-cmake-config:x64-windows: 8.51 ms
Installing 3/3 protobuf:x64-windows...
Building protobuf:x64-windows...
-- Using cached protocolbuffers-protobuf-v3.21.12.tar.gz.
-- Cleaning sources at C:/vcpkg-clion/vcpkg/buildtrees/protobuf/src/v3.21.12-fdb7676342.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg-clion/vcpkg/downloads/protocolbuffers-protobuf-v3.21.12.tar.gz
-- Applying patch fix-static-build.patch
-- Applying patch fix-default-proto-file-path.patch
-- Applying patch compile_options.patch
-- Using source at C:/vcpkg-clion/vcpkg/buildtrees/protobuf/src/v3.21.12-fdb7676342.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/Users/slobo/.dotnet/tools/pwsh.exe -noprofile -executionpolicy Bypass -nologo -file C:/vcpkg-clion/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/vcpkg-clion/vcpkg/packages/protobuf_x64-windows/tools/protobuf/protoc.exe -installedDir C:/vcpkg-clion/vcpkg/packages/protobuf_x64-windows/bin -verbose
    Working Directory: C:/vcpkg-clion/vcpkg
    Error code: -532462766
    See logs for more information:
      C:\vcpkg-clion\vcpkg\buildtrees\protobuf\copy-tool-dependencies-0-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:9 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:41 (z_vcpkg_copy_tool_dependencies_search)
  scripts/cmake/vcpkg_copy_tools.cmake:48 (vcpkg_copy_tool_dependencies)
  ports/protobuf/portfile.cmake:81 (vcpkg_copy_tools)
  scripts/ports.cmake:147 (include)

error: building protobuf:x64-windows failed with: BUILD_FAILED
Elapsed time to handle protobuf:x64-windows: 1.6 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+protobuf
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[protobuf]+Build+error&body=Copy+issue+body+from+C%3A%2Fvcpkg-clion%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Additional context

vcpkg package management program version 2023-09-15-ac02a9f660977426b8ec6392919fbb1d51b10998

**Comment by mikara89** [comment]
copy-tool-dependencies-0-err.log
```
Unhandled exception. System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'dotnet' with working directory 'C:\vcpkg-clion\vcpkg'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Microsoft.PowerShell.GlobalTool.Shim.EntryPoint.Main(String[] args)
```
