### ISSUE TITLE
[protobuf] build failure

### ISSUE THREAD

**Issue by mikara89** [microsoft/vcpkg#33961]
Package: protobuf:x64-windows -> 3.21.12

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.36.32537.0
-    vcpkg-tool version: 2023-09-15-ac02a9f660977426b8ec6392919fbb1d51b10998
    vcpkg-scripts version: 78ba9711d 2023-09-22 (22 hours ago)

**To Reproduce**

`vcpkg install protobuf`
**Failure logs**

```
-- Using cached protocolbuffers-protobuf-v3.21.12.tar.gz.
-- Cleaning sources at C:/vcpkg-clion/vcpkg/buildtrees/protobuf/src/v3.21.12-fdb7676342.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg-clion/vcpkg/downloads/protocolbuffers-protobuf-v3.21.12.tar.gz
-- Applying patch fix-static-build.patch
-- Applying patch fix-default-proto-file-path.patch
-- Applying patch compile_options.patch
-- Using source at C:/vcpkg-clion/vcpkg/buildtrees/protobuf/src/v3.21.12-fdb7676342.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/Users/slobo/.dotnet/tools/pwsh.exe -noprofile -executionpolicy Bypass -nologo -file C:/vcpkg-clion/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/vcpkg-clion/vcpkg/packages/protobuf_x64-windows/tools/protobuf/protoc.exe -installedDir C:/vcpkg-clion/vcpkg/packages/protobuf_x64-windows/bin -verbose
    Working Directory: C:/vcpkg-clion/vcpkg
    Error code: -532462766
    See logs for more information:
      C:\vcpkg-clion\vcpkg\buildtrees\protobuf\copy-tool-dependencies-0-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:9 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:41 (z_vcpkg_copy_tool_dependencies_search)
  scripts/cmake/vcpkg_copy_tools.cmake:48 (vcpkg_copy_tool_dependencies)
  ports/protobuf/portfile.cmake:81 (vcpkg_copy_tools)
  scripts/ports.cmake:147 (include)



```
<details><summary>C:\vcpkg-clion\vcpkg\buildtrees\protobuf\copy-tool-dependencies-0-err.log</summary>

```
Unhandled exception. System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'dotnet' with working directory 'C:\vcpkg-clion\vcpkg'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Microsoft.PowerShell.GlobalTool.Shim.EntryPoint.Main(String[] args)
```
</details>

**Comment by mikara89** [comment]
Problem is fixed by changing root of vcpkg to be on D drive. So for `C:/vcpkg-clion/vcpkg/` to `D:/vcpkg-clion/vcpkg/
