### ISSUE TITLE
[python3] python3 ssl module is not built

### ISSUE THREAD

**Issue by TrentWeiss** [microsoft/vcpkg#34308]
**Describe the bug**
The ssl module is not being built in the current python3 port.

**Environment**
- OS: Linux
- Compiler: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0

**To Reproduce**
1. ./vcpkg install python3
2. Follow the recommended usage for setting up a virtual environment with the built python interpreter.
3. Attempt to import the ssl module with that interpreter by running: python3 -c "import ssl"

**Expected behavior**
Nothing interesting happens. python3 successfully imports the module and then exits without incident.

**Failure logs**
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/path/to/my/vcpkg/installed/x64-linux/lib/python3.11/ssl.py", line 100, in <module>
    import _ssl             # if we can't import it, let the error propagate
    ^^^^^^^^^^^
ModuleNotFoundError: No module named '_ssl'

**Additional context**
Pulled from vcpkg's config step log files:
**_checking for openssl/ssl.h in /home/deepracing/source_builds/vcpkg/installed/x64-linux... yes
checking whether compiling and linking against OpenSSL works... yes
checking for --with-openssl-rpath... 
checking whether OpenSSL provides required ssl module APIs... no
checking whether OpenSSL provides required hashlib module APIs... no_**
checking for --with-ssl-default-suites... python
checking for --with-builtin-hashlib-hashes... md5,sha1,sha256,sha512,sha3,blake2
checking for LIBB2... no
checking for --disable-test-modules... no
checking for additional Modules/Setup files... 
checking for stdlib extension module _multiprocessing... yes
checking for stdlib extension module _posixshmem... yes
checking for stdlib extension module fcntl... yes
checking for stdlib extension module mmap... yes
checking for stdlib extension module _socket... yes
checking for stdlib extension module grp... yes
checking for stdlib extension module ossaudiodev... yes
checking for stdlib extension module pwd... yes
checking for stdlib extension module resource... yes
checking for stdlib extension module _scproxy... n/a
checking for stdlib extension module spwd... yes
checking for stdlib extension module syslog... yes
checking for stdlib extension module termios... yes
checking for stdlib extension module pyexpat... yes
checking for stdlib extension module _elementtree... yes
checking for stdlib extension module _md5... yes
checking for stdlib extension module _sha1... yes
checking for stdlib extension module _sha256... yes
checking for stdlib extension module _sha512... yes
checking for stdlib extension module _sha3... yes
checking for stdlib extension module _blake2... yes
checking for stdlib extension module _crypt... yes
checking for stdlib extension module _decimal... yes
checking for stdlib extension module _gdbm... missing
checking for stdlib extension module nis... yes
checking for stdlib extension module _sqlite3... yes
checking for stdlib extension module _tkinter... yes
checking for stdlib extension module _uuid... yes
checking for stdlib extension module zlib... yes
checking for stdlib extension module _bz2... yes
checking for stdlib extension module _lzma... yes
**_checking for stdlib extension module _ssl... missing_**

**Comment by TrentWeiss** [comment]
Investigating further, it's the openssl port that is causing the issue.

Taking two steps fixed it:
1. Reverting the openssl port to ae76307e4b5ccd3737397b1c6a4cac3bbcfa5ee8
2. Using an [unsupported option in cpython](https://github.com/python/cpython/commit/bacefbf41461ab703b8d561f0e3d766427eab367) to make it link against static openssl properly.  That is, I set an environment variable PY_UNSUPPORTED_OPENSSL_BUILD=static and VCPKG_KEEP_ENV_VARS=PY_UNSUPPORTED_OPENSSL_BUILD (to ensure it gets passed through to vcpkg).

Something about the switch away from the custom CMake build present in ae76307e4b5ccd3737397b1c6a4cac3bbcfa5ee8 to the "unified" build architecture in 9ccc64ca98b320404d059df4349220bd2c1b4a46 broke the ssl module in the python3 port.
