### ISSUE TITLE
[brotli] Build error

### ISSUE THREAD

**Issue by xzunknownzx** [microsoft/vcpkg#34687]
Package: brotli:x86-windows -> 1.0.9#5

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.37.32825.0
-    vcpkg-tool version: 2023-06-22-f19f3d9939100085fe2f7e41502d60b08e2083b6
    vcpkg-readonly: true
    vcpkg-scripts version: 638b1588be3a265a9c7ad5b212cef72a1cad336a

**To Reproduce**

`vcpkg install `

**Failure logs**

```
-- Using cached google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz.
-- Cleaning sources at C:/Users/Administrator/source/repos/Latency Test/vcpkg_installed/vcpkg/blds/brotli/src/6c62fc2c71-3fc02d8e7f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/Administrator/AppData/Local/vcpkg/downloads/google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz
-- Applying patch install.patch
-- Applying patch fix-arm-uwp.patch
-- Applying patch pkgconfig.patch
-- Using source at C:/Users/Administrator/source/repos/Latency Test/vcpkg_installed/vcpkg/blds/brotli/src/6c62fc2c71-3fc02d8e7f.clean
-- Found external ninja('1.11.0').
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Fixing pkgconfig file: C:/Users/Administrator/source/repos/Latency Test/vcpkg_installed/vcpkg/pkgs/brotli_x86-windows/lib/pkgconfig/libbrotlicommon.pc
-- Fixing pkgconfig file: C:/Users/Administrator/source/repos/Latency Test/vcpkg_installed/vcpkg/pkgs/brotli_x86-windows/lib/pkgconfig/libbrotlidec.pc
-- Fixing pkgconfig file: C:/Users/Administrator/source/repos/Latency Test/vcpkg_installed/vcpkg/pkgs/brotli_x86-windows/lib/pkgconfig/libbrotlienc.pc
-- Using cached mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using msys root at C:/Users/Administrator/AppData/Local/vcpkg/downloads/tools/msys2/5b9374e6ec2c4e17
-- Fixing pkgconfig file: C:/Users/Administrator/source/repos/Latency Test/vcpkg_installed/vcpkg/pkgs/brotli_x86-windows/debug/lib/pkgconfig/libbrotlicommon.pc
-- Fixing pkgconfig file: C:/Users/Administrator/source/repos/Latency Test/vcpkg_installed/vcpkg/pkgs/brotli_x86-windows/debug/lib/pkgconfig/libbrotlidec.pc
-- Fixing pkgconfig file: C:/Users/Administrator/source/repos/Latency Test/vcpkg_installed/vcpkg/pkgs/brotli_x86-windows/debug/lib/pkgconfig/libbrotlienc.pc
-- Installing: C:/Users/Administrator/source/repos/Latency Test/vcpkg_installed/vcpkg/pkgs/brotli_x86-windows/share/unofficial-brotli/unofficial-brotli-config.cmake
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/Users/Administrator/.dotnet/tools/pwsh.exe -noprofile -executionpolicy Bypass -nologo -file "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/vcpkg/scripts/buildsystems/msbuild/applocal.ps1" -targetBinary "C:/Users/Administrator/source/repos/Latency Test/vcpkg_installed/vcpkg/pkgs/brotli_x86-windows/tools/brotli/brotli.exe" -installedDir "C:/Users/Administrator/source/repos/Latency Test/vcpkg_installed/vcpkg/pkgs/brotli_x86-windows/bin" -verbose
    Working Directory: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/vcpkg
    Error code: -532462766
    See logs for more information:
      C:\Users\Administrator\source\repos\Latency Test\vcpkg_installed\vcpkg\blds\brotli\copy-tool-dependencies-0-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:9 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:41 (z_vcpkg_copy_tool_dependencies_search)
  C:/Users/Administrator/AppData/Local/vcpkg/registries/git-trees/32ea6c4b0d18fa3172ad52147599983acc71d748/portfile.cmake:28 (vcpkg_copy_tool_dependencies)
  scripts/ports.cmake:147 (include)



```
<details><summary>C:\Users\Administrator\source\repos\Latency Test\vcpkg_installed\vcpkg\blds\brotli\copy-tool-dependencies-0-err.log</summary>

```
Unhandled exception. System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'dotnet' with working directory 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\vcpkg'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Microsoft.PowerShell.GlobalTool.Shim.EntryPoint.Main(String[] args)
```
</details>

**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "name": "my-project",
  "version-string": "0.0.1",
  "builtin-baseline": "638b1588be3a265a9c7ad5b212cef72a1cad336a",
  "dependencies": [
    {
      "name": "cpprestsdk",
      "features": []
    }
  ]
}

```
</details>

**Comment by Cheney-W** [comment]
Thank you for submitting this issue. In order to reproduce your problem, could you provide the following information:
1. Are you using the vcpkg that comes with Visual Studio or did you clone it from the vcpkg official website?
2. Have you installed .NET Core or .NET 5/6 runtime/SDK on your system?
