### ISSUE TITLE
[skia] Build error

### ISSUE THREAD

**Issue by stolen-programmer** [microsoft/vcpkg#34880]
Package: skia[core,default-features,gl,harfbuzz,icu]:x64-windows -> 0.38.2

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.37.32825.0
-    vcpkg-tool version: 2023-10-18-27de5b69dac4b6fe8259d283cd4011e6d20a84ce
    vcpkg-scripts version: 51aa78731 2023-11-02 (4 hours ago)

**To Reproduce**

`vcpkg install skia:x64-windows`
**Failure logs**

```
-- Using cached google-skia-canvaskit_-0.38.2.tar.gz.
-- Cleaning sources at D:/work/repos/vcpkg/buildtrees/skia/src/it_-0.38.2-7705ea7844.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/work/repos/vcpkg/downloads/google-skia-canvaskit_-0.38.2.tar.gz
-- Applying patch uwp.patch
-- Applying patch core-opengl32.patch
-- Applying patch disable-dev-test.patch
-- Applying patch support-x86-MSVC-build.patch
-- Using source at D:/work/repos/vcpkg/buildtrees/skia/src/it_-0.38.2-7705ea7844.clean
CMake Warning at ports/skia/skia-functions.cmake:13 (message):
  Dependency abseil-cpp diverges from upstream.  Upstream:
  "https://skia.googlesource.com/external/github.com/abseil/abseil-cpp.git@cb436cf0142b4cbe47aae94223443df7f82e2920",
  Actual:
  "https://skia.googlesource.com/external/github.com/abseil/abseil-cpp.git@c5a424a2a21005660b182516eb7a079cd8021699"
Call Stack (most recent call first):
  ports/skia/portfile.cmake:17 (declare_external_from_git)
  scripts/ports.cmake:168 (include)


CMake Warning at ports/skia/skia-functions.cmake:13 (message):
  Dependency dawn diverges from upstream.  Upstream:
  "https://dawn.googlesource.com/dawn.git@6e25bf7674bbcb1d1e613dc0700c958830950037",
  Actual:
  "https://dawn.googlesource.com/dawn.git@30fa0d8d2ced43e44baa522dd4bd4684b14a3099"
Call Stack (most recent call first):
  ports/skia/portfile.cmake:27 (declare_external_from_git)
  scripts/ports.cmake:168 (include)


CMake Warning at ports/skia/skia-functions.cmake:13 (message):
  Dependency libgifcodec diverges from upstream.  Upstream: Actual:
  "https://skia.googlesource.com/libgifcodec@fd59fa92a0c86788dcdd84d091e1ce81eda06a77"
Call Stack (most recent call first):
  ports/skia/portfile.cmake:42 (declare_external_from_git)
  scripts/ports.cmake:168 (include)


CMake Warning at ports/skia/skia-functions.cmake:13 (message):
  Dependency sfntly diverges from upstream.  Upstream:
  "https://chromium.googlesource.com/external/github.com/googlei18n/sfntly.git@b55ff303ea2f9e26702b514cf6a3196a2e3e2974",
  Actual:
  "https://github.com/googlefonts/sfntly.git@b55ff303ea2f9e26702b514cf6a3196a2e3e2974"
Call Stack (most recent call first):
  ports/skia/portfile.cmake:57 (declare_external_from_git)
  scripts/ports.cmake:168 (include)


CMake Warning at ports/skia/skia-functions.cmake:13 (message):
  Dependency spirv-cross diverges from upstream.  Upstream:
  "https://chromium.googlesource.com/external/github.com/KhronosGroup/SPIRV-Cross@030d0be28c35bafebd20660c112852b1d8c8c6ca",
  Actual:
  "https://chromium.googlesource.com/external/github.com/KhronosGroup/SPIRV-Cross@61c603f3baa5270e04bcfb6acf83c654e3c57679"
Call Stack (most recent call first):
  ports/skia/portfile.cmake:62 (declare_external_from_git)
  scripts/ports.cmake:168 (include)


CMake Warning at ports/skia/skia-functions.cmake:13 (message):
  Dependency spirv-headers diverges from upstream.  Upstream:
  "https://skia.googlesource.com/external/github.com/KhronosGroup/SPIRV-Headers.git@8e2ad27488ed2f87c068c01a8f5e8979f7086405",
  Actual:
  "https://skia.googlesource.com/external/github.com/KhronosGroup/SPIRV-Headers.git@0bcc624926a25a2a273d07877fd25a6ff5ba1cfb"
Call Stack (most recent call first):
  ports/skia/portfile.cmake:67 (declare_external_from_git)
  scripts/ports.cmake:168 (include)


CMake Warning at ports/skia/skia-functions.cmake:13 (message):
  Dependency spirv-tools diverges from upstream.  Upstream:
  "https://skia.googlesource.com/external/github.com/KhronosGroup/SPIRV-Tools.git@93c13345e176f3f8bdb4b07e59c5e3365b3dbf44",
  Actual:
  "https://skia.googlesource.com/external/github.com/KhronosGroup/SPIRV-Tools.git@0073a1fa36f7c52ad3d58059cb5d5de8efa825ad"
Call Stack (most recent call first):
  ports/skia/portfile.cmake:72 (declare_external_from_git)
  scripts/ports.cmake:168 (include)


CMake Warning at ports/skia/skia-functions.cmake:13 (message):
  Dependency tint diverges from upstream.  Upstream: Actual:
  "https://dawn.googlesource.com/tint@200492e32b94f042d9942154fb4fa7f93bb8289a"
Call Stack (most recent call first):
  ports/skia/portfile.cmake:77 (declare_external_from_git)
  scripts/ports.cmake:168 (include)


CMake Warning at ports/skia/skia-functions.cmake:13 (message):
  Dependency vulkan-tools diverges from upstream.  Upstream:
  "https://chromium.googlesource.com/external/github.com/KhronosGroup/Vulkan-Tools@2c83dd6cb2ef710bab843b69776997d6f2c12ba4",
  Actual:
  "https://chromium.googlesource.com/external/github.com/KhronosGroup/Vulkan-Tools@d55c7aaf041af331bee8c22fb448a6ff4c797f73"
Call Stack (most recent call first):
  ports/skia/portfile.cmake:82 (declare_external_from_git)
  scripts/ports.cmake:168 (include)


CMake Warning at ports/skia/skia-functions.cmake:13 (message):
  Dependency wuffs diverges from upstream.  Upstream:
  "https://skia.googlesource.com/external/github.com/google/wuffs-mirror-release-c.git@a0041ac0310b3156b963e2f2bea09245f25ec073",
  Actual:
  "https://skia.googlesource.com/external/github.com/google/wuffs-mirror-release-c.git@e3f919ccfe3ef542cfc983a82146070258fb57f8"
Call Stack (most recent call first):
  ports/skia/portfile.cmake:87 (declare_external_from_git)
  scripts/ports.cmake:168 (include)


-- Creating third_party/externals/dng_sdk
-- Using cached D:/work/repos/vcpkg/downloads/skia-c8d0c9b1d16bfda56f15165d39e0ffa360a11123.tar.gz
-- Extracting source D:/work/repos/vcpkg/downloads/skia-c8d0c9b1d16bfda56f15165d39e0ffa360a11123.tar.gz
-- Using source at D:/work/repos/vcpkg/buildtrees/skia/src/a360a11123-3e98e4208e.clean
-- Creating third_party/externals/libgifcodec
-- Using cached D:/work/repos/vcpkg/downloads/skia-fd59fa92a0c86788dcdd84d091e1ce81eda06a77.tar.gz
-- Extracting source D:/work/repos/vcpkg/downloads/skia-fd59fa92a0c86788dcdd84d091e1ce81eda06a77.tar.gz
-- Using source at D:/work/repos/vcpkg/buildtrees/skia/src/81eda06a77-b5a19f0dc7.clean
-- Creating third_party/externals/piex
-- Using cached D:/work/repos/vcpkg/downloads/skia-bb217acdca1cc0c16b704669dd6f91a1b509c406.tar.gz
-- Extracting source D:/work/repos/vcpkg/downloads/skia-bb217acdca1cc0c16b704669dd6f91a1b509c406.tar.gz
-- Using source at D:/work/repos/vcpkg/buildtrees/skia/src/a1b509c406-84c7e7ac21.clean
-- Creating third_party/externals/sfntly
-- Using cached D:/work/repos/vcpkg/downloads/skia-b55ff303ea2f9e26702b514cf6a3196a2e3e2974.tar.gz
-- Extracting source D:/work/repos/vcpkg/downloads/skia-b55ff303ea2f9e26702b514cf6a3196a2e3e2974.tar.gz
-- Using source at D:/work/repos/vcpkg/buildtrees/skia/src/6a2e3e2974-0a8350d725.clean
-- Creating third_party/externals/wuffs
-- Using cached D:/work/repos/vcpkg/downloads/skia-e3f919ccfe3ef542cfc983a82146070258fb57f8.tar.gz
-- Extracting source D:/work/repos/vcpkg/downloads/skia-e3f919ccfe3ef542cfc983a82146070258fb57f8.tar.gz
-- Using source at D:/work/repos/vcpkg/buildtrees/skia/src/0258fb57f8-69c6ce6bfb.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Generating build (x64-windows-dbg)...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: D:/work/repos/vcpkg/installed/x64-windows/tools/gn/gn.exe gen D:/work/repos/vcpkg/buildtrees/skia/x64-windows-dbg "--args=target_cpu=\"x64\" target_os=\"win\" is_component_build=true skia_use_fontconfig=false skia_use_freetype=false skia_use_harfbuzz=true skia_use_icu=true skia_use_gl=true win_vc=\"D:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\" skia_use_lua=false skia_enable_tools=false skia_enable_spirv_validation=false is_debug=true     extra_cflags_c=[\"-nologo\",\"-DWIN32\",\"-D_WINDOWS\",\"-W3\",\"-utf-8\",\"-MP\",\"-D_DEBUG\",\"-MDd\",\"-Z7\",\"-Ob0\",\"-Od\",\"-RTC1\"]     extra_cflags_cc=[\"-nologo\",\"-DWIN32\",\"-D_WINDOWS\",\"-W3\",\"-utf-8\",\"-GR\",\"-EHsc\",\"-MP\",\"-D_DEBUG\",\"-MDd\",\"-Z7\",\"-Ob0\",\"-Od\",\"-RTC1\"]"
    Working Directory: D:/work/repos/vcpkg/buildtrees/skia/src/it_-0.38.2-7705ea7844.clean
    Error code: 1
    See logs for more information:
      D:\work\repos\vcpkg\buildtrees\skia\generate-x64-windows-dbg-out.log
      D:\work\repos\vcpkg\buildtrees\skia\generate-x64-windows-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-gn/vcpkg_gn_configure.cmake:11 (vcpkg_execute_required_process)
  installed/x64-windows/share/vcpkg-gn/vcpkg_gn_configure.cmake:35 (z_vcpkg_gn_configure_generate)
  ports/skia/portfile.cmake:286 (vcpkg_gn_configure)
  scripts/ports.cmake:168 (include)



```
<details><summary>D:\work\repos\vcpkg\buildtrees\skia\generate-x64-windows-dbg-out.log</summary>

```
ERROR at //gn/BUILDCONFIG.gn:154:23: Script returned non-zero exit code.
    win_sdk_version = exec_script("//gn/highest_version_dir.py",
                      ^----------
Current dir: D:/work/repos/vcpkg/buildtrees/skia/x64-windows-dbg/
Command: D:/work/repos/vcpkg/downloads/tools/python/python-3.11.5-x64/python.exe D:/work/repos/vcpkg/buildtrees/skia/src/it_-0.38.2-7705ea7844.clean/gn/highest_version_dir.py "C:/Program Files (x86)/Windows Kits/10/Include" "[0-9]{2}\.[0-9]\.[0-9]{5}\.[0-9]"
Returned 1.
```
</details>
<details><summary>D:\work\repos\vcpkg\buildtrees\skia\generate-x64-windows-dbg-err.log</summary>

```
Traceback (most recent call last):
  File "D:\work\repos\vcpkg\buildtrees\skia\src\it_-0.38.2-7705ea7844.clean\gn\highest_version_dir.py", line 17, in <module>
    print(sorted(filter(regex.match, os.listdir(dirpath)))[-1])
                                     ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] ϵͳ Ҳ   ָ    ·    : 'C:/Program Files (x86)/Windows Kits/10/Include'
```
</details>

my win 10 sdk include  D:\Windows Kits\10\Include

**Comment by dg0yt** [comment]
Please look at https://github.com/microsoft/vcpkg/pull/34787/files. Try to restore the `disable-msvc-env-setup.patch` instead of `support-x86-MSVC-build.patch`.

**Comment by jimwang118** [comment]
I used the same version of `vcpkg` locally as you and did not reproduce this issue.
![image](https://github.com/microsoft/vcpkg/assets/122244446/ef148496-5c6b-4dac-b63c-15d9d74a835d)

**Comment by stolen-programmer** [comment]
My Windows SDK is installed on a non default path
D:\work\repos\vcpkg\buildtrees\skia\src\it_-0.38.2-7705ea7844.clean\gn\BUILDCONFIG.gn 
![image](https://github.com/microsoft/vcpkg/assets/23734345/3e505344-9f2b-4750-a56c-0067294f8a58)

**Comment by stolen-programmer** [comment]
I'm sorry, but I'm not sure about the working mechanism of gn and vcpkg. After making changes on my end, they were overwritten

**Comment by jimwang118** [comment]
Can you let the `win SDK` install to the default location? The error occurs because the corresponding file cannot be found.

**Comment by stolen-programmer** [comment]
Okay, I'll try reinstalling vs

But this path should not be written dead

**Comment by dg0yt** [comment]
> Please look at https://github.com/microsoft/vcpkg/pull/34787/files. Try to restore the `disable-msvc-env-setup.patch` instead of `support-x86-MSVC-build.patch`.

Please try #34951. Currently it has only this change, so it can be tested in isolation before I can look at the other regressions.

**Comment by stolen-programmer** [comment]
I pulled the latest warehouse and successfully built Skia

**Comment by stolen-programmer** [comment]
Unfortunately, I even reinstalled the operating system to reinstall VS

**Comment by Houseton** [comment]
Hello, I had a similar issue but not quite the same.... trying to install skia (via DevCMD) and found this work around 
The error is the same in the 2nd log of the poster
Workaround: (https://stackoverflow.com/questions/75859981/building-skia4delphi-with-powershell-error)

I'm not a programmer so I don't know how to list everything but
- Host: Windows 11 Version 23H2 (OS Build 22631.3447)
- Compiler: MS Visual Studio Community 2022?

My error:
```
C:\Compile\skia>gn gen out/Release-x64 --args="is_debug=false is_official_build=true skia_use_system_expat=false skia_use_system_icu=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false skia_use_sfntly=false skia_use_freetype=true skia_use_harfbuzz=true skia_pdf_subset_harfbuzz=true skia_use_system_freetype2=false skia_use_system_harfbuzz=false target_cpu=""x64"" cc=""clang"" cxx=""clang++"" clang_win=""C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\llvm"" win_vc=""C:\Program Files\Microsoft Visual Studio\2022\Community\VC"" extra_cflags=[""-MT""]"
Traceback (most recent call last):
  File "C:\Compile\skia\gn\highest_version_dir.py", line 17, in <module>
    print(sorted(filter(regex.match, os.listdir(dirpath)))[-1])
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
ERROR at //gn/BUILDCONFIG.gn:155:25: Script returned non-zero exit code.
    clang_win_version = exec_script("//gn/highest_version_dir.py",
                        ^----------
Current dir: C:/Compile/skia/out/Release-x64/
Command: C:/Compile/deps/depot_tools/bootstrap-2@3_11_8_chromium_35_bin/python3/bin/python3.exe C:/Compile/skia/gn/highest_version_dir.py "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\llvm/lib/clang" "[0-9]+\.[0-9]+\.[0-9]+"
Returned 1.
```

The work around was going into skia/gn/BUILDCONFIG.gn and changing this:
```
if (clang_win != "" && clang_win_version == "")
    clang_win_version = exec_script("//gn/highest_version_dir.py",
                                    [
                                      "$clang_win/lib/clang",
                                      "[0-9]+\.[0-9]+\.[0-9]+",
                                    ],
                                    "trim string")
```
to this:
```
if (clang_win != "" && clang_win_version == "") {
    clang_win_version = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\llvm"
```
Output:
```
C:\Compile\skia>gn gen out/Release-x64 --args="is_debug=false is_official_build=true skia_use_system_expat=false skia_use_system_icu=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false skia_use_sfntly=false skia_use_freetype=true skia_use_harfbuzz=true skia_pdf_subset_harfbuzz=true skia_use_system_freetype2=false skia_use_system_harfbuzz=false target_cpu=""x64"" cc=""clang"" cxx=""clang++"" clang_win=""C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\llvm"" win_vc=""C:\Program Files\Microsoft Visual Studio\2022\Community\VC"" extra_cflags=[""-MT""]"
Done. Made 98 targets from 54 files in 345ms
```

**Comment by dg0yt** [comment]
@Houseton No.

**Comment by Houseton** [comment]
@dg0yt Sorry then, googling the error came to this closed issue. Remove my comment if needed.
