### ISSUE TITLE
colmap

### ISSUE THREAD

**Issue by XueXiJinBuShangShang** [microsoft/vcpkg#35294]
### Library name

colmap

### Source repository URL

bfgh

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

F20231124 10:07:41.138367  4620 bundle_adjustment.cc:302] Check failed: solver_options.IsValid(&solver_error) Can't use SPARSE_SCHUR with Solver::Options::sparse_linear_algebra_library_type = NO_SPARSE.
*** Check failure stack trace: ***
    @   00007FFEFAC372AA  google::LogMessage::Flush
    @   00007FFEFAC35979  google::LogMessageFatal::~LogMessageFatal
    @   00007FF64E017913  (unknown)
    @   00007FF64E01D010  (unknown)
    @   00007FF64E023D63  (unknown)
    @   00007FF64E024C41  (unknown)
    @   00007FF64E02606C  (unknown)
    @   00007FF64E0265CF  (unknown)
    @   00007FF64DFADC80  (unknown)
    @   00007FF64DFAC34F  (unknown)
    @   00007FFF11B61BB2  _configthreadlocale
    @   00007FFF13577604  BaseThreadInitThunk
    @   00007FFF144826A1  RtlUserThreadStart
cp: cannot stat 'datasets/lego_ds2/sparse/0/*.bin': No such file or directory
projects/scripts/run_colmap.sh: line 34: [: too many arguments
F20231124 10:07:46.531155 15284 reconstruction.cc:809] cameras, images, points3D files do not exist at datasets/lego_ds2/sparse
*** Check failure stack trace: ***
    @   00007FFEFAC372AA  google::LogMessage::Flush
    @   00007FFEFAC35979  google::LogMessageFatal::~LogMessageFatal
    @   00007FF64DF8D813  (unknown)
    @   00007FF64DF22D2A  (unknown)
    @   00007FF64DF0DD56  (unknown)
    @   00007FF64DF5454B  (unknown)
    @   00007FF64E5620D0  (unknown)
    @   00007FFF13577604  BaseThreadInitThunk
    @   00007FFF144826A1  RtlUserThreadStart
Traceback (most recent call last):
  File "projects/scripts/convert_data_to_json.py", line 226, in <module>
    data_to_json(args)
  File "projects/scripts/convert_data_to_json.py", line 191, in data_to_json
    cameras, images, points3D = read_model(os.path.join(args.data_dir, "sparse"), ext=".bin")
  File "H:\colmap\scripts\python\read_write_model.py", line 505, in read_model
    cameras = read_cameras_binary(os.path.join(path, "cameras" + ext))
  File "H:\third_party\colmap\scripts\python\read_write_model.py", line 143, in read_cameras_binary
    with open(path_to_model_file, "rb") as fid:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/lego_ds2\\sparse\\cameras.bin'
Traceback (most recent call last):
  File "projects/scripts/generate_config.py", line 83, in <module>
    generate_config(args)
  File "projects/scripts/generate_config.py", line 30, in generate_config
    num_images = len(os.listdir(os.path.join(args.data_dir, "images")))
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'datasets/lego_ds2\\images'

**Comment by Cheney-W** [comment]
There is a `colmap` port in vcpkg, is it what you expected?
https://github.com/microsoft/vcpkg/tree/master/ports/colmap

**Comment by XueXiJinBuShangShang** [comment]
> There is a `colmap` port in vcpkg, is it what you expected? https://github.com/microsoft/vcpkg/tree/master/ports/colmap
colmap is ok.    But my issue ：
Sometimes the use is completed smoothly, sometimes it is not. Based on the data, it may be possible that the internal calculation results do not meet the conditions and an error will be reported

**Comment by Cheney-W** [comment]
So what is the new port you want to add? Is there a specific download path?
