### ISSUE TITLE
[libsystemd] Build error on x64-linux

### ISSUE THREAD

**Issue by ArthurChan2018** [microsoft/vcpkg#35553]
Package: libsystemd:x64-linux -> 254

**Host Environment**

- Host: x64-linux
- Compiler: GNU 11.4.0
-    vcpkg-tool version: 2023-11-16-4c1df40a3c5c5e18de299a99e9accb03c2a82e1e
    vcpkg-scripts version: 45f6e57d3 2023-12-06 (26 小时前)

**To Reproduce**

`./vcpkg install wxwidgets:x64-linux`
**Failure logs**

```
-- Using cached systemd-systemd-v254.tar.gz.
-- Cleaning sources at Path-to-vcpkg-install-dir/buildtrees/libsystemd/src/v254-832da4078b.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source Path-to-vcpkg-install-dir/downloads/systemd-systemd-v254.tar.gz
-- Applying patch pkgconfig.patch
-- Using source at Path-to-vcpkg-install-dir/buildtrees/libsystemd/src/v254-832da4078b.clean
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Configuring x64-linux-dbg
-- Configuring x64-linux-dbg done
-- Configuring x64-linux-rel
-- Configuring x64-linux-rel done
-- Building (x64-linux-dbg)...
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: Path-to-vcpkg-install-dir/downloads/tools/ninja/1.10.2-linux/ninja -C Path-to-vcpkg-install-dir/buildtrees/libsystemd/x64-linux-dbg libsystemd.a devel
    Working Directory: Path-to-vcpkg-install-dir/buildtrees/libsystemd/src/v254-832da4078b.clean
    See logs for more information:
      Path-to-vcpkg-install-dir/buildtrees/libsystemd/build-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_ninja.cmake:3 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_build_ninja.cmake:24 (z_vcpkg_build_ninja_build)
  ports/libsystemd/portfile.cmake:24 (vcpkg_build_ninja)
  scripts/ports.cmake:170 (include)



```
<details><summary>Path-to-vcpkg-install-dir/buildtrees/libsystemd/build-x64-linux-dbg-out.log</summary>

```
ninja: Entering directory `Path-to-vcpkg-install-dir/buildtrees/libsystemd/x64-linux-dbg'
[1/191] Generating src/basic/filesystems-gperf.h with a custom command
[2/191] Generating version.h with a custom command
[3/191] Generating src/basic/filesystem-switch-case.h with a custom command (wrapped by meson to capture output)
[4/191] Generating src/basic/errno-list.txt with a custom command (wrapped by meson to capture output)
[5/191] Generating src/libsystemd/audit_type-list.txt with a custom command (wrapped by meson to capture output)
[6/191] Generating src/basic/arphrd-list.txt with a custom command (wrapped by meson to capture output)
[7/191] Generating src/basic/cap-list.txt with a custom command (wrapped by meson to capture output)
[8/191] Generating src/basic/filesystem-list.h with a custom command (wrapped by meson to capture output)
[9/191] Generating src/basic/af-list.txt with a custom command (wrapped by meson to capture output)
[10/191] Generating src/core/systemd.pc with a custom command
FAILED: src/core/systemd.pc 
Path-to-vcpkg-install-dir/buildtrees/libsystemd/src/v254-832da4078b.clean/tools/meson-render-jinja2.py config.h version.h ../src/v254-832da4078b.clean/src/core/systemd.pc.in src/core/systemd.pc
Traceback (most recent call last):
  File "Path-to-vcpkg-install-dir/buildtrees/libsystemd/src/v254-832da4078b.clean/tools/meson-render-jinja2.py", line 9, in <module>
    import jinja2
ModuleNotFoundError: No module named 'jinja2'
[11/191] Generating src/udev/udev.pc with a custom command
FAILED: src/udev/udev.pc 
Path-to-vcpkg-install-dir/buildtrees/libsystemd/src/v254-832da4078b.clean/tools/meson-render-jinja2.py config.h version.h ../src/v254-832da4078b.clean/src/udev/udev.pc.in src/udev/udev.pc
Traceback (most recent call last):
  File "Path-to-vcpkg-install-dir/buildtrees/libsystemd/src/v254-832da4078b.clean/tools/meson-render-jinja2.py", line 9, in <module>
    import jinja2
ModuleNotFoundError: No module named 'jinja2'
[12/191] Generating src/libudev/libudev.pc with a custom command
FAILED: src/libudev/libudev.pc 
Path-to-vcpkg-install-dir/buildtrees/libsystemd/src/v254-832da4078b.clean/tools/meson-render-jinja2.py config.h version.h ../src/v254-832da4078b.clean/src/libudev/libudev.pc.in src/libudev/libudev.pc
Traceback (most recent call last):
  File "Path-to-vcpkg-install-dir/buildtrees/libsystemd/src/v254-832da4078b.clean/tools/meson-render-jinja2.py", line 9, in <module>
    import jinja2
ModuleNotFoundError: No module named 'jinja2'
[13/191] Generating src/libsystemd/libsystemd.pc with a custom command
FAILED: src/libsystemd/libsystemd.pc 
Path-to-vcpkg-install-dir/buildtrees/libsystemd/src/v254-832da4078b.clean/tools/meson-render-jinja2.py config.h version.h ../src/v254-832da4078b.clean/src/libsystemd/libsystemd.pc.in src/libsystemd/libsystemd.pc
Traceback (most recent call last):
  File "Path-to-vcpkg-install-dir/buildtrees/libsystemd/src/v254-832da4078b.clean/tools/meson-render-jinja2.py", line 9, in <module>
    import jinja2
ModuleNotFoundError: No module named 'jinja2'
[14/191] Generating src/basic/errno-to-name.h with a custom command (wrapped by meson to capture output)
[15/191] Generating src/basic/errno-from-name.gperf with a custom command (wrapped by meson to capture output)
[16/191] Generating src/basic/arphrd-to-name.h with a custom command (wrapped by meson to capture output)
[17/191] Generating src/basic/arphrd-from-name.gperf with a custom command (wrapped by meson to capture output)
[18/191] Generating src/basic/cap-from-name.gperf with a custom command (wrapped by meson to capture output)
[19/191] Generating src/basic/af-from-name.gperf with a custom command (wrapped by meson to capture output)
ninja: build stopped: subcommand failed.
```
</details>

**Comment by ArthurChan2018** [comment]
I tried on a virtual ubuntu 22.04 and got same error

**Comment by jimwang118** [comment]
You use the following command to install jinja2, and then reinstall it.
`apt-get install python-jinja2`

**Comment by ArthurChan2018** [comment]
Thanks a lot, it worked.
I have virtual python environment activated and it has jinja2, and I think it should work but not. Now, I deactivate the virtual env and install python-jinja2 package, it worked.
