### ISSUE TITLE
[nss] Build error on x64-windows

### ISSUE THREAD

**Issue by jngb** [microsoft/vcpkg#35946]
Package: nss:x64-windows@3.87#2

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.38.33133.0
-    vcpkg-tool version: 2023-12-12-1c9ec1978a6b0c2b39c9e9554a96e3e275f7556e
    vcpkg-scripts version: f1c6efe 2023-12-24 (7 days ago)

**To Reproduce**

`vcpkg install nss`
**Failure logs**

```
-- Using cached nss-3.87.tar.gz.
-- Cleaning sources at K:/source/vcpkg/buildtrees/nss/src/3.87-229a607b1a.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source K:/source/vcpkg/downloads/nss-3.87.tar.gz
-- Applying patch 01-nspr-no-lib-prefix.patch
-- Applying patch 02-gen-debug-info-for-release.patch
-- Using source at K:/source/vcpkg/buildtrees/nss/src/3.87-229a607b1a.clean
-- Found bash: K:/source/vcpkg/installed/x64-windows/tools/mozbuild/msys2/usr/bin/bash.exe
-- Found python: K:/source/vcpkg/installed/x64-windows/tools/mozbuild/python3/python.exe
-- Using headers from: /k/source/vcpkg/installed/x64-windows/include arch: x64
-- Using libraries from: /k/source/vcpkg/installed/x64-windows/lib arch: x64
-- Found gyp-next: K:/source/vcpkg/installed/x64-windows/tools/gyp-next/gyp.bat
-- Found external ninja('1.11.0').
-- Copying sources to debug build dir ...
-- Building debug ...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: K:/source/vcpkg/installed/x64-windows/tools/mozbuild/msys2/usr/bin/env.exe "VSPATH=/c/Program Files/Microsoft Visual Studio/2022/Professional/" "GYP_MSVS_OVERRIDE_PATH=/c/Program Files/Microsoft Visual Studio/2022/Professional/" GYP_MSVS_VERSION=2022 bash ./build.sh -v -g --disable-tests --with-nspr=/k/source/vcpkg/installed/x64-windows/include/nspr:/k/source/vcpkg/installed/x64-windows/lib --system-sqlite -Dsign_libs=0 --target=x64 --msvc
    Working Directory: K:/source/vcpkg/buildtrees/nss/x64-windows-dbg/nss
    Error code: 1
    See logs for more information:
      K:\source\vcpkg\buildtrees\nss\build-x64-windows-out.log

Call Stack (most recent call first):
  ports/nss/portfile.cmake:138 (vcpkg_execute_required_process)
  scripts/ports.cmake:170 (include)



```
<details><summary>K:\source\vcpkg\buildtrees\nss\build-x64-windows-out.log</summary>

```
Assuming env setup is already done.
VSPATH=/c/Program Files/Microsoft Visual Studio/2022/Professional/
run_scanbuild gyp -f ninja --depth=/k/source/vcpkg/buildtrees/nss/x64-windows-dbg/nss --generator-output=. -Ddisable_tests=1 -Dnspr_include_dir=/k/source/vcpkg/installed/x64-windows/include/nspr -Dnspr_lib_dir=/k/source/vcpkg/installed/x64-windows/lib -Duse_system_sqlite=1 -Dsign_libs=0 -Dtarget_arch=x64 -Denable_sslkeylogfile=1 -Dnss_dist_dir=/k/source/vcpkg/buildtrees/nss/x64-windows-dbg/dist -Dnss_dist_obj_dir=/k/source/vcpkg/buildtrees/nss/x64-windows-dbg/dist/Debug /k/source/vcpkg/buildtrees/nss/x64-windows-dbg/nss/nss.gyp
ninja: Entering directory `K:/source/vcpkg/buildtrees/nss/x64-windows-dbg/nss/out/Debug'
[1/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\softoken\softokn_static.padbuf.obj.rsp /c ..\..\lib\softoken\padbuf.c /Foobj\lib\softoken\softokn_static.padbuf.obj /Fdobj\lib\softoken\softokn_static.c.pdb 
[2/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\softoken\softokn_static.jpakesftk.obj.rsp /c ..\..\lib\softoken\jpakesftk.c /Foobj\lib\softoken\softokn_static.jpakesftk.obj /Fdobj\lib\softoken\softokn_static.c.pdb 
[3/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\softoken\softokn_static.lowkey.obj.rsp /c ..\..\lib\softoken\lowkey.c /Foobj\lib\softoken\softokn_static.lowkey.obj /Fdobj\lib\softoken\softokn_static.c.pdb 
[4/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\softoken\softokn_static.lowpbe.obj.rsp /c ..\..\lib\softoken\lowpbe.c /Foobj\lib\softoken\softokn_static.lowpbe.obj /Fdobj\lib\softoken\softokn_static.c.pdb 
[5/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\softoken\softokn_static.kbkdf.obj.rsp /c ..\..\lib\softoken\kbkdf.c /Foobj\lib\softoken\softokn_static.kbkdf.obj /Fdobj\lib\softoken\softokn_static.c.pdb 
[6/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\softoken\softokn_static.fipstokn.obj.rsp /c ..\..\lib\softoken\fipstokn.c /Foobj\lib\softoken\softokn_static.fipstokn.obj /Fdobj\lib\softoken\softokn_static.c.pdb 
[7/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\softoken\softokn_static.sftkdhverify.obj.rsp /c ..\..\lib\softoken\sftkdhverify.c /Foobj\lib\softoken\softokn_static.sftkdhverify.obj /Fdobj\lib\softoken\softokn_static.c.pdb 
[8/350] K:\source\vcpkg\installed\x64-windows\tools\mozbuild\python3\python.exe gyp-win-tool link-wrapper environment.x64 False lib.exe /nologo /ignore:4221 /OUT:freebl_static.lib @freebl_static.lib.rsp
[9/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\softoken\softokn_static.pkcs11u.obj.rsp /c ..\..\lib\softoken\pkcs11u.c /Foobj\lib\softoken\softokn_static.pkcs11u.obj /Fdobj\lib\softoken\softokn_static.c.pdb 
[10/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\softoken\softokn_static.sftkhmac.obj.rsp /c ..\..\lib\softoken\sftkhmac.c /Foobj\lib\softoken\softokn_static.sftkhmac.obj /Fdobj\lib\softoken\softokn_static.c.pdb 
[11/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\softoken\softokn_static.softkver.obj.rsp /c ..\..\lib\softoken\softkver.c /Foobj\lib\softoken\softokn_static.softkver.obj /Fdobj\lib\softoken\softokn_static.c.pdb 
[12/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\softoken\softokn_static.pkcs11c.obj.rsp /c ..\..\lib\softoken\pkcs11c.c /Foobj\lib\softoken\softokn_static.pkcs11c.obj /Fdobj\lib\softoken\softokn_static.c.pdb 
[13/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\softoken\softokn_static.sftkpwd.obj.rsp /c ..\..\lib\softoken\sftkpwd.c /Foobj\lib\softoken\softokn_static.sftkpwd.obj /Fdobj\lib\softoken\softokn_static.c.pdb 
[14/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\softoken\softokn_static.sftkpars.obj.rsp /c ..\..\lib\softoken\sftkpars.c /Foobj\lib\softoken\softokn_static.sftkpars.obj /Fdobj\lib\softoken\softokn_static.c.pdb 
[15/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\softoken\softokn_static.sftkike.obj.rsp /c ..\..\lib\softoken\sftkike.c /Foobj\lib\softoken\softokn_static.sftkike.obj /Fdobj\lib\softoken\softokn_static.c.pdb 
[16/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\softoken\softokn_static.pkcs11.obj.rsp /c ..\..\lib\softoken\pkcs11.c /Foobj\lib\softoken\softokn_static.pkcs11.obj /Fdobj\lib\softoken\softokn_static.c.pdb 
[17/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\softoken\softokn_static.sftkmessage.obj.rsp /c ..\..\lib\softoken\sftkmessage.c /Foobj\lib\softoken\softokn_static.sftkmessage.obj /Fdobj\lib\softoken\softokn_static.c.pdb 
[18/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\softoken\softokn_static.tlsprf.obj.rsp /c ..\..\lib\softoken\tlsprf.c /Foobj\lib\softoken\softokn_static.tlsprf.obj /Fdobj\lib\softoken\softokn_static.c.pdb 
[19/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\pk11wrap\pk11wrap_static.dev3hack.obj.rsp /c ..\..\lib\pk11wrap\dev3hack.c /Foobj\lib\pk11wrap\pk11wrap_static.dev3hack.obj /Fdobj\lib\pk11wrap\pk11wrap_static.c.pdb 
[20/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\pk11wrap\pk11wrap_static.pk11auth.obj.rsp /c ..\..\lib\pk11wrap\pk11auth.c /Foobj\lib\pk11wrap\pk11wrap_static.pk11auth.obj /Fdobj\lib\pk11wrap\pk11wrap_static.c.pdb 
[21/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\pk11wrap\pk11wrap_static.pk11cert.obj.rsp /c ..\..\lib\pk11wrap\pk11cert.c /Foobj\lib\pk11wrap\pk11wrap_static.pk11cert.obj /Fdobj\lib\pk11wrap\pk11wrap_static.c.pdb 
[22/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\pk11wrap\pk11wrap_static.pk11akey.obj.rsp /c ..\..\lib\pk11wrap\pk11akey.c /Foobj\lib\pk11wrap\pk11wrap_static.pk11akey.obj /Fdobj\lib\pk11wrap\pk11wrap_static.c.pdb 
[23/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\softoken\softokn_static.sdb.obj.rsp /c ..\..\lib\softoken\sdb.c /Foobj\lib\softoken\softokn_static.sdb.obj /Fdobj\lib\softoken\softokn_static.c.pdb 
[24/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\softoken\softokn_static.sftkdb.obj.rsp /c ..\..\lib\softoken\sftkdb.c /Foobj\lib\softoken\softokn_static.sftkdb.obj /Fdobj\lib\softoken\softokn_static.c.pdb 
[25/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\pk11wrap\pk11wrap_static.pk11err.obj.rsp /c ..\..\lib\pk11wrap\pk11err.c /Foobj\lib\pk11wrap\pk11wrap_static.pk11err.obj /Fdobj\lib\pk11wrap\pk11wrap_static.c.pdb 
[26/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\pk11wrap\pk11wrap_static.pk11obj.obj.rsp /c ..\..\lib\pk11wrap\pk11obj.c /Foobj\lib\pk11wrap\pk11wrap_static.pk11obj.obj /Fdobj\lib\pk11wrap\pk11wrap_static.c.pdb 
[27/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\pk11wrap\pk11wrap_static.pk11cxt.obj.rsp /c ..\..\lib\pk11wrap\pk11cxt.c /Foobj\lib\pk11wrap\pk11wrap_static.pk11cxt.obj /Fdobj\lib\pk11wrap\pk11wrap_static.c.pdb 
[28/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\pk11wrap\pk11wrap_static.pk11mech.obj.rsp /c ..\..\lib\pk11wrap\pk11mech.c /Foobj\lib\pk11wrap\pk11wrap_static.pk11mech.obj /Fdobj\lib\pk11wrap\pk11wrap_static.c.pdb 
[29/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\pk11wrap\pk11wrap_static.pk11pars.obj.rsp /c ..\..\lib\pk11wrap\pk11pars.c /Foobj\lib\pk11wrap\pk11wrap_static.pk11pars.obj /Fdobj\lib\pk11wrap\pk11wrap_static.c.pdb 
[30/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\pk11wrap\pk11wrap_static.pk11list.obj.rsp /c ..\..\lib\pk11wrap\pk11list.c /Foobj\lib\pk11wrap\pk11wrap_static.pk11list.obj /Fdobj\lib\pk11wrap\pk11wrap_static.c.pdb 
[31/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\pk11wrap\pk11wrap_static.pk11nobj.obj.rsp /c ..\..\lib\pk11wrap\pk11nobj.c /Foobj\lib\pk11wrap\pk11wrap_static.pk11nobj.obj /Fdobj\lib\pk11wrap\pk11wrap_static.c.pdb 
[32/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\pk11wrap\pk11wrap_static.pk11hpke.obj.rsp /c ..\..\lib\pk11wrap\pk11hpke.c /Foobj\lib\pk11wrap\pk11wrap_static.pk11hpke.obj /Fdobj\lib\pk11wrap\pk11wrap_static.c.pdb 
[33/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\pk11wrap\pk11wrap_static.pk11load.obj.rsp /c ..\..\lib\pk11wrap\pk11load.c /Foobj\lib\pk11wrap\pk11wrap_static.pk11load.obj /Fdobj\lib\pk11wrap\pk11wrap_static.c.pdb 
[34/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\pk11wrap\pk11wrap_static.pk11merge.obj.rsp /c ..\..\lib\pk11wrap\pk11merge.c /Foobj\lib\pk11wrap\pk11wrap_static.pk11merge.obj /Fdobj\lib\pk11wrap\pk11wrap_static.c.pdb 
[35/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\pk11wrap\pk11wrap_static.pk11kea.obj.rsp /c ..\..\lib\pk11wrap\pk11kea.c /Foobj\lib\pk11wrap\pk11wrap_static.pk11kea.obj /Fdobj\lib\pk11wrap\pk11wrap_static.c.pdb 
[36/350] K:\source\vcpkg\installed\x64-windows\tools\mozbuild\python3\python.exe gyp-win-tool stamp obj\lib\freebl\freebl3.compile_depends.stamp
[37/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\softoken\softokn.fipstest.obj.rsp /c ..\..\lib\softoken\fipstest.c /Foobj\lib\softoken\softokn.fipstest.obj /Fdobj\lib\softoken\softokn.c.pdb 
[38/350] K:\source\vcpkg\installed\x64-windows\tools\mozbuild\python3\python.exe gyp-win-tool link-wrapper environment.x64 False lib.exe /nologo /ignore:4221 /OUT:softokn_static.lib @softokn_static.lib.rsp
[39/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\freebl\freebl.loader.obj.rsp /c ..\..\lib\freebl\loader.c /Foobj\lib\freebl\freebl.loader.obj /Fdobj\lib\freebl\freebl.c.pdb 
[40/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\pk11wrap\pk11wrap_static.pk11sdr.obj.rsp /c ..\..\lib\pk11wrap\pk11sdr.c /Foobj\lib\pk11wrap\pk11wrap_static.pk11sdr.obj /Fdobj\lib\pk11wrap\pk11wrap_static.c.pdb 
[41/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\pk11wrap\pk11wrap_static.pk11pbe.obj.rsp /c ..\..\lib\pk11wrap\pk11pbe.c /Foobj\lib\pk11wrap\pk11wrap_static.pk11pbe.obj /Fdobj\lib\pk11wrap\pk11wrap_static.c.pdb 
[42/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\softoken\softokn.fipsaudt.obj.rsp /c ..\..\lib\softoken\fipsaudt.c /Foobj\lib\softoken\softokn.fipsaudt.obj /Fdobj\lib\softoken\softokn.c.pdb 
[43/350] K:\source\vcpkg\installed\x64-windows\tools\mozbuild\python3\python.exe gyp-win-tool link-with-manifests environment.x64 True K:/source/vcpkg/buildtrees/nss/x64-windows-dbg/dist/Debug/lib\nssutil3.dll "K:\source\vcpkg\installed\x64-windows\tools\mozbuild\python3\python.exe gyp-win-tool link-wrapper environment.x64 False link.exe /nologo /IMPLIB:K:/source/vcpkg/buildtrees/nss/x64-windows-dbg/dist/Debug/lib\nssutil3.dll.lib /DLL /OUT:K:/source/vcpkg/buildtrees/nss/x64-windows-dbg/dist/Debug/lib\nssutil3.dll @K:/source/vcpkg/buildtrees/nss/x64-windows-dbg/dist/Debug/lib\nssutil3.dll.rsp" 2 mt.exe rc.exe "obj\lib\util\nssutil3.nssutil3.dll.intermediate.manifest" obj\lib\util\nssutil3.nssutil3.dll.generated.manifest
FAILED: K:/source/vcpkg/buildtrees/nss/x64-windows-dbg/dist/Debug/lib/nssutil3.dll K:/source/vcpkg/buildtrees/nss/x64-windows-dbg/dist/Debug/lib/nssutil3.dll.lib K:/source/vcpkg/buildtrees/nss/x64-windows-dbg/dist/Debug/lib/nssutil3.dll.pdb 
K:\source\vcpkg\installed\x64-windows\tools\mozbuild\python3\python.exe gyp-win-tool link-with-manifests environment.x64 True K:/source/vcpkg/buildtrees/nss/x64-windows-dbg/dist/Debug/lib\nssutil3.dll "K:\source\vcpkg\installed\x64-windows\tools\mozbuild\python3\python.exe gyp-win-tool link-wrapper environment.x64 False link.exe /nologo /IMPLIB:K:/source/vcpkg/buildtrees/nss/x64-windows-dbg/dist/Debug/lib\nssutil3.dll.lib /DLL /OUT:K:/source/vcpkg/buildtrees/nss/x64-windows-dbg/dist/Debug/lib\nssutil3.dll @K:/source/vcpkg/buildtrees/nss/x64-windows-dbg/dist/Debug/lib\nssutil3.dll.rsp" 2 mt.exe rc.exe "obj\lib\util\nssutil3.nssutil3.dll.intermediate.manifest" obj\lib\util\nssutil3.nssutil3.dll.generated.manifest
Traceback (most recent call last):
  File "K:\source\vcpkg\buildtrees\nss\x64-windows-dbg\nss\out\Debug\gyp-win-tool", line 375, in <module>
    sys.exit(main(sys.argv[1:]))
  File "K:\source\vcpkg\buildtrees\nss\x64-windows-dbg\nss\out\Debug\gyp-win-tool", line 31, in main
    exit_code = executor.Dispatch(args)
  File "K:\source\vcpkg\buildtrees\nss\x64-windows-dbg\nss\out\Debug\gyp-win-tool", line 74, in Dispatch

    return getattr(self, method)(*args[1:])

  File "K:\source\vcpkg\buildtrees\nss\x64-windows-dbg\nss\out\Debug\gyp-win-tool", line 226, in ExecLinkWithManifests

    our_data = our_f.read().translate(translator)

UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence

[44/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\softoken\softokn.fipstokn.obj.rsp /c ..\..\lib\softoken\fipstokn.c /Foobj\lib\softoken\softokn.fipstokn.obj /Fdobj\lib\softoken\softokn.c.pdb 
[45/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\pk11wrap\pk11wrap_static.pk11pk12.obj.rsp /c ..\..\lib\pk11wrap\pk11pk12.c /Foobj\lib\pk11wrap\pk11wrap_static.pk11pk12.obj /Fdobj\lib\pk11wrap\pk11wrap_static.c.pdb 
[46/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\pk11wrap\pk11wrap_static.pk11skey.obj.rsp /c ..\..\lib\pk11wrap\pk11skey.c /Foobj\lib\pk11wrap\pk11wrap_static.pk11skey.obj /Fdobj\lib\pk11wrap\pk11wrap_static.c.pdb 
[47/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\freebl\freebl3.aeskeywrap.obj.rsp /c ..\..\lib\freebl\aeskeywrap.c /Foobj\lib\freebl\freebl3.aeskeywrap.obj /Fdobj\lib\freebl\freebl3.c.pdb 
[48/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\freebl\freebl3.alghmac.obj.rsp /c ..\..\lib\freebl\alghmac.c /Foobj\lib\freebl\freebl3.alghmac.obj /Fdobj\lib\freebl\freebl3.c.pdb 
[49/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\pk11wrap\pk11wrap_static.pk11pqg.obj.rsp /c ..\..\lib\pk11wrap\pk11pqg.c /Foobj\lib\pk11wrap\pk11wrap_static.pk11pqg.obj /Fdobj\lib\pk11wrap\pk11wrap_static.c.pdb 
[50/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\pk11wrap\pk11wrap_static.pk11util.obj.rsp /c ..\..\lib\pk11wrap\pk11util.c /Foobj\lib\pk11wrap\pk11wrap_static.pk11util.obj /Fdobj\lib\pk11wrap\pk11wrap_static.c.pdb 
[51/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\freebl\freebl3.arcfive.obj.rsp /c ..\..\lib\freebl\arcfive.c /Foobj\lib\freebl\freebl3.arcfive.obj /Fdobj\lib\freebl\freebl3.c.pdb 
[52/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\freebl\freebl3.arcfour.obj.rsp /c ..\..\lib\freebl\arcfour.c /Foobj\lib\freebl\freebl3.arcfour.obj /Fdobj\lib\freebl\freebl3.c.pdb 
[53/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\pk11wrap\pk11wrap_static.pk11slot.obj.rsp /c ..\..\lib\pk11wrap\pk11slot.c /Foobj\lib\pk11wrap\pk11wrap_static.pk11slot.obj /Fdobj\lib\pk11wrap\pk11wrap_static.c.pdb 
[54/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\freebl\freebl3.cmac.obj.rsp /c ..\..\lib\freebl\cmac.c /Foobj\lib\freebl\freebl3.cmac.obj /Fdobj\lib\freebl\freebl3.c.pdb 
[55/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\freebl\freebl3.camellia.obj.rsp /c ..\..\lib\freebl\camellia.c /Foobj\lib\freebl\freebl3.camellia.obj /Fdobj\lib\freebl\freebl3.c.pdb 
[56/350] ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\freebl\freebl3.blake2b.obj.rsp /c ..\..\lib\freebl\blake2b.c /Foobj\lib\freebl\freebl3.blake2b.obj /Fdobj\lib\freebl\freebl3.c.pdb 
ninja: build stopped: subcommand failed.
```
</details>

**Comment by WuhenPhi** [comment]
hey, I have met exactly the same problem with you while downloading and compiling the NSS through vcpkg. How did you fix it?
