### ISSUE TITLE
[gobject-introspection] build failure

### ISSUE THREAD

**Issue by talregev** [microsoft/vcpkg#38282]
### Operating system

wsl2 ubuntu 22.04

### Compiler

gcc 11.4.0

### Steps to reproduce the behavior

I change this line:
https://github.com/microsoft/vcpkg/blob/master/ports/gobject-introspection/portfile.cmake#L47
to this:
```
python='${CURRENT_HOST_INSTALLED_DIR}/tools/python3/python3${VCPKG_HOST_EXECUTABLE_SUFFIX}'
```

```Shell
./vcpkg install gobject-introspection --allow-unsupported
./vcpkg install gobject-introspection --triplet=x64-linux-dynamic --host-triplet=x64-linux-dynamic
```

### Failure logs

```
[107/164] /home/tal/vcpkg/buildtrees/gobject-introspection/x64-linux-rel/tools/g-ir-scanner --output=gir/GLib-2.0.gir --no-libtool --quiet --reparse-validate --add-include-path /home/tal/vcpkg/buildtrees/gobject-introspection/x64-linux-rel/gir --add-include-path /home/tal/vcpkg/buildtrees/gobject-introspection/src/spection-1-3ccf0e7785.clean/gir --identifier-prefix=G --symbol-prefix=g --symbol-prefix=glib --c-include=glib.h --namespace=GLib --nsversion=2.0 --library=glib-2.0 --library=gobject-2.0 --external-library --pkg=glib-2.0 --cflags-begin -I/home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0 -I/home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../lib/glib-2.0/include -DGLIB_COMPILATION -D__G_I18N_LIB_H__ -DGETTEXT_PACKAGE=Dummy --cflags-end /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/gobject/glib-types.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../lib/glib-2.0/include/glibconfig.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib-unix.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/galloca.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/garray.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gasyncqueue.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gatomic.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gbacktrace.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gbase64.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gbitlock.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gbookmarkfile.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gbytes.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gcharset.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gchecksum.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gconvert.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gdataset.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gdate.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gdatetime.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gdir.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/genviron.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gerror.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gfileutils.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/ggettext.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/ghash.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/ghmac.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/ghook.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/ghostutils.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gi18n-lib.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gi18n.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/giochannel.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gkeyfile.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/glib-typeof.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/glib-visibility.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/glist.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gmacros.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gmain.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gmappedfile.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gmarkup.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gmem.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gmessages.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gnode.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/goption.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gpathbuf.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gpattern.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gpoll.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gprimes.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gprintf.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gqsort.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gquark.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gqueue.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/grand.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/grcbox.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/grefcount.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/grefstring.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gregex.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gscanner.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gsequence.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gshell.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gslice.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gslist.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gspawn.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gstdio.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gstrfuncs.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gstring.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gstringchunk.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gstrvbuilder.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gtestutils.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gthread.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gthreadpool.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gtimer.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gtimezone.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gtrashstack.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gtree.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gtypes.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gunicode.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/guri.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gutils.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/guuid.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gvariant.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gvarianttype.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gversion.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gversionmacros.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gwin32.h ../src/spection-1-3ccf0e7785.clean/gir/glib-2.0.c
FAILED: gir/GLib-2.0.gir 
/home/tal/vcpkg/buildtrees/gobject-introspection/x64-linux-rel/tools/g-ir-scanner --output=gir/GLib-2.0.gir --no-libtool --quiet --reparse-validate --add-include-path /home/tal/vcpkg/buildtrees/gobject-introspection/x64-linux-rel/gir --add-include-path /home/tal/vcpkg/buildtrees/gobject-introspection/src/spection-1-3ccf0e7785.clean/gir --identifier-prefix=G --symbol-prefix=g --symbol-prefix=glib --c-include=glib.h --namespace=GLib --nsversion=2.0 --library=glib-2.0 --library=gobject-2.0 --external-library --pkg=glib-2.0 --cflags-begin -I/home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0 -I/home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../lib/glib-2.0/include -DGLIB_COMPILATION -D__G_I18N_LIB_H__ -DGETTEXT_PACKAGE=Dummy --cflags-end /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/gobject/glib-types.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../lib/glib-2.0/include/glibconfig.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib-unix.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/galloca.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/garray.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gasyncqueue.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gatomic.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gbacktrace.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gbase64.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gbitlock.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gbookmarkfile.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gbytes.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gcharset.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gchecksum.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gconvert.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gdataset.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gdate.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gdatetime.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gdir.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/genviron.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gerror.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gfileutils.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/ggettext.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/ghash.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/ghmac.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/ghook.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/ghostutils.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gi18n-lib.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gi18n.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/giochannel.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gkeyfile.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/glib-typeof.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/glib-visibility.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/glist.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gmacros.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gmain.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gmappedfile.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gmarkup.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gmem.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gmessages.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gnode.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/goption.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gpathbuf.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gpattern.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gpoll.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gprimes.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gprintf.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gqsort.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gquark.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gqueue.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/grand.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/grcbox.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/grefcount.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/grefstring.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gregex.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gscanner.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gsequence.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gshell.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gslice.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gslist.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gspawn.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gstdio.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gstrfuncs.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gstring.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gstringchunk.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gstrvbuilder.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gtestutils.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gthread.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gthreadpool.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gtimer.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gtimezone.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gtrashstack.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gtree.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gtypes.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gunicode.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/guri.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gutils.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/guuid.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gvariant.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gvarianttype.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gversion.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gversionmacros.h /home/tal/vcpkg/installed/x64-linux/lib/pkgconfig/../../include/glib-2.0/glib/gwin32.h ../src/spection-1-3ccf0e7785.clean/gir/glib-2.0.c
Traceback (most recent call last):
  File "/home/tal/vcpkg/buildtrees/gobject-introspection/x64-linux-rel/tools/g-ir-scanner", line 103, in <module>
    from giscanner.scannermain import scanner_main
  File "/home/tal/vcpkg/buildtrees/gobject-introspection/x64-linux-rel/giscanner/scannermain.py", line 35, in <module>
    from giscanner.ast import Include, Namespace
  File "/home/tal/vcpkg/buildtrees/gobject-introspection/x64-linux-rel/giscanner/ast.py", line 29, in <module>
    from .sourcescanner import CTYPE_TYPEDEF, CSYMBOL_TYPE_TYPEDEF
  File "/home/tal/vcpkg/buildtrees/gobject-introspection/x64-linux-rel/giscanner/sourcescanner.py", line 34, in <module>
    from giscanner._giscanner import SourceScanner as CSourceScanner
ModuleNotFoundError: No module named 'giscanner._giscanner'
```
[gobject-introspection.zip](https://github.com/microsoft/vcpkg/files/15047596/gobject-introspection.zip)

### Additional context

I am not sure what it mean the native in the support. 
https://github.com/microsoft/vcpkg/blob/master/ports/gobject-introspection/vcpkg.json#L8

Also the path of the python is not fit for python3:
https://github.com/microsoft/vcpkg/blob/master/ports/gobject-introspection/portfile.cmake#L47

This line should be:
python='${CURRENT_HOST_INSTALLED_DIR}/tools/python3/python**3**${VCPKG_HOST_EXECUTABLE_SUFFIX}'

For me it indicate that who did that change, didn't check that port.

**Comment by dg0yt** [comment]
Yes, the port is broken and only tested on windows...

**Comment by dg0yt** [comment]
FTR the capabilities of gobject-introspection depend on shared libs. There is no benefit from enabling it in the static triplets, except for eventually providing host tools. But I can't even cross-build from x64-linux to arm64-linux, because python3 doesn't cross-build...

**Comment by talregev** [comment]
maybe python can be host tool?

**Comment by talregev** [comment]
or target tool?

**Comment by talregev** [comment]
@dg0yt 
Can we use `vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)` on gobject-introspection port?

**Comment by dg0yt** [comment]
> @dg0yt Can we use `vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)` on gobject-introspection port?

The port might perhaps build successfully, and some artifacts might even be usable for targeting dynamic triplets. But downstream usage wouldn't benefit in the static triplets: AFAICT it can introspect (and provide access) only to dynamic libs.
And with lack of CI for dynamic triplets where vcpkg's default is static, it would be very fragile without a minimal test port for the promised capabilities. And that test port based on meson, because that is the dominating build system in downstream ports (GNOME).
(So that why this port is undermaintained.)
