### ISSUE TITLE
[qtinterfaceframework] Build error on x64-windows

### ISSUE THREAD

**Issue by wystephen** [microsoft/vcpkg#38320]
Package: qtinterfaceframework:x64-windows@6.6.1#1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.39.33523.0
-    vcpkg-tool version: 2024-03-14-7d353e869753e5609a1f1a057df3db8fd356e49d
    vcpkg-scripts version: 9224b3bbd 2024-04-20 (2 days ago)

**To Reproduce**

`vcpkg install qt opencv pcl hdf5`
**Failure logs**

```
-- Using cached D:/vcpkg/downloads/qtinterfaceframework-a2085374e38a135eaacfe7533888f0a361d4c721.tar.gz
-- Cleaning sources at D:/vcpkg/buildtrees/qtinterfaceframework/src/a361d4c721-2c693f67de.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/qtinterfaceframework-a2085374e38a135eaacfe7533888f0a361d4c721.tar.gz
-- Applying patch fix-taglib-search.patch
-- Using source at D:/vcpkg/buildtrees/qtinterfaceframework/src/a361d4c721-2c693f67de.clean
-- Using cached msys2-mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst.
-- Using msys root at D:/vcpkg/downloads/tools/msys2/d33df895d441a36d
-- Using cached pypa-get-pip-38e54e5de07c66e875c11a1ebbdb938854625dd8.tar.gz.
-- Cleaning sources at D:/vcpkg/buildtrees/qtinterfaceframework/src/8854625dd8-861bd167bd.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/pypa-get-pip-38e54e5de07c66e875c11a1ebbdb938854625dd8.tar.gz
-- Using source at D:/vcpkg/buildtrees/qtinterfaceframework/src/8854625dd8-861bd167bd.clean
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: D:/vcpkg/downloads/tools/python/python-3.11.8-x64/python.exe D:/vcpkg/buildtrees/qtinterfaceframework/src/8854625dd8-861bd167bd.clean/public/get-pip.py --no-warn-script-location
    Working Directory: D:/vcpkg/buildtrees/qtinterfaceframework
    Error code: 1
    See logs for more information:
      D:\vcpkg\buildtrees\qtinterfaceframework\get-pip-x64-windows-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake:48 (vcpkg_execute_required_process)
  ports/qtinterfaceframework/portfile.cmake:22 (x_vcpkg_get_python_packages)
  scripts/ports.cmake:175 (include)



```
<details><summary>D:\vcpkg\buildtrees\qtinterfaceframework\get-pip-x64-windows-err.log</summary>

```
Traceback (most recent call last):
  File "D:\vcpkg\buildtrees\qtinterfaceframework\src\8854625dd8-861bd167bd.clean\public\get-pip.py", line 33324, in <module>
    main()
  File "D:\vcpkg\buildtrees\qtinterfaceframework\src\8854625dd8-861bd167bd.clean\public\get-pip.py", line 135, in main
    bootstrap(tmpdir=tmpdir)
  File "D:\vcpkg\buildtrees\qtinterfaceframework\src\8854625dd8-861bd167bd.clean\public\get-pip.py", line 111, in bootstrap
    monkeypatch_for_cert(tmpdir)
  File "D:\vcpkg\buildtrees\qtinterfaceframework\src\8854625dd8-861bd167bd.clean\public\get-pip.py", line 92, in monkeypatch_for_cert
    from pip._internal.commands.install import InstallCommand
  File "C:\Users\WYSTEP~1\AppData\Local\Temp\tmpao_pj0x5\pip.zip\pip\_internal\commands\__init__.py", line 9, in <module>
  File "C:\Users\WYSTEP~1\AppData\Local\Temp\tmpao_pj0x5\pip.zip\pip\_internal\cli\base_command.py", line 15, in <module>
  File "C:\Users\WYSTEP~1\AppData\Local\Temp\tmpao_pj0x5\pip.zip\pip\_internal\cli\cmdoptions.py", line 23, in <module>
  File "C:\Users\WYSTEP~1\AppData\Local\Temp\tmpao_pj0x5\pip.zip\pip\_internal\cli\parser.py", line 12, in <module>
  File "C:\Users\WYSTEP~1\AppData\Local\Temp\tmpao_pj0x5\pip.zip\pip\_internal\configuration.py", line 24, in <module>
  File "C:\Users\WYSTEP~1\AppData\Local\Temp\tmpao_pj0x5\pip.zip\pip\_internal\utils\appdirs.py", line 13, in <module>
  File "C:\Users\WYSTEP~1\AppData\Local\Temp\tmpao_pj0x5\pip.zip\pip\_vendor\platformdirs\__init__.py", line 33, in <module>
  File "C:\Users\WYSTEP~1\AppData\Local\Temp\tmpao_pj0x5\pip.zip\pip\_vendor\platformdirs\__init__.py", line 29, in _set_platform_dir_class
  File "importlib\__init__.py", line 126, in import_module
  File "C:\Users\WYSTEP~1\AppData\Local\Temp\tmpao_pj0x5\pip.zip\pip\_vendor\platformdirs\windows.py", line 3, in <module>
  File "ctypes\__init__.py", line 8, in <module>
ImportError: DLL load failed while importing _ctypes: �Ҳ���ָ����ģ�顣
```
</details>

**Comment by WangWeiLin-MV** [comment]
Not reproduced on Windows 11 with the latest version of vcpkg. Could you clean and reset the vcpkg directory and re-test it?
