### ISSUE TITLE
[qtinterfaceframework] Build error on x64-linux

### ISSUE THREAD

**Issue by wangfangkai** [microsoft/vcpkg#38689]
Package: qtinterfaceframework:x64-linux@6.5.0

**Host Environment**

- Host: x64-linux
- Compiler: GNU 11.4.0
-    vcpkg-tool version: 2024-04-23-d6945642ee5c3076addd1a42c331bbf4cfc97457
    vcpkg-scripts version: cbf4a6641 2024-05-09 (22 hours ago)

**To Reproduce**

`vcpkg install `

**Failure logs**

```
-- Using cached /home/wfk/vcpkg/vcpkg/downloads/qtinterfaceframework-062662be9975e186a64c19a43b04f13c3e2aebfc.tar.gz
-- Cleaning sources at /home/wfk/vcpkg/vcpkg/buildtrees/qtinterfaceframework/src/3c3e2aebfc-243481cf92.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/wfk/vcpkg/vcpkg/downloads/qtinterfaceframework-062662be9975e186a64c19a43b04f13c3e2aebfc.tar.gz
-- Applying patch fix-taglib-search.patch
-- Using source at /home/wfk/vcpkg/vcpkg/buildtrees/qtinterfaceframework/src/3c3e2aebfc-243481cf92.clean
-- Setting up python virtual environmnent...
-- Installing requirements from: /home/wfk/vcpkg/vcpkg/buildtrees/versioning_/versions/qtinterfaceframework/3c0fac0141ef882b26d1904189a1aafd4dc4540f/requirements_minimal.txt
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /home/wfk/vcpkg/vcpkg/buildtrees/qtinterfaceframework/x64-linux-venv/bin/python -m pip install -r /home/wfk/vcpkg/vcpkg/buildtrees/versioning_/versions/qtinterfaceframework/3c0fac0141ef882b26d1904189a1aafd4dc4540f/requirements_minimal.txt
    Working Directory: /home/wfk/vcpkg/vcpkg/buildtrees/qtinterfaceframework
    Error code: 1
    See logs for more information:
      /home/wfk/vcpkg/vcpkg/buildtrees/qtinterfaceframework/pip-install-requirements-file-x64-linux-out.log
      /home/wfk/vcpkg/vcpkg/buildtrees/qtinterfaceframework/pip-install-requirements-file-x64-linux-err.log

Call Stack (most recent call first):
  /home/wfk/project/hydro_3d_navi/src/build/vcpkg_installed/x64-linux/share/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake:103 (vcpkg_execute_required_process)
  buildtrees/versioning_/versions/qtinterfaceframework/3c0fac0141ef882b26d1904189a1aafd4dc4540f/portfile.cmake:22 (x_vcpkg_get_python_packages)
  scripts/ports.cmake:175 (include)



```

<details><summary>/home/wfk/vcpkg/vcpkg/buildtrees/qtinterfaceframework/pip-install-requirements-file-x64-linux-out.log</summary>

```
Collecting antlr4-python3-runtime==4.7.1
  Using cached antlr4-python3-runtime-4.7.1.tar.gz (111 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting argh==0.26.2
  Using cached argh-0.26.2-py2.py3-none-any.whl (30 kB)
Collecting click==6.7
  Using cached click-6.7-py2.py3-none-any.whl (71 kB)
Collecting coloredlogs==10.0
  Using cached coloredlogs-10.0-py2.py3-none-any.whl (47 kB)
Collecting humanfriendly==4.15.1
  Using cached humanfriendly-4.15.1-py2.py3-none-any.whl (70 kB)
Collecting Jinja2==2.11.3
  Using cached Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
Collecting MarkupSafe==1.1
  Using cached MarkupSafe-1.1.0.tar.gz (18 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting path.py==11.0.1
  Using cached path.py-11.0.1-py2.py3-none-any.whl (32 kB)
Collecting pathtools==0.1.2
  Using cached pathtools-0.1.2.tar.gz (11 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting PyYAML==5.4
  Using cached PyYAML-5.4.tar.gz (174 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
```
</details>

<details><summary>/home/wfk/vcpkg/vcpkg/buildtrees/qtinterfaceframework/pip-install-requirements-file-x64-linux-err.log</summary>

```
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x702025446a70>, 'Connection to 192.168.35.1 timed out. (connect timeout=15)')': /simple/antlr4-python3-runtime/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x702025445f30>, 'Connection to 192.168.35.1 timed out. (connect timeout=15)')': /simple/antlr4-python3-runtime/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x702025446530>, 'Connection to 192.168.35.1 timed out. (connect timeout=15)')': /simple/antlr4-python3-runtime/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7020254464a0>, 'Connection to 192.168.35.1 timed out. (connect timeout=15)')': /simple/antlr4-python3-runtime/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7020254461a0>, 'Connection to 192.168.35.1 timed out. (connect timeout=15)')': /simple/antlr4-python3-runtime/
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/home/wfk/vcpkg/vcpkg/buildtrees/qtinterfaceframework/x64-linux-venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/wfk/vcpkg/vcpkg/buildtrees/qtinterfaceframework/x64-linux-venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/wfk/vcpkg/vcpkg/buildtrees/qtinterfaceframework/x64-linux-venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-ezktn6lx/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-ezktn6lx/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-ezktn6lx/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/tmp/pip-build-env-ezktn6lx/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-ezktn6lx/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-ezktn6lx/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-ezktn6lx/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-ezktn6lx/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-ezktn6lx/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-ezktn6lx/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/tmp/pip-build-env-ezktn6lx/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
          mm.run()
        File "/tmp/pip-build-env-ezktn6lx/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 550, in run
          self.add_defaults()
        File "/tmp/pip-build-env-ezktn6lx/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 588, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-ezktn6lx/overlay/lib/python3.10/site-packages/setuptools/command/sdist.py", line 102, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-ezktn6lx/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 250, in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-ezktn6lx/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 335, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 201, in get_source_files
        File "/tmp/pip-build-env-ezktn6lx/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
</details>

**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "name": "manifest",
  "version": "0.1.0",
  "description": "",
  "dependencies": [
    "glib",
    "osg",
    "osgearth",
    "pcl",
    "spdlog",
    "vtk",
    "qt"
  ],
  "builtin-baseline": "40619a55c3e76dc4005c8d1b7395071471bb8b96",
  "overrides": [
    {
      "name": "glib",
      "$note": "version 2.76.2 build failed, trying to use latest version instead",
      "version": "2.78.4#1"
    },
    {
      "name": "osg",
      "version": "3.6.5#18"
    },
    {
      "name": "osgearth",
      "version": "3.3#7"
    },
    {
      "name": "pcl",
      "version": "1.13.0#3"
    },
    {
      "name": "spdlog",
      "version": "1.11.0"
    },
    {
      "name": "vtk",
      "version": "9.2.0-pv5.11.0#6"
    },
    {
      "name": "qt",
      "version": "6.5.0"
    }
  ]
}

```
</details>

**Comment by wangfangkai** [comment]
#32630
