### ISSUE TITLE
[nss] Build error on x64-windows

### ISSUE THREAD

**Issue by zhangsilong521** [microsoft/vcpkg#39027]
Copy issue body from C:/vcpkg-master/installed/vcpkg/issue_body.md

**Comment by xiaozhuai** [comment]
The logs provide by @zhangsilong521 miss the most important part.
```
[336/878] D:\vcpkg\installed\x64-windows\tools\mozbuild\python3\python.exe gyp-win-tool link-with-manifests environment.x64 True D:/vcpkg/buildtrees/nss/x64-windows-dbg/dist/Debug/lib\nssutil3.dll "D:\vcpkg\installed\x64-windows\tools\mozbuild\python3\python.exe gyp-win-tool link-wrapper environment.x64 False link.exe /nologo /IMPLIB:D:/vcpkg/buildtrees/nss/x64-windows-dbg/dist/Debug/lib\nssutil3.dll.lib /DLL /OUT:D:/vcpkg/buildtrees/nss/x64-windows-dbg/dist/Debug/lib\nssutil3.dll @D:/vcpkg/buildtrees/nss/x64-windows-dbg/dist/Debug/lib\nssutil3.dll.rsp" 2 mt.exe rc.exe "obj\lib\util\nssutil3.nssutil3.dll.intermediate.manifest" obj\lib\util\nssutil3.nssutil3.dll.generated.manifest
FAILED: D:/vcpkg/buildtrees/nss/x64-windows-dbg/dist/Debug/lib/nssutil3.dll D:/vcpkg/buildtrees/nss/x64-windows-dbg/dist/Debug/lib/nssutil3.dll.lib D:/vcpkg/buildtrees/nss/x64-windows-dbg/dist/Debug/lib/nssutil3.dll.pdb 
D:\vcpkg\installed\x64-windows\tools\mozbuild\python3\python.exe gyp-win-tool link-with-manifests environment.x64 True D:/vcpkg/buildtrees/nss/x64-windows-dbg/dist/Debug/lib\nssutil3.dll "D:\vcpkg\installed\x64-windows\tools\mozbuild\python3\python.exe gyp-win-tool link-wrapper environment.x64 False link.exe /nologo /IMPLIB:D:/vcpkg/buildtrees/nss/x64-windows-dbg/dist/Debug/lib\nssutil3.dll.lib /DLL /OUT:D:/vcpkg/buildtrees/nss/x64-windows-dbg/dist/Debug/lib\nssutil3.dll @D:/vcpkg/buildtrees/nss/x64-windows-dbg/dist/Debug/lib\nssutil3.dll.rsp" 2 mt.exe rc.exe "obj\lib\util\nssutil3.nssutil3.dll.intermediate.manifest" obj\lib\util\nssutil3.nssutil3.dll.generated.manifest
Traceback (most recent call last):
  File "D:\vcpkg\buildtrees\nss\x64-windows-dbg\nss\out\Debug\gyp-win-tool", line 375, in <module>
    sys.exit(main(sys.argv[1:]))
  File "D:\vcpkg\buildtrees\nss\x64-windows-dbg\nss\out\Debug\gyp-win-tool", line 31, in main
    exit_code = executor.Dispatch(args)
  File "D:\vcpkg\buildtrees\nss\x64-windows-dbg\nss\out\Debug\gyp-win-tool", line 74, in Dispatch
    return getattr(self, method)(*args[1:])
  File "D:\vcpkg\buildtrees\nss\x64-windows-dbg\nss\out\Debug\gyp-win-tool", line 226, in ExecLinkWithManifests

    our_data = our_f.read().translate(translator)

UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence
```

**Comment by xiaozhuai** [comment]
@zhangsilong521 
Please try #39033
