### ISSUE TITLE
[brotli] Build failure on x64-windows

### ISSUE THREAD

**Issue by owlright** [microsoft/vcpkg#39089]
Package: brotli:x64-windows@1.1.0#1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.40.33811.0
-    vcpkg-tool version: 2024-04-23-d6945642ee5c3076addd1a42c331bbf4cfc97457
    vcpkg-scripts version: 47364fbc3 2024-05-31 (2 days ago)

**To Reproduce**

`vcpkg install brotli[core]:x64-windows`

**Failure logs**

```
-- Using cached google-brotli-v1.1.0.tar.gz.
-- Cleaning sources at C:/vcpkg/buildtrees/brotli/src/v1.1.0-958bece74c.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/google-brotli-v1.1.0.tar.gz
-- Applying patch install.patch
-- Applying patch fix-arm-uwp.patch
-- Applying patch pkgconfig.patch
-- Applying patch emscripten.patch
-- Using source at C:/vcpkg/buildtrees/brotli/src/v1.1.0-958bece74c.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig file: C:/vcpkg/packages/brotli_x64-windows/lib/pkgconfig/libbrotlicommon.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/brotli_x64-windows/lib/pkgconfig/libbrotlidec.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/brotli_x64-windows/lib/pkgconfig/libbrotlienc.pc
-- Using cached msys2-mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst.
-- Using msys root at C:/vcpkg/downloads/tools/msys2/d33df895d441a36d
-- Fixing pkgconfig file: C:/vcpkg/packages/brotli_x64-windows/debug/lib/pkgconfig/libbrotlicommon.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/brotli_x64-windows/debug/lib/pkgconfig/libbrotlidec.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/brotli_x64-windows/debug/lib/pkgconfig/libbrotlienc.pc
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/Users/sheng/.dotnet/tools/pwsh.exe -noprofile -executionpolicy Bypass -nologo -file C:/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/vcpkg/packages/brotli_x64-windows/tools/brotli/brotli.exe -installedDir C:/vcpkg/packages/brotli_x64-windows/bin -verbose
    Working Directory: C:/vcpkg
    Error code: -532462766
    See logs for more information:
      C:\vcpkg\buildtrees\brotli\copy-tool-dependencies-0-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:9 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:41 (z_vcpkg_copy_tool_dependencies_search)
  scripts/cmake/vcpkg_copy_tools.cmake:48 (vcpkg_copy_tool_dependencies)
  ports/brotli/portfile.cmake:32 (vcpkg_copy_tools)
  scripts/ports.cmake:175 (include)



```

<details><summary>C:\vcpkg\buildtrees\brotli\copy-tool-dependencies-0-err.log</summary>

```
Unhandled exception. System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'dotnet' with working directory 'C:\vcpkg'. 系统找不到指定的文件。
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Microsoft.PowerShell.GlobalTool.Shim.EntryPoint.Main(String[] args)
```
</details>

**Comment by owlright** [comment]
I have dotnet installed and C:\vcpkg exists(where I run this command)

**Comment by jimwang118** [comment]
There is a special character '.' in the C:/Users/sheng/.dotnet/tools/pwsh.exe file path, and the special character causes the file path to be unrecognized. You can install `pwsh` in a path without special characters to solve this problem.

**Comment by jimwang118** [comment]
> I'm confused. The dotnet installation is fully automated by Microsoft, right? So why does it choosse .dotnet at first place?

Pwsh.exe is obtained from the system environment variables, so `.dotnet` is sorted first in your system environment variables, so it is obtained first.

**Comment by owlright** [comment]
> > I'm confused. The dotnet installation is fully automated by Microsoft, right? So why does it choosse .dotnet at first place?
> 
> Pwsh.exe is obtained from the system environment variables, so `.dotnet` is sorted first in your system environment variables, so it is obtained first.

Ok, I understand what's going on now. I should just delete the .dotnet folder, then vcpkg will automatically download pwsh.exe. 

I would like to ask a question unrelated to the topic at hand, which program generated the .dotnet folder?
