### ISSUE TITLE
[wxwidgets] Build failure on x64-windows

### ISSUE THREAD

**Issue by owlright** [microsoft/vcpkg#39094]
Package: wxwidgets[core,debug-support,sound]:x64-windows@3.2.5

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.40.33811.0
-    vcpkg-tool version: 2024-04-23-d6945642ee5c3076addd1a42c331bbf4cfc97457
    vcpkg-scripts version: 47364fbc3 2024-05-31 (2 days ago)

**To Reproduce**

`vcpkg install wxWidgets`

**Failure logs**

```
-- Using cached wxWidgets-wxWidgets-v3.2.5.tar.gz.
-- Cleaning sources at C:/vcpkg/buildtrees/wxwidgets/src/v3.2.5-737796f0e2.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/wxWidgets-wxWidgets-v3.2.5.tar.gz
-- Applying patch install-layout.patch
-- Applying patch relocatable-wx-config.patch
-- Applying patch nanosvg-ext-depend.patch
-- Applying patch fix-libs-export.patch
-- Applying patch fix-pcre2.patch
-- Applying patch gtk3-link-libraries.patch
-- Applying patch sdl2.patch
-- Using source at C:/vcpkg/buildtrees/wxwidgets/src/v3.2.5-737796f0e2.clean
-- Using cached msys2-mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst.
-- Using msys root at C:/vcpkg/downloads/tools/msys2/d33df895d441a36d
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/Users/sheng/.dotnet/tools/pwsh.exe -noprofile -executionpolicy Bypass -nologo -file C:/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/vcpkg/packages/wxwidgets_x64-windows/tools/wxwidgets/wxrc.exe -installedDir C:/vcpkg/packages/wxwidgets_x64-windows/bin -verbose
    Working Directory: C:/vcpkg
    Error code: -532462766
    See logs for more information:
      C:\vcpkg\buildtrees\wxwidgets\copy-tool-dependencies-0-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:9 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:41 (z_vcpkg_copy_tool_dependencies_search)
  scripts/cmake/vcpkg_copy_tools.cmake:48 (vcpkg_copy_tool_dependencies)
  ports/wxwidgets/portfile.cmake:109 (vcpkg_copy_tools)
  scripts/ports.cmake:175 (include)



```

<details><summary>C:\vcpkg\buildtrees\wxwidgets\copy-tool-dependencies-0-err.log</summary>

```
Unhandled exception. System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'dotnet' with working directory 'C:\vcpkg'. 系统找不到指定的文件。
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Microsoft.PowerShell.GlobalTool.Shim.EntryPoint.Main(String[] args)
```
</details>

**Comment by owlright** [comment]
Guess the bug is caused by: 
In VScode, 
-> I installed plugin "CMake Language Support" 
-> require plugin ".NET Install Tool" which creates the folder .dotnet and with pwsh.exe in it 
-> vcpkg will first use the pwsh.exe in .dotnet (why? if ".dotnet" name is not correct why chose it at the first place?) .

My current solution is to just delete the .dotnet folder, run the vcpkg install command again, it will automatically install the pwsh.exe in the right place.
