### ISSUE TITLE
[glib] Build error on arm64-osx

### ISSUE THREAD

**Issue by ingslh** [microsoft/vcpkg#39217]
Package: glib:arm64-osx@2.78.4#1

**Host Environment**

- Host: arm64-osx
- Compiler: AppleClang 14.0.0.14000029
-    vcpkg-tool version: 2024-04-23-d6945642ee5c3076addd1a42c331bbf4cfc97457
    vcpkg-scripts version: b27651341 2024-06-10 (9 hours ago)

**To Reproduce**

`vcpkg install `

**Failure logs**

```
-- Found Python version '3.12.3 at /opt/homebrew/bin/python3'
-- Using meson: /Users/ingslh/Code/vcpkg/downloads/tools/meson-1.3.2-aa4767/meson.py
-- Using cached glib-2.78.4.tar.xz.
-- Cleaning sources at /Users/ingslh/Code/vcpkg/buildtrees/glib/src/glib-2-322e03f702.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/ingslh/Code/vcpkg/downloads/glib-2.78.4.tar.xz
-- Applying patch use-libiconv-on-windows.patch
-- Applying patch libintl.patch
-- Using source at /Users/ingslh/Code/vcpkg/buildtrees/glib/src/glib-2-322e03f702.clean
-- Found external ninja('1.11.1').
-- Getting CMake variables for arm64-osx-dbg
-- Getting CMake variables for arm64-osx-rel
-- Configuring arm64-osx-dbg
-- Configuring arm64-osx-dbg done
-- Configuring arm64-osx-rel
-- Configuring arm64-osx-rel done
-- Package arm64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /opt/homebrew/bin/ninja install -v
    Working Directory: /Users/ingslh/Code/vcpkg/buildtrees/glib/arm64-osx-dbg
    Error code: 1
    See logs for more information:
      /Users/ingslh/Code/vcpkg/buildtrees/glib/package-arm64-osx-dbg-out.log

Call Stack (most recent call first):
  /Users/ingslh/Code/mgtv/mlt-package/vcpkg_installed/arm64-osx/share/vcpkg-tool-meson/vcpkg_install_meson.cmake:33 (vcpkg_execute_required_process)
  buildtrees/versioning_/versions/glib/d73077209c5fcb5a0340baf7d8ba76d128c1ab27/portfile.cmake:56 (vcpkg_install_meson)
  scripts/ports.cmake:175 (include)



```

<details><summary>/Users/ingslh/Code/vcpkg/buildtrees/glib/package-arm64-osx-dbg-out.log</summary>

```
[1/587] /Users/ingslh/Code/vcpkg/buildtrees/glib/src/glib-2-322e03f702.clean/tools/gen-visibility-macros.py 2.78.4 versions-macros ../src/glib-2-322e03f702.clean/glib/gversionmacros.h.in glib/gversionmacros.h
[2/587] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -fPIC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -g -Igio/xdgmime/libxdgmime.a.p -Igio/xdgmime -I../src/glib-2-322e03f702.clean/gio/xdgmime -I. -I../src/glib-2-322e03f702.clean -I/Users/ingslh/Code/mgtv/mlt-package/vcpkg_installed/arm64-osx/include -fvisibility=hidden -fdiagnostics-color=always -Wall -Winvalid-pch -Wextra -Wpedantic -std=gnu99 -g -D_GNU_SOURCE -fno-strict-aliasing -DG_DISABLE_CAST_CHECKS -Wimplicit-fallthrough -Wmisleading-indentation -Wmissing-field-initializers -Wnonnull -Wunused -Wno-unused-parameter -Wno-cast-function-type -Wno-pedantic -Wno-format-zero-length -Wno-variadic-macros -Werror=format=2 -Werror=init-self -Werror=missing-include-dirs -Werror=pointer-arith -Werror=unused-result -Wstrict-prototypes -Wno-bad-function-cast -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=pointer-sign -Wno-string-plus-int -fPIC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -g -DHAVE_CONFIG_H -DXDG_PREFIX=_gio_xdg -MD -MQ gio/xdgmime/libxdgmime.a.p/xdgmimealias.c.o -MF gio/xdgmime/libxdgmime.a.p/xdgmimealias.c.o.d -o gio/xdgmime/libxdgmime.a.p/xdgmimealias.c.o -c ../src/glib-2-322e03f702.clean/gio/xdgmime/xdgmimealias.c
[3/587] /opt/homebrew/opt/python@3.12/bin/python3.12 gio/gdbus-2.0/codegen/gdbus-codegen --interface-prefix org.freedesktop.portal. --output-directory gio --generate-c-code xdp-dbus --c-namespace GXdp ../src/glib-2-322e03f702.clean/gio/org.freedesktop.portal.Documents.xml ../src/glib-2-322e03f702.clean/gio/org.freedesktop.portal.OpenURI.xml ../src/glib-2-322e03f702.clean/gio/org.freedesktop.portal.ProxyResolver.xml ../src/glib-2-322e03f702.clean/gio/org.freedesktop.portal.Trash.xml
FAILED: gio/xdp-dbus.h gio/xdp-dbus.c 
/opt/homebrew/opt/python@3.12/bin/python3.12 gio/gdbus-2.0/codegen/gdbus-codegen --interface-prefix org.freedesktop.portal. --output-directory gio --generate-c-code xdp-dbus --c-namespace GXdp ../src/glib-2-322e03f702.clean/gio/org.freedesktop.portal.Documents.xml ../src/glib-2-322e03f702.clean/gio/org.freedesktop.portal.OpenURI.xml ../src/glib-2-322e03f702.clean/gio/org.freedesktop.portal.ProxyResolver.xml ../src/glib-2-322e03f702.clean/gio/org.freedesktop.portal.Trash.xml
Traceback (most recent call last):
  File "/Users/ingslh/Code/vcpkg/buildtrees/glib/arm64-osx-dbg/gio/gdbus-2.0/codegen/gdbus-codegen", line 53, in <module>
    from codegen import codegen_main
  File "/Users/ingslh/Code/vcpkg/buildtrees/glib/arm64-osx-dbg/gio/gdbus-2.0/codegen/codegen_main.py", line 29, in <module>
    from . import dbustypes
  File "/Users/ingslh/Code/vcpkg/buildtrees/glib/arm64-osx-dbg/gio/gdbus-2.0/codegen/dbustypes.py", line 22, in <module>
    from . import utils
  File "/Users/ingslh/Code/vcpkg/buildtrees/glib/arm64-osx-dbg/gio/gdbus-2.0/codegen/utils.py", line 22, in <module>
    import distutils.version
ModuleNotFoundError: No module named 'distutils'
[4/587] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -fPIC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -g -Iglib/libcharset/libcharset.a.p -Iglib/libcharset -I../src/glib-2-322e03f702.clean/glib/libcharset -I. -I../src/glib-2-322e03f702.clean -I/Users/ingslh/Code/mgtv/mlt-package/vcpkg_installed/arm64-osx/include -fvisibility=hidden -fdiagnostics-color=always -Wall -Winvalid-pch -Wextra -Wpedantic -std=gnu99 -g -D_GNU_SOURCE -fno-strict-aliasing -DG_DISABLE_CAST_CHECKS -Wimplicit-fallthrough -Wmisleading-indentation -Wmissing-field-initializers -Wnonnull -Wunused -Wno-unused-parameter -Wno-cast-function-type -Wno-pedantic -Wno-format-zero-length -Wno-variadic-macros -Werror=format=2 -Werror=init-self -Werror=missing-include-dirs -Werror=pointer-arith -Werror=unused-result -Wstrict-prototypes -Wno-bad-function-cast -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=pointer-sign -Wno-string-plus-int -fPIC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -g '-DGLIB_CHARSETALIAS_DIR="/Users/ingslh/Code/vcpkg/packages/glib_arm64-osx/debug/lib"' -MD -MQ glib/libcharset/libcharset.a.p/localcharset.c.o -MF glib/libcharset/libcharset.a.p/localcharset.c.o.d -o glib/libcharset/libcharset.a.p/localcharset.c.o -c ../src/glib-2-322e03f702.clean/glib/libcharset/localcharset.c
[5/587] /opt/homebrew/opt/python@3.12/bin/python3.12 gio/gdbus-2.0/codegen/gdbus-codegen --interface-prefix org. --output-directory gio --generate-c-code gdbus-daemon-generated --c-namespace _G ../src/glib-2-322e03f702.clean/gio/dbus-daemon.xml
FAILED: gio/gdbus-daemon-generated.h gio/gdbus-daemon-generated.c 
/opt/homebrew/opt/python@3.12/bin/python3.12 gio/gdbus-2.0/codegen/gdbus-codegen --interface-prefix org. --output-directory gio --generate-c-code gdbus-daemon-generated --c-namespace _G ../src/glib-2-322e03f702.clean/gio/dbus-daemon.xml
Traceback (most recent call last):
  File "/Users/ingslh/Code/vcpkg/buildtrees/glib/arm64-osx-dbg/gio/gdbus-2.0/codegen/gdbus-codegen", line 53, in <module>
    from codegen import codegen_main
  File "/Users/ingslh/Code/vcpkg/buildtrees/glib/arm64-osx-dbg/gio/gdbus-2.0/codegen/codegen_main.py", line 29, in <module>
    from . import dbustypes
  File "/Users/ingslh/Code/vcpkg/buildtrees/glib/arm64-osx-dbg/gio/gdbus-2.0/codegen/dbustypes.py", line 22, in <module>
    from . import utils
  File "/Users/ingslh/Code/vcpkg/buildtrees/glib/arm64-osx-dbg/gio/gdbus-2.0/codegen/utils.py", line 22, in <module>
    import distutils.version
ModuleNotFoundError: No module named 'distutils'
[6/587] /Users/ingslh/Code/vcpkg/buildtrees/glib/src/glib-2-322e03f702.clean/tools/gen-visibility-macros.py 2.78.4 visibility-macros GLIB glib/glib-visibility.h
[7/587] /Users/ingslh/Code/vcpkg/buildtrees/glib/src/glib-2-322e03f702.clean/tools/gen-visibility-macros.py 2.78.4 visibility-macros GOBJECT gobject/gobject-visibility.h
[8/587] /Users/ingslh/Code/vcpkg/buildtrees/glib/src/glib-2-322e03f702.clean/tools/gen-visibility-macros.py 2.78.4 visibility-macros GMODULE gmodule/gmodule-visibility.h
[9/587] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -fPIC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -g -Igio/xdgmime/libxdgmime.a.p -Igio/xdgmime -I../src/glib-2-322e03f702.clean/gio/xdgmime -I. -I../src/glib-2-322e03f702.clean -I/Users/ingslh/Code/mgtv/mlt-package/vcpkg_installed/arm64-osx/include -fvisibility=hidden -fdiagnostics-color=always -Wall -Winvalid-pch -Wextra -Wpedantic -std=gnu99 -g -D_GNU_SOURCE -fno-strict-aliasing -DG_DISABLE_CAST_CHECKS -Wimplicit-fallthrough -Wmisleading-indentation -Wmissing-field-initializers -Wnonnull -Wunused -Wno-unused-parameter -Wno-cast-function-type -Wno-pedantic -Wno-format-zero-length -Wno-variadic-macros -Werror=format=2 -Werror=init-self -Werror=missing-include-dirs -Werror=pointer-arith -Werror=unused-result -Wstrict-prototypes -Wno-bad-function-cast -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=pointer-sign -Wno-string-plus-int -fPIC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -g -DHAVE_CONFIG_H -DXDG_PREFIX=_gio_xdg -MD -MQ gio/xdgmime/libxdgmime.a.p/xdgmime.c.o -MF gio/xdgmime/libxdgmime.a.p/xdgmime.c.o.d -o gio/xdgmime/libxdgmime.a.p/xdgmime.c.o -c ../src/glib-2-322e03f702.clean/gio/xdgmime/xdgmime.c
[10/587] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -fPIC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -g -Igio/xdgmime/libxdgmime.a.p -Igio/xdgmime -I../src/glib-2-322e03f702.clean/gio/xdgmime -I. -I../src/glib-2-322e03f702.clean -I/Users/ingslh/Code/mgtv/mlt-package/vcpkg_installed/arm64-osx/include -fvisibility=hidden -fdiagnostics-color=always -Wall -Winvalid-pch -Wextra -Wpedantic -std=gnu99 -g -D_GNU_SOURCE -fno-strict-aliasing -DG_DISABLE_CAST_CHECKS -Wimplicit-fallthrough -Wmisleading-indentation -Wmissing-field-initializers -Wnonnull -Wunused -Wno-unused-parameter -Wno-cast-function-type -Wno-pedantic -Wno-format-zero-length -Wno-variadic-macros -Werror=format=2 -Werror=init-self -Werror=missing-include-dirs -Werror=pointer-arith -Werror=unused-result -Wstrict-prototypes -Wno-bad-function-cast -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=pointer-sign -Wno-string-plus-int -fPIC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -g -DHAVE_CONFIG_H -DXDG_PREFIX=_gio_xdg -MD -MQ gio/xdgmime/libxdgmime.a.p/xdgmimeglob.c.o -MF gio/xdgmime/libxdgmime.a.p/xdgmimeglob.c.o.d -o gio/xdgmime/libxdgmime.a.p/xdgmimeglob.c.o -c ../src/glib-2-322e03f702.clean/gio/xdgmime/xdgmimeglob.c
[11/587] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -fPIC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -g -Igio/xdgmime/libxdgmime.a.p -Igio/xdgmime -I../src/glib-2-322e03f702.clean/gio/xdgmime -I. -I../src/glib-2-322e03f702.clean -I/Users/ingslh/Code/mgtv/mlt-package/vcpkg_installed/arm64-osx/include -fvisibility=hidden -fdiagnostics-color=always -Wall -Winvalid-pch -Wextra -Wpedantic -std=gnu99 -g -D_GNU_SOURCE -fno-strict-aliasing -DG_DISABLE_CAST_CHECKS -Wimplicit-fallthrough -Wmisleading-indentation -Wmissing-field-initializers -Wnonnull -Wunused -Wno-unused-parameter -Wno-cast-function-type -Wno-pedantic -Wno-format-zero-length -Wno-variadic-macros -Werror=format=2 -Werror=init-self -Werror=missing-include-dirs -Werror=pointer-arith -Werror=unused-result -Wstrict-prototypes -Wno-bad-function-cast -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=pointer-sign -Wno-string-plus-int -fPIC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -g -DHAVE_CONFIG_H -DXDG_PREFIX=_gio_xdg -MD -MQ gio/xdgmime/libxdgmime.a.p/xdgmimecache.c.o -MF gio/xdgmime/libxdgmime.a.p/xdgmimecache.c.o.d -o gio/xdgmime/libxdgmime.a.p/xdgmimecache.c.o -c ../src/glib-2-322e03f702.clean/gio/xdgmime/xdgmimecache.c
[12/587] /opt/homebrew/opt/python@3.12/bin/python3.12 /Users/ingslh/Code/vcpkg/downloads/tools/meson-1.3.2-aa4767/meson.py --internal exe --capture gobject/glib-enumtypes.h -- /opt/homebrew/opt/python@3.12/bin/python3.12 gobject/glib-mkenums --template ../src/glib-2-322e03f702.clean/gobject/glib-enumtypes.h.template ../src/glib-2-322e03f702.clean/gobject/../glib/gunicode.h
ninja: build stopped: subcommand failed.
```
</details>

**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "name": "mlt-package",
  "version": "1.0.0",
  "dependencies": [
    {
      "name": "ffmpeg",
      "version>=": "6.1.1",
      "features": [
        "theora",
        "vorbis",
        "mp3lame",
        "x264",
        "x265",
        "vpx",
        "opus",
        "aom",
        "webp"
      ]
    },
    {
      "name": "fftw3",
      "version>=": "3.3.10"
    },
    {
      "name": "vcpkg-tool-meson",
      "version>=": "1.3.2"
    },
    {
      "name": "glib",
      "version>=": "2.78.4"
    },
    {
      "name": "jack2",
      "version>=": "1.9.22"
    },
    {
      "name": "libxml2",
      "version>=": "2.11.7"
    },
    {
      "name": "pango",
      "version>=": "1.50.14"
    },
    {
      "name": "pthread",
      "version>=": "3.0.0#2"
    },
    {
      "name": "rtaudio",
      "version>=": "6.0.1"
    },
    {
      "name": "rubberband",
      "version>=": "3.3.0"
    },
    {
      "name": "libsamplerate",
      "version>=": "0.2.2#1"
    },
    {
      "name": "sdl2",
      "version>=": "2.30.1"
    },
    {
      "name": "opencv",
      "version>=": "4.8.0"
    }
  ],
  "builtin-baseline": "01f602195983451bc83e72f4214af2cbc495aa94"
}

```
</details>

**Comment by ingslh** [comment]
> Please install the external dependency `python-setuptools` and try again.

Thx!! It worked for me.
