### ISSUE TITLE
[glib] Build error on x64-linux

### ISSUE THREAD

**Issue by hflemmen** [microsoft/vcpkg#39652]
Package: glib:x64-linux@2.78.4#3

I am trying to use vcpkg inside a docker image. I see that it complains on not finding 'distutils', but I am not sure if that is the root issue. `python3-setuptools` is installed via apt.

**Host Environment**

- Ubuntu 24.04 LTS

- Host: x64-linux
- Compiler: GNU 13.2.0
-    vcpkg-tool version: 2024-06-10-02590c430e4ed9215d27870138c2e579cc338772
    vcpkg-scripts version: f61a294e7 2024-07-01 (17 hours ago)

**To Reproduce**

`vcpkg install `

**Failure logs**

```
-- Found Python version '3.12.3 at /usr/bin/python3'
-- Using meson: /vcpkg/downloads/tools/meson-1.3.2-c18b6a/meson.py
-- Downloading https://download.gnome.org/sources/glib/2.78/glib-2.78.4.tar.xz -> glib-2.78.4.tar.xz...
-- Extracting source /vcpkg/downloads/glib-2.78.4.tar.xz
-- Applying patch use-libiconv-on-windows.patch
-- Applying patch libintl.patch
-- Using source at /vcpkg/buildtrees/glib/src/glib-2-322e03f702.clean
-- Found external ninja('1.11.1').
-- Configuring x64-linux-dbg
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Configuring x64-linux-dbg done
-- Configuring x64-linux-rel
-- Configuring x64-linux-rel done
-- Package x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: /usr/bin/ninja install -v
    Working Directory: /vcpkg/buildtrees/glib/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /vcpkg/buildtrees/glib/package-x64-linux-dbg-out.log

Call Stack (most recent call first):
  /optical_flow/build/vcpkg_installed/x64-linux/share/vcpkg-tool-meson/vcpkg_install_meson.cmake:33 (vcpkg_execute_required_process)
  buildtrees/versioning_/versions/glib/ca77eedd8dca92c9e6c021316e81b9c7f648b58a/portfile.cmake:56 (vcpkg_install_meson)
  scripts/ports.cmake:192 (include)



```

<details><summary>/vcpkg/buildtrees/glib/package-x64-linux-dbg-out.log</summary>

```
[1/589] /usr/bin/cc -fPIC -g -Igio/gio-launch-desktop.p -Igio -I../src/glib-2-322e03f702.clean/gio -Iglib -I../src/glib-2-322e03f702.clean/glib -I/optical_flow/build/vcpkg_installed/x64-linux/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=gnu99 -g -D_GNU_SOURCE -fno-strict-aliasing -DG_DISABLE_CAST_CHECKS -Wduplicated-branches -Wimplicit-fallthrough -Wmisleading-indentation -Wmissing-field-initializers -Wnonnull -Wunused -Wno-unused-parameter -Wno-cast-function-type -Wno-pedantic -Wno-format-zero-length -Wno-variadic-macros -Werror=format=2 -Werror=init-self -Werror=missing-include-dirs -Werror=pointer-arith -Werror=unused-result -Wstrict-prototypes -Wno-bad-function-cast -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=pointer-sign -fPIC -g '-DG_LOG_DOMAIN="GLib-GIO"' '-DGIO_LAUNCH_DESKTOP="/vcpkg/packages/glib_x64-linux/debug/libexec/gio-launch-desktop"' '-DGIO_MODULE_DIR="/vcpkg/packages/glib_x64-linux/debug/lib/gio/modules"' '-DLOCALSTATEDIR="/vcpkg/packages/glib_x64-linux/debug/var"' -MD -MQ gio/gio-launch-desktop.p/.._glib_gjournal-private.c.o -MF gio/gio-launch-desktop.p/.._glib_gjournal-private.c.o.d -o gio/gio-launch-desktop.p/.._glib_gjournal-private.c.o -c ../src/glib-2-322e03f702.clean/glib/gjournal-private.c
[2/589] /usr/bin/python3 gio/gdbus-2.0/codegen/gdbus-codegen --interface-prefix org.freedesktop.portal. --output-directory gio --generate-c-code xdp-dbus --c-namespace GXdp ../src/glib-2-322e03f702.clean/gio/org.freedesktop.portal.Documents.xml ../src/glib-2-322e03f702.clean/gio/org.freedesktop.portal.OpenURI.xml ../src/glib-2-322e03f702.clean/gio/org.freedesktop.portal.ProxyResolver.xml ../src/glib-2-322e03f702.clean/gio/org.freedesktop.portal.Trash.xml
FAILED: gio/xdp-dbus.h gio/xdp-dbus.c 
/usr/bin/python3 gio/gdbus-2.0/codegen/gdbus-codegen --interface-prefix org.freedesktop.portal. --output-directory gio --generate-c-code xdp-dbus --c-namespace GXdp ../src/glib-2-322e03f702.clean/gio/org.freedesktop.portal.Documents.xml ../src/glib-2-322e03f702.clean/gio/org.freedesktop.portal.OpenURI.xml ../src/glib-2-322e03f702.clean/gio/org.freedesktop.portal.ProxyResolver.xml ../src/glib-2-322e03f702.clean/gio/org.freedesktop.portal.Trash.xml
Traceback (most recent call last):
  File "/vcpkg/buildtrees/glib/x64-linux-dbg/gio/gdbus-2.0/codegen/gdbus-codegen", line 53, in <module>
    from codegen import codegen_main
  File "/vcpkg/buildtrees/glib/x64-linux-dbg/gio/gdbus-2.0/codegen/codegen_main.py", line 29, in <module>
    from . import dbustypes
  File "/vcpkg/buildtrees/glib/x64-linux-dbg/gio/gdbus-2.0/codegen/dbustypes.py", line 22, in <module>
    from . import utils
  File "/vcpkg/buildtrees/glib/x64-linux-dbg/gio/gdbus-2.0/codegen/utils.py", line 22, in <module>
    import distutils.version
ModuleNotFoundError: No module named 'distutils'
[3/589] /vcpkg/buildtrees/glib/src/glib-2-322e03f702.clean/tools/gen-visibility-macros.py 2.78.4 visibility-macros GOBJECT gobject/gobject-visibility.h
[4/589] /usr/bin/cc -fPIC -g -Igio/xdgmime/libxdgmime.a.p -Igio/xdgmime -I../src/glib-2-322e03f702.clean/gio/xdgmime -I. -I../src/glib-2-322e03f702.clean -I/optical_flow/build/vcpkg_installed/x64-linux/include -fvisibility=hidden -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=gnu99 -g -D_GNU_SOURCE -fno-strict-aliasing -DG_DISABLE_CAST_CHECKS -Wduplicated-branches -Wimplicit-fallthrough -Wmisleading-indentation -Wmissing-field-initializers -Wnonnull -Wunused -Wno-unused-parameter -Wno-cast-function-type -Wno-pedantic -Wno-format-zero-length -Wno-variadic-macros -Werror=format=2 -Werror=init-self -Werror=missing-include-dirs -Werror=pointer-arith -Werror=unused-result -Wstrict-prototypes -Wno-bad-function-cast -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=pointer-sign -fPIC -g -fPIC -DHAVE_CONFIG_H -DXDG_PREFIX=_gio_xdg -MD -MQ gio/xdgmime/libxdgmime.a.p/xdgmimeint.c.o -MF gio/xdgmime/libxdgmime.a.p/xdgmimeint.c.o.d -o gio/xdgmime/libxdgmime.a.p/xdgmimeint.c.o -c ../src/glib-2-322e03f702.clean/gio/xdgmime/xdgmimeint.c
[5/589] /usr/bin/cc -fPIC -g -Iglib/libcharset/libcharset.a.p -Iglib/libcharset -I../src/glib-2-322e03f702.clean/glib/libcharset -I. -I../src/glib-2-322e03f702.clean -I/optical_flow/build/vcpkg_installed/x64-linux/include -fvisibility=hidden -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=gnu99 -g -D_GNU_SOURCE -fno-strict-aliasing -DG_DISABLE_CAST_CHECKS -Wduplicated-branches -Wimplicit-fallthrough -Wmisleading-indentation -Wmissing-field-initializers -Wnonnull -Wunused -Wno-unused-parameter -Wno-cast-function-type -Wno-pedantic -Wno-format-zero-length -Wno-variadic-macros -Werror=format=2 -Werror=init-self -Werror=missing-include-dirs -Werror=pointer-arith -Werror=unused-result -Wstrict-prototypes -Wno-bad-function-cast -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=pointer-sign -fPIC -g -fPIC '-DGLIB_CHARSETALIAS_DIR="/vcpkg/packages/glib_x64-linux/debug/lib"' -MD -MQ glib/libcharset/libcharset.a.p/localcharset.c.o -MF glib/libcharset/libcharset.a.p/localcharset.c.o.d -o glib/libcharset/libcharset.a.p/localcharset.c.o -c ../src/glib-2-322e03f702.clean/glib/libcharset/localcharset.c
[6/589] /usr/bin/cc -fPIC -g -Igio/xdgmime/libxdgmime.a.p -Igio/xdgmime -I../src/glib-2-322e03f702.clean/gio/xdgmime -I. -I../src/glib-2-322e03f702.clean -I/optical_flow/build/vcpkg_installed/x64-linux/include -fvisibility=hidden -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=gnu99 -g -D_GNU_SOURCE -fno-strict-aliasing -DG_DISABLE_CAST_CHECKS -Wduplicated-branches -Wimplicit-fallthrough -Wmisleading-indentation -Wmissing-field-initializers -Wnonnull -Wunused -Wno-unused-parameter -Wno-cast-function-type -Wno-pedantic -Wno-format-zero-length -Wno-variadic-macros -Werror=format=2 -Werror=init-self -Werror=missing-include-dirs -Werror=pointer-arith -Werror=unused-result -Wstrict-prototypes -Wno-bad-function-cast -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=pointer-sign -fPIC -g -fPIC -DHAVE_CONFIG_H -DXDG_PREFIX=_gio_xdg -MD -MQ gio/xdgmime/libxdgmime.a.p/xdgmimeicon.c.o -MF gio/xdgmime/libxdgmime.a.p/xdgmimeicon.c.o.d -o gio/xdgmime/libxdgmime.a.p/xdgmimeicon.c.o -c ../src/glib-2-322e03f702.clean/gio/xdgmime/xdgmimeicon.c
[7/589] /usr/bin/cc -fPIC -g -Igio/xdgmime/libxdgmime.a.p -Igio/xdgmime -I../src/glib-2-322e03f702.clean/gio/xdgmime -I. -I../src/glib-2-322e03f702.clean -I/optical_flow/build/vcpkg_installed/x64-linux/include -fvisibility=hidden -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=gnu99 -g -D_GNU_SOURCE -fno-strict-aliasing -DG_DISABLE_CAST_CHECKS -Wduplicated-branches -Wimplicit-fallthrough -Wmisleading-indentation -Wmissing-field-initializers -Wnonnull -Wunused -Wno-unused-parameter -Wno-cast-function-type -Wno-pedantic -Wno-format-zero-length -Wno-variadic-macros -Werror=format=2 -Werror=init-self -Werror=missing-include-dirs -Werror=pointer-arith -Werror=unused-result -Wstrict-prototypes -Wno-bad-function-cast -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=pointer-sign -fPIC -g -fPIC -DHAVE_CONFIG_H -DXDG_PREFIX=_gio_xdg -MD -MQ gio/xdgmime/libxdgmime.a.p/xdgmimealias.c.o -MF gio/xdgmime/libxdgmime.a.p/xdgmimealias.c.o.d -o gio/xdgmime/libxdgmime.a.p/xdgmimealias.c.o -c ../src/glib-2-322e03f702.clean/gio/xdgmime/xdgmimealias.c
[8/589] /vcpkg/buildtrees/glib/src/glib-2-322e03f702.clean/tools/gen-visibility-macros.py 2.78.4 visibility-macros GLIB glib/glib-visibility.h
[9/589] /vcpkg/buildtrees/glib/src/glib-2-322e03f702.clean/tools/gen-visibility-macros.py 2.78.4 versions-macros ../src/glib-2-322e03f702.clean/glib/gversionmacros.h.in glib/gversionmacros.h
[10/589] /usr/bin/python3 gio/gdbus-2.0/codegen/gdbus-codegen --interface-prefix org. --output-directory gio --generate-c-code gdbus-daemon-generated --c-namespace _G ../src/glib-2-322e03f702.clean/gio/dbus-daemon.xml
FAILED: gio/gdbus-daemon-generated.h gio/gdbus-daemon-generated.c 
/usr/bin/python3 gio/gdbus-2.0/codegen/gdbus-codegen --interface-prefix org. --output-directory gio --generate-c-code gdbus-daemon-generated --c-namespace _G ../src/glib-2-322e03f702.clean/gio/dbus-daemon.xml
Traceback (most recent call last):
  File "/vcpkg/buildtrees/glib/x64-linux-dbg/gio/gdbus-2.0/codegen/gdbus-codegen", line 53, in <module>
    from codegen import codegen_main
  File "/vcpkg/buildtrees/glib/x64-linux-dbg/gio/gdbus-2.0/codegen/codegen_main.py", line 29, in <module>
    from . import dbustypes
  File "/vcpkg/buildtrees/glib/x64-linux-dbg/gio/gdbus-2.0/codegen/dbustypes.py", line 22, in <module>
    from . import utils
  File "/vcpkg/buildtrees/glib/x64-linux-dbg/gio/gdbus-2.0/codegen/utils.py", line 22, in <module>
    import distutils.version
ModuleNotFoundError: No module named 'distutils'
[11/589] /usr/bin/cc -fPIC -g -Igio/gio-launch-desktop.p -Igio -I../src/glib-2-322e03f702.clean/gio -Iglib -I../src/glib-2-322e03f702.clean/glib -I/optical_flow/build/vcpkg_installed/x64-linux/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=gnu99 -g -D_GNU_SOURCE -fno-strict-aliasing -DG_DISABLE_CAST_CHECKS -Wduplicated-branches -Wimplicit-fallthrough -Wmisleading-indentation -Wmissing-field-initializers -Wnonnull -Wunused -Wno-unused-parameter -Wno-cast-function-type -Wno-pedantic -Wno-format-zero-length -Wno-variadic-macros -Werror=format=2 -Werror=init-self -Werror=missing-include-dirs -Werror=pointer-arith -Werror=unused-result -Wstrict-prototypes -Wno-bad-function-cast -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=pointer-sign -fPIC -g '-DG_LOG_DOMAIN="GLib-GIO"' '-DGIO_LAUNCH_DESKTOP="/vcpkg/packages/glib_x64-linux/debug/libexec/gio-launch-desktop"' '-DGIO_MODULE_DIR="/vcpkg/packages/glib_x64-linux/debug/lib/gio/modules"' '-DLOCALSTATEDIR="/vcpkg/packages/glib_x64-linux/debug/var"' -MD -MQ gio/gio-launch-desktop.p/gio-launch-desktop.c.o -MF gio/gio-launch-desktop.p/gio-launch-desktop.c.o.d -o gio/gio-launch-desktop.p/gio-launch-desktop.c.o -c ../src/glib-2-322e03f702.clean/gio/gio-launch-desktop.c
[12/589] /usr/bin/cc -fPIC -g -Igio/xdgmime/libxdgmime.a.p -Igio/xdgmime -I../src/glib-2-322e03f702.clean/gio/xdgmime -I. -I../src/glib-2-322e03f702.clean -I/optical_flow/build/vcpkg_installed/x64-linux/include -fvisibility=hidden -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=gnu99 -g -D_GNU_SOURCE -fno-strict-aliasing -DG_DISABLE_CAST_CHECKS -Wduplicated-branches -Wimplicit-fallthrough -Wmisleading-indentation -Wmissing-field-initializers -Wnonnull -Wunused -Wno-unused-parameter -Wno-cast-function-type -Wno-pedantic -Wno-format-zero-length -Wno-variadic-macros -Werror=format=2 -Werror=init-self -Werror=missing-include-dirs -Werror=pointer-arith -Werror=unused-result -Wstrict-prototypes -Wno-bad-function-cast -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=pointer-sign -fPIC -g -fPIC -DHAVE_CONFIG_H -DXDG_PREFIX=_gio_xdg -MD -MQ gio/xdgmime/libxdgmime.a.p/xdgmimeparent.c.o -MF gio/xdgmime/libxdgmime.a.p/xdgmimeparent.c.o.d -o gio/xdgmime/libxdgmime.a.p/xdgmimeparent.c.o -c ../src/glib-2-322e03f702.clean/gio/xdgmime/xdgmimeparent.c
[13/589] /vcpkg/buildtrees/glib/src/glib-2-322e03f702.clean/tools/gen-visibility-macros.py 2.78.4 visibility-macros GMODULE gmodule/gmodule-visibility.h
[14/589] /usr/bin/cc -fPIC -g -Igio/xdgmime/libxdgmime.a.p -Igio/xdgmime -I../src/glib-2-322e03f702.clean/gio/xdgmime -I. -I../src/glib-2-322e03f702.clean -I/optical_flow/build/vcpkg_installed/x64-linux/include -fvisibility=hidden -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=gnu99 -g -D_GNU_SOURCE -fno-strict-aliasing -DG_DISABLE_CAST_CHECKS -Wduplicated-branches -Wimplicit-fallthrough -Wmisleading-indentation -Wmissing-field-initializers -Wnonnull -Wunused -Wno-unused-parameter -Wno-cast-function-type -Wno-pedantic -Wno-format-zero-length -Wno-variadic-macros -Werror=format=2 -Werror=init-self -Werror=missing-include-dirs -Werror=pointer-arith -Werror=unused-result -Wstrict-prototypes -Wno-bad-function-cast -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=pointer-sign -fPIC -g -fPIC -DHAVE_CONFIG_H -DXDG_PREFIX=_gio_xdg -MD -MQ gio/xdgmime/libxdgmime.a.p/xdgmimeglob.c.o -MF gio/xdgmime/libxdgmime.a.p/xdgmimeglob.c.o.d -o gio/xdgmime/libxdgmime.a.p/xdgmimeglob.c.o -c ../src/glib-2-322e03f702.clean/gio/xdgmime/xdgmimeglob.c
[15/589] /usr/bin/cc -fPIC -g -Igio/xdgmime/libxdgmime.a.p -Igio/xdgmime -I../src/glib-2-322e03f702.clean/gio/xdgmime -I. -I../src/glib-2-322e03f702.clean -I/optical_flow/build/vcpkg_installed/x64-linux/include -fvisibility=hidden -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=gnu99 -g -D_GNU_SOURCE -fno-strict-aliasing -DG_DISABLE_CAST_CHECKS -Wduplicated-branches -Wimplicit-fallthrough -Wmisleading-indentation -Wmissing-field-initializers -Wnonnull -Wunused -Wno-unused-parameter -Wno-cast-function-type -Wno-pedantic -Wno-format-zero-length -Wno-variadic-macros -Werror=format=2 -Werror=init-self -Werror=missing-include-dirs -Werror=pointer-arith -Werror=unused-result -Wstrict-prototypes -Wno-bad-function-cast -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=pointer-sign -fPIC -g -fPIC -DHAVE_CONFIG_H -DXDG_PREFIX=_gio_xdg -MD -MQ gio/xdgmime/libxdgmime.a.p/xdgmimemagic.c.o -MF gio/xdgmime/libxdgmime.a.p/xdgmimemagic.c.o.d -o gio/xdgmime/libxdgmime.a.p/xdgmimemagic.c.o -c ../src/glib-2-322e03f702.clean/gio/xdgmime/xdgmimemagic.c
[16/589] /vcpkg/buildtrees/glib/src/glib-2-322e03f702.clean/tools/gen-visibility-macros.py 2.78.4 visibility-macros GIO gio/gio-visibility.h
[17/589] /usr/bin/cc -fPIC -g -Igio/xdgmime/libxdgmime.a.p -Igio/xdgmime -I../src/glib-2-322e03f702.clean/gio/xdgmime -I. -I../src/glib-2-322e03f702.clean -I/optical_flow/build/vcpkg_installed/x64-linux/include -fvisibility=hidden -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=gnu99 -g -D_GNU_SOURCE -fno-strict-aliasing -DG_DISABLE_CAST_CHECKS -Wduplicated-branches -Wimplicit-fallthrough -Wmisleading-indentation -Wmissing-field-initializers -Wnonnull -Wunused -Wno-unused-parameter -Wno-cast-function-type -Wno-pedantic -Wno-format-zero-length -Wno-variadic-macros -Werror=format=2 -Werror=init-self -Werror=missing-include-dirs -Werror=pointer-arith -Werror=unused-result -Wstrict-prototypes -Wno-bad-function-cast -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=pointer-sign -fPIC -g -fPIC -DHAVE_CONFIG_H -DXDG_PREFIX=_gio_xdg -MD -MQ gio/xdgmime/libxdgmime.a.p/xdgmime.c.o -MF gio/xdgmime/libxdgmime.a.p/xdgmime.c.o.d -o gio/xdgmime/libxdgmime.a.p/xdgmime.c.o -c ../src/glib-2-322e03f702.clean/gio/xdgmime/xdgmime.c
[18/589] /usr/bin/cc -fPIC -g -Igio/xdgmime/libxdgmime.a.p -Igio/xdgmime -I../src/glib-2-322e03f702.clean/gio/xdgmime -I. -I../src/glib-2-322e03f702.clean -I/optical_flow/build/vcpkg_installed/x64-linux/include -fvisibility=hidden -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=gnu99 -g -D_GNU_SOURCE -fno-strict-aliasing -DG_DISABLE_CAST_CHECKS -Wduplicated-branches -Wimplicit-fallthrough -Wmisleading-indentation -Wmissing-field-initializers -Wnonnull -Wunused -Wno-unused-parameter -Wno-cast-function-type -Wno-pedantic -Wno-format-zero-length -Wno-variadic-macros -Werror=format=2 -Werror=init-self -Werror=missing-include-dirs -Werror=pointer-arith -Werror=unused-result -Wstrict-prototypes -Wno-bad-function-cast -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=pointer-sign -fPIC -g -fPIC -DHAVE_CONFIG_H -DXDG_PREFIX=_gio_xdg -MD -MQ gio/xdgmime/libxdgmime.a.p/xdgmimecache.c.o -MF gio/xdgmime/libxdgmime.a.p/xdgmimecache.c.o.d -o gio/xdgmime/libxdgmime.a.p/xdgmimecache.c.o -c ../src/glib-2-322e03f702.clean/gio/xdgmime/xdgmimecache.c
[19/589] /usr/bin/python3 /vcpkg/downloads/tools/meson-1.3.2-c18b6a/meson.py --internal exe --capture gobject/glib-enumtypes.h -- /usr/bin/python3 gobject/glib-mkenums --template ../src/glib-2-322e03f702.clean/gobject/glib-enumtypes.h.template ../src/glib-2-322e03f702.clean/gobject/../glib/gunicode.h
ninja: build stopped: subcommand failed.
```
</details>

**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "name": "optical-flow",
  "version-string": "1.0.0",
  "builtin-baseline": "f61a294e765b257926ae9e9d85f96468a0af74e7",
  "dependencies": [
    {
      "name": "manif",
      "version>=": "2023-07-17",
      "$comment": "    # this is heuristically generated, and may not be correct\n\n    find_package(manif CONFIG REQUIRED)\n\n    target_link_libraries(main PRIVATE MANIF::manif)\n"
    },
    {
      "name": "opencv",
      "version>=": "4.8.0",
      "$comment": "    # this is heuristically generated, and may not be correct\n\n    find_package(OpenCV CONFIG REQUIRED)\n\n    # note: 15 additional targets are not displayed.\n\n    target_link_libraries(main PRIVATE opencv_ml opencv_dnn opencv_core opencv_flann)\n",
      "features": [
        "ffmpeg"
      ]
    },
    {
      "name": "eigen3",
      "version>=": "3.4.0#2"
    },
    {
      "name": "gtest",
      "version>=": "1.14.0"
    },
    {
      "name": "geographiclib",
      "version>=": "2.3#1"
    },
    {
      "name": "boost",
      "version>=": "1.84.0"
    },
    {
      "name": "toml11",
      "version>=": "3.7.1"
    }
  ]
}

```
</details>

**Comment by hflemmen** [comment]
`python3-distutils` is not it apt, but `python3-setuptools` [should](https://stackoverflow.com/questions/77233855/why-did-i-get-an-error-modulenotfounderror-no-module-named-distutils) allegedly provide it.

I tried to install it yesterday, and it seemed ok, but now I tried to install it again and it worked(Or, it failed, but glib seemed to build). Sorry for not discovering this before opening this issue and thanks for the help.
