### ISSUE TITLE
[onnx] Missing ONNX 1.16 package in vcpkg

### ISSUE THREAD

**Issue by jacekpawlak** [microsoft/vcpkg#39891]
Hello,

is it possible to share ONNX 1.16 in vckpkg? https://vcpkg.link/ports/onnx/versions

**Comment by jacekpawlak** [comment]
Hi @MonicaLiu0311, any update here?

**Comment by MonicaLiu0311** [comment]
Resolving the error that occurred.

```
Installing 4/4 onnx[core,pybind11]:x64-windows@1.16.1...
Building onnx[core,pybind11]:x64-windows@1.16.1...
-- Note: onnx only supports static library linkage. Building static library.
-- Using cached onnx-onnx-v1.16.1.tar.gz.
-- Cleaning sources at F:/vcpkg/buildtrees/onnx/src/v1.16.1-981051b7ce.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/vcpkg/downloads/onnx-onnx-v1.16.1.tar.gz
-- Applying patch fix-cmakelists.patch
-- Applying patch fix-dependency-protobuf.patch
-- Using source at F:/vcpkg/buildtrees/onnx/src/v1.16.1-981051b7ce.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: F:/vcpkg/downloads/tools/cmake-3.29.2-windows/cmake-3.29.2-windows-i386/bin/cmake.exe --build . --config Debug --target onnx_cpp2py_export -- -v -j9
    Working Directory: F:/vcpkg/buildtrees/onnx/x64-windows-dbg
    See logs for more information:
      F:\vcpkg\buildtrees\onnx\build-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  ports/onnx/portfile.cmake:61 (vcpkg_cmake_build)
  scripts/ports.cmake:192 (include)
```
```
[2/66] C:\Windows\system32\cmd.exe /C "cd /D F:\vcpkg\buildtrees\onnx\x64-windows-dbg && F:\vcpkg\installed\x64-windows\tools\protobuf\protoc.exe F:/vcpkg/buildtrees/onnx/x64-windows-dbg/onnx/onnx-ml.proto -I F:/vcpkg/buildtrees/onnx/x64-windows-dbg --cpp_out dllexport_decl=ONNX_API:F:/vcpkg/buildtrees/onnx/x64-windows-dbg --python_out F:/vcpkg/buildtrees/onnx/x64-windows-dbg --plugin protoc-gen-mypy=F:/vcpkg/buildtrees/onnx/src/v1.16.1-981051b7ce.clean/tools/protoc-gen-mypy.bat --mypy_out dllexport_decl=ONNX_API:F:/vcpkg/buildtrees/onnx/x64-windows-dbg"
FAILED: onnx/onnx-ml.pb.cc onnx/onnx-ml.pb.h F:/vcpkg/buildtrees/onnx/x64-windows-dbg/onnx/onnx-ml.pb.cc F:/vcpkg/buildtrees/onnx/x64-windows-dbg/onnx/onnx-ml.pb.h 
C:\Windows\system32\cmd.exe /C "cd /D F:\vcpkg\buildtrees\onnx\x64-windows-dbg && F:\vcpkg\installed\x64-windows\tools\protobuf\protoc.exe F:/vcpkg/buildtrees/onnx/x64-windows-dbg/onnx/onnx-ml.proto -I F:/vcpkg/buildtrees/onnx/x64-windows-dbg --cpp_out dllexport_decl=ONNX_API:F:/vcpkg/buildtrees/onnx/x64-windows-dbg --python_out F:/vcpkg/buildtrees/onnx/x64-windows-dbg --plugin protoc-gen-mypy=F:/vcpkg/buildtrees/onnx/src/v1.16.1-981051b7ce.clean/tools/protoc-gen-mypy.bat --mypy_out dllexport_decl=ONNX_API:F:/vcpkg/buildtrees/onnx/x64-windows-dbg"
Traceback (most recent call last):
  File "F:\vcpkg\buildtrees\onnx\src\v1.16.1-981051b7ce.clean\tools\\protoc-gen-mypy.py", line 28, in <module>
    import google.protobuf.descriptor_pb2 as d_typed
ModuleNotFoundError: No module named 'google'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\vcpkg\buildtrees\onnx\src\v1.16.1-981051b7ce.clean\tools\\protoc-gen-mypy.py", line 31, in <module>
    raise RuntimeError("Failed to generate mypy stubs") from e
RuntimeError: Failed to generate mypy stubs
--mypy_out: protoc-gen-mypy: Plugin failed with status code 1.
ninja: build stopped: subcommand failed.
```

**Comment by jacekpawlak** [comment]
Hi @MonicaLiu0311, any update here?
