### ISSUE TITLE
[qtinterfaceframework] Build error on x64-windows

### ISSUE THREAD

**Issue by zhouniandi** [microsoft/vcpkg#40591]
Package: qtinterfaceframework:x64-windows@6.7.2

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.40.33811.0
-    vcpkg-tool version: 2024-08-01-fd884a0d390d12783076341bd43d77c3a6a15658
    vcpkg-scripts version: fb544875b 2024-08-22 (9 hours ago)

**To Reproduce**

`vcpkg install qt`

**Failure logs**

```
-- Using cached F:/vcpkg/downloads/qtinterfaceframework-146d9eabba1bf49b333744e19519f3746c3e2adc.tar.gz
-- Cleaning sources at F:/vcpkg/buildtrees/qtinterfaceframework/src/746c3e2adc-c38bff769e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/vcpkg/downloads/qtinterfaceframework-146d9eabba1bf49b333744e19519f3746c3e2adc.tar.gz
-- Using source at F:/vcpkg/buildtrees/qtinterfaceframework/src/746c3e2adc-c38bff769e.clean
-- Using cached msys2-mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.5.3-3-x86_64.pkg.tar.zst.
-- Using msys root at F:/vcpkg/downloads/tools/msys2/1e74ca60daa10104
-- Using cached pypa-get-pip-38e54e5de07c66e875c11a1ebbdb938854625dd8.tar.gz.
-- Cleaning sources at F:/vcpkg/buildtrees/qtinterfaceframework/src/8854625dd8-861bd167bd.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/vcpkg/downloads/pypa-get-pip-38e54e5de07c66e875c11a1ebbdb938854625dd8.tar.gz
-- Using source at F:/vcpkg/buildtrees/qtinterfaceframework/src/8854625dd8-861bd167bd.clean
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: F:/vcpkg/downloads/tools/python/python-3.11.8-x64/python.exe F:/vcpkg/buildtrees/qtinterfaceframework/src/8854625dd8-861bd167bd.clean/public/get-pip.py --no-warn-script-location
    Working Directory: F:/vcpkg/buildtrees/qtinterfaceframework
    Error code: 2
    See logs for more information:
      F:\vcpkg\buildtrees\qtinterfaceframework\get-pip-x64-windows-out.log
      F:\vcpkg\buildtrees\qtinterfaceframework\get-pip-x64-windows-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake:48 (vcpkg_execute_required_process)
  ports/qtinterfaceframework/portfile.cmake:18 (x_vcpkg_get_python_packages)
  scripts/ports.cmake:192 (include)



```

<details><summary>F:\vcpkg\buildtrees\qtinterfaceframework\get-pip-x64-windows-out.log</summary>

```
Collecting pip
  Downloading pip-24.2-py3-none-any.whl (1.8 MB)
                                              0.0/1.8 MB ? eta -:--:--
```
</details>

<details><summary>F:\vcpkg\buildtrees\qtinterfaceframework\get-pip-x64-windows-err.log</summary>

```
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\di\AppData\Local\Temp\tmpx8e86tll\pip.zip\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\di\AppData\Local\Temp\tmpx8e86tll\pip.zip\pip\_vendor\urllib3\response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\di\AppData\Local\Temp\tmpx8e86tll\pip.zip\pip\_vendor\cachecontrol\filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
           ^^^^^^^^^^^^^^^^^^^
  File "http\client.py", line 473, in read
  File "socket.py", line 706, in readinto
  File "ssl.py", line 1314, in recv_into
  File "ssl.py", line 1166, in read
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\di\AppData\Local\Temp\tmpx8e86tll\pip.zip\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "C:\Users\di\AppData\Local\Temp\tmpx8e86tll\pip.zip\pip\_internal\cli\req_command.py", line 205, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\di\AppData\Local\Temp\tmpx8e86tll\pip.zip\pip\_internal\commands\install.py", line 339, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\di\AppData\Local\Temp\tmpx8e86tll\pip.zip\pip\_internal\resolution\resolvelib\resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\di\AppData\Local\Temp\tmpx8e86tll\pip.zip\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\di\AppData\Local\Temp\tmpx8e86tll\pip.zip\pip\_vendor\resolvelib\resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\Users\di\AppData\Local\Temp\tmpx8e86tll\pip.zip\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "C:\Users\di\AppData\Local\Temp\tmpx8e86tll\pip.zip\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\di\AppData\Local\Temp\tmpx8e86tll\pip.zip\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
           ^^^^^^^^^
  File "C:\Users\di\AppData\Local\Temp\tmpx8e86tll\pip.zip\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\di\AppData\Local\Temp\tmpx8e86tll\pip.zip\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
                ^^^^^^
  File "C:\Users\di\AppData\Local\Temp\tmpx8e86tll\pip.zip\pip\_internal\resolution\resolvelib\factory.py", line 215, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "C:\Users\di\AppData\Local\Temp\tmpx8e86tll\pip.zip\pip\_internal\resolution\resolvelib\candidates.py", line 288, in __init__
    super().__init__(
  File "C:\Users\di\AppData\Local\Temp\tmpx8e86tll\pip.zip\pip\_internal\resolution\resolvelib\candidates.py", line 158, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "C:\Users\di\AppData\Local\Temp\tmpx8e86tll\pip.zip\pip\_internal\resolution\resolvelib\candidates.py", line 227, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\di\AppData\Local\Temp\tmpx8e86tll\pip.zip\pip\_internal\resolution\resolvelib\candidates.py", line 299, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\di\AppData\Local\Temp\tmpx8e86tll\pip.zip\pip\_internal\operations\prepare.py", line 487, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\di\AppData\Local\Temp\tmpx8e86tll\pip.zip\pip\_internal\operations\prepare.py", line 532, in _prepare_linked_requirement
    local_file = unpack_url(
                 ^^^^^^^^^^^
  File "C:\Users\di\AppData\Local\Temp\tmpx8e86tll\pip.zip\pip\_internal\operations\prepare.py", line 214, in unpack_url
    file = get_http_url(
           ^^^^^^^^^^^^^
  File "C:\Users\di\AppData\Local\Temp\tmpx8e86tll\pip.zip\pip\_internal\operations\prepare.py", line 94, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\di\AppData\Local\Temp\tmpx8e86tll\pip.zip\pip\_internal\network\download.py", line 146, in __call__
    for chunk in chunks:
  File "C:\Users\di\AppData\Local\Temp\tmpx8e86tll\pip.zip\pip\_internal\cli\progress_bars.py", line 304, in _rich_progress_bar
    for chunk in iterable:
  File "C:\Users\di\AppData\Local\Temp\tmpx8e86tll\pip.zip\pip\_internal\network\utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "C:\Users\di\AppData\Local\Temp\tmpx8e86tll\pip.zip\pip\_vendor\urllib3\response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\di\AppData\Local\Temp\tmpx8e86tll\pip.zip\pip\_vendor\urllib3\response.py", line 512, in read
    with self._error_catcher():
  File "contextlib.py", line 158, in __exit__
  File "C:\Users\di\AppData\Local\Temp\tmpx8e86tll\pip.zip\pip\_vendor\urllib3\response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
```
</details>

**Comment by greenozon** [comment]
>TimeoutError: The read operation timed out

loos like some issues with internet connectivity...

could you check that you could access https://files.pythonhosted.org ?

**Comment by zhouniandi** [comment]
> > TimeoutError: The read operation timed out
> 
> loos like some issues with internet connectivity...
> 
> could you check that you could access https://files.pythonhosted.org ?

I checked the network, and I can access https://files.pythonhosted.org

**Comment by zhouniandi** [comment]
> > TimeoutError: The read operation timed out
> 
> loos like some issues with internet connectivity...
> 
> could you check that you could access https://files.pythonhosted.org ?

![Uploading image.png…]()

**Comment by zhouniandi** [comment]
<img width="1092" alt="console logs" src="https://github.com/user-attachments/assets/42cbc14f-0279-4186-bb5a-75cd35f5e7f6">

**Comment by MonicaLiu0311** [comment]
> ```
> pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
> ```


Please check your network and disable the firewall and try again.

**Comment by MonicaLiu0311** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
