### ISSUE TITLE
Error when Install and use packages with CMake in Visual Studio

### ISSUE THREAD

**Issue by IshaanKarnik** [microsoft/vcpkg#40616]
**Describe the bug**
I'm getting bellow mentioned error when I trying to Install and use packages with CMake in Visual Studio

**Environment**
- OS: Windows
- Compiler: MSVC 17.111
- CMake: 3.30.2

**To Reproduce**
I'm following the bellow linked guide
https://learn.microsoft.com/en-us/vcpkg/get_started/get-started-vs?pivots=shell-cmd
On Step 2. Configure the CMakePresets.json file.

**Failure logs**
1> CMake generation started for configuration: 'default'.
1> Illegal characters in path.
Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at libcmake.RelativePathStringComparer.GetCanonicalPath(String path)
   at libcmake.RelativePathStringComparer.Equals(String x, String y)
   at libcmake.CMakeDaemonDriver.HasToolchainChanged(CMakeCommandLine cmdLine, String currentToolchain, List`1 messages, IEqualityComparer`1 comparer)
   at libcmake.CMakeDaemonDriver.<DeleteCacheIfConsistencyCheckFailsAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.CMakeListsParser.<SetAndCheckToolchainAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.CMakeListsParser.<ParseImplAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.CMakeListsParser.<ParseAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.CMake.Project.ExternalBuildProject.ProjectProvider.<ParseProjectAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.CMake.Project.ExternalBuildProject.ProjectProvider.<ParseProjectAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Workspace.ExternalBuildFramework.Impl.ParseCache.<ParseAsyncImpl>d__34.MoveNext()

**Comment by LilyWangLL** [comment]
There is the following error message in your log, please confirm that your vcpkg path is entirely in English and does not contain any special characters or spaces.
> 1> Illegal characters in path.
> Illegal characters in path.

**Comment by IshaanKarnik** [comment]
I've set VCPKG_ROOT=C:\vcpkg in environment variables.

**Comment by jose94752** [comment]
> I've set VCPKG_ROOT=C:\vcpkg in environment variables.

If you install integrated vcpkg of Visual Studio uninstall it because VS2022 will use these one instead of the vcpkg.exe you have setting. You can check in command line terminal with
`c:\where vcpkg`
if you have like
`C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg.exe
C:\source\vcpkg\vcpkg.exe`
It's not good you may have like a line like these one check these with 'C:\set' in Visual Studio 2022 Command Prompt
![2024-10-04 14-33-21-VCPKG_ROOT-Modifié par Visual Studio Community 2022-Flouté](https://github.com/user-attachments/assets/6159214f-682b-490e-b99b-6f0f716ffcba)
Even if you have setting the vcpk folder in VS2022
![2024-10-04 14-37-09-VCPKG_ROOT-Modifié par Visual Studio Community 2022-2](https://github.com/user-attachments/assets/b1fa123e-7f7f-4fe9-ad0d-86458619bbd4)
