### ISSUE TITLE
[pkgconf] Build error on x64-windows

### ISSUE THREAD

**Issue by mycaosf** [microsoft/vcpkg#40796]
Package: pkgconf:x64-windows@2.3.0

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.41.34120.0
-    vcpkg-tool version: 2024-06-10-02590c430e4ed9215d27870138c2e579cc338772
    vcpkg-scripts version: 4e08971f3 2024-09-03 (12 hours ago)

**To Reproduce**

`vcpkg install libpq:x64-windows-static`

**Failure logs**

```
-- Found Python version '3.11.8 at D:/cc/vcpkg/downloads/tools/python/python-3.11.8-x64/python.exe'
-- Using meson: D:/cc/vcpkg/downloads/tools/meson-1.5.1-81f7e3/meson.py
-- Using cached pkgconf-pkgconf-pkgconf-2.3.0.tar.gz.
-- Cleaning sources at D:/cc/vcpkg/buildtrees/pkgconf/src/conf-2.3.0-07e4a066bf.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/cc/vcpkg/downloads/pkgconf-pkgconf-pkgconf-2.3.0.tar.gz
-- Using source at D:/cc/vcpkg/buildtrees/pkgconf/src/conf-2.3.0-07e4a066bf.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-dbg
-- Getting CMake variables for x64-windows
-- Configuring x64-windows-dbg done
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Package x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: C:/cc/vc17/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe install -v
    Working Directory: D:/cc/vcpkg/buildtrees/pkgconf/x64-windows-dbg
    Error code: 1
    See logs for more information:
      D:\cc\vcpkg\buildtrees\pkgconf\package-x64-windows-dbg-out.log
      D:\cc\vcpkg\buildtrees\pkgconf\package-x64-windows-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-tool-meson/vcpkg_install_meson.cmake:33 (vcpkg_execute_required_process)
  ports/pkgconf/portfile.cmake:67 (vcpkg_install_meson)
  scripts/ports.cmake:192 (include)



```

<details><summary>D:\cc\vcpkg\buildtrees\pkgconf\package-x64-windows-dbg-err.log</summary>

```
Traceback (most recent call last):
  File "D:\cc\vcpkg\downloads\tools\meson-1.5.1-81f7e3\meson.py", line 27, in <module>
    sys.exit(mesonmain.main())
             ^^^^^^^^^^^^^^^^
  File "D:\cc\vcpkg\downloads\tools\meson-1.5.1-81f7e3\mesonbuild\mesonmain.py", line 288, in main
    return run(sys.argv[1:], launcher)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\cc\vcpkg\downloads\tools\meson-1.5.1-81f7e3\mesonbuild\mesonmain.py", line 279, in run
    return CommandLineParser().run(args)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\cc\vcpkg\downloads\tools\meson-1.5.1-81f7e3\mesonbuild\mesonmain.py", line 64, in __init__
    from . import mconf, mdist, minit, minstall, mintro, msetup, mtest, rewriter, msubprojects, munstable_coredata, mcompile, mdevenv, mformat
  File "D:\cc\vcpkg\downloads\tools\meson-1.5.1-81f7e3\mesonbuild\mconf.py", line 20, in <module>
    from . import mintro
  File "D:\cc\vcpkg\downloads\tools\meson-1.5.1-81f7e3\mesonbuild\mintro.py", line 23, in <module>
    from .ast import IntrospectionInterpreter, BUILD_TARGET_FUNCTIONS, AstConditionLevel, AstIDGenerator, AstIndentationGenerator, AstJSONPrinter
  File "D:\cc\vcpkg\downloads\tools\meson-1.5.1-81f7e3\mesonbuild\ast\__init__.py", line 19, in <module>
    from .interpreter import AstInterpreter
  File "D:\cc\vcpkg\downloads\tools\meson-1.5.1-81f7e3\mesonbuild\ast\interpreter.py", line 25, in <module>
    from ..interpreter import (
  File "D:\cc\vcpkg\downloads\tools\meson-1.5.1-81f7e3\mesonbuild\interpreter\__init__.py", line 33, in <module>
    from .interpreter import Interpreter, permitted_dependency_kwargs
  File "D:\cc\vcpkg\downloads\tools\meson-1.5.1-81f7e3\mesonbuild\interpreter\interpreter.py", line 19, in <module>
    from ..wrap import wrap, WrapMode
  File "D:\cc\vcpkg\downloads\tools\meson-1.5.1-81f7e3\mesonbuild\wrap\wrap.py", line 9, in <module>
    import urllib.request
  File "urllib\request.py", line 88, in <module>
  File "http\client.py", line 71, in <module>
  File "email\parser.py", line 12, in <module>
  File "email\feedparser.py", line 27, in <module>
  File "email\_policybase.py", line 9, in <module>
  File "email\utils.py", line 29, in <module>
  File "socket.py", line 51, in <module>
    
    ^
ImportError: DLL load failed while importing _socket:  Ҳ   ָ    ģ 顣
```
</details>

<details><summary>D:\cc\vcpkg\buildtrees\pkgconf\package-x64-windows-dbg-out.log</summary>

```
[1/21] "C:/cc/vc17/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-Ipkgconf-5.dll.p" "-I." "-I..\src\conf-2.3.0-07e4a066bf.clean" "-ID:/cc/vcpkg/installed/x64-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/Zi" "-D_BSD_SOURCE" "-D_DEFAULT_SOURCE" "-nologo" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DLIBPKGCONF_EXPORT" "-DPKGCONFIG_IS_NOT_STATIC" "/Fdpkgconf-5.dll.p\libpkgconf_bsdstubs.c.pdb" /Fopkgconf-5.dll.p/libpkgconf_bsdstubs.c.obj "/c" ../src/conf-2.3.0-07e4a066bf.clean/libpkgconf/bsdstubs.c
cl : Command line warning D9025 : overriding '/Z7' with '/Zi'
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
[2/21] "C:/cc/vc17/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-Ipkgconf-5.dll.p" "-I." "-I..\src\conf-2.3.0-07e4a066bf.clean" "-ID:/cc/vcpkg/installed/x64-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/Zi" "-D_BSD_SOURCE" "-D_DEFAULT_SOURCE" "-nologo" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DLIBPKGCONF_EXPORT" "-DPKGCONFIG_IS_NOT_STATIC" "/Fdpkgconf-5.dll.p\libpkgconf_audit.c.pdb" /Fopkgconf-5.dll.p/libpkgconf_audit.c.obj "/c" ../src/conf-2.3.0-07e4a066bf.clean/libpkgconf/audit.c
cl : Command line warning D9025 : overriding '/Z7' with '/Zi'
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
[3/21] "C:/cc/vc17/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-Ipkgconf-5.dll.p" "-I." "-I..\src\conf-2.3.0-07e4a066bf.clean" "-ID:/cc/vcpkg/installed/x64-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/Zi" "-D_BSD_SOURCE" "-D_DEFAULT_SOURCE" "-nologo" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DLIBPKGCONF_EXPORT" "-DPKGCONFIG_IS_NOT_STATIC" "/Fdpkgconf-5.dll.p\libpkgconf_dependency.c.pdb" /Fopkgconf-5.dll.p/libpkgconf_dependency.c.obj "/c" ../src/conf-2.3.0-07e4a066bf.clean/libpkgconf/dependency.c
cl : Command line warning D9025 : overriding '/Z7' with '/Zi'
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
[4/21] "C:/cc/vc17/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-Ipkgconf-5.dll.p" "-I." "-I..\src\conf-2.3.0-07e4a066bf.clean" "-ID:/cc/vcpkg/installed/x64-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/Zi" "-D_BSD_SOURCE" "-D_DEFAULT_SOURCE" "-nologo" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DLIBPKGCONF_EXPORT" "-DPKGCONFIG_IS_NOT_STATIC" "/Fdpkgconf-5.dll.p\libpkgconf_cache.c.pdb" /Fopkgconf-5.dll.p/libpkgconf_cache.c.obj "/c" ../src/conf-2.3.0-07e4a066bf.clean/libpkgconf/cache.c
cl : Command line warning D9025 : overriding '/Z7' with '/Zi'
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
[5/21] "C:/cc/vc17/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-Ipkgconf-5.dll.p" "-I." "-I..\src\conf-2.3.0-07e4a066bf.clean" "-ID:/cc/vcpkg/installed/x64-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/Zi" "-D_BSD_SOURCE" "-D_DEFAULT_SOURCE" "-nologo" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DLIBPKGCONF_EXPORT" "-DPKGCONFIG_IS_NOT_STATIC" "/Fdpkgconf-5.dll.p\libpkgconf_argvsplit.c.pdb" /Fopkgconf-5.dll.p/libpkgconf_argvsplit.c.obj "/c" ../src/conf-2.3.0-07e4a066bf.clean/libpkgconf/argvsplit.c
cl : Command line warning D9025 : overriding '/Z7' with '/Zi'
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
[6/21] "C:/cc/vc17/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-Ipkgconf-5.dll.p" "-I." "-I..\src\conf-2.3.0-07e4a066bf.clean" "-ID:/cc/vcpkg/installed/x64-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/Zi" "-D_BSD_SOURCE" "-D_DEFAULT_SOURCE" "-nologo" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DLIBPKGCONF_EXPORT" "-DPKGCONFIG_IS_NOT_STATIC" "/Fdpkgconf-5.dll.p\libpkgconf_fragment.c.pdb" /Fopkgconf-5.dll.p/libpkgconf_fragment.c.obj "/c" ../src/conf-2.3.0-07e4a066bf.clean/libpkgconf/fragment.c
cl : Command line warning D9025 : overriding '/Z7' with '/Zi'
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
[7/21] "C:/cc/vc17/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-Ipkgconf-5.dll.p" "-I." "-I..\src\conf-2.3.0-07e4a066bf.clean" "-ID:/cc/vcpkg/installed/x64-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/Zi" "-D_BSD_SOURCE" "-D_DEFAULT_SOURCE" "-nologo" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DLIBPKGCONF_EXPORT" "-DPKGCONFIG_IS_NOT_STATIC" "/Fdpkgconf-5.dll.p\libpkgconf_fileio.c.pdb" /Fopkgconf-5.dll.p/libpkgconf_fileio.c.obj "/c" ../src/conf-2.3.0-07e4a066bf.clean/libpkgconf/fileio.c
cl : Command line warning D9025 : overriding '/Z7' with '/Zi'
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
[8/21] "C:/cc/vc17/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-Ipkgconf-5.dll.p" "-I." "-I..\src\conf-2.3.0-07e4a066bf.clean" "-ID:/cc/vcpkg/installed/x64-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/Zi" "-D_BSD_SOURCE" "-D_DEFAULT_SOURCE" "-nologo" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DLIBPKGCONF_EXPORT" "-DPKGCONFIG_IS_NOT_STATIC" "/Fdpkgconf-5.dll.p\libpkgconf_client.c.pdb" /Fopkgconf-5.dll.p/libpkgconf_client.c.obj "/c" ../src/conf-2.3.0-07e4a066bf.clean/libpkgconf/client.c
cl : Command line warning D9025 : overriding '/Z7' with '/Zi'
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
[9/21] "C:/cc/vc17/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-Ipkgconf-5.dll.p" "-I." "-I..\src\conf-2.3.0-07e4a066bf.clean" "-ID:/cc/vcpkg/installed/x64-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/Zi" "-D_BSD_SOURCE" "-D_DEFAULT_SOURCE" "-nologo" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DLIBPKGCONF_EXPORT" "-DPKGCONFIG_IS_NOT_STATIC" "/Fdpkgconf-5.dll.p\libpkgconf_path.c.pdb" /Fopkgconf-5.dll.p/libpkgconf_path.c.obj "/c" ../src/conf-2.3.0-07e4a066bf.clean/libpkgconf/path.c
cl : Command line warning D9025 : overriding '/Z7' with '/Zi'
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
[10/21] "C:/cc/vc17/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-Ipkgconf-5.dll.p" "-I." "-I..\src\conf-2.3.0-07e4a066bf.clean" "-ID:/cc/vcpkg/installed/x64-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/Zi" "-D_BSD_SOURCE" "-D_DEFAULT_SOURCE" "-nologo" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DLIBPKGCONF_EXPORT" "-DPKGCONFIG_IS_NOT_STATIC" "/Fdpkgconf-5.dll.p\libpkgconf_pkg.c.pdb" /Fopkgconf-5.dll.p/libpkgconf_pkg.c.obj "/c" ../src/conf-2.3.0-07e4a066bf.clean/libpkgconf/pkg.c
cl : Command line warning D9025 : overriding '/Z7' with '/Zi'
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
[11/21] "C:/cc/vc17/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-Ipkgconf.exe.p" "-I." "-I..\src\conf-2.3.0-07e4a066bf.clean" "-ID:/cc/vcpkg/installed/x64-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/Zi" "-D_BSD_SOURCE" "-D_DEFAULT_SOURCE" "-nologo" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DPKGCONFIG_IS_NOT_STATIC" "/Fdpkgconf.exe.p\cli_getopt_long.c.pdb" /Fopkgconf.exe.p/cli_getopt_long.c.obj "/c" ../src/conf-2.3.0-07e4a066bf.clean/cli/getopt_long.c
cl : Command line warning D9025 : overriding '/Z7' with '/Zi'
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
[12/21] "C:/cc/vc17/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-Ipkgconf-5.dll.p" "-I." "-I..\src\conf-2.3.0-07e4a066bf.clean" "-ID:/cc/vcpkg/installed/x64-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/Zi" "-D_BSD_SOURCE" "-D_DEFAULT_SOURCE" "-nologo" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DLIBPKGCONF_EXPORT" "-DPKGCONFIG_IS_NOT_STATIC" "/Fdpkgconf-5.dll.p\libpkgconf_parser.c.pdb" /Fopkgconf-5.dll.p/libpkgconf_parser.c.obj "/c" ../src/conf-2.3.0-07e4a066bf.clean/libpkgconf/parser.c
cl : Command line warning D9025 : overriding '/Z7' with '/Zi'
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
[13/21] "C:/cc/vc17/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-Ipkgconf-5.dll.p" "-I." "-I..\src\conf-2.3.0-07e4a066bf.clean" "-ID:/cc/vcpkg/installed/x64-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/Zi" "-D_BSD_SOURCE" "-D_DEFAULT_SOURCE" "-nologo" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DLIBPKGCONF_EXPORT" "-DPKGCONFIG_IS_NOT_STATIC" "/Fdpkgconf-5.dll.p\libpkgconf_personality.c.pdb" /Fopkgconf-5.dll.p/libpkgconf_personality.c.obj "/c" ../src/conf-2.3.0-07e4a066bf.clean/libpkgconf/personality.c
cl : Command line warning D9025 : overriding '/Z7' with '/Zi'
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
[14/21] "C:/cc/vc17/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-Ipkgconf-5.dll.p" "-I." "-I..\src\conf-2.3.0-07e4a066bf.clean" "-ID:/cc/vcpkg/installed/x64-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/Zi" "-D_BSD_SOURCE" "-D_DEFAULT_SOURCE" "-nologo" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DLIBPKGCONF_EXPORT" "-DPKGCONFIG_IS_NOT_STATIC" "/Fdpkgconf-5.dll.p\libpkgconf_tuple.c.pdb" /Fopkgconf-5.dll.p/libpkgconf_tuple.c.obj "/c" ../src/conf-2.3.0-07e4a066bf.clean/libpkgconf/tuple.c
cl : Command line warning D9025 : overriding '/Z7' with '/Zi'
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
[15/21] "C:/cc/vc17/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-Ipkgconf.exe.p" "-I." "-I..\src\conf-2.3.0-07e4a066bf.clean" "-ID:/cc/vcpkg/installed/x64-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/Zi" "-D_BSD_SOURCE" "-D_DEFAULT_SOURCE" "-nologo" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DPKGCONFIG_IS_NOT_STATIC" "/Fdpkgconf.exe.p\cli_renderer-msvc.c.pdb" /Fopkgconf.exe.p/cli_renderer-msvc.c.obj "/c" ../src/conf-2.3.0-07e4a066bf.clean/cli/renderer-msvc.c
cl : Command line warning D9025 : overriding '/Z7' with '/Zi'
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
[16/21] "C:/cc/vc17/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-Ipkgconf.exe.p" "-I." "-I..\src\conf-2.3.0-07e4a066bf.clean" "-ID:/cc/vcpkg/installed/x64-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/Zi" "-D_BSD_SOURCE" "-D_DEFAULT_SOURCE" "-nologo" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DPKGCONFIG_IS_NOT_STATIC" "/Fdpkgconf.exe.p\cli_main.c.pdb" /Fopkgconf.exe.p/cli_main.c.obj "/c" ../src/conf-2.3.0-07e4a066bf.clean/cli/main.c
cl : Command line warning D9025 : overriding '/Z7' with '/Zi'
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
[17/21] "C:/cc/vc17/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-Ipkgconf-5.dll.p" "-I." "-I..\src\conf-2.3.0-07e4a066bf.clean" "-ID:/cc/vcpkg/installed/x64-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/Zi" "-D_BSD_SOURCE" "-D_DEFAULT_SOURCE" "-nologo" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DLIBPKGCONF_EXPORT" "-DPKGCONFIG_IS_NOT_STATIC" "/Fdpkgconf-5.dll.p\libpkgconf_queue.c.pdb" /Fopkgconf-5.dll.p/libpkgconf_queue.c.obj "/c" ../src/conf-2.3.0-07e4a066bf.clean/libpkgconf/queue.c
cl : Command line warning D9025 : overriding '/Z7' with '/Zi'
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
[18/21] "C:/cc/vc17/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/link.exe"  /MACHINE:x64 /OUT:pkgconf-5.dll pkgconf-5.dll.p/libpkgconf_argvsplit.c.obj pkgconf-5.dll.p/libpkgconf_audit.c.obj pkgconf-5.dll.p/libpkgconf_bsdstubs.c.obj pkgconf-5.dll.p/libpkgconf_cache.c.obj pkgconf-5.dll.p/libpkgconf_client.c.obj pkgconf-5.dll.p/libpkgconf_dependency.c.obj pkgconf-5.dll.p/libpkgconf_fileio.c.obj pkgconf-5.dll.p/libpkgconf_fragment.c.obj pkgconf-5.dll.p/libpkgconf_parser.c.obj pkgconf-5.dll.p/libpkgconf_path.c.obj pkgconf-5.dll.p/libpkgconf_personality.c.obj pkgconf-5.dll.p/libpkgconf_pkg.c.obj pkgconf-5.dll.p/libpkgconf_queue.c.obj pkgconf-5.dll.p/libpkgconf_tuple.c.obj "-INCREMENTAL" "/release" "/nologo" "/DEBUG" "/PDB:pkgconf-5.pdb" "/DLL" "/IMPLIB:pkgconf.lib" "-machine:x64" "-nologo" "-debug" "/LIBPATH:D:/cc/vcpkg/installed/x64-windows/debug/lib" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "comdlg32.lib" "advapi32.lib"
LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/RELEASE' specification
   Creating library pkgconf.lib and object pkgconf.exp
[19/21] "D:\cc\vcpkg\downloads\tools\python\python-3.11.8-x64\python.exe" "D:\cc\vcpkg\downloads\tools\meson-1.5.1-81f7e3\meson.py" "--internal" "symbolextractor" "D:\cc\vcpkg\buildtrees\pkgconf\x64-windows-dbg" pkgconf-5.dll "pkgconf.lib" pkgconf-5.dll.p/pkgconf-5.dll.symbols 
[20/21] "C:/cc/vc17/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/link.exe"  /MACHINE:x64 /OUT:pkgconf.exe pkgconf.exe.p/cli_main.c.obj pkgconf.exe.p/cli_getopt_long.c.obj pkgconf.exe.p/cli_renderer-msvc.c.obj "-INCREMENTAL" "/release" "/nologo" "/DEBUG" "/PDB:pkgconf.pdb" "-machine:x64" "-nologo" "-debug" "/LIBPATH:D:/cc/vcpkg/installed/x64-windows/debug/lib" "pkgconf.lib" "/SUBSYSTEM:CONSOLE" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "comdlg32.lib" "advapi32.lib"
LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/RELEASE' specification
[20/21] "D:\cc\vcpkg\downloads\tools\python\python-3.11.8-x64\python.exe" "D:\cc\vcpkg\downloads\tools\meson-1.5.1-81f7e3\meson.py" "install" "--no-rebuild"
FAILED: meson-internal__install 
"D:\cc\vcpkg\downloads\tools\python\python-3.11.8-x64\python.exe" "D:\cc\vcpkg\downloads\tools\meson-1.5.1-81f7e3\meson.py" "install" "--no-rebuild"
ninja: build stopped: subcommand failed.
```
</details>

**Comment by MonicaLiu0311** [comment]
Is the VS English language pack installed?

![image](https://github.com/user-attachments/assets/32e344ca-3185-4259-9722-85f179ec6295)

**Comment by mycaosf** [comment]
Yes, I installed VS English language pack.
