### ISSUE TITLE
Latest VCPKG Triton install, fails Xformers dependencies.

### ISSUE THREAD

**Issue by Xorba001** [microsoft/vcpkg#41382]
### Library name

AttributeError: module 'triton' has no attribute 'language'

### New version number

Xformers 0.0.28.post1, torch2.4.1 with cuda121

### Other information that may be useful (release notes, etc...)

Installing Triton for Xformers, as such.
Now, as Xformers finds triton, it doesn't bypass it's usage anymore, but fails onto an attribute language missing !
All my Xformers projects are now failing to load. 😣🙄
![373959645-450bd28d-3ad9-413e-ab68-66c1adebde11](https://github.com/user-attachments/assets/453f3c33-1de8-4ad7-acec-b2b4b9b31153)

python -m xformers.info output
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "E:\Python312\Lib\site-packages\xformers\__init__.py", line 12, in <module>
    from .checkpoint import (  # noqa: E402, F401
  File "E:\Python312\Lib\site-packages\xformers\checkpoint.py", line 475, in <module>
    class SelectiveCheckpointWrapper(ActivationWrapper):
  File "E:\Python312\Lib\site-packages\xformers\checkpoint.py", line 491, in SelectiveCheckpointWrapper
    @torch.compiler.disable
     ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python312\Lib\site-packages\torch\compiler\__init__.py", line 152, in disable
    import torch._dynamo
  File "E:\Python312\Lib\site-packages\torch\_dynamo\__init__.py", line 2, in <module>
    from . import convert_frame, eval_frame, resume_execution
  File "E:\Python312\Lib\site-packages\torch\_dynamo\convert_frame.py", line 48, in <module>
    from . import config, exc, trace_rules
  File "E:\Python312\Lib\site-packages\torch\_dynamo\exc.py", line 12, in <module>
    from .utils import counters
  File "E:\Python312\Lib\site-packages\torch\_dynamo\utils.py", line 1066, in <module>
    common_constant_types.add(triton.language.dtype)
                              ^^^^^^^^^^^^^^^
AttributeError: module 'triton' has no attribute 'language'

**Comment by dg0yt** [comment]
This issue doesn't seem to be related to vcpkg.
