### ISSUE TITLE
[libepoxy] Build error on x64-windows

### ISSUE THREAD

**Issue by yuedianchaomei** [microsoft/vcpkg#41654]
Package: libepoxy:x64-windows@1.5.10#2

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.34.31942.0
-    vcpkg-tool version: 2024-10-18-e392d7347fe72dff56e7857f7571c22301237ae6
    vcpkg-scripts version: d567b667a 2024-10-19 (4 hours ago)

**To Reproduce**

`vcpkg install pangolin:x64-windows`

**Failure logs**

```
CMake Warning (dev) at scripts/cmake/vcpkg_find_acquire_program.cmake:70 (cmake_parse_arguments):
  An empty string was given as the value after the INTERPRETER keyword.
  Policy CMP0174 is not set, so cmake_parse_arguments() will unset the
  arg_INTERPRETER variable rather than setting it to an empty string.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:143 (z_vcpkg_find_acquire_program_find_internal)
  installed/x64-windows/share/vcpkg-tool-meson/vcpkg-port-config.cmake:50 (vcpkg_find_acquire_program)
  scripts/ports.cmake:185 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Python version '3.12.7 at D:/vcpkg/vcpkg/downloads/tools/python/python-3.12.7-x64/python.exe'
-- Using meson: D:/vcpkg/vcpkg/downloads/tools/meson-1.5.2-dd4692/meson.py
-- Downloading https://github.com/anholt/libepoxy/archive/1.5.10.tar.gz -> anholt-libepoxy-1.5.10.tar.gz...
-- Extracting source D:/vcpkg/vcpkg/downloads/anholt-libepoxy-1.5.10.tar.gz
-- Using source at D:/vcpkg/vcpkg/buildtrees/libepoxy/src/1.5.10-92989bd778.clean
CMake Warning (dev) at scripts/cmake/vcpkg_find_acquire_program.cmake:70 (cmake_parse_arguments):
  An empty string was given as the value after the INTERPRETER keyword.
  Policy CMP0174 is not set, so cmake_parse_arguments() will unset the
  arg_INTERPRETER variable rather than setting it to an empty string.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:143 (z_vcpkg_find_acquire_program_find_internal)
  installed/x64-windows/share/vcpkg-tool-meson/vcpkg_configure_meson.cmake:427 (vcpkg_find_acquire_program)
  ports/libepoxy/portfile.cmake:31 (vcpkg_configure_meson)
  scripts/ports.cmake:192 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at scripts/cmake/vcpkg_find_acquire_program.cmake:30 (cmake_parse_arguments):
  An empty string was given as the value after the INTERPRETER keyword.
  Policy CMP0174 is not set, so cmake_parse_arguments() will unset the
  arg_INTERPRETER variable rather than setting it to an empty string.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:149 (z_vcpkg_find_acquire_program_find_external)
  installed/x64-windows/share/vcpkg-tool-meson/vcpkg_configure_meson.cmake:427 (vcpkg_find_acquire_program)
  ports/libepoxy/portfile.cmake:31 (vcpkg_configure_meson)
  scripts/ports.cmake:192 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found external ninja('1.11.0').
-- Downloading https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst -> msys2-mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst...
-- Downloading https://mirror.msys2.org/msys/x86_64/msys2-runtime-3.5.3-3-x86_64.pkg.tar.zst;https://repo.msys2.org/msys/x86_64/msys2-runtime-3.5.3-3-x86_64.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/msys2-runtime-3.5.3-3-x86_64.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/msys2-runtime-3.5.3-3-x86_64.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/msys/x86_64/msys2-runtime-3.5.3-3-x86_64.pkg.tar.zst;https://mirror.selfnet.de/msys2/msys/x86_64/msys2-runtime-3.5.3-3-x86_64.pkg.tar.zst -> msys2-msys2-runtime-3.5.3-3-x86_64.pkg.tar.zst...
-- Using msys root at D:/vcpkg/vcpkg/downloads/tools/msys2/1e74ca60daa10104
CMake Warning (dev) at scripts/cmake/vcpkg_find_acquire_program.cmake:70 (cmake_parse_arguments):
  An empty string was given as the value after the INTERPRETER keyword.
  Policy CMP0174 is not set, so cmake_parse_arguments() will unset the
  arg_INTERPRETER variable rather than setting it to an empty string.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:143 (z_vcpkg_find_acquire_program_find_internal)
  installed/x64-windows/share/vcpkg-tool-meson/vcpkg_configure_meson.cmake:430 (vcpkg_find_acquire_program)
  ports/libepoxy/portfile.cmake:31 (vcpkg_configure_meson)
  scripts/ports.cmake:192 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring x64-windows-dbg
-- Getting CMake variables for x64-windows
-- Configuring x64-windows-dbg done
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Package x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" install -v
    Working Directory: D:/vcpkg/vcpkg/buildtrees/libepoxy/x64-windows-dbg
    Error code: 1
    See logs for more information:
      D:\vcpkg\vcpkg\buildtrees\libepoxy\package-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-tool-meson/vcpkg_install_meson.cmake:33 (vcpkg_execute_required_process)
  ports/libepoxy/portfile.cmake:37 (vcpkg_install_meson)
  scripts/ports.cmake:192 (include)



```

<details><summary>D:\vcpkg\vcpkg\buildtrees\libepoxy\package-x64-windows-dbg-out.log</summary>

```
[1/10] "D:\vcpkg\vcpkg\downloads\tools\python\python-3.12.7-x64\python.exe" "D:/vcpkg/vcpkg/buildtrees/libepoxy/src/1.5.10-92989bd778.clean/src/gen_dispatch.py" "--header" "--no-source" "--outputdir=include/epoxy" "../src/1.5.10-92989bd778.clean/registry/wgl.xml"
FAILED: include/epoxy/wgl_generated.h 
"D:\vcpkg\vcpkg\downloads\tools\python\python-3.12.7-x64\python.exe" "D:/vcpkg/vcpkg/buildtrees/libepoxy/src/1.5.10-92989bd778.clean/src/gen_dispatch.py" "--header" "--no-source" "--outputdir=include/epoxy" "../src/1.5.10-92989bd778.clean/registry/wgl.xml"
Traceback (most recent call last):
  File "xml\etree\ElementTree.py", line 1515, in __init__
  File "xml\parsers\expat.py", line 4, in <module>
ImportError: DLL load failed while importing pyexpat: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "xml\etree\ElementTree.py", line 1518, in __init__
ImportError: DLL load failed while importing pyexpat: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\vcpkg\vcpkg\buildtrees\libepoxy\src\1.5.10-92989bd778.clean\src\gen_dispatch.py", line 903, in <module>
    generator.parse(f)
  File "D:\vcpkg\vcpkg\buildtrees\libepoxy\src\1.5.10-92989bd778.clean\src\gen_dispatch.py", line 426, in parse
    reg = ET.parse(xml_file)
          ^^^^^^^^^^^^^^^^^^
  File "xml\etree\ElementTree.py", line 1204, in parse
  File "xml\etree\ElementTree.py", line 563, in parse

  File "xml\etree\ElementTree.py", line 1520, in __init__

ImportError: No module named expat; use SimpleXMLTreeBuilder instead

[2/10] "D:\vcpkg\vcpkg\downloads\tools\python\python-3.12.7-x64\python.exe" "D:/vcpkg/vcpkg/buildtrees/libepoxy/src/1.5.10-92989bd778.clean/src/gen_dispatch.py" "--source" "--no-header" "--outputdir=src" "../src/1.5.10-92989bd778.clean/registry/wgl.xml"
FAILED: src/wgl_generated_dispatch.c 
"D:\vcpkg\vcpkg\downloads\tools\python\python-3.12.7-x64\python.exe" "D:/vcpkg/vcpkg/buildtrees/libepoxy/src/1.5.10-92989bd778.clean/src/gen_dispatch.py" "--source" "--no-header" "--outputdir=src" "../src/1.5.10-92989bd778.clean/registry/wgl.xml"
Traceback (most recent call last):
  File "xml\etree\ElementTree.py", line 1515, in __init__
  File "xml\parsers\expat.py", line 4, in <module>
ImportError: DLL load failed while importing pyexpat: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "xml\etree\ElementTree.py", line 1518, in __init__
ImportError: DLL load failed while importing pyexpat: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\vcpkg\vcpkg\buildtrees\libepoxy\src\1.5.10-92989bd778.clean\src\gen_dispatch.py", line 903, in <module>
    generator.parse(f)
  File "D:\vcpkg\vcpkg\buildtrees\libepoxy\src\1.5.10-92989bd778.clean\src\gen_dispatch.py", line 426, in parse

    reg = ET.parse(xml_file)

          ^^^^^^^^^^^^^^^^^^

  File "xml\etree\ElementTree.py", line 1204, in parse

  File "xml\etree\ElementTree.py", line 563, in parse

  File "xml\etree\ElementTree.py", line 1520, in __init__

ImportError: No module named expat; use SimpleXMLTreeBuilder instead

[3/10] "D:\vcpkg\vcpkg\downloads\tools\python\python-3.12.7-x64\python.exe" "D:/vcpkg/vcpkg/buildtrees/libepoxy/src/1.5.10-92989bd778.clean/src/gen_dispatch.py" "--header" "--no-source" "--outputdir=include/epoxy" "../src/1.5.10-92989bd778.clean/registry/gl.xml"
FAILED: include/epoxy/gl_generated.h 
"D:\vcpkg\vcpkg\downloads\tools\python\python-3.12.7-x64\python.exe" "D:/vcpkg/vcpkg/buildtrees/libepoxy/src/1.5.10-92989bd778.clean/src/gen_dispatch.py" "--header" "--no-source" "--outputdir=include/epoxy" "../src/1.5.10-92989bd778.clean/registry/gl.xml"
Traceback (most recent call last):
  File "xml\etree\ElementTree.py", line 1515, in __init__
  File "xml\parsers\expat.py", line 4, in <module>
ImportError: DLL load failed while importing pyexpat: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "xml\etree\ElementTree.py", line 1518, in __init__
ImportError: DLL load failed while importing pyexpat: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\vcpkg\vcpkg\buildtrees\libepoxy\src\1.5.10-92989bd778.clean\src\gen_dispatch.py", line 903, in <module>

    generator.parse(f)

  File "D:\vcpkg\vcpkg\buildtrees\libepoxy\src\1.5.10-92989bd778.clean\src\gen_dispatch.py", line 426, in parse

    reg = ET.parse(xml_file)

          ^^^^^^^^^^^^^^^^^^

  File "xml\etree\ElementTree.py", line 1204, in parse

  File "xml\etree\ElementTree.py", line 563, in parse

  File "xml\etree\ElementTree.py", line 1520, in __init__

ImportError: No module named expat; use SimpleXMLTreeBuilder instead

[4/10] "D:\vcpkg\vcpkg\downloads\tools\python\python-3.12.7-x64\python.exe" "D:/vcpkg/vcpkg/buildtrees/libepoxy/src/1.5.10-92989bd778.clean/src/gen_dispatch.py" "--source" "--no-header" "--outputdir=src" "../src/1.5.10-92989bd778.clean/registry/gl.xml"
FAILED: src/gl_generated_dispatch.c 
"D:\vcpkg\vcpkg\downloads\tools\python\python-3.12.7-x64\python.exe" "D:/vcpkg/vcpkg/buildtrees/libepoxy/src/1.5.10-92989bd778.clean/src/gen_dispatch.py" "--source" "--no-header" "--outputdir=src" "../src/1.5.10-92989bd778.clean/registry/gl.xml"
Traceback (most recent call last):
  File "xml\etree\ElementTree.py", line 1515, in __init__
  File "xml\parsers\expat.py", line 4, in <module>
ImportError: DLL load failed while importing pyexpat: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "xml\etree\ElementTree.py", line 1518, in __init__
ImportError: DLL load failed while importing pyexpat: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\vcpkg\vcpkg\buildtrees\libepoxy\src\1.5.10-92989bd778.clean\src\gen_dispatch.py", line 903, in <module>
    generator.parse(f)
  File "D:\vcpkg\vcpkg\buildtrees\libepoxy\src\1.5.10-92989bd778.clean\src\gen_dispatch.py", line 426, in parse
    reg = ET.parse(xml_file)
          ^^^^^^^^^^^^^^^^^^
  File "xml\etree\ElementTree.py", line 1204, in parse
  File "xml\etree\ElementTree.py", line 563, in parse
  File "xml\etree\ElementTree.py", line 1520, in __init__

ImportError: No module named expat; use SimpleXMLTreeBuilder instead

ninja: build stopped: subcommand failed.
```
</details>

**Comment by dg0yt** [comment]
Run `.\vcpkg upgrade` in order to update `vcpkg-tool-meson` and other ports.

**Comment by yuedianchaomei** [comment]
> Run `.\vcpkg upgrade` in order to update `vcpkg-tool-meson` and other ports.

All installed packages are up-to-date.

> Run `.\vcpkg upgrade` in order to update `vcpkg-tool-meson` and other ports.

**Comment by dg0yt** [comment]
I see 🤦 ... CMP0174 is from CMake 3.31, and the warnings are just distractions.
The actual error is with python and pyexpat.
