### ISSUE TITLE
[fontconfig] Build error on OSX (arm64-osx, x64-osx) on GitHub's Actions build-in GitHub MacOS builders

### ISSUE THREAD

**Issue by blessio** [microsoft/vcpkg#41687]
I experienced a build failure in GH Actions, which happens on MacOS builders but not on my old Mac x86 (Sequoia 15.0.1). The VCPKG build recommends entering a defect with an md file as content.

Thus, here is the defect. The md file was "cat"-ed to the output of GitHub actions build. The problem happens on all MacOS builds in a matrix build (not on my local computer). That is the issue happens not only on arm64-osx but also on x86-osx.

Here are links to the failing builds (all of them MacOS):
   - MacOS arm64: [Debug, Dynamic, arm64](https://github.com/blessio/keepassxc-B/actions/runs/11428478115/job/31793777876#step:15:629)
   - MacOS arm64: [RelWithDebInfo, Dynamic, arm64](https://github.com/blessio/keepassxc-B/actions/runs/11428478115/job/31793777594#step:15:634)
   - MaxOS x64: [Dynamic, x64](https://github.com/blessio/keepassxc-B/actions/runs/11428478115/job/31793777665#step:15:696)
   - one more MacOS failure can be seen here [Build attempt](https://github.com/blessio/keepassxc-B/actions/runs/11428478115) together with Linux and Windows Builds that succeed 

-----
This seems like the root-cause but I did not manage to resolve it. 
```
Program stderr:

Traceback (most recent call last):
  File "/var/folders/t_/mmhnh941511_hp2lwh383bp00000gn/T/tmpisnqwcp1.py", line 5, in <module>
    import distutils.command.install
ModuleNotFoundError: No module named 'distutils'

../src/2.14.2-7f52ee670b.clean/meson.build:47:0: ERROR: <PythonExternalProgram 'python' -> ['/opt/homebrew/bin/python3']> is not a valid python or it is missing distutils
```
-----

------------------------------
The report is only from arm64-osx - as taken from the md file with a unix `cat xxx.md`:
------------------------------
package: fontconfig:arm64-osx@2.14.2#1
**Host Environment**
- Host: arm64-osx
- Compiler: AppleClang 15.0.0.15000309
-    vcpkg-tool version: 2024-09-30-ab8988503c7cffabfd440b243a383c0a352a023d
    vcpkg-scripts version: c82f74667 2024-09-30 (3 weeks ago)
**To Reproduce**
`vcpkg install `
**Failure logs**
```
-- Downloading https://gitlab.freedesktop.org/fontconfig/fontconfig/-/archive/2.14.2/fontconfig-2.14.2.tar.gz -> fontconfig-fontconfig-2.14.2.tar.gz...
-- Extracting source /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/downloads/fontconfig-fontconfig-2.14.2.tar.gz
-- Applying patch no-etc-symlinks.patch
-- Applying patch libgetopt.patch
-- Applying patch fix-preprocessor-clang-cl.patch
-- Using source at /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/buildtrees/fontconfig/src/2.14.2-7f52ee670b.clean
-- Found external ninja('1.12.1').
-- Getting CMake variables for arm64-osx-dbg
-- Getting CMake variables for arm64-osx-rel
-- Configuring arm64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: /opt/homebrew/bin/python3 -I /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/tools/meson/meson.py -Ddoc=disabled -Dcache-build=disabled -Dtests=disabled --backend ninja --wrap-mode nodownload -Dbuildtype=plain --libdir lib --native /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/buildtrees/fontconfig/meson-arm64-osx-dbg.log -Ddebug=true --prefix /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/packages/fontconfig_arm64-osx/debug --includedir ../include -Dcmake_prefix_path=['/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/debug','/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx'] /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/buildtrees/fontconfig/src/2.14.2-7f52ee670b.clean
    Working Directory: /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/buildtrees/fontconfig/arm64-osx-dbg
    Error code: 1
    See logs for more information:
      /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/buildtrees/fontconfig/config-arm64-osx-dbg-meson-log.txt.log
      /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/buildtrees/fontconfig/config-arm64-osx-dbg-out.log
Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:436 (vcpkg_execute_required_process)
  buildtrees/versioning_/versions/fontconfig/de73339d579963e68fed652ed2e206b307a0c03f/portfile.cmake:16 (vcpkg_configure_meson)
  scripts/ports.cmake:192 (include)
```
<details><summary>/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/buildtrees/fontconfig/config-arm64-osx-dbg-out.log</summary>
```
WARNING: Recommend using either -Dbuildtype or -Doptimization + -Ddebug. Using both is redundant since they override each other. See: https://mesonbuild.com/Builtin-options.html#build-type-options
The Meson build system
Version: 0.62.1
Source dir: /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/buildtrees/fontconfig/src/2.14.2-7f52ee670b.clean
Build dir: /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/buildtrees/fontconfig/arm64-osx-dbg
Build type: native build
Project name: fontconfig
Project version: 2.14.2
C compiler for the host machine: /Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -fPIC -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -g (clang 15.0.0 "Apple clang version 15.0.0 (clang-1500.3.9.4)")
C linker for the host machine: /Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -fPIC -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -g ld64 1053.12
Host machine cpu family: aarch64
Host machine cpu: arm64
Found pkg-config: /opt/homebrew/bin/pkg-config (0.29.2)
Run-time dependency freetype2 found: YES 24.3.18
Run-time dependency expat found: YES 2.5.0
../src/2.14.2-7f52ee670b.clean/meson.build:47:0: ERROR: <PythonExternalProgram 'python' -> ['/opt/homebrew/bin/python3']> is not a valid python or it is missing distutils
A full log can be found at /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/buildtrees/fontconfig/arm64-osx-dbg/meson-logs/meson-log.txt
```
</details>
<details><summary>/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/buildtrees/fontconfig/config-arm64-osx-dbg-meson-log.txt.log</summary>
```
Build started at 2024-10-20T18:32:25.934645
Main binary: /opt/homebrew/opt/python@3.12/bin/python3.12
Build Options: -Ddoc=disabled -Dcache-build=disabled -Dtests=disabled -Dbuildtype=plain -Ddebug=true '-Dcmake_prefix_path=['"'"'/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/debug'"'"','"'"'/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx'"'"']' -Dprefix=/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/packages/fontconfig_arm64-osx/debug -Dincludedir=../include -Dlibdir=lib -Dbackend=ninja -Dwrap_mode=nodownload '--native-file /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/buildtrees/fontconfig/meson-arm64-osx-dbg.log'
Python system: Darwin
The Meson build system
Version: 0.62.1
Source dir: /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/buildtrees/fontconfig/src/2.14.2-7f52ee670b.clean
Build dir: /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/buildtrees/fontconfig/arm64-osx-dbg
Build type: native build
Project name: fontconfig
Project version: 2.14.2
Sanity testing C compiler: /Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -fPIC -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -g
Is cross compiler: False.
Sanity check compiler command line: /Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -fPIC -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -g sanitycheckc.c -o sanitycheckc.exe -fPIC -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -g -I/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/include -fuse-ld=/Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld -L/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/debug/lib
Sanity check compile stdout:
-----
Sanity check compile stderr:
-----
Running test binary command: /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/buildtrees/fontconfig/arm64-osx-dbg/meson-private/sanitycheckc.exe
C compiler for the host machine: /Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -fPIC -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -g (clang 15.0.0 "Apple clang version 15.0.0 (clang-1500.3.9.4)")
C linker for the host machine: /Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -fPIC -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -g ld64 1053.12
Sanity testing C compiler: /Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -fPIC -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -g
Is cross compiler: False.
Sanity check compiler command line: /Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -fPIC -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -g sanitycheckc.c -o sanitycheckc.exe -fuse-ld=/Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
Sanity check compile stdout:
-----
Sanity check compile stderr:
-----
Running test binary command: /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/buildtrees/fontconfig/arm64-osx-dbg/meson-private/sanitycheckc.exe
C compiler for the build machine: /Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -fPIC -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -g (clang 15.0.0 "Apple clang version 15.0.0 (clang-1500.3.9.4)")
C linker for the build machine: /Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -fPIC -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -g ld64 1053.12
Build machine cpu family: aarch64
Build machine cpu: arm64
Host machine cpu family: aarch64
Host machine cpu: arm64
Target machine cpu family: aarch64
Target machine cpu: arm64
Pkg-config binary for 1 is not cached.
Pkg-config binary for 1 specified from cross file, native file, or env var as ['/opt/homebrew/bin/pkg-config']
Found pkg-config: /opt/homebrew/bin/pkg-config (0.29.2)
Determining dependency 'freetype2' with pkg-config executable '/opt/homebrew/bin/pkg-config'
env[PKG_CONFIG]: /opt/homebrew/bin/pkg-config
env[PKG_CONFIG_PATH]: /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/packages/fontconfig_arm64-osx/debug/lib/pkgconfig:/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/packages/fontconfig_arm64-osx/share/pkgconfig:/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/debug/lib/pkgconfig:/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/share/pkgconfig
Called `/opt/homebrew/bin/pkg-config --modversion freetype2` -> 0
24.3.18
env[PKG_CONFIG]: /opt/homebrew/bin/pkg-config
env[PKG_CONFIG_PATH]: /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/packages/fontconfig_arm64-osx/debug/lib/pkgconfig:/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/packages/fontconfig_arm64-osx/share/pkgconfig:/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/debug/lib/pkgconfig:/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/share/pkgconfig
Called `/opt/homebrew/bin/pkg-config --cflags freetype2` -> 0
-I/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/debug/lib/pkgconfig/../../../include -I/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/debug/lib/pkgconfig/../../../include/libpng16 -I/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/debug/lib/pkgconfig/../../../include
env[PKG_CONFIG]: /opt/homebrew/bin/pkg-config
env[PKG_CONFIG_PATH]: /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/packages/fontconfig_arm64-osx/debug/lib/pkgconfig:/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/packages/fontconfig_arm64-osx/share/pkgconfig:/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/debug/lib/pkgconfig:/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/share/pkgconfig
env[PKG_CONFIG_ALLOW_SYSTEM_LIBS]: 1
Called `/opt/homebrew/bin/pkg-config --libs freetype2` -> 0
-L/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/debug/lib/pkgconfig/../../lib -lfreetyped -lbz2d -lpng16d -lz -lbrotlidec -lbrotlicommon
env[PKG_CONFIG]: /opt/homebrew/bin/pkg-config
env[PKG_CONFIG_PATH]: /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/packages/fontconfig_arm64-osx/debug/lib/pkgconfig:/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/packages/fontconfig_arm64-osx/share/pkgconfig:/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/debug/lib/pkgconfig:/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/share/pkgconfig
Called `/opt/homebrew/bin/pkg-config --libs freetype2` -> 0
-L/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/debug/lib/pkgconfig/../../lib -lfreetyped -lbz2d -lpng16d -lz -lbrotlidec -lbrotlicommon
Running compile:
Working directory:  /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/buildtrees/fontconfig/arm64-osx-dbg/meson-private/tmp_pb9yv_o
Command line:  /Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -fPIC -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -g -L/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/debug/lib -I/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/include /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/buildtrees/fontconfig/arm64-osx-dbg/meson-private/tmp_pb9yv_o/testfile.c -o /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/buildtrees/fontconfig/arm64-osx-dbg/meson-private/tmp_pb9yv_o/output.exe -fPIC -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -g -O0 -Werror=implicit-function-declaration -fuse-ld=/Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld 
Code:
 #include<stdio.h>
        
        int main(void) {
            printf("%ld\n", (long)(sizeof(void *)));
            return 0;
        }
Compiler stdout:
 
Compiler stderr:
 
Program stdout:
8
Program stderr:
Running compile:
Working directory:  /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/buildtrees/fontconfig/arm64-osx-dbg/meson-private/tmpdhm5xbcc
Command line:  /Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -fPIC -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -g -I/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/include /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/buildtrees/fontconfig/arm64-osx-dbg/meson-private/tmpdhm5xbcc/testfile.c -o /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/buildtrees/fontconfig/arm64-osx-dbg/meson-private/tmpdhm5xbcc/output.obj -c -fPIC -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -g -O0 -Werror=implicit-function-declaration -Werror=unknown-warning-option -Werror=unused-command-line-argument -Werror=ignored-optimization-argument --print-search-dirs 
Code:
 
Compiler stdout:
 programs: =/Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
libraries: =/Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/15.0.0
Compiler stderr:
 
Run-time dependency freetype2 found: YES 24.3.18
Pkg-config binary for 1 is cached.
Determining dependency 'expat' with pkg-config executable '/opt/homebrew/bin/pkg-config'
env[PKG_CONFIG]: /opt/homebrew/bin/pkg-config
env[PKG_CONFIG_PATH]: /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/packages/fontconfig_arm64-osx/debug/lib/pkgconfig:/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/packages/fontconfig_arm64-osx/share/pkgconfig:/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/debug/lib/pkgconfig:/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/share/pkgconfig
Called `/opt/homebrew/bin/pkg-config --modversion expat` -> 0
2.5.0
env[PKG_CONFIG]: /opt/homebrew/bin/pkg-config
env[PKG_CONFIG_PATH]: /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/packages/fontconfig_arm64-osx/debug/lib/pkgconfig:/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/packages/fontconfig_arm64-osx/share/pkgconfig:/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/debug/lib/pkgconfig:/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/share/pkgconfig
Called `/opt/homebrew/bin/pkg-config --cflags expat` -> 0
-I/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/debug/lib/pkgconfig/../../../include
env[PKG_CONFIG]: /opt/homebrew/bin/pkg-config
env[PKG_CONFIG_PATH]: /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/packages/fontconfig_arm64-osx/debug/lib/pkgconfig:/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/packages/fontconfig_arm64-osx/share/pkgconfig:/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/debug/lib/pkgconfig:/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/share/pkgconfig
env[PKG_CONFIG_ALLOW_SYSTEM_LIBS]: 1
Called `/opt/homebrew/bin/pkg-config --libs expat` -> 0
-L/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/debug/lib/pkgconfig/../../lib -lexpat -lm
env[PKG_CONFIG]: /opt/homebrew/bin/pkg-config
env[PKG_CONFIG_PATH]: /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/packages/fontconfig_arm64-osx/debug/lib/pkgconfig:/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/packages/fontconfig_arm64-osx/share/pkgconfig:/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/debug/lib/pkgconfig:/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/share/pkgconfig
Called `/opt/homebrew/bin/pkg-config --libs expat` -> 0
-L/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/debug/lib/pkgconfig/../../lib -lexpat -lm
Running compile:
Working directory:  /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/buildtrees/fontconfig/arm64-osx-dbg/meson-private/tmpyna9ja99
Command line:  /Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -fPIC -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -g -L/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/debug/lib -I/Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/installed/arm64-osx/include /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/buildtrees/fontconfig/arm64-osx-dbg/meson-private/tmpyna9ja99/testfile.c -o /Users/runner/work/keepassxc-B/keepassxc-B/_vpkg/buildtrees/fontconfig/arm64-osx-dbg/meson-private/tmpyna9ja99/output.exe -fPIC -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -g -O0 -Werror=implicit-function-declaration -lm -fuse-ld=/Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld -Wl,-undefined,dynamic_lookup -fuse-ld=/Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.
Code:
 int main(void) { return 0; }
Compiler stdout:
 
Compiler stderr:
 
Run-time dependency expat found: YES 2.5.0
Could not introspect Python (['/opt/homebrew/bin/python3', '/var/folders/t_/mmhnh941511_hp2lwh383bp00000gn/T/tmpe9q0cqxi.py']): exit code 1
Program stdout:
Program stderr:
Traceback (most recent call last):
  File "/var/folders/t_/mmhnh941511_hp2lwh383bp00000gn/T/tmpe9q0cqxi.py", line 5, in <module>
    import distutils.command.install
ModuleNotFoundError: No module named 'distutils'
../src/2.14.2-7f52ee670b.clean/meson.build:47:0: ERROR: <PythonExternalProgram 'python' -> ['/opt/homebrew/bin/python3']> is not a valid python or it is missing distutils
```
</details>
**Additional context**
<details><summary>vcpkg.json</summary>
```
{
  "name": "keepassxc",
  "version-string": "2.8.0",
  "builtin-baseline": "2a6371b01420d8820d158b4707e79931feba27aa",
  "dependencies": [
    {
      "name": "argon2",
      "version>=": "20190702"
    },
    {
      "name": "botan",
      "version>=": "3.1.1"
    },
    {
      "name": "minizip",
      "version>=": "1.3"
    },
    {
      "name": "libqrencode",
      "version>=": "4.1.1"
    },
    {
      "name": "libusb",
      "version>=": "1.0.26.11791",
      "platform": "linux | freebsd"
    },
    {
      "name": "libxi",
      "version>=": "1.8",
      "platform": "linux | freebsd"
    },
    {
      "name": "libxtst",
      "version>=": "1.2.4",
      "platform": "linux | freebsd"
    },
    {
      "name": "qt5",
      "version>=": "5.15.11"
    },
    {
      "name": "qt5-imageformats",
      "version>=": "5.15.11"
    },
    {
      "name": "qt5-macextras",
      "version>=": "5.15.11",
      "platform": "osx"
    },
    {
      "name": "qt5-svg",
      "version>=": "5.15.11"
    },
    {
      "name": "qt5-tools",
      "version>=": "5.15.11"
    },
    {
      "name": "qt5-translations",
      "version>=": "5.15.11"
    },
    {
      "name": "qt5-wayland",
      "version>=": "5.15.11",
      "platform": "linux | freebsd"
    },
    {
      "name": "qt5-x11extras",
      "version>=": "5.15.11",
      "platform": "linux | freebsd"
    },
    {
      "name": "readline",
      "version>=": "0#5"
    },
    {
      "name": "zlib",
      "version>=": "1.3"
    }
  ]
}
```
</details>

**Comment by jimwang118** [comment]
Sorry, i cannot reproduce this issue locally.
![Image](https://github.com/user-attachments/assets/16ca1a2e-678f-43f6-a248-9bf09994cf9e)

**Comment by blessio** [comment]
Indeed, as I said it does not happen on my local machine ... it happens only on the Github runner. On the runner the file cannot be easily seen from outside.

That is, the file that reports details of the error is printed out in the build log all between: 
 - `*********>>>>>DUMPING FILE>>>>`>
   *and*
 - `<<<<<********* ` 

*is a _print out_ (unix `cat ./path-to/issue_body.md` command).*

-----
For the sake of precise understanding, here is what it is done:
     ![Image](https://github.com/user-attachments/assets/84a3d538-97ef-4c14-83c4-1f3daa2fb463)

Here is the result on [this page](https://github.com/blessio/keepassxc-B/actions/runs/11428478115/job/31793777876#step:15:633)

That is, between these 2 lines is the md file that should include all info available (unless u get the Github runner computer that is)  
- ![Image](https://github.com/user-attachments/assets/bdd1cbbe-c5bc-46ed-952f-f3643bcafc0e)
- ..........
- --------FILE DUMP HERE already pasted as body of this defect--------------------
- ..........
- ![Image](https://github.com/user-attachments/assets/2d85ea7d-829e-404e-a978-1f3c0ebaa9da)

**Comment by blessio** [comment]
The fix is to use an older python version.

```
   brew install python@3.10
```
