### ISSUE TITLE
[glib] Build error on x64-windows

### ISSUE THREAD

**Issue by interloper98** [microsoft/vcpkg#41791]
**Package**: glib:x64-windows@2.78.4#1

**Host Environment**
- Host: x64-windows
- Compiler: MSVC 19.41.34123.0
-    vcpkg-tool version: 2024-[10](https://github.com/dosbox-staging/dosbox-staging/actions/runs/11526216749/job/32089962829#step:10:11)-18-e392d7347fe72dff56e7857f7571c22301237ae6
    vcpkg-scripts version: 3a747a4fc 2024-10-21 (4 days ago)

**To Reproduce**
`vcpkg install `

**Failure logs**

```
-- Found Python version '3.12.7 at C:/vcpkg/downloads/tools/python/python-3.12.7-x64/python.exe'
-- Using meson: C:/vcpkg/downloads/tools/meson-1.3.2-aa4767/meson.py
-- Downloading https://download.gnome.org/sources/glib/2.78/glib-2.78.4.tar.xz -> glib-2.78.4.tar.xz...
-- Extracting source C:/vcpkg/downloads/glib-2.78.4.tar.xz
-- Applying patch use-libiconv-on-windows.patch
-- Applying patch libintl.patch
-- Using source at C:/vcpkg/buildtrees/glib/src/glib-2-322e03f702.clean
CMake Warning at scripts/ports.cmake:168 (message):
  Unexpected UNKNOWN_READ_ACCESS on variable APPLE in script mode.
  This variable name insufficiently expresses whether it refers to the target
  system or to the host system.  Use a prefixed variable instead.
  - Variables providing information about the host:
    CMAKE_HOST_<SYSTEM>
    VCPKG_HOST_IS_<SYSTEM>
  - Variables providing information about the target:
    VCPKG_TARGET_IS_<SYSTEM>
    VCPKG_DETECTED_<VARIABLE> (using vcpkg_cmake_get_vars)
Call Stack (most recent call first):
  buildtrees/versioning_/versions/glib/d73077209c5fcb5a0340baf7d8ba76d128c1ab27/portfile.cmake:2147483647 (z_vcpkg_warn_ambiguous_system_variables)
  buildtrees/versioning_/versions/glib/d73077209c5fcb5a0340baf7d8ba76d128c1ab27/portfile.cmake:15 (if)
  scripts/ports.cmake:192 (include)
-- Found external ninja('1.[11](https://github.com/dosbox-staging/dosbox-staging/actions/runs/11526216749/job/32089962829#step:10:12).0').
-- Getting CMake variables for x64-windows
CMake Warning at scripts/ports.cmake:168 (message):
  Unexpected READ_ACCESS on variable WIN32 in script mode.
  This variable name insufficiently expresses whether it refers to the target
  system or to the host system.  Use a prefixed variable instead.
  - Variables providing information about the host:
    CMAKE_HOST_<SYSTEM>
    VCPKG_HOST_IS_<SYSTEM>
  - Variables providing information about the target:
    VCPKG_TARGET_IS_<SYSTEM>
    VCPKG_DETECTED_<VARIABLE> (using vcpkg_cmake_get_vars)
Call Stack (most recent call first):
  D:/a/dosbox-staging/dosbox-staging/vcpkg_installed/x64-windows/x64-windows/share/vcpkg-tool-meson/vcpkg_configure_meson.cmake:2147483647 (z_vcpkg_warn_ambiguous_system_variables)
  D:/a/dosbox-staging/dosbox-staging/vcpkg_installed/x64-windows/x64-windows/share/vcpkg-tool-meson/vcpkg_configure_meson.cmake:192 (if)
  D:/a/dosbox-staging/dosbox-staging/vcpkg_installed/x64-windows/x64-windows/share/vcpkg-tool-meson/vcpkg_configure_meson.cmake:361 (z_vcpkg_get_build_and_host_system)
  buildtrees/versioning_/versions/glib/d73077209c5fcb5a0340baf7d8ba76d[12](https://github.com/dosbox-staging/dosbox-staging/actions/runs/11526216749/job/32089962829#step:10:13)8c1ab27/portfile.cmake:42 (vcpkg_configure_meson)
  scripts/ports.cmake:192 (include)
CMake Warning at scripts/ports.cmake:168 (message):
  Unexpected READ_ACCESS on variable WIN32 in script mode.
  This variable name insufficiently expresses whether it refers to the target
  system or to the host system.  Use a prefixed variable instead.
  - Variables providing information about the host:
    CMAKE_HOST_<SYSTEM>
    VCPKG_HOST_IS_<SYSTEM>
  - Variables providing information about the target:
    VCPKG_TARGET_IS_<SYSTEM>
    VCPKG_DETECTED_<VARIABLE> (using vcpkg_cmake_get_vars)
Call Stack (most recent call first):
  D:/a/dosbox-staging/dosbox-staging/vcpkg_installed/x64-windows/x64-windows/share/vcpkg-tool-meson/vcpkg_configure_meson.cmake:2147483647 (z_vcpkg_warn_ambiguous_system_variables)
  D:/a/dosbox-staging/dosbox-staging/vcpkg_installed/x64-windows/x64-windows/share/vcpkg-tool-meson/vcpkg_configure_meson.cmake:254 (if)
  D:/a/dosbox-staging/dosbox-staging/vcpkg_installed/x64-windows/x64-windows/share/vcpkg-tool-meson/vcpkg_configure_meson.cmake:361 (z_vcpkg_get_build_and_host_system)
  buildtrees/versioning_/versions/glib/d73077209c5fcb5a0340baf7d8ba76d128c1ab27/portfile.cmake:42 (vcpkg_configure_meson)
  scripts/ports.cmake:192 (include)
-- Configuring x64-windows-dbg
-- Downloading https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst -> msys2-mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst...
-- Downloading https://mirror.msys2.org/msys/x86_64/msys2-runtime-3.5.3-3-x86_64.pkg.tar.zst;https://repo.msys2.org/msys/x86_64/msys2-runtime-3.5.3-3-x86_64.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/msys2-runtime-3.5.3-3-x86_64.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/msys2-runtime-3.5.3-3-x86_64.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/msys/x86_64/msys2-runtime-3.5.3-3-x86_64.pkg.tar.zst;https://mirror.selfnet.de/msys2/msys/x86_64/msys2-runtime-3.5.3-3-x86_64.pkg.tar.zst -> msys2-msys2-runtime-3.5.3-3-x86_64.pkg.tar.zst...
-- Using msys root at C:/vcpkg/downloads/tools/msys2/1e74ca60daa10104
-- Configuring x64-windows-dbg done
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Package x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" install -v
    Working Directory: C:/vcpkg/buildtrees/glib/x64-windows-dbg
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\glib\package-x64-windows-dbg-out.log
Call Stack (most recent call first):
  D:/a/dosbox-staging/dosbox-staging/vcpkg_installed/x64-windows/x64-windows/share/vcpkg-tool-meson/vcpkg_install_meson.cmake:33 (vcpkg_execute_required_process)
  buildtrees/versioning_/versions/glib/d73077209c5fcb5a0340baf7d8ba76d128c1ab27/portfile.cmake:56 (vcpkg_install_meson)
  scripts/ports.cmake:192 (include)
```

<details><summary>C:\vcpkg\buildtrees\glib\package-x64-windows-dbg-out.log</summary>

```
[1/483] "C:/Program Files (x86)/Windows Kits/10/bin/10.0.22621.0/x64/rc.exe" "-c65001" "-DWIN32" "-D_DEBUG" "/nologo" "/foglib/glib_glib.rc_glib.res" "glib/glib.rc"
[2/483] "C:/Program Files (x86)/Windows Kits/10/bin/10.0.22621.0/x64/rc.exe" "-c65001" "-DWIN32" "-D_DEBUG" "/nologo" "/fogobject/gobject_gobject.rc_gobject.res" "gobject/gobject.rc"
[3/483] "C:/Program Files (x86)/Windows Kits/10/bin/10.0.22621.0/x64/rc.exe" "-c65001" "-DWIN32" "-D_DEBUG" "/nologo" "/fogthread/gthread_gthread.rc_gthread.res" "gthread/gthread.rc"
[4/483] "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-Iglib\libcharset\libcharset.a.p" "-Iglib\libcharset" "-I..\src\glib-2-322e03f702.clean\glib\libcharset" "-I." "-I..\src\glib-2-322e03f702.clean" "-ID:/a/dosbox-staging/dosbox-staging/vcpkg_installed/x64-windows/x64-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W4" "/Zi" "/FIglib/msvc_recommended_pragmas.h" "/utf-8" "-D_GNU_SOURCE" "-DG_DISABLE_CAST_CHECKS" "/wo4057" "/wd4068" "/wo4090" "/wd4100" "/wd4116" "/wo4125" "/wd4127" "/wd4146" "/wd4152" "/wd4201" "/wd4232" "/wo4245" "/wo4267" "/wd4334" "/wo4389" "/wo4702" "/wd4706" "-nologo" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DGLIB_CHARSETALIAS_DIR=\"C:/vcpkg/packages/glib_x64-windows/debug/lib\"" "/Fdglib\libcharset\libcharset.a.p\localcharset.c.pdb" /Foglib/libcharset/libcharset.a.p/localcharset.c.obj "/c
cl : Command line warning D9025 : overriding '/Z7' with '/Zi'
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
[5/483] "C:\vcpkg\downloads\tools\python\python-3.12.7-x64\python.exe" "C:/vcpkg/buildtrees/glib/src/glib-2-322e03f702.clean/tools/gen-visibility-macros.py" "2.78.4" "versions-macros" "../src/glib-2-322e03f702.clean/glib/gversionmacros.h.in" "glib/gversionmacros.h"
[6/483] "C:\vcpkg\downloads\tools\python\python-3.12.7-x64\python.exe" "C:/vcpkg/buildtrees/glib/src/glib-2-322e03f702.clean/tools/gen-visibility-macros.py" "2.78.4" "visibility-macros" "GOBJECT" "gobject/gobject-visibility.h"
[7/483] "C:\vcpkg\downloads\tools\python\python-3.12.7-x64\python.exe" "C:/vcpkg/buildtrees/glib/src/glib-2-322e03f702.clean/tools/gen-visibility-macros.py" "2.78.4" "visibility-macros" "GLIB" "glib/glib-visibility.h"
[8/483] "C:\vcpkg\downloads\tools\python\python-3.12.7-x64\python.exe" "C:/vcpkg/buildtrees/glib/src/glib-2-322e03f702.clean/tools/gen-visibility-macros.py" "2.78.4" "visibility-macros" "GMODULE" "gmodule/gmodule-visibility.h"
[9/483] "C:/Program Files (x86)/Windows Kits/10/bin/10.0.22621.0/x64/rc.exe" "-c65001" "-DWIN32" "-D_DEBUG" "/nologo" "/fogmodule/gmodule_gmodule.rc_gmodule.res" "gmodule/gmodule.rc"
[10/483] "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/lib.exe" "-machine:x64" "-nologo" "/NOLOGO" /MACHINE:x64 /OUT:glib/libcharset/libcharset.a glib/libcharset/libcharset.a.p/localcharset.c.obj
[11/483] "C:\vcpkg\downloads\tools\python\python-3.12.7-x64\python.exe" "gio/gdbus-2.0/codegen/gdbus-codegen" "--interface-prefix" "org." "--output-directory" "gio" "--generate-c-code" "gdbus-daemon-generated" "--c-namespace" "_G" "../src/glib-2-322e03f702.clean/gio/dbus-daemon.xml"
FAILED: gio/gdbus-daemon-generated.h gio/gdbus-daemon-generated.c 
"C:\vcpkg\downloads\tools\python\python-3.12.7-x64\python.exe" "gio/gdbus-2.0/codegen/gdbus-codegen" "--interface-prefix" "org." "--output-directory" "gio" "--generate-c-code" "gdbus-daemon-generated" "--c-namespace" "_G" "../src/glib-2-322e03f702.clean/gio/dbus-daemon.xml"
Traceback (most recent call last):
  File "C:\vcpkg\buildtrees\glib\x64-windows-dbg\gio\gdbus-2.0\codegen\gdbus-codegen", line 53, in <module>
    from codegen import codegen_main
  File "C:\vcpkg\buildtrees\glib\x64-windows-dbg\gio\gdbus-2.0\codegen\codegen_main.py", line 29, in <module>
    from . import dbustypes
  File "C:\vcpkg\buildtrees\glib\x64-windows-dbg\gio\gdbus-2.0\codegen\dbustypes.py", line 22, in <module>
    from . import utils
  File "C:\vcpkg\buildtrees\glib\x64-windows-dbg\gio\gdbus-2.0\codegen\utils.py", line 22, in <module>
    import distutils.version
ModuleNotFoundError: No module named 'distutils'
[12/483] "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-Iglib\gnulib\libgnulib.a.p" "-Iglib\gnulib" "-I..\src\glib-2-322e03f702.clean\glib\gnulib" "-I." "-I..\src\glib-2-322e03f702.clean" "-Iglib" "-I..\src\glib-2-322e03f702.clean\glib" "-ID:/a/dosbox-staging/dosbox-staging/vcpkg_installed/x64-windows/x64-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W4" "/Zi" "/FIglib/msvc_recommended_pragmas.h" "/utf-8" "-D_GNU_SOURCE" "-DG_DISABLE_CAST_CHECKS" "/wo4057" "/wd4068" "/wo4090" "/wd4100" "/wd4116" "/wo4125" "/wd4127" "/wd4146" "/wd4152" "/wd4201" "/wd4232" "/wo4245" "/wo4267" "/wd4334" "/wo4389" "/wo4702" "/wd4706" "-nologo" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DGCC_LINT=1" "-DLIBDIR=\"C:/vcpkg/packages/glib_x64-windows/debug/lib\"" "-DG_LOG_DOMAIN=\"GLib\"" "-DGLIB_COMPILATION" "-DHAVE_ISNAN_IN_LIBC" "-DH
cl : Command line warning D9025 : overriding '/Z7' with '/Zi'
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
[[13](https://github.com/dosbox-staging/dosbox-staging/actions/runs/11526216749/job/32089962829#step:10:14)/483] "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/[14](https://github.com/dosbox-staging/dosbox-staging/actions/runs/11526216749/job/32089962829#step:10:15).41.34120/bin/Hostx64/x64/cl.exe" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-Iglib\gnulib\libgnulib.a.p" "-Iglib\gnulib" "-I..\src\glib-2-322e03f702.clean\glib\gnulib" "-I." "-I..\src\glib-2-322e03f702.clean" "-Iglib" "-I..\src\glib-2-322e03f702.clean\glib" "-ID:/a/dosbox-staging/dosbox-staging/vcpkg_installed/x64-windows/x64-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W4" "/Zi" "/FIglib/msvc_recommended_pragmas.h" "/utf-8" "-D_GNU_SOURCE" "-DG_DISABLE_CAST_CHECKS" "/wo4057" "/wd4068" "/wo4090" "/wd4100" "/wd4116" "/wo4125" "/wd4127" "/wd4146" "/wd4[15](https://github.com/dosbox-staging/dosbox-staging/actions/runs/11526216749/job/32089962829#step:10:16)2" "/wd4201" "/wd4232" "/wo4245" "/wo4267" "/wd4334" "/wo4389" "/wo4702" "/wd4706" "-nologo" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DGCC_LINT=1" "-DLIBDIR=\"C:/vcpkg/packages/glib_x64-windows/debug/lib\"" "-DG_LOG_DOMAIN=\"GLib\"" "-DGLIB_COMPILATION" "-DHAVE_ISNAN_IN_LIBC" "-DH
cl : Command line warning D9025 : overriding '/Z7' with '/Zi'
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
[14/483] "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-Iglib\gnulib\libgnulib.a.p" "-Iglib\gnulib" "-I..\src\glib-2-322e03f702.clean\glib\gnulib" "-I." "-I..\src\glib-2-322e03f702.clean" "-Iglib" "-I..\src\glib-2-322e03f702.clean\glib" "-ID:/a/dosbox-staging/dosbox-staging/vcpkg_installed/x64-windows/x64-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W4" "/Zi" "/FIglib/msvc_recommended_pragmas.h" "/utf-8" "-D_GNU_SOURCE" "-DG_DISABLE_CAST_CHECKS" "/wo4057" "/wd4068" "/wo4090" "/wd4100" "/wd41[16](https://github.com/dosbox-staging/dosbox-staging/actions/runs/11526216749/job/32089962829#step:10:17)" "/wo4125" "/wd4127" "/wd4146" "/wd4152" "/wd4201" "/wd4232" "/wo4245" "/wo4267" "/wd4334" "/wo4389" "/wo4702" "/wd4706" "-nologo" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DGCC_LINT=1" "-DLIBDIR=\"C:/vcpkg/packages/glib_x64-windows/debug/lib\"" "-DG_LOG_DOMAIN=\"GLib\"" "-DGLIB_COMPILATION" "-DHAVE_ISNAN_IN_LIBC" "-DH
cl : Command line warning D9025 : overriding '/Z7' with '/Zi'
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
../src/glib-2-322e03f702.clean/glib/gnulib/printf.c(98): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
[15/483] "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-Iglib\gnulib\libgnulib.a.p" "-Iglib\gnulib" "-I..\src\glib-2-322e03f702.clean\glib\gnulib" "-I." "-I..\src\glib-2-322e03f702.clean" "-Iglib" "-I..\src\glib-2-322e03f702.clean\glib" "-ID:/a/dosbox-staging/dosbox-staging/vcpkg_installed/x64-windows/x64-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W4" "/Zi" "/FIglib/msvc_recommended_pragmas.h" "/utf-8" "-D_GNU_SOURCE" "-DG_DISABLE_CAST_CHECKS" "/wo4057" "/wd4068" "/wo4090" "/wd4100" "/wd4116" "/wo4125" "/wd4127" "/wd4146" "/wd4152" "/wd4201" "/wd4232" "/wo4245" "/wo4267" "/wd4334" "/wo4389" "/wo4702" "/wd4706" "-nologo" "-DWIN32" "-D_WINDOWS" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DGCC_LINT=1" "-DLIBDIR=\"C:/vcpkg/packages/glib_x64-windows/debug/lib\"" "-DG_LOG_DOMAIN=\"GLib\"" "-DGLIB_COMPILATION" "-DHAVE_ISNAN_IN_LIBC" "-DH
cl : Command line warning D9025 : overriding '/Z7' with '/Zi'
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
[16/483] "C:\vcpkg\downloads\tools\python\python-3.12.7-x64\python.exe" "C:\vcpkg\downloads\tools\meson-1.3.2-aa4767\meson.py" "--internal" "exe" "--capture" "gobject\glib-enumtypes.h" "--" "C:\vcpkg\downloads\tools\python\python-3.12.7-x64\python.exe" "gobject/glib-mkenums" "--template" "../src/glib-2-322e03f702.clean/gobject/glib-enumtypes.h.template" "../src/glib-2-322e03f702.clean/gobject/../glib/gunicode.h"
ninja: build stopped: subcommand failed.
```

</details>

**Additional context**

<details><summary>vcpkg.json</summary>

```json
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg-tool/main/docs/vcpkg.schema.json",
  "name": "dosbox-staging",
  "description": "DOSBox Staging is a modern continuation of DOSBox with advanced features and current development practices.",
  "version": "0.83.0-alpha",
  "dependencies": [
    "fluidsynth",
    "gtest",
    "iir1",
    "libmt32emu",
    "libpng",
    "libslirp",
    "opusfile",
    "sdl2",
    "sdl2-net",
    "speexdsp",
    {
      "name": "tracy",
      "platform": "!(windows & arm64)"
    },
    "zlib-ng",
    {
      "name": "pkgconf",
      "host": true
    }
  ],
  "builtin-baseline": "0f6d4051514549541e61b[18](https://github.com/dosbox-staging/dosbox-staging/actions/runs/11526216749/job/32089962829#step:10:19)6c4543341fd6ca8dd"
}
```

</details>

**Comment by shermp** [comment]
This appears to be a Python issue.

```
[11/483] "C:\vcpkg\downloads\tools\python\python-3.12.7-x64\python.exe" "gio/gdbus-2.0/codegen/gdbus-codegen" "--interface-prefix" "org." "--output-directory" "gio" "--generate-c-code" "gdbus-daemon-generated" "--c-namespace" "_G" "../src/glib-2-322e03f702.clean/gio/dbus-daemon.xml"
FAILED: gio/gdbus-daemon-generated.h gio/gdbus-daemon-generated.c 
"C:\vcpkg\downloads\tools\python\python-3.12.7-x64\python.exe" "gio/gdbus-2.0/codegen/gdbus-codegen" "--interface-prefix" "org." "--output-directory" "gio" "--generate-c-code" "gdbus-daemon-generated" "--c-namespace" "_G" "../src/glib-2-322e03f702.clean/gio/dbus-daemon.xml"
Traceback (most recent call last):
  File "C:\vcpkg\buildtrees\glib\x64-windows-dbg\gio\gdbus-2.0\codegen\gdbus-codegen", line 53, in <module>
    from codegen import codegen_main
  File "C:\vcpkg\buildtrees\glib\x64-windows-dbg\gio\gdbus-2.0\codegen\codegen_main.py", line 29, in <module>
    from . import dbustypes
  File "C:\vcpkg\buildtrees\glib\x64-windows-dbg\gio\gdbus-2.0\codegen\dbustypes.py", line 22, in <module>

    from . import utils

  File "C:\vcpkg\buildtrees\glib\x64-windows-dbg\gio\gdbus-2.0\codegen\utils.py", line 22, in <module>

    import distutils.version

ModuleNotFoundError: No module named 'distutils'
```

(Note, I believe `distutils` was removed from the stdlib in Python 3.12)

**Comment by Osyotr** [comment]
> Package: glib:x64-windows@2.78.4#1

glib 2.78.4 cannot be built with python 3.12.
The latest available version in vcpkg is 2.80.0 can be built with python 3.12.

**Comment by interloper98** [comment]
I suppose we have two options:
- use glib 2.80
- downgrade to an older vxpkg that uses python 3.11

Thanks @Osyotr. Will close this.

**Comment by johnnovak** [comment]
> > Package: glib:x64-windows@2.78.4#1
> 
> glib 2.78.4 cannot be built with python 3.12. The latest available version in vcpkg is 2.80.0 can be built with python 3.12.

That's all good and well, but doesn't that break the promise of vcpkg to have reproducible builds with pinned dependencies, even when going back in time?

As a user, I don't really care about these details; I should able to use a baseline from a year ago with the latest vcpkg and it should just work. If the Python version used by vcpkg and any package it manages can clash, I consider that a serious bug. These should be decoupled and multiple Python version should be allowed to exist in parallell then.

**Comment by Osyotr** [comment]
> That's all good and well, but doesn't that break the promise of vcpkg to have reproducible builds with pinned dependencies, even when going back in time?

I'm not sure this promise has ever been given. I think there was a similar promise but for the whole repo (i.e. scripts *and* ports) and it was before versioning implementation. Pinning scripts will improve reproducibility but you have to consider other things like msys2 removing outdated packages from its repo.

I personally don't see any reason to update scripts without updating ports and vice versa.

**Comment by shermp** [comment]
I had a quick look at the `glib` port, and it seems it has no specific Python dependency. It seems it relies on whatever is pulled in by Meson. So a part of this issue has been `glib` being... well... `glib`.
