### ISSUE TITLE
[glad] Build error on x64-windows

### ISSUE THREAD

**Issue by qipaifeiying** [microsoft/vcpkg#42134]
Package: glad[core,loader]:x64-windows@0.1.36

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.41.34123.0
- vcpkg-tool version: 2024-10-18-e392d7347fe72dff56e7857f7571c22301237ae6
  vcpkg-scripts version: 89f00b3b8 2024-11-11 (25 hours ago)

**To Reproduce**

`vcpkg install libigl[cgal,embree,xml,glfw]`

**Failure logs**

```
-- Note: glad only supports static library linkage. Building static library.
-- Using cached Dav1dde-glad-1ecd45775d96f35170458e6b148eb0708967e402.tar.gz.
-- Cleaning sources at F:/Library/vcpkg/buildtrees/glad/src/708967e402-274d415499.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/Library/vcpkg/downloads/Dav1dde-glad-1ecd45775d96f35170458e6b148eb0708967e402.tar.gz
-- Applying patch encoding.patch
-- Applying patch find_python.patch
-- Using source at F:/Library/vcpkg/buildtrees/glad/src/708967e402-274d415499.clean
-- This version of glad uses the compatibility profile. To use the core profile instead, create an overlay port of this with GLAD_PROFILE set to 'core' or set GLAD_PROFILE to 'core' in a custom triplet.
-- This recipe is at F:/Library/vcpkg/ports/glad
-- See the overlay ports documentation at https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: E:/cmake/bin/cmake.exe --build . --config Debug --target install -- -v -j17
    Working Directory: F:/Library/vcpkg/buildtrees/glad/x64-windows-dbg
    See logs for more information:
      F:\Library\vcpkg\buildtrees\glad\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/glad/portfile.cmake:143 (vcpkg_cmake_install)
  scripts/ports.cmake:192 (include)



```

<details><summary>F:\Library\vcpkg\buildtrees\glad\install-x64-windows-dbg-out.log</summary>

```
Change Dir: 'F:/Library/vcpkg/buildtrees/glad/x64-windows-dbg'

Run Build Command(s): D:/VS/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe -v -v -j17 install
[1/4] C:\WINDOWS\system32\cmd.exe /C "cd /D F:\Library\vcpkg\buildtrees\glad\src\708967e402-274d415499.clean && F:\Library\vcpkg\downloads\tools\python\python-3.12.7-x64\python.exe -m glad --profile=compatibility --out-path=F:/Library/vcpkg/buildtrees/glad/x64-windows-dbg --api= --generator=c-debug --extensions= --spec=gl --reproducible"
FAILED: include/glad/glad.h src/glad.c F:/Library/vcpkg/buildtrees/glad/x64-windows-dbg/include/glad/glad.h F:/Library/vcpkg/buildtrees/glad/x64-windows-dbg/src/glad.c 
C:\WINDOWS\system32\cmd.exe /C "cd /D F:\Library\vcpkg\buildtrees\glad\src\708967e402-274d415499.clean && F:\Library\vcpkg\downloads\tools\python\python-3.12.7-x64\python.exe -m glad --profile=compatibility --out-path=F:/Library/vcpkg/buildtrees/glad/x64-windows-dbg --api= --generator=c-debug --extensions= --spec=gl --reproducible"
[11/13/2024 16:33:49][INFO	][glad   	]: reproducible build, using packaged specification: 'gl.xml'
[11/13/2024 16:33:49][INFO	][glad.files	]: opening 'gl.xml' from packaged path
Traceback (most recent call last):
  File "xml\etree\ElementTree.py", line 1515, in __init__
  File "xml\parsers\expat.py", line 4, in <module>
ImportError: DLL load failed while importing pyexpat: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "xml\etree\ElementTree.py", line 1518, in __init__
ImportError: DLL load failed while importing pyexpat: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "F:\Library\vcpkg\buildtrees\glad\src\708967e402-274d415499.clean\glad\__main__.py", line 192, in <module>
    main()
  File "F:\Library\vcpkg\buildtrees\glad\src\708967e402-274d415499.clean\glad\__main__.py", line 151, in main
    spec = get_spec(spec_name, reproducible=ns.reproducible)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Library\vcpkg\buildtrees\glad\src\708967e402-274d415499.clean\glad\__main__.py", line 43, in get_spec
    return spec_cls.from_file(glad.files.open_local(value + '.xml', encoding='utf-8-sig'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Library\vcpkg\buildtrees\glad\src\708967e402-274d415499.clean\glad\parse.py", line 74, in from_file
    return cls(xml_frompath(path))
               ^^^^^^^^^^^^^^^^^^
  File "F:\Library\vcpkg\buildtrees\glad\src\708967e402-274d415499.clean\glad\parse.py", line 20, in xml_frompath

    return etree.parse(path).getroot()

           ^^^^^^^^^^^^^^^^^

  File "xml\etree\ElementTree.py", line 1204, in parse

  File "xml\etree\ElementTree.py", line 563, in parse

  File "xml\etree\ElementTree.py", line 1520, in __init__

ImportError: No module named expat; use SimpleXMLTreeBuilder instead

ninja: build stopped: subcommand failed.
```

</details>

**Comment by JonLiu1993** [comment]
Duplicate of #40786
