### ISSUE TITLE
[nss] tries to call vcvarsall.bat

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#42453]
```
Assuming env setup is already done.
VSPATH=/d/installed/x64-windows/VS/
run_scanbuild gyp -f ninja --depth=/d/b/nss/x64-windows-rel/nss --generator-output=. -Ddisable_tests=1 -Dnspr_include_dir=/d/installed/x64-windows/include/nspr -Dnspr_lib_dir=/d/installed/x64-windows/lib -Duse_system_sqlite=1 -Dsign_libs=0 -Dtarget_arch=x64 -Denable_sslkeylogfile=1 -Dnss_dist_dir=/d/b/nss/x64-windows-rel/dist -Dnss_dist_obj_dir=/d/b/nss/x64-windows-rel/dist/Release /d/b/nss/x64-windows-rel/nss/nss.gyp
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "D:\installed\x64-windows\tools\mozbuild\python3\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "D:\installed\x64-windows\tools\mozbuild\python3\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "D:\installed\x64-windows\tools\gyp-next\pylib\gyp\generator\ninja.py", line 2900, in CallGenerateOutputForConfig
    GenerateOutputForConfig(target_list, target_dicts, data, params, config_name)
  File "D:\installed\x64-windows\tools\gyp-next\pylib\gyp\generator\ninja.py", line 2325, in GenerateOutputForConfig
    cl_paths = gyp.msvs_emulation.GenerateEnvironmentFiles(
  File "D:\installed\x64-windows\tools\gyp-next\pylib\gyp\msvs_emulation.py", line 1203, in GenerateEnvironmentFiles
    args = vs.SetupScript(arch)
  File "D:\installed\x64-windows\tools\gyp-next\pylib\gyp\MSVSVersion.py", line 148, in SetupScript
    raise Exception(
Exception: D:\installed\x64-windows\VS\VC\Auxiliary\Build\vcvarsall.bat is missing - make sure VC++ tools are installed.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\installed\x64-windows\tools\gyp-next\gyp_main.py", line 45, in <module>
    sys.exit(gyp.script_main())
  File "D:\installed/x64-windows/tools/gyp-next\pylib\gyp\__init__.py", line 688, in script_main
    return main(sys.argv[1:])
  File "D:\installed/x64-windows/tools/gyp-next\pylib\gyp\__init__.py", line 680, in main
    return gyp_main(args)
  File "D:\installed/x64-windows/tools/gyp-next\pylib\gyp\__init__.py", line 665, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "D:\installed/x64-windows/tools/gyp-next\pylib\gyp\generator\ninja.py", line 2928, in GenerateOutput
    pool.map(CallGenerateOutputForConfig, arglists)
  File "D:\installed\x64-windows\tools\mozbuild\python3\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "D:\installed\x64-windows\tools\mozbuild\python3\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
Exception: D:\installed\x64-windows\VS\VC\Auxiliary\Build\vcvarsall.bat is missing - make sure VC++ tools are installed.

```

**Comment by dg0yt** [comment]
mozbuild...
